### PR TITLE
Add 'copyFormatting' global setting

### LINKED ISSUE #4191: Add setting to select which formats of copy to perform (text, rtf or html)
# Description of the new feature/enhancement

This is extension of #2690, which would allow to separately enable/disable all formats of copy, which there are currently 3, but might be more in the future.

Why disable? Ideally, all editors should well handle these formats, allow selection etc. However, in addition to what #2690 stated,, certain editors might for example better support RTF that HTML or whatever format there might be (I still think about #1084).

# Proposed technical implementation details (optional)

This might either be a profile setting in form of:

`"copyFormats": "text,html,rtf"`

or an argument on copy action, when that is the thing. You could the just remove one or more of these formats, e.g. keep only plain text.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
Implements `copyFormatting` as a global setting. When enabled, formatting such as font and foreground/background colors are copied to the clipboard on _all_ copy operations.

Also updates the schema and docs.

## References
#5212 - Spec for Formatted Copying
#4191 - Setting to enable/disable formatted copy

#5263 - PR prematurely merged without approval of #5212 

This feature will also have an impact on these yet-to-be-implemented features:
- #5262 - copyFormatting Keybinding Arg for Copy
- #1553 - Pointer Bindings
- #4191 - add array support for `copyFormatting`

## Detailed Description of the Pull Request
We already check if the hstring passed into the clipboard is empty before setting it. So the majority of the changes are actually just adding the global setting in.

## Validation Steps Performed
| `copyFormatting` | Mouse Copy | Keyboard Copy |
|--|--|--|
| not set (`false`) | ✔ | ✔ |
| `true` | ✔ | ✔ |
| `false` | ✔ | ✔ |

### CODE REVIEW

**Comment by mcpiroman** [comment]
Well, don't wanna complain and all, but technically this only closes #2690, not #4191 (actually the former happens to be already closed, because you apparently decided to not implement it back then).

This also looks like the implementation of option `1b` from the spec at #5212, and what i was really into was the option `2b` - it is what was originally requested (to split html from rtf) and is flexible so you can e.g. create separate commands for plain copy and html copy, which is common in other terminals, and is what some guy proposed in the original issue. I don't know your plans about that though, just throwing my opinion.

**Comment by DHowett-MSFT** [comment]
To be fair, this is called out in the discussion section.

---
> Question: Should this actually close #4191?
> Yes: the sentiment behind this issue was to disable/enable formatted copy
> No: the proposal was to copy specific formats
> For now, I've assumed yes, but still wanted to point it out

**Comment by carlos-zamora** [comment]
> Well, don't wanna complain and all, but technically this only closes #2690, not #4191 (actually the former happens to be already closed, because you apparently decided to not implement it back then).
> 
> This also looks like the implementation of option `1b` from the spec at #5212, and what i was really into was the option `2b` - it is what was originally requested (to split html from rtf) and is flexible so you can e.g. create separate commands for plain copy and html copy, which is common in other terminals, and is what some guy proposed in the original issue. I don't know your plans about that though, just throwing my opinion.

Yeah. The spec now says that #4191 will be implemented later. So you're right. Updating the PR header now

**Comment by DHowett-MSFT** [comment]
@msftbot merge this in 1 minute

**Pull request merged**
