### PR TITLE
Update wil. Fixes GDI handle leak

### LINKED ISSUE #5949: Tabs leak GDI handles on tab title resizes
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.11.1333.0
```

# Steps to reproduce

1. In the preferences, set `"tabWidthMode": "titleLength"` or any other configuration that allows for variably-sized tab titles (to trigger this bug)
2. Run the following  in a powershell tab (or anything similar in any type of tab) to trigger lots of tab title resizes
```powershell
for ($i=0;;++$i) { $host.UI.RawUI.WindowTitle = "oops " + @(Get-Random -Minimum 0.0 -Maximum 100000000.3) + @(Get-Random) + @(Get-Random) + " oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooops"; }
```
# Expected behavior

Windows Terminal should keep running, keep updating the tab title, without leaking GDI handles.

# Actual behavior

Windows Terminal keeps allocating new GDI handles (as seen in Task Manager/ProcessHacker) and will eventually crash and just vanish.

The leaked GDI handles will be retained even when the corresponding tab is closed

term resource ex

# Please note
It is *not* enough to just update the title when tabs are in `equal` mode/are not resized.

### PR DESCRIPTION
**Pull request by miniksa**
## Summary of the Pull Request
When resizing the window title, a GDI object would be leaked. This has to do with our island message handler using `wil` to track these objects and `wil` having a bug.

## References
microsoft/wil#100

## PR Checklist
* [x] Closes #5949 
* [x] I work here.
* [x] Tested manually
* [x] Doc not required.
* [x] Am core contributor.

## Validation Steps Performed
* [x] Added the GDI Objects column to Task Manager, set the Terminal to use the `titleWidth` size tabs, then changed the title a bunch with PowerShell. Confirmed repro before (increasing GDI count). Confirmed it's gone after (no change to object count).

### CODE REVIEW

**Comment by WSLUser** [comment]
> src\cascadia\PublicTerminalCore\HwndTerminal.cpp(721,0): Error C26447: The function is declared 'noexcept' but calls function 'Log_GetLastErrorIf()' which may throw exceptions (f.6).

Missed a spot it looks like. This actually looks easier than updating gsl. It has way more build errors.

**Comment by DHowett** [comment]
@wsluser yeah, GSL is really annoying because they changed the definition of `span` to align with C++20 span. This breaks all existing consumers everywhere :)

**Comment by WSLUser** [comment]
Well we have fmt, can we use it in place of normal span?

**Comment by DHowett** [comment]
fmt is a string formatting library, not a general-purpose safe memory region access library. :smile:

**Comment by WSLUser** [comment]
Yeah I didn't think it could but was hopeful

**Pull request merged**
