### PR TITLE
Changing a phrase to "expected"

### PR DESCRIPTION
**Pull request by crutkas**
Saw a phrase that has been deprecated and swapped it with a more modern one :)

### CODE REVIEW

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/microsoft/terminal/pull/5922> renamed the `whitelist` directory to `expect`. It would be good to keep the terminology consistent with that.

**Comment by DHowett** [comment]
I’d agree!

**Comment by crutkas** [comment]
changed to `expected`

**Review by DHowett — APPROVED** [review]
Thanks!

**Pull request merged**
