### PR TITLE
Update to XAML 2.7.3

### PR DESCRIPTION
**Pull request by AtariDreams**
And the prerelease version of it

### CODE REVIEW

**Review by lhecker — COMMENTED** [review]
I'm not sure if there's any value in updating to 2.7.3, when we could also upgrade to 2.8. (I'm not a WinUI versioning expert though...)

**Comment by zadjii-msft** [comment]
I'd rather we keep the scratch on the same version as the main solution (i.e., 2.7.3).

Was this tested locally? The scratch sln doesn't build in CI, so it'll need a manual validation

**Comment by DHowett** [comment]
> I'm not sure if there's any value in updating to 2.7.3, when we could also upgrade to 2.8. (I'm not a WinUI versioning expert though...)

2.8 is much riskier (new version and all!) and requires a WebView2 dependency...

**Review by lhecker — APPROVED** [review]

**Review by carlos-zamora — APPROVED** [review]
@zadjii-msft yup, scratch builds and deploys just fine :)

For anybody that's interested, here's the [XAML releases page](https://github.com/Microsoft/microsoft-ui-xaml/releases)

**Comment by carlos-zamora** [comment]
@msftbot merge this in 10 minutes

**Comment by zadjii-msft** [comment]
Hmm. This predates 1.15.2875.0, which was the first time that #14501 was reported, so this ain't it.

**Pull request merged**
