### PR TITLE
Bugfix: TextBuffer Line Wrapping from VTRenderer

### LINKED ISSUE #2275: Copy inconsistently copies as "copyTextWithoutNewlines"
# Environment

```none
Windows build number: Version 10.0.18362.239
Windows Terminal version: 0.3.2142.0
```

# Steps to reproduce

1. Launch cmd and run following command:

```
C:\>set path
```

2. Using mouse highlight from 1,1 -> end of the terminal
3. Right-click (or CTRL+SHIFT+C) to copy text

# Expected behavior
Newlines to be copied
```

c:\project-system>set path                                                                                                                                                                                    
Path=C:\Program Files (x86)\Microsoft Visual Studio\2019\master\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\master\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\master\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\master\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools\;C:\Program Files (x86)\Microsoft Visual Studio\2019\master\Common7\IDE\CommonExtensions\Microsoft\FSharp\;C:\Program Files (x86)\Microsoft Visual Studio\2019\master\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\master\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\master\Common7\Tools\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Users\davkean\AppData\Local\Microsoft\WindowsApps;C:\Users\davkean\.dotnet\tools                                                                   
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC 
```

# Actual behavior
Newlines are thrown away:
```
                                                                                                                                                                                                              c:\>set path                                                                                                                                                                                    Path=C:\Program Files (x86)\Microsoft Visual Studio\2019\master\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\master\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\master\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\master\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools\;C:\Program Files (x86)\Microsoft Visual Studio\2019\master\Common7\IDE\CommonExtensions\Microsoft\FSharp\;C:\Program Files (x86)\Microsoft Visual Studio\2019\master\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\master\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\master\Common7\Tools\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Users\davkean\AppData\Local\Microsoft\WindowsApps;C:\Users\davkean\.dotnet\tools                                                                   PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC 
```

I've confirmed that @drewnoakes and @davidwengier can also reproduce this. Occasionally it will copy the newlines but have not been able to figure out logic.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request

Making the VT Renderer erase the entire line instead of erasing characters until it reaches the end of the line. Should be more efficient and also set wrapping properly.

## PR Checklist
* [x] Closes #2275 
* [x] CLA signed
* [ ] Tests added/passed
* [x] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments
Honestly, not too sure about this fix. More just want it to be here so that @miniksa and @zadjii-msft can discuss. 

## Validation Steps Performed
If this is right, I should add a test...I'll need some help with that too though.

### CODE REVIEW

**Comment by miniksa** [comment]
@zadjii-msft, I wrote this with Carlos on his computer this afternoon.

I wasn't sure if there is ever a circumstance where the number of characters to be erased is somehow less than the right edge of the viewport.

I think it could theoretically be possible if only a part of the window (not touching the right edge) was invalidated and the painting routines only handed the subsegment of the buffer text into the renderer as a part of drawing.

But I'm not certain. I'm also not certain why you wouldn't have used ^[[K to begin with here to erase the line instead of the less efficient ^[[<n>X unless you had a reason. It looks like you spent quite a bit of time here on trying to make this more efficient with some of the flags detecting whether we should even bother doing ECH.

This is really waiting on your input to proceed.

**Comment by zadjii-msft** [comment]
So you can definitely have text where we need to ECH instead of just EL. Consider:
```
12345678901234567890123456789
Foo                | Bar
```
drawn to the console. There are 16 spaces after "Foo", but there's more text later. This kind of thing can happen with tmux or emacs, where they're drawing panes. Here, we want to ECH to only erase the 16 spaces, but not the rest of the line. If the application were to update the frame to the following:
```
12345678901234567890123456789
Baz                | Bar
```
then EL would corrupt the right pane with "Bar" in it.

<hr>

That all being said, this seems like it's safe. We're still handling the case where we're not erasing all the way to the end of the line. This seems like it might have just been a missed optimization tbh. A missed optimization that just so happened to also break wrapping in the Terminal.

Here's another question - should the ECH handler in the Terminal cause the line to be marked as wrapping? This change is good on it's own, but maybe we need another PR to handle that too. What happens when conhost sees `foo\x1b[120Xbar` (assuming a 120 wide console)? Do we copy that as "foo\<120 spaces>bar" or "foo\<newline>bar"?

**Comment by miniksa** [comment]
> So you can definitely have text where we need to ECH instead of just EL. Consider:
> 
> ```
> 12345678901234567890123456789
> Foo                | Bar
> ```
> 
> drawn to the console. There are 16 spaces after "Foo", but there's more text later. This kind of thing can happen with tmux or emacs, where they're drawing panes. Here, we want to ECH to only erase the 16 spaces, but not the rest of the line. If the application were to update the frame to the following:
> 
> ```
> 12345678901234567890123456789
> Baz                | Bar
> ```
> 
> then EL would corrupt the right pane with "Bar" in it.
> 
> That all being said, this seems like it's safe. We're still handling the case where we're not erasing all the way to the end of the line. This seems like it might have just been a missed optimization tbh. A missed optimization that just so happened to also break wrapping in the Terminal.
> 
> Here's another question - should the ECH handler in the Terminal cause the line to be marked as wrapping? This change is good on it's own, but maybe we need another PR to handle that too. What happens when conhost sees `foo\x1b[120Xbar` (assuming a 120 wide console)? Do we copy that as "foo<120 spaces>bar" or "foo<newline>bar"?

I initially didn't want to change ECH handler because it is using the ->Write method which has implicit newlines when it runs off the end. So the solution there would have been to either change it to using ->WriteLine (with wrap potentially off, figuring it out from the outside.... YUCK.) or to wait until ElectricBoogaloo is done and have some sort of choice with ->WriteStream (which is probably what ECH wanted anyway.)

**Comment by miniksa** [comment]
I guess, unless.... if you treat all ECHs as rectangular write commands then maybe they clear the wrap status whether or not they draw all the way up to the right most cell? That's probably worse.

And one more thought I had is that we could explicitly send a \r\n out the VT when it knows it is going to wrap down. That might force a break and unwrap but also require more ElectricBoogaloo work.

**Comment by zadjii-msft** [comment]
> And one more thought I had is that we could explicitly send a \r\n out the VT when it knows it is going to wrap down. That might force a break and unwrap but also require more ElectricBoogaloo work.

For the record, this is something I meant to investigate in #405. I played with it in like RS5, but I couldn't get it right, maybe because of this nonsense. It's something that would certainly be _more correct_, but we'll need to play with it. Emitting a `\r\n` is certainly shorter that `\x1b[120X\x1b[D`

**Pull request merged**
