### PR TITLE
Localization Updates - fix issues in Korean, Italian, Spanish

### LINKED ISSUE #12665: Inconsistent/incorrect translations in Spanish localization for settings
### Windows Terminal version

1.13.10395.0

### Windows build number

10.0.22572.0

### Other Software

_No response_

### Steps to reproduce

Use Terminal in Spanish, then go to Configuración -> Acciones (Settings -> Actions)

### Expected Behavior

_No response_

### Actual Behavior

Some items are translated inconsistently or incorrectly.
* Most actions use infinitive verbs, but some use imperative: "Cierre la ventana" should be "Cerrar ventana", "Desplácese hacia arriba una página" should be "Desplazarse hacia arriba una página" (likewise for "abajo").
* Some ambiguous words are translated as nouns instead of verbs:
  - "Panel dividido" (as in 'a split panel') should be "Dividir panel" (as in 'do split panel').
  - "Citación de la ventana Quake" ('summon Quake window') should be something like "Invocar ventana de Quake", likewise for "Citación de la ventana de terminal", which also doesn't have Terminal capitalized.
  - "abajo panel de intercambio" should be "Intercambiar panel hacia abajo" (capitalize first word, and change noun by verb), same for all other three directions.
  - "Zoom del panel de alternancia" should probably be "Alternar zoom del panel".

  I would suggest adding notes for the localization team on all items like these that can be understood in multiple ways.
* Next/Previous Tab are translated as "Pestaña anterior" and "Siguiente pestaña" (different order); I'd prefer "Pestaña siguiente" for consistency.

I also noticed that the sorting of the list for picking actions puts the lowercase items at the bottom, so it goes A...Za..z. I would expect it to be Aa...Zz.

### LINKED ISSUE #12712: inconsistent capitalization in Italian profile menu tooltip
### Windows Terminal version

1.13.10395.0

### Windows build number

10.0.19044.1586

### Other Software

_No response_

### Steps to reproduce

Configure Windows Terminal Preview to display in the Italian language.
Press Ctrl+Shift+Space to open the profile menu.
Wait a second and look at the tool tip that pops up.

### Expected Behavior

Consistent capitalization and spacing.

### Actual Behavior

The tool tip has inconsistent capitalization and spacing:

> Apri nuova scheda\
> _ALT + clic per dividere la finestra corrente_
> _MAIUSC+clic per aprire una nuova finestra_
> _CTRL+Clic per aprire come amministratore_

"Alt + clic" has spaces around the plus sign, but "MAIUSC+clic" and "CTRL+Clic" don't.

"CTRL+Clic" capitalizes "Clic", but "Alt + clic" and "MAIUSC+clic" don't.

### LINKED ISSUE #16867: Inconsistent Korean translations in Font Weight settings
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.22631.3235

### Other Software

_No response_

### Steps to reproduce

Set Terminal's language to Korean.
Go to Settings > Profiles > Appearance.
Click on "Font Weight(글꼴 두께)" dropdown menu.

### Expected Behavior

_No response_

### Actual Behavior

Three items have incorrect/inconsistent translations.

|English|Korean|Suggestion|
|-|-|-|
|Thin|얇은|얇게|
|Extra-Light|아주 가늘게||
|Light|밝게|가늘게|
|Semi-Light|약간 가늘게||
|Normal|보통||
|Medium|중간||
|Semi-Bold|약간 굵은|약간 굵게|
|Bold|굵게||
|Extra-Bold|아주 굵게||
|Black|검정||
|Extra-Black|진한 검정||
|Custom|사용자 지정||

### PR DESCRIPTION
**Pull request by consvc**
Closes #12665 
Closes #12712 
Closes #16867

### CODE REVIEW

**Review by DHowett — CHANGES_REQUESTED** [review]
more coming

**Comment by lhecker** [comment]
Specifically: https://task.ms/gcs/553438

**Comment by leejy12** [comment]
This closes #16867 , right?

**Comment by DHowett** [comment]
> This closes #16867 , right?

it should! thanks

**Review by DHowett — APPROVED** [review]

**Review by lhecker — APPROVED** [review]

**Pull request merged**
