### PR TITLE
Avoid passing commands through with the shift modifier

### PR DESCRIPTION
**Pull request by hatf0**
## Summary of the Pull Request
This change would enable keybinds like Ctrl+Shift+C or Ctrl+Shift+V  to work, as they would be captured inadvertently, and sent as their respective escape sequences.

 
## References
#2000 

## PR Checklist
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed

## Validation Steps Performed
Built Terminal on separate instance of Azure Pipelines, then validated that functionality (Ctrl+Shift+V/Ctrl+Shift+C) work as intended (which is, that they properly copy and paste)

### CODE REVIEW

**Comment by zadjii-msft** [comment]
I'm almost certain this isn't the right fix. This would change the behavior of input in conhost.exe, not the Windows Terminal. Could you provide better explanation of why you're making this change at this location in the code? Will this regress any existing behavior?

**Comment by hatf0** [comment]
@zadjii-msft Typically, any control sequence (that is, ^C, ^D, etc) does not (and should not, you can test this with `showkey -a` on any terminal emulator in an Linux environment) require the use of the Shift key. No behavior should be regressed from this, and it's just intended to enable an extra layer of keybinding (i.e Ctrl+Shift+C, Ctrl+Shift+V)

**Comment by DHowett-MSFT** [comment]
However, this low-level input processor is shared between conhost and Windows Terminal. Should Shift be stripped off in the much higher-level `TerminalControl` layer?

**Comment by zadjii-msft** [comment]
Aye, but there are already keybindings that work just fine in conhost on Ctrl+Shift+V and Ctrl+Shift+C. 

Does this affect `INPUT_RECORD`s that are generated for console applications reading input with ReadConsoleInput?

This might be more correct for _just_ the terminal portion of conhost, but I'm worried about the _console_ bits of conhost regressing. 

If this does change the behavior, we should probably add a test to cover it, since it's clearly not covered currently :P

**Comment by hatf0** [comment]
I believe this is already fixed higher up in the input chain (rather then directly at conhost), seemingly inadvertently with #2235 
See: https://github.com/microsoft/terminal/blob/4529e46d3ef4ca2d34a4cf0e95c9389622ee46e7/src/cascadia/TerminalControl/TermControl.cpp#L643-L652

**Pull request closed without merging**
