### PR TITLE
Fix deserialization failure message of combined types

### PR DESCRIPTION
**Pull request by Don-Vito**
## PR Checklist
* [x] Closes https://github.com/microsoft/terminal/issues/7690
* [x] CLA signed. 
* [ ] Tests added/passed
* [ ] Documentation updated. 
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already.

## Validation Steps Performed
Manual tests

### CODE REVIEW

**Review by DHowett — CHANGES_REQUESTED** [review]
So, for all of these except FontWeight, the boolean is not something I'd like to recommend to people. It's something we did for convenience, or something we did for compatibility (closeOnExit), but never _recommended_. I'd be more inclined to leave those ones alone.

For FontWeight, though. We're only adding the exception handling so that we can call our local `TypeDescription`, right?

It seems like FlagMapper and EnumMapper should just use `TBase::TypeDescription`. That will let them _automatically_ get the derived type's description with automatic rollup to the parent's implementation. That way, you don't need to catch/rethrow/etc. :smile:

**Comment by Don-Vito** [comment]
> 
> 
> So, for all of these except FontWeight, the boolean is not something I'd like to recommend to people. It's something we did for convenience, or something we did for compatibility (closeOnExit), but never _recommended_. I'd be more inclined to leave those ones alone.
> 
> For FontWeight, though. We're only adding the exception handling so that we can call our local `TypeDescription`, right?
> 
> It seems like FlagMapper and EnumMapper should just use `TBase::TypeDescription`. That will let them _automatically_ get the derived type's description with automatic rollup to the parent's implementation. That way, you don't need to catch/rethrow/etc. 😄

Actually, I wanted to make TypeDescription `virtual`. Do you see any problem with this?

**Comment by DHowett** [comment]
I'd rather we not do that -- right now it all compiles down to free immediate dispatch without vtable lookups... and we're not particularly _helped_ by making it virtual (since there's workarounds here.)

The converter type never changes _at runtime_, which is the big thing `virtual` would let us do.

**Comment by Don-Vito** [comment]
> 
> 
> I'd rather we not do that -- right now it all compiles down to free immediate dispatch without vtable lookups... and we're not particularly _helped_ by making it virtual (since there's workarounds here.)
> 
> The converter type never changes _at runtime_, which is the big thing `virtual` would let us do.

Yeah. Makes sense. That is why I avoided it in the first place. :blush: 
I will try to call TBase.

**Comment by Don-Vito** [comment]
@DHowett - any reason TypeDescription is not static? I mean I can always do something like:

```
e.expectedType = static_cast<const TBase&>(*this).TypeDescription();
```

or to convert this method to static.

**Comment by Don-Vito** [comment]
Submitted without changing to static.. to make less damage :smile:
Though probably static is a better way to go.

**Review by DHowett — APPROVED** [review]
Love this. Yeah, static thing is weird. I'm interested in cleaning up JsonUtils a little in the future, too. Got a couple todo list items in there :smile:

**Review by zadjii-msft — APPROVED** [review]
Alright, seems cool to me. Thanks!

**Comment by zadjii-msft** [comment]
I'm gonna tag in @DHowett to massage the commit message and make sure that the build doesn't break on merging `main`

**Review by andrewchoi5 — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
Thanks!

**Pull request merged**
