### PR TITLE
Add `--pos` and `--size` cmdline args

### LINKED ISSUE #4620: initialPosition (and others) should be available as commandline args
_initial issue description mentions "per-profile", but consider that they could be commandline arguments_

# Description of the new feature/enhancement

i want to create multiple shortcuts that launch wt at different sizes and screen positions. i'm talking about multiple instances of wt, not multiple tabs within wt.

however, the `initialPosition` setting is global and cannot be overridden on a per-profile basis. ditto for `initialRows`, `initialCols` and `launchMode`. because these are global settings, any shortcut can only launch wt at one position and size.

i'm looking for parity with CMD here. a shortcut to CMD has a bunch of settings tabs, including screen size and position. i have shortcuts to launch CMD in different places for various reasons. i'd like to use shortcuts to launch wt instead.

# Proposed technical implementation details (optional)

allow `initialPosition`, `initialRows`, `initialCols` and `launchMode` to be specified within a profile in settings.json. if that profile is the main one active at launch time, then use them instead of the globals.

### PR DESCRIPTION
**Pull request by ianjoneill**
Adds `--pos`, and `--size` commandline arguments to `wt`.

Closes #4620

### CODE REVIEW

**Comment by ianjoneill** [comment]
I have written some commandline parsing tests, but didn't push them as TAEF is erroring out for some reason when running the `localTerminalApp` test suite:

```
Summary of Errors Outside of Tests:
    Error: TAEF: [HRESULT: 0x80070005] A failure occurred while preparing to run tests in 'TerminalApp.LocalTests.dll'. (Failed to load "F:\windows-terminal\bin\x64\Debug\TestHostApp\TerminalApp.LocalTests.dll" or one of its dependencies.)
```

It's done this to me in the past - when I was back on Windows 10. Upgrading to Windows 11 fixed it for a bit, then it started erroring again.

**Comment by DHowett** [comment]
I'm (vaguely) worried about these, even though we have an open feature request for them. They specify what happens to a new WT window, but they don't control windowing semantics. So, if your settings are such that all invocations launch in the same window, you'll never see the impact of these args unless you add `-w -1` to force the creation of a new window.

In addition, should we consider something more "all-in-one" like xterm's `-geometry` (which takes an x11 geometry spec which looks like `100x300+30+10` or something?

AKA: It's three arguments, should it be one? Or maybe two? We perhaps incorrectly made it three different _settings_... but we don't need to repeat that mistake.

Thoughts? I know I'm just brain-dumping right now.

**Comment by ianjoneill** [comment]
What you are suggesting certainly sounds more powerful. Especially if you allow it to change the location of an existing window. You could _potentially_ open yourself up to malicious programs arbitrarily changing the position of your terminal, but I would imagine that's a low risk - it sounds more annoying than anything else.

Unless I'm reading it wrong, [X's geometry spec](https://linux.die.net/man/7/x#:~:text=Xsecurity%20manual%20page.-,Geometry%20Specifications,-One%20of%20the) seems a bit rigid compared to what terminal currently allows - i.e. you have to provide the complete specification or nothing. Maybe two arguments would be better - a position and a size? e.g. `--position ,200 --size 10,` would give you something that's 200 pixels from the top of the screen and 10 rows tall.

**Comment by serd2011** [comment]
I don't think that changing location of an existing window is natural. Are there any applications where this is implemented?
And I think it's reasonable to expect user to add `-w -1` if he set a setting to launch all invocations in the same window.

**Comment by WSLUser** [comment]
Adding initialRows and initialCols as a single argument makes more sense to me when used this way. You're typically changing both anyways and if you only enter one of them, the other can just remain default. And now that we have semicolons, that can be used as the delimiter to determine which is which (rows first; cols) and yes still need `-w -1` when manipulating the existing window. All these window positioning arguments can easily be scripted together with the other arguments to get the perfect custom setup so it's not a huge deal.

**Comment by ianjoneill** [comment]
@DHowett it's been a couple of weeks since I opened this - have you/the team had any thoughts on what you'd like the command line args to be?

**Comment by zadjii-msft** [comment]
quick 5pm note:

* `--initialPosition x,y`: needs both, makes sense
* `--size c,r`: needs both, accepts size in chars
  - (in the future, we can add `--size {w}px,{h}px`, where a literal `px` would disambiguate between px and chars. And it could be `--size {w}px,r`

**Comment by DHowett** [comment]
> * `--initialPosition x,y`: needs both, makes sense

I'd go further and call it `--pos`; thoughts Mike?

Sorry for the delay @ianjoneill!

**Comment by zadjii-msft** [comment]
> I'd go further and call it `--pos`; thoughts Mike?

sure

**Comment by ianjoneill** [comment]
I've updated the cmdline args as per your suggestions.

**Review by DHowett — APPROVED** [review]
This is simple and I'm cool with it. I don't love our `ProposedSize` implementation, but that's not on you at all. Sheesh, getting data from one end of the app to the other is a bear, innit?

Thanks for doing this & putting up with the delay!

**Comment by ianjoneill** [comment]
We're now in the slightly weird situation where this is documented, but not merged!

https://learn.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows

**Comment by DHowett** [comment]
paging @PankajBhojwani into the ER

**Review by PankajBhojwani — APPROVED** [review]

**Comment by carlos-zamora** [comment]
Since this has two approvals, merging.

@msftbot merge this in 5 minutes

**Pull request merged**
