### PR TITLE
Added even more quick exit in InsertAttrRuns

### PR DESCRIPTION
**Pull request by skyline75489**
## Summary of the Pull Request

In tonight's episode of "I wanna my CPU back", we'll see a quite familiar face whose name is Mr.AttrRow.

 
## References

#2937

## PR Checklist
* [ ] Closes #xxx
* [ ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments

I knew this is possible a long time ago. Just didn't got the chance to actually implement this. I understand that you guys are busy preparing the v1.0 release. So if this is a bad time, this can wait.

## Validation Steps Performed

Manually tested. If all goes well, nothing will be broken.

### CODE REVIEW

**Comment by skyline75489** [comment]
Before:

before2

After:

after2

**Comment by zadjii-msft** [comment]
uhg obey me bot

@msftbot make sure @miniksa signs off on this

**Comment by zadjii-msft** [comment]
@msftbot make sure @miniksa signs off on this

**Comment by miniksa** [comment]
> In tonight's episode of "I wanna my CPU back", we'll see a quite familiar face whose name is Mr.AttrRow.

Bahahahahahahahahahaha.

**Comment by miniksa** [comment]
@msftbot wait 1 minute before merge

**Comment by DHowett-MSFT** [comment]
@msftbot merge this in 1 minute

**Comment by DHowett** [comment]
:tada: Once again, thanks for the contribution!

This pull request was included in a set of conhost changes that was just
released with [Windows Insider Build 20161](https://blogs.windows.com/windowsexperience/2020/07/01/announcing-windows-10-insider-preview-build-20161/).

**Pull request merged**
