### PR TITLE
Send a Ctrl-C KeyUp event

### LINKED ISSUE #1894: Ctrl+C can't be intercepted by PowerShell for shutdown
# Environment

```none
Windows build number: 10.0.18362.175
Windows Terminal version: 0.2.1831.0
PowerShell Core 6.2.1
PowerShell 5.1
```

I'm on a Microsoft Surface Book. There is no Pause key and no Break key. Ctrl+Break is not an option for stopping a program unless I plug in an external keyboard or do some sort of key remapping specifically for this.

# Steps to reproduce

Create a script in PowerShell that intercepts Ctrl+C so it can gracefully shut down. Run that script and try to use Ctrl+C. The script can't intercept it.

It behaves the same in PowerShell Core and in PowerShell.

```powershell
[Console]::TreatControlCAsInput = $True
Start-Sleep -Seconds 1
$Host.UI.RawUI.FlushInputBuffer()
$exiting = $false
while ((-Not $exiting)) {
    Write-Host "Sleeping..."
    Start-Sleep -Seconds 1
    while ($Host.UI.RawUI.KeyAvailable -and ($Key = $Host.UI.RawUI.ReadKey("AllowCtrlC,NoEcho,IncludeKeyUp"))) {
        If ([Int]$Key.Character -eq 3) {
            Write-Warning "Got CTRL-C!"
            $exiting = $true
        }

        $Host.UI.RawUI.FlushInputBuffer()
    }
}
Write-Host "Done."
[Console]::TreatControlCAsInput = $False
```

# Expected behavior

I should be able to hit Ctrl+C to stop the program. In a standard PowerShell terminal (not hosted in the new Microsoft Terminal) this works fine.

# Actual behavior

The program pauses, ostensibly to allow copy/paste behavior to work, and if I hit Enter it continues running. There is no way to capture Ctrl+C.

### PR DESCRIPTION
**Pull request by leonMSFT**
## Summary of the Pull Request
Users were not able to intercept Ctrl-C input using `$Host.UI.RawUI.ReadKey("IncludeKeyUp")`, because we weren't sending a Ctrl-C KeyUp event. This PR simply adds a KeyUp event alongside the existing KeyDown.

## PR Checklist
* [x] Closes #1894
* [x] CLA signed.
* [x] Tests added/passed

## Validation Steps Performed
The repro script in #1894 now works, both options for `ReadKey`: `IncludeKeyUp` and `IncludeKeyDown` work fine.

### CODE REVIEW

**Comment by leonMSFT** [comment]
Actually maybe `WriteCtrlC` should also be sending `Ctrl` Down and Up events? 🤔

**Comment by DHowett-MSFT** [comment]
@msftbot make sure @miniksa signs off

**Comment by DHowett-MSFT** [comment]
Just want to make sure: Control events can be sketchy business here in Terminal land

**Comment by miniksa** [comment]
> Just want to make sure: Control events can be sketchy business here in Terminal land

> This seems sane to me, I'm just worried about the repercussions on ^C generation 😄

The Ctrl+C chord in regular conhost event dispatch land always comes with the pair of down and up. It's actually really weird to only be doing half of it. As far as I can tell, this is what we should have been doing the whole time (until proven otherwise by some mysterious future bug that may or may not exist.)

**Comment by MarcLaf** [comment]
Ctrl+C produces a ^C and does not copy in this release. I still need to use Ctrl+Shift+C.

**Pull request merged**
