### PR TITLE
Convert pasted line endings

### LINKED ISSUE #1091: Pasted text includes CRLF pairs where unneeded
Multiline text pasted from the clipboard includes CRLF pairs in all cases; this is inappropriate for "Unix-space" sessions, such as WSL.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.145]
Windows Terminal version (if applicable): 71e19cd82528d66a0a7867cbed85990cfc1685f1
```

# Steps to reproduce

Select multiline text in Terminal.
Copy it (via right-click, ostensibly)
Paste it (again via right-click)

# Expected behavior

When pasting into a Unix-space session -- such as WSL -- pasted text should have a reasonable set of line-ending characters.

# Actual behavior

Line endings are "doubled" on text paste to Unix-space sessions.

### PR DESCRIPTION
**Pull request by pi1024e**
## Summary of the Pull Request
This is from a PR request by @d-bingham. However, there have been 89 commits since then, and there are merge conflicts that have not been attended to in a month, and I think converting pasted line endings is a neat idea, so this PR has the changes in PR#1094, but rebased to be current.

 
## References
PR#1094

## PR Checklist
* [x ] Closes #1091
* [ x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed
* [x ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
@d-bingham said 

> The new option, convertPasteLineEndings does what it says -- replacing Windows-space CRLF pairs with Unix-space LFs in text pasted to the console. This option applies to both the keyboard-shortcut paste and the right-click paste. Without this most multiline text pasted into Terminal will be "double-spaced" due to the Windows-style CRLF pairs. Furthermore, any multiline text copied from Terminal (in trim whitespace mode) generates CRLF pairs, which guarantees double-spacing when copying from a WSL Terminal session.
Changes:

> - Added TermControl::_SendPastedTextToConnection which adds a pre-processing layer on top of _SendInputToConnection to allow line-ending conversion

> - Various code in Profile/TerminalSettings to support the new option "convertPasteLineEndings" (optional, defaults to false)

## Validation Steps Performed
I performed a manual test, ensuring this would not break any current code.

### CODE REVIEW

**Comment by pi1024e** [comment]
cc @DHowett-MSFT

**Comment by pi1024e** [comment]
Could someone please review this PR. Thank you!

**Comment by DHowett-MSFT** [comment]
@pi1024e I appreciate your excitement, but it’s the weekend here in Redmond where most of the team works. We try not to work _too much_ outside normal working hours.

**Comment by pi1024e** [comment]
Ok, is this good, or are there any requested changes?

**Comment by miniksa** [comment]
It looks like @zadjii-msft and @DHowett-MSFT had outstanding concerns with #1094 and whether it was even being solved in the right place. As such, I'm deferring to them to review this and decide how to proceed.

**Comment by pi1024e** [comment]
fixed

**Comment by pi1024e** [comment]
Rebased to be current. I hope these changes are appropriate!

**Comment by zadjii-msft** [comment]
So for the record, @DHowett-MSFT mentioned in #1094
> I'm not sure this needs to be a setting. conpty should be turning `<CR>` into the right format on the other end. Maybe this is important for other types of connections?

And I concur that's a good hypothesis to investigate. So I don't really want to merge this without first investigating if conpty can just make this happen automatically.

**Comment by pi1024e** [comment]
Conpty does not, and I checked. The question now is: should I change this so the functionality is moved to conpty, or is this good as is?

**Comment by zadjii-msft** [comment]
I would definitely want to make sure the conpty option is investigated first. I don't really have an idea of where to investigate that at the moment - I'd think we'd need to be smarter in the InteractDispatch/InputBuffer area about text that's input from conpty. We'd probably want to take into account the input mode that's set by the client app (if we're not already).

I'd want to know what input records the InputStateMachineEngine is generating for pasted text with newline/carriage returns, and how the input buffer processes that text (compared to a normal conhost window).

**Comment by zadjii-msft** [comment]
@pi1024e I'm going to close this PR for the time being. If you do investigate the conpty copy-paste and find a suitable solution, feel free to open another, or if you find that the conpty route is a dead end, I'd love to see an update on this thread. In the latter case, we'll be happy to re-open this PR.

**Comment by pi1024e** [comment]
Looking at the conpty, I found it does nothing of the sort. That being written, I don't know if I should start over and add this functionality to conpty or keep it here.

**Comment by pi1024e** [comment]
Pasted line endings only really happen when being pasted as input, so I do not think conpty should do that.

**Comment by pi1024e** [comment]
This appears to be the best solution I can come up with

**Comment by pi1024e** [comment]
No, conpty does not fix the line endings

**Comment by pi1024e** [comment]
cc @zadjii-msft

**Comment by gitfool** [comment]
ConEmu gets this right. I'm reluctant to switch to Microsoft Terminal until this is working; functional copy paste from Windows to Linux and vice versa is crucial!

**Pull request closed without merging**
