### PR TITLE
Shell Extension: Remove C++/WinRT authoring dependency

### PR DESCRIPTION
**Pull request by DHowett**
We don't need to use C++/WinRT's component authoring capabilities to be
a COM component. It's easier for us if we're not (and it makes the build
slightly faster!)

Binary size savings (x64 Release):

Note   | WindowsTerminalShellExt.dll
------ | ---------------------------
Before | 136192
After  | 130048
Delta  | 6144
%Delta | 4.5%

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]
will we still be able to use WinRT for like, getting at the settings in TSM.dll?

**Comment by DHowett** [comment]
Good lord, if we remove the fmt dependency (and only the fmt dependency) it drops from 128000 to 71168 (which is a further 44% savings.)

**Comment by DHowett** [comment]
Yeah, we can still consume cppwinrt things. This is just to avoid _producing any_ (we don't have a winmd, we don't have an idl, etc.)

**Review by carlos-zamora — APPROVED** [review]

**Comment by DHowett** [comment]
Size reduction lost a bit. Wonder why.

**Comment by DHowett** [comment]
@msftbot merge this in 2 minutes

**Pull request merged**
