### PR TITLE
Bump the minversion of the Terminal

### LINKED ISSUE #11371: In a coming Terminal version, we'll be bumping the MinVersion to 10.0.19041.0 / 2004 / Vb
_(for MSFT folks, this is bumping the min version from 19H1 to Vb)_

There's a couple big reasons why:
* Vintage opacity only works on Windows 11, and the bug fix will only be serviceable to 19041. 
  * Work was done in #11285 to mitigate this, which can be reverted when we bump the min version
* The OS-side fix to #8238, https://github.com/microsoft/microsoft-ui-xaml/issues/3953, which we need for #1571, will similarly only be able to make it back to 19041
* 18362 (our current min version) "reached end of service after the release of build 18362.1256 on December 8, 2020"<sup>[1](https://support.microsoft.com/en-us/topic/december-8-2020-kb4592449-os-builds-18362-1256-and-18363-1256-expired-c448f3df-a5f1-1d55-aa31-0e1cf7a440a9)</sup> so it's high time y'all updated

When we do this, we should make sure to revert the changes that fixed #11285

### PR DESCRIPTION
**Pull request by zadjii-msft**
As discussed. We're not going to be able to consistently get bugfixes below Vb anymore, so let's leave that as the MinVersion, so we can start adding features that depend on those bugfixes.

* [x] Closes #11371

### CODE REVIEW

**Review by carlos-zamora — APPROVED** [review]
Don't forget to...
> When we do this, we should make sure to revert the changes that fixed 11285

I guess this should be a separate code-health issue? 🤷

**Comment by zadjii-msft** [comment]
> > When we do this, we should make sure to revert the changes that fixed 11285
> 
> I guess this should be a separate code-health issue? 🤷

Meh, we're in an annoying place with that. We're still waiting to get the transparency fix backported, but the person who needs to help us with that is still on leave. So we can't really remove that hack until that's in, but we also plan on bumping the version in this release regardless. 

Lemme ping that thread again. I never got a servicing ticket number to follow, so it might have already been done ¯\\\_(ツ)_/¯

**Comment by miniksa** [comment]
Please check that the UIA tests still run in the lab after this change.

**Review by miniksa — CHANGES_REQUESTED** [review]
Double check UIA test run in lab first please.

**Comment by zadjii-msft** [comment]
> Double check UIA test run in lab first please.

https://dev.azure.com/microsoft/Dart/_build/results?buildId=43624857&view=logs&j=9235745c-fc54-53ad-475a-db0cef308774&t=620c6769-1e8e-5797-d1c8-312bc84864fc

**Review by miniksa — APPROVED** [review]
Task failed successfully.

**Comment by miniksa** [comment]
(aka it's #12131 you're seeing, not a problem from this change)

**Comment by phil-blain** [comment]
Hello, I noticed that the minimum version mentioned in the README was not updated:

https://github.com/microsoft/terminal/blob/d07c53671e98888048bc28b6f67effa4be7a79ca/README.md#L22-L25

It's also mentioned later on in the developer setup requirements:

https://github.com/microsoft/terminal/blob/d07c53671e98888048bc28b6f67effa4be7a79ca/README.md#L283-L288

**Pull request merged**
