### PR TITLE
[1.20] Backport session persistence improvements

### PR DESCRIPTION
**Pull request by lhecker**
This contains all the changes of 5dda507, c4c5206, 9f08ee7, and
5f10159 (#16598 and all related PRs), but without the buffer restore
feature. The hope is that these changes fix some rarer issues
we've been hearing about, where persistence doesn't work correctly.

## Validation Steps Performed
This changeset was tested on Windows 11 with 2 windows and 4 tabs
where 1 tab had 2 mixed split panes. All windows and tabs got
restored properly. It didn't crash on Windows 10.

### CODE REVIEW

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
grab that stable build from the bug bash if you need a test build for Win10!

**Comment by lhecker** [comment]
Done. However, I found that we leak memory every time a window gets opened/closed. Because Visual Studio is a marvel of engineering, I can't tell you what it leaks though. It's been, no joke, 20 minutes:
image

**Comment by DHowett** [comment]
Did that leak turn out to be the xaml content root?

**Comment by lhecker** [comment]
> Did that leak turn out to be the xaml content root?

No it's unrelated.

**Review by zadjii-msft — APPROVED** [review]

**Pull request merged**
