### PR TITLE
A "_random_" color scheme option. Any new window chooses randomly from those in settings.schemes.

### LINKED ISSUE #9422: Support random color scheme, pseudocode [ scheme = rand(settings.schemes) ]
# Description of the new feature/enhancement

There is a site [https://windowsterminalthemes.dev/](https://windowsterminalthemes.dev/), it shares many awesome color themes. I choose some of them, pasted in settings.schemes, then I may change the colorScheme daily depends on my feeling.

The `Oh-My-Zsh` has a similar feature, the random theme, a theme will be chosen randomly every time a new shell is opened.

Wish Windows Terminal could have something like that.

# Proposed technical implementation details (optional)

Introduce a keyword like `random`, so every time a new tag or window is opened, randomly choose a color schema from settings.schemes .

### PR DESCRIPTION
**Pull request by hessedoneen**
## Summary of the Pull Request
If the user sets schema = "\_random", then every new terminal window they open will have a random color scheme applied. This color scheme is chosen from existing schemes in settings.schemes (as compared to colors/fonts being randomly generated).

## Detailed Description of the Pull Request / Additional comments
Pull request will pass all of the following tests:
1.  "\_random" chooses from both default and user added schemes (also ensure last or first never gets ignored)
2. "\_random" will work even if there are only default schemes
3. "\_random" will work no matter how many (or which) default schemes there are (will not hard code in Campbell/Vintage/Tango or anything)
4.  If someone tries to add a new scheme named "\_random" then their new random scheme will take precedence (following current convention where if you make a new "Campbell" scheme, then the new scheme will show up instead.

## Validation Steps Performed
N/A yet

### CODE REVIEW

**Comment by hessedoneen** [comment]
Cases I don't know how to handle yet:
- What to do if default and user made schemes are both empty? I don't think this can happen since users can't edit defaults.json, but I want to make sure I follow what y'all are doing.
- I am pretty sure if a user defines "\_random\_" then it will automatically take care of test4, because I'm only checking if the scheme == "\_random\_" if it was already not found in the lookup, but I'm not sure yet until I implement everything

**Comment by hessedoneen** [comment]
Chosen Implementation:
"\_random\_" is a keyword, and when present the scheme will randomly load one of the other defaults schemes
- Pro: does not introduce too much change, can work quickly
- Con: requires future programmers to know about and account for the "\_random\_" scheme case, which is applied functionally different from the other schemes.

Another implementation I considered: "\_random\_" comes as a "dummy" default scheme which is never used -

- Pro: Do not have to hard-code in exceptions outside of TerminalSettings.cpp for applying "\_random\_". Future programmers don't even really have to know about "\_random\_"'s existence outside of TerminalSettings.cpp
- Con: I don't know much about security, but if users aren't allowed to edit defaults.json, I assume overwriting "\_random\_" housed in defaults.json is a big no-no. If this is a problem we could start off userDefaults.json with a single scheme "\_random\_", with a comment saying what it does?
- Con: I think opening a closing lots of windows, all of which rewrite the userDefaults.json, could lead to some weird race conditions. We could implement it so the file is not actually overwritten?
- Con: this approach was getting more and more complicated the more I thought about it, and could be difficult to make follow the same default behavior as the other schemes.

**Comment by zadjii-msft** [comment]
I think this is a great writeup! My thoughts:
* I definitely like the chosen implementation over the "_"_random_" comes as a "dummy" default scheme which is never used_" implementation. This way seems much easier to me. 
* I know I said in #9422 that the key should be `_random_`, but after the work that's being done in #9785, maybe we should align on `_random` (to be closer to `_quake`)


> What to do if default and user made schemes are both empty
That definitely can't happen, so don't worry about that. If that was possible, then we'd have much bigger problems to worry about 😄 

> If someone tries to add a new scheme named "_random_" then their new random scheme will take precedence

That seems sensible to me


I look forward to the whole PR!

**Comment by hessedoneen** [comment]
Okay great! Thank you for the feedback and I look forward to it too haha :)

**Comment by hessedoneen** [comment]
Before I decided how to choose a scheme randomly, I wanted to make sure I could apply a scheme name which technically doesn't exist.

The first thing I tried was searching the following warning which comes up whenever I set the scheme to "\_random":
> "Found a profile with an invalid "colorScheme". Defaulting that profile to the default colors. Make sure that when setting a "colorScheme", the value matches the "name" of a color scheme in the "schemes" list."

Which took me down this line of files/functions/variables:
> TerminalApp/Resources/en-US/Resources.resw::UnknownColorSchemeText -->
> TerminalApp/AppLogic.cpp::settingsLoadWarningsLabels -->
> TerminalApp/AppLogic.cpp::_GetWarningText -->
> TerminalApp/AppLogic.cpp::_ShowLoadWarningsDialog -->
> TerminalApp/AppLogic.cpp::_ShowLoadWarningsDialog::_warnings -->

At that point I realized I didn't understand the warnings system well enough to trace backward easily so I thought I would try a less frictioned way to find the warning throwing code: If the warning is thrown every time a scheme name is not found in ColorScheme, just find every instance where the color schemes are searched.

In this push I tried to do so. I tried to find and change every instance of .TryLookup() on a ColorScheme object I could find (when it didn't work when I changed the first one I just changed them all), but when I ran the terminal it still threw the warning :[

Could anyone give me some pointers on where to account for this error? Or maybe showing me where the documentation on how all these warnings objects mix with one another if that's the route I should go down? Or just any advice really, haha, thank you.

**Comment by hessedoneen** [comment]
Also, this probably won't apply once I figure out where the error is actually handled, but all the functions I've had to edit so far ask for some behavior based on a ColorScheme object. Whether it was calling .ApplyColorScheme([some scheme which should come from "/_random"]), or "get_strong"?, or something like that.

I just let "/_random" be L"Campbell" in these intermediate steps, but it kind of makes me reconsider whether there should be a dummy "/_random" scheme? Because its random name wouldn't have been chosen by this point, right?

**Comment by hessedoneen** [comment]
**WAIT READ FIRST PLS :**
What if its random name is chosen immediately after the user inputs "_/random" in their settings.json? If a random one is chosen immediately after input, then there won't be a need to account for it later. It'll immediately change its name to "Campbell" or "Tango Light" or whatever the random choice is. And then the previous framework will take care of it all correctly.

**Comment by zadjii-msft** [comment]
Hey so that warning is coming from `CascadiaSettings::_ValidateSettings`, specifically `CascadiaSettings::_ValidateAllSchemesExist`. I'd probably just add a case in that method to skip validating `_random` as the name of a scheme. That should probably make the rest of the code just work ☺️ 

> It'll immediately change its name to "Campbell" or "Tango Light" or whatever the random choice is

I think it's a cool idea, but A: I think it would be harder to implement. B: It would involve writing out the settings file when someone edits the scheme, even in json, and that's highly fraught with peril. We just tend to avoid it, because that means the file is going to get reformatted, and people generally don't love that. And C: I _personally_ want this setting for "pick a random scheme each and every time". Like, I want the setting to be useful for booting to different schemes each time.

**Comment by zadjii-msft** [comment]
> I just let "/_random" be L"Campbell" in these intermediate steps, but it kind of makes me reconsider whether there should be a dummy "/_random" scheme? Because its random name wouldn't have been chosen by this point, right?

After reading the diff, it almost seems like we should have a helper for 

```c++
GlobalSettings().ColorSchemes().TryLookup(*schemeName)
```

that's instead something like:
```c++
ColorScheme GlobalAppSettings::ResolveColorScheme(winrt::hstring name) {
    if (const auto scheme = ColorSchemes().TryLookup(realArgs.SchemeName()))
    {
        return scheme;
    }
    else if (realArgs.SchemeName() == winrt::to_hstring(L"_random"))
    {
        // do whatever to get a random scheme
        return scheme;
    }
    return nullptr;
}
```

So that we can do the logic for `_random`  in only one place

**Comment by hessedoneen** [comment]
That's a really great solution! Thank you so much for pointing me in the right direction, I had been looking for it for so long! I'm excited to get working on it now, and I really appreciate you helpful and thoughtful responses :)

**Comment by hessedoneen** [comment]
Update:
So I wanted to make sure I could get the warning to stop at all before I went and implemented accounting for it, but I don't think I can do this only in `CascadiaSettings`. I removed the warning appending you mentioned, then every other warning I could find that seemed related to ColorScheme, then every warning which was appended at all in the file, but none of these fixed the problem. So I think this behavior might be reinforced in another file as well, or also I may have missed one.

I just cleaned the project in visual studio too and rebuilt but that wasn't the problem either. I'll keep working and seeing if I can find what I'll have to remove to get this error to stop.

**Comment by zadjii-msft** [comment]
Weird. Hopefully I'll get a chance later this week to check out this branch and investigate.

**Comment by DHowett** [comment]
Hey there! Since this one has been in draft for a couple years, I'm hitting it as part of my cleanup spree.. I love this idea, and I'm sorry we weren't able to converge. You're always welcome here! :smile:

**Pull request closed without merging**
