### PR TITLE
Remove static analysis builds because they're running out of disk space.

### PR DESCRIPTION
**Pull request by miniksa**
@DHowett-MSFT has a thread with the relevant people trying to sort this whole thing out.

But in the meantime, the static analysis builds are low value and are blocking actual work from happening.

So I commented them out for now.

### CODE REVIEW

**Comment by adiviness** [comment]
This is annoying to see.

**Comment by miniksa** [comment]
> This is annoying to see.

I know, but I need to merge things today. I want to get them back online.

**Comment by miniksa** [comment]
> Shall I be the guy? Want to whack a TODO and a followup issue to re-enable these?

Yes, I'll write one.

**Comment by adiviness** [comment]
> 
> 
> > This is annoying to see.
> 
> I know, but I need to merge things today. I want to get them back online.

I understand. I approved but it doesn't hold the same weight it used to. You'll need a real 2nd approver.

**Pull request merged**
