### PR TITLE
Ensure X/Y controls are updated when default launch pos selected

### PR DESCRIPTION
**Pull request by ianjoneill**
Ensures the X & Y XAML controls are updated when the default launch position checkbox is toggled.
References #14518

### CODE REVIEW

**Comment by ianjoneill** [comment]
I must be _extremely_ unlucky with the CI.

**Review by zadjii-msft — APPROVED** [review]

**Review by PankajBhojwani — APPROVED** [review]
Thanks!

**Review by DHowett — APPROVED** [review]
Thanks!

**Comment by DHowett** [comment]
And yes, we have all been getting quite unlucky with the CI. It's not a good look.

**Pull request merged**
