### PR TITLE
Bind Ctrl+Numpad Plus,Minus to the font size controls

### LINKED ISSUE #7518: Font size can't be changed while using + and - from numeric keypad
# Environment

Microsoft Windows [Version 10.0.19041.450]
Windows Terminal version (if applicable): latest preview

# Steps to reproduce

- Hold Ctrl and press + or - from numeric keypad

# Expected behavior

- font size should increase or decrease

# Actual behavior

- nothing happens

### PR DESCRIPTION
**Pull request by hessedoneen**
"ctrl+numpad_plus" command now increases font size and
"ctrl+numpad_minus" command now decreases font size.

Before this only "ctrl+=" and "ctrl+-" controlled font size. Increase in
font size follows previous convention where zooms in arbitrarily large,
but decrease in font size is capped.

## Validation Steps Performed
I first ran "ctrl+=" and "ctrl+-" in my terminal to verify its behavior,
then compared that against "ctrl+numpad_plus" and "ctrl+"numpad_minus".
Both increased and decreased the font size by the same amount, and both
appeared to have a cap for how small they could get, but did not appear
to have a cap for how big they could get.

Closes #7518

### CODE REVIEW

**Comment by zadjii-msft** [comment]
Yep, I'm pretty sure that's all that needs to be done here. Have you been able to build the Terminal and verify that the numpad keys now work for changing the font size?

**Comment by hessedoneen** [comment]
Hey! I'm actually having trouble building the project. I have been able to run the available tests from the command line, and they're passing the same as the original code, but I'm not familiar with VS and I've had trouble "building"? "launching"? the terminal into something I can interact with. A lot of the time I have spent on this so far has been googling and trying to get used to the VS interface and how they set up projects.

But if you're interested in where I am the thing I'm trying right now is:
`git submodule update --init --recursive`
`.\tools\razzle.cmd`
`bcz`

and then following these instructions:
'right click on CascadiaPackage (in the Solution Explorer) and go to properties. In the Debug menu, change "Application process" and "Background task process" to "Native Only".  Build & debug the Terminal project by hitting F5'

I think that's right? I am not familiar with VS though, so I don't know where the debug menu is, or how to change its settings, and there are 8 things named something similar to "CascadiaPackage", so I'm just using trial & error to figure these things out haha.

Thank you for checking up on me!

**Comment by hessedoneen** [comment]
Hello! I just got everything built and running and I manually checked it too. Is there any documentation on how to run the Unit tests correctly? I ran from the command line before I ever made any changes, but there were still a couple API checks which did not pass even then, which tells me I'm doing something wrong.

My process is now:
1. Clean CascadiaPackage
2. Rebuild CascadiaPackage
3. Deploy CascadiaPackage
4. Test > Run all tests

Is there another way I'm supposed to do this? What output should be expected and is okay to push with? Will this way run all of `runut.cmd`, `runft.cmd`, `runuia.cmd`, and `runformat` mentioned in "How to build OpenConsole"?

Sorry if this is a little bit a lot. I haven't contributed to open source before, and so I'm trying to get the hang of it all (as well as Visual Studio).

Thank you for all your help!

**Comment by hessedoneen** [comment]
I am about to write an issue request for testing clarification. I tried to run them with what I saw in:
- [How to build OpenConsole](https://github.com/microsoft/terminal/blob/fb597ed304ec6eef245405c9652e9b8a029b821f/doc/building.md)
- [TAEF.md](https://github.com/microsoft/terminal/blob/fb597ed304ec6eef245405c9652e9b8a029b821f/doc/TAEF.md)
- [doc: address how to use TAEF](https://github.com/microsoft/terminal/pull/7590)

But they were not passing on my local computer (even before I made any changes). Since this one has passed all your checks, and because it wasn't really any new logic, I am going to make this a full pull request now. I'll definitely be in the issues though asking for some testing help.

**Comment by zadjii-msft** [comment]
Which _specific_ tests didn't pass locally? There's a couple known test failures right now, but this PR _certainly_ shouldn't have caused them.

**Review by zadjii-msft — APPROVED** [review]

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@hessedoneen thanks so much for working on this! :smile: I changed the title and the description of your pull request so that they would show up in our commit history with a more descriptive title.

**Comment by hessedoneen** [comment]
Thank you so much! I'll take note and try to make future pulls similar in conciseness / style :)
I was running the tests just now to get all the ones which didn't pass, and I ended up running it in powershell instead and it went a lot better for some reason?


The output from powershell says everything passed, but just has a couple errors:
```
Invoke-OpenConsoleTests -AllTests
...
Summary: Total=329, Passed=329, Failed=0, Blocked=0, Not Run=0, Skipped=0
Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At C:\Users\hesse\481\p6-open-source\terminal\tools\OpenConsole.psm1:132 char:5
+     Start-Process $OpenConsolePath -Wait -ArgumentList "powershell.ex ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At C:\Users\hesse\481\p6-open-source\terminal\tools\OpenConsole.psm1:132 char:5
+     Start-Process $OpenConsolePath -Wait -ArgumentList "powershell.ex ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

But there are a lot of failures for my cmd prompt:

```
runut.cmd
...
Summary of Errors Outside of Tests:
    Error: TAEF: [HRESULT: 0x80070005] A failure occurred while preparing to run tests in 'TerminalApp.LocalTests.dll'. (Failed to load "C:\Users\hesse\481\p6-open-source\terminal\bin\x64\Debug\TestHostApp\TerminalApp.LocalTests.dll" or one of its dependencies.)
    Error: TAEF: [HRESULT: 0x80070005] A failure occurred while preparing to run tests in 'SettingsModel.LocalTests.dll'. (Failed to load "C:\Users\hesse\481\p6-open-source\terminal\bin\x64\Debug\TestHostApp\SettingsModel.LocalTests.dll" or one of its dependencies.)

Summary of Non-passing Tests (showing 20 of 150):
    ApiRoutinesTests::ApiGetConsoleTitleA [Failed]
    ApiRoutinesTests::ApiGetConsoleOriginalTitleA [Failed]
    TerminalAppLocalTests::CommandlineTest::ParseSimpleCommandline [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseTrickyCommandlines [Blocked]
    TerminalAppLocalTests::CommandlineTest::TestEscapeDelimiters [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseSimpleHelp#metadataSet0 [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseSimpleHelp#metadataSet1 [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseSimpleHelp#metadataSet2 [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseSimpleHelp#metadataSet3 [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseBadOptions#metadataSet0 [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseBadOptions#metadataSet1 [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseBadOptions#metadataSet2 [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseSubcommandHelp#metadataSet0 [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseSubcommandHelp#metadataSet1 [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseSubcommandHelp#metadataSet2 [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseSubcommandHelp#metadataSet3 [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseBasicCommandlineIntoArgs [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseNewTabCommand#metadataSet0 [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseNewTabCommand#metadataSet1 [Blocked]
    TerminalAppLocalTests::CommandlineTest::ParseSplitPaneIntoArgs#metadataSet0 [Blocked]

Summary: Total=7098, Passed=6948, Failed=2, Blocked=144, Not Run=0, Skipped=4
```
```
runft.cmd:
...
Summary of Non-passing Tests:
    DimensionsTests::TestGetLargestConsoleWindowSize [Failed]
    InputTests::TestMouseWheelReadConsoleMouseInput [Skipped]
    InputTests::TestMouseHorizWheelReadConsoleMouseInput [Skipped]
    InputTests::TestMouseWheelReadConsoleNoMouseInput [Skipped]
    InputTests::TestMouseHorizWheelReadConsoleNoMouseInput [Skipped]
    InputTests::TestMouseWheelReadConsoleInputQuickEdit [Skipped]
    InputTests::TestMouseHorizWheelReadConsoleInputQuickEdit [Skipped]

Summary: Total=406, Passed=399, Failed=1, Blocked=0, Not Run=0, Skipped=6
```
```
runuia.cmd
...
Summary of Non-passing Tests:
    Conhost.UIA.Tests.AccessibilityTests.CanAccessAccessibilityTree [Failed]
    Conhost.UIA.Tests.AccessibilityTests.CanCloneTextRangeProvider [Failed]
    Conhost.UIA.Tests.KeyPressTests.VerifyCtrlZCmd [Failed]
    Conhost.UIA.Tests.KeyPressTests.VerifyCtrlHCmd [Failed]
    Conhost.UIA.Tests.KeyPressTests.VerifyCtrlCCmd [Failed]
    Conhost.UIA.Tests.MiscTests.DotNetSetWindowPosition [Failed]
    Conhost.UIA.Tests.MouseWheelTests.TestMouseWheel [Failed]
    Conhost.UIA.Tests.SelectionApiTests.TestCtrlHomeEnd [Failed]
    Conhost.UIA.Tests.SelectionApiTests.TestKeyboardSelection [Failed]
    Conhost.UIA.Tests.SelectionApiTests.TestMouseSelection [Failed]
    Conhost.UIA.Tests.VirtualTerminalTests.RunVtAppTester [Failed]

Summary: Total=12, Passed=1, Failed=11, Blocked=0, Not Run=0, Skipped=0
```

Is this normal? Which one should I run against for future pull requests do you think?
Thank you so much for your help. This is super exciting, and I appreciate all your support :)

**Comment by zadjii-msft** [comment]
Alright so: 
* I'm not sure about this powershell error. Never seen anything like that before, but I use the cmd version of the tools so I'm not a lot of help here.
* The "local" tests are notoriously finicky. Someone else on the team was hitting a bug just like that recently. You might have a better chance building the `TestHostApp` project first, but if that doesn't work, don't sweat it. Those don't run in the CI, so we've just got to run them locally every so often to make sure nothing regresses 😂
* As far as the feature (`runft`) and UIA (`runuia`) tests go - those are also really touchy. you've got to immediately stop using your PC as soon as you start those tests, because they'll drive your mouse, so anything you do will mess with the test. They _do_ run in CI, so I wouldn't be too worried about running them before a PR.

**Comment by hessedoneen** [comment]
This is super helpful feedback :)
I will build TestHostApp first from now on and see if that makes a difference. I look forward to keeping working!

**Pull request merged**
