### PR TITLE
Use ControlProperties macros everywhere

### PR DESCRIPTION
**Pull request by zadjii-msft**
When I added these macros in #11619, the real purpose was to make sure we don't forget to add new settings to these test mocks as well. However, I totally forgot to convert those. I guess that happens with a 1300 line diff ¯\\\_(ツ)_/¯

* [x] Is a codehealth thing
* [x] I work here
* [x] tests still pass

### CODE REVIEW

**Review by miniksa — APPROVED** [review]
Thank you!

**Review by carlos-zamora — APPROVED** [review]

**Review by lhecker — APPROVED** [review]

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in 2 minutes

**Review by PankajBhojwani — APPROVED** [review]

**Comment by zadjii-msft** [comment]
# 5 / 5 ✅

**Comment by lhecker** [comment]
Gotta make sure PRs are properly reviewed!

**Pull request merged**
