### PR TITLE
Make sure to disable pane entrance animation if user requests

### PR DESCRIPTION
**Pull request by Don-Vito**

### CODE REVIEW

**Comment by Don-Vito** [comment]
@zadjii-msft - please review

**Comment by skyline75489** [comment]
Is there a issue for this? I vaguely remember this is one...

**Comment by Don-Vito** [comment]
@skyline75489 - no issue for this. I encountered that while fixing https://github.com/microsoft/terminal/issues/8230

**Comment by skyline75489** [comment]
Oh no problem. Guess I’m lost in issues 😅

Thanks for the work

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Don-Vito <notifications@github.com>
发送时间: Thursday, November 12, 2020 6:55:58 PM
收件人: microsoft/terminal <terminal@noreply.github.com>
抄送: Chester Liu <skyline75489@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [microsoft/terminal] Allow disabling entrance animation from settings (#8237)


@skyline75489<https://github.com/skyline75489> - no issue for this. I encountered that while fixing #8230<https://github.com/microsoft/terminal/issues/8230>

**Review by zadjii-msft — APPROVED** [review]
Well that's the darndest thing, the animation definitely doesn't play for me if I enable the setting. That's really bizarre. I'd love for someone else to confirm that the setting isn't working as it currently is, just for my own sanity. 

In the meantime, this will definitely work, so :shipit:

**Comment by Don-Vito** [comment]
> 
> 
> Well that's the darndest thing, the animation definitely doesn't play for me if I enable the setting. That's really bizarre. I'd love for someone else to confirm that the setting isn't working as it currently is, just for my own sanity.
> 
> In the meantime, this will definitely work, so :shipit:

Sanity is important in our days 😄 . Do you say don't enter it even with a debugger (my debugger definitely gets there)

**Review by DHowett — APPROVED** [review]
Good eye!

**Pull request merged**
