### PR TITLE
Remove the Solarized color schemes from the defaults

### PR DESCRIPTION
**Pull request by DHowett**
Solarized is not suitable for Terminal use, and as such, these themes are a bug factory.
If users want these, they can add them back themselves.

There's a number of discussions, both open and closed, about Solarized's insuitability as a default scheme. Here's my proposal: everyone who is using Solarized today will be using Campbell tomorrow. We will get an influx of issues complaining about the colors not working, but we will stop getting reports that "i can't see my text" and "you were mistaken for including these."

## PR Checklist
* [ ] Closes #xxx
* [ ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

### CODE REVIEW

**Comment by j4james** [comment]
I'm very much in favour of getting these schemes out of the defaults, but I did wonder whether it might be necessary to include some sort of backwards-compatibility hack that auto-updated users that were already using _Solarized_, maybe patching their settings with a custom instance of the scheme? I'm not sure if that's feasible, or worth the effort, but perhaps it's worth checking the telemetry to get an idea of how many users this would actually affect.

**Comment by soul4soul** [comment]
If it counts for anything VS Code ships modified solarized themes

[VS Code Solarized Dark](https://github.com/microsoft/vscode/blob/db2f1d929c48ba6abb0e066f21f8eb62acdd2cbd/extensions/theme-solarized-dark/themes/solarized-dark-color-theme.json) This is a snip of the terminal color portion. I'm not sure which background and foreground is used for the terminal.  It could be "editor.background"?
```
		"terminal.ansiBlack": "#073642",
		"terminal.ansiRed": "#dc322f",
		"terminal.ansiGreen": "#859900",
		"terminal.ansiYellow": "#b58900",
		"terminal.ansiBlue": "#268bd2",
		"terminal.ansiMagenta": "#d33682",
		"terminal.ansiCyan": "#2aa198",
		"terminal.ansiWhite": "#eee8d5",
		"terminal.ansiBrightBlack": "#586e75", // This is the modified 
		"terminal.ansiBrightRed": "#cb4b16",
		"terminal.ansiBrightGreen": "#586e75",
		"terminal.ansiBrightYellow": "#657b83",
		"terminal.ansiBrightBlue": "#839496",
		"terminal.ansiBrightMagenta": "#6c71c4",
		"terminal.ansiBrightCyan": "#93a1a1",
		"terminal.ansiBrightWhite": "#fdf6e3"
```

[VS Code Solarized light](https://github.com/microsoft/vscode/blob/40077f5ea98dfb9cb801c84f74f64cb33b589084/extensions/theme-solarized-light/themes/solarized-light-color-theme.json)

And a referencing to #4480 where more discussion on the topic occurred

**Comment by gordonmessmer** [comment]
I agree with @soul4soul .  It would be easier to fix the bug in the short term without breaking existing configurations if Terminal simply modified the Solarized themes so that none of the foreground colors are identical to the background color.

The biggest problem with Solarized isn't that the theme is broken (which, to be clear, it is.  There's no good reason to have matching foreground and background colors), the biggest problem is that Terminal treats "bold" text as being bright *white* specifically, which makes all of the light-background themes bad.

I gathered some information for #109, and in doing so I found that *most* terminal emulators, in their default configuration, have at least one matching foreground and background color, producing invisible text.  Yet those emulators don't (as far as I can tell) suffer the steady stream of bug reports that Windows Terminal does.

I'm convinced that this bug is unique, and specific to Windows Terminal, simply because it is the only terminal emulator where "bold" means "white".

**Comment by DHowett** [comment]
I'd like to put a pin in this for now, and come back to it when we have the ability to patch it into a user's settings if she's using Solarized. Gonna close pending discussion in #6618.

**Pull request closed without merging**
