### PR TITLE
UTF8 torture test text file and a solution dependency graph diagram

### PR DESCRIPTION
**Pull request by oising**
## Summary of the Pull Request

Provide a slightly abridged solution dependency diagram...

solution-dependencygraph

... and a UTF8 "torture test" text file that I've had for a while. It runs through the gamut of UTF8 trickery  to ensure conformance and rendering ability. 

## PR Checklist
* [ ] Closes #xxx
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: n/a (spoke with Mike Z over twitter)

### CODE REVIEW

**Comment by oising** [comment]
@DHowett-MSFT I used a tool (resharper) to build it and removed some cruft and minor things. I guess I'd have to update it myself should that happen? Hardly optimal but I'm okay with it -- it only took about ten minutes.

**Comment by zadjii-msft** [comment]
@oising forgive me for not really knowing how resharper works, but is there like a raw file that's used to render this diagram? Something like a `.psd` that's used as the working file, then exported as a `.png`? I think I'd be more comfortable checking it in if there was an easy way for someone to update the graph when they changes (i.e. me making changes in #1164).

**Comment by oising** [comment]
@zadjii-msft Good idea -- I'll have a look.

**Comment by zadjii-msft** [comment]
Eh, it's probably fine as is. The changes I'm making in that PR aren't that fundamentally different from what you have in the diagram, so it's definitely still useful

**Comment by oising** [comment]
If you want to ping me when you're about to merge the PR, I'm sure I could update it fairly quickly.

**Pull request merged**
