### PR TITLE
Add support for DA2 and DA3 device attributes reports

### LINKED ISSUE #5836: No support for xterm Send Device Attributes (Secondary DA) control sequence
# Environment

Windows build number:  [Version 10.0.19041.208]
Windows Terminal version (if applicable): 0.11.1251.0

# Steps to reproduce

`echo -e '\e[>c'`

# Expected behavior

A secondary device attribute response providing information that better describes what capabilities Windows Terminal actually supports.

Excerpt from [xterm ctl sequences](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_):
```
CSI > Ps c
          Send Device Attributes (Secondary DA).
            Ps = 0  or omitted ⇒  request the terminal's identification
          code.  The response depends on the decTerminalID resource set-
          ting.  It should apply only to VT220 and up, but xterm extends
          this to VT100.
            ⇒  CSI  > Pp ; Pv ; Pc c
          where Pp denotes the terminal type
            Pp = 0  ⇒  "VT100".
            Pp = 1  ⇒  "VT220".
            Pp = 2  ⇒  "VT240" or "VT241".
            Pp = 1 8  ⇒  "VT330".
            Pp = 1 9  ⇒  "VT340".
            Pp = 2 4  ⇒  "VT320".
            Pp = 3 2  ⇒  "VT382".
            Pp = 4 1  ⇒  "VT420".
            Pp = 6 1  ⇒  "VT510".
            Pp = 6 4  ⇒  "VT520".
            Pp = 6 5  ⇒  "VT525".

          and Pv is the firmware version (for xterm, this was originally
          the XFree86 patch number, starting with 95).  In a DEC termi-
          nal, Pc indicates the ROM cartridge registration number and is
          always zero.
```

# Actual behavior
No response to control sequence

# Why this matters right now?

When Windows Terminal sets `TERM` to be `xterm-256color`, certain popular applications expect it to respond to xterm control sequences. I came across this issue (and suspect many others have as well, although it's surprising to me that I didn't see an existing issue for it) because Emacs was hanging for 2 seconds on load whenever being launched inside Windows Terminal due to code in `xterm.el` ([see here](https://github.com/emacs-mirror/emacs/blob/master/lisp/term/xterm.el#L704)) (part of its terminal-capability-determination startup code) that queries the capabilities of xterm using the Secondary Device Attribute control sequence. Other terminals that masquerade as xterm (such as iTerm2, OS X's Terminal, and gnome-terminal) respond to this query.

### PR DESCRIPTION
**Pull request by j4james**
This PR adds support for the `DA2` (Secondary Device Attributes) and
`DA3` (Tertiary Device Attributes) escape sequences, which are standard
VT queries reporting basic information about the terminal.

The _Secondary Device Attributes_ response is made up of a number of
parameters:
1. An identification code, for which I've used 0 to indicate that we
   have the capabilities of a VT100 (using code 0 for this is an XTerm
   convention, since technically DA2 would not have been supported by a
   VT100).
2. A firmware revision level, which some terminal emulators use to
   report their actual version number, but I thought it best we just
   hardcode a value of 10 (the DEC convention for 1.0).
3. Additional hardware options, which tend to be device specific, but
   I've followed the convention of the later DEC terminals using 1 to
   indicate the presence of a PC keyboard.

The _Tertiary Device Attributes_ response was originally used to provide
a unique terminal identification code, and which some terminal emulators
use as a way to identify themselves. However, I think that's information
we'd probably prefer not to reveal, so I've followed the more common
practice of returning all zeros for the ID.

In terms of implementation, the only complication was the need to add an
additional code path in the `OutputStateMachine` to handle the `>` and
`=` intermediates (technically private parameter prefixes) that these
sequences require. I've done this as a single method - rather than one
for each prefix - since I think that makes the code easier to follow.

VALIDATION
----------

I've added output engine tests to make sure the sequences are dispatched
correctly, and adapter tests to confirm that they are returning the
responses we expect. I've also manually confirmed that they pass the
_Test of terminal reports_ in Vttest.

Closes #5836

### CODE REVIEW

**Comment by j4james** [comment]
For the record, I'm happy to consider returning a genuine version number in DA2 and some kind of ID in DA3 if that's preferable, but I thought we'd probably want to remain essentially anonymous. For more info on how these sequences are implemented and used, see issue https://github.com/microsoft/terminal/issues/5836#issuecomment-648204837.

**Comment by DHowett** [comment]
So, it looks like xterm (344) responds to `DA2` as a "VT420", firmware version "344", 0 (`^[[>41;344;0c`) in the default configu shipped with Debian buster.

I know that Vim, as an example, uses the xterm version, but I don't know if it uses `DA2` or `\e[>0q` to do so.

For what it's worth, I can't get that build of xterm to respond to `\e[>0q`, and vim fails to autodetect it ... :smile: so I'm guessing it doesn't use `DA2`.

Regardless; how much should we pretend to be xterm and how much should we not? Open question!

**Comment by DHowett** [comment]
I do like the idea of remaining anonymous; I don't want people taking dependencies (like vim has done with xterm) on our implementation details especially when they change so rapidly in Terminal (and so slowly in Windows).
There's also no stable version number that we can use across Windows conhost and OpenConsole that would be monotonically increasing such that an application _could_ rely on it.

**Comment by DHowett** [comment]
I see now that you literally covered everything I just said, in the comment I opened to "read after I wrote my comments". Sorry. 😬

**Comment by j4james** [comment]
Note that the `\e[>0q` sequence is a relative new thing. XTerm only added it in April (patch 354). I think it arose from discussions about standardising the `TERM_PROGRAM` and `TERM_PROGRAM_VERSION` environment variables (which is issue #1040 for us). But I'm in agreement with you that we're better off remaining anonymous and not supporting stuff like that until the app is more stable.

**Pull request merged**
