### PR TITLE
Typos: Incorrect use of the possessive of "it".

### PR DESCRIPTION
**Pull request by jroberts101**
Should use "its" rather than "it's".

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
@jroberts101 thanks for keeping us honest. Is there some way you could do this in a single pull request instead of one per file? Thanks!

**Comment by jroberts101** [comment]
Thanks for your response @DHowett-MSFT .
My apologies. Unfortunately I'd reviewed `Terminal-master\doc\cascadia\TerminalSettings-spec.md` and created the Pull Request before I saw the same issue in `Terminal-master\doc\cascadia\Keybindings-spec.md`.

**Comment by DHowett-MSFT** [comment]
That’s okay! You can push new changes to the same branch you already made for this pull request. Git is pretty cool like that!

________________________________

**Comment by DHowett-MSFT** [comment]
Eh, I'll just reopen this one.

**Pull request merged**
