### PR TITLE
Add .clang-format

### PR DESCRIPTION
**Pull request by fcharlie**
These files help to unify the source format. 
These two files are from: https://github.com/microsoft/calculator

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
@microsoft/windows-console-team anyone know if the calculator style matches our style? It should, since it came from windows ...

I'm worried about introducing a `.clang-format` without simultaneously reformatting all the code. I _love_ clang-format-formatted code, but I'm worried about the impact on individual developers' changesets if and how painful that will make merging in pull requests if people are using editors that do full file formats on save.

**Comment by DHowett-MSFT** [comment]
And for `editorconfig`, there's also #585

**Comment by gpotter2** [comment]
fixes https://github.com/microsoft/Terminal/issues/655

**Comment by adiviness** [comment]
@DHowett-MSFT I was playing around with clang-format sometime last year, we can write the format file such that it doesn't change too much code formatting. I can look into this more on Monday if needed.

**Comment by fcharlie** [comment]
@DHowett-MSFT Update PR.

**Comment by adiviness** [comment]
So I ran this format file on our codebase and it's not quite right. Some of the things I've noticed that are formatted incorrectly are:
- it's not respecting our newlines in binary operators
```
-    return stream << L"KeyEvent(" <<
-        keyMotion << L", " <<
-        L"repeat: " << pKeyEvent->_repeatCount << L", " <<
-        L"keyCode: " << pKeyEvent->_virtualKeyCode << L", " <<
-        L"scanCode: " << pKeyEvent->_virtualScanCode << L", " <<
-        L"char: " << charData << L", " <<
-        L"mods: " << pKeyEvent->_activeModifierKeys << L")";
+    return stream << L"KeyEvent(" << keyMotion << L", " << L"repeat: " << pKeyEvent->_repeatCount << L", " << L"keyCode: " << pKeyEvent->_virtualKeyCode
+                  << L", " << L"scanCode: " << pKeyEvent->_virtualScanCode << L", " << L"char: " << charData << L", " << L"mods: "
+                  << pKeyEvent->_activeModifierKeys << L")";
```
- some doc comments are being indented
- function attributes (ex. `[[nodiscard`) are having their line merged with the rest of the function declaration (also the `{` moved up a line)
```
-[[nodiscard]]
-std::wstring ConvertToW(const UINT codePage, const std::string_view source)
-{
+[[nodiscard]] std::wstring ConvertToW(const UINT codePage, const std::string_view source) {
```
- it's adding spaces around `:` in the warning suppression pragmas:
```
-#pragma prefast(suppress:__WARNING_W2A_BEST_FIT, "WC_NO_BEST_FIT_CHARS doesn't work in many codepages. Retain old behavior.")
+#pragma prefast(suppress : __WARNING_W2A_BEST_FIT, "WC_NO_BEST_FIT_CHARS doesn't work in many codepages. Retain old behavior.")
```
- it's turning some function calls that have the args on multiple lines into one long line
```
-        keyEvents.push_back(std::make_unique<KeyEvent>(true,
-                                                       1ui16,
-                                                       static_cast<WORD>(VK_MENU),
-                                                       altScanCode,
-                                                       UNICODE_NULL,
-                                                       (ENHANCED_KEY | LEFT_CTRL_PRESSED | RIGHT_ALT_PRESSED)));
+        keyEvents.push_back(std::make_unique<KeyEvent>(
+            true, 1ui16, static_cast<WORD>(VK_MENU), altScanCode, UNICODE_NULL, (ENHANCED_KEY | LEFT_CTRL_PRESSED | RIGHT_ALT_PRESSED)));
```
- if statements with a break after `||` or `&&` are being merged into one line
```
-    else if ((0xffa0 <= wch && wch <= 0xffbe) ||
-             (0xffc2 <= wch && wch <= 0xffc7) ||
-             (0xffca <= wch && wch <= 0xffcf) ||
-             (0xffd2 <= wch && wch <= 0xffd7) ||
-             (0xffda <= wch && wch <= 0xffdc))
+    else if (^M
+        (0xffa0 <= wch && wch <= 0xffbe) || (0xffc2 <= wch && wch <= 0xffc7) || (0xffca <= wch && wch <= 0xffcf) || (0xffd2 <= wch && wch <= 0xffd7)
+        || (0xffda <= wch && wch <= 0xffdc))
```
- constructors are having the `:` moved from the end of the line to the beginning of the line below
```
-Viewport::Viewport(const SMALL_RECT sr) noexcept :
-    _sr(sr)
+Viewport::Viewport(const SMALL_RECT sr) noexcept
+    : _sr(sr)
```

These are all examples I pulled from the *.cpp files in `/src/types`. We're going to need to turn off the formatting in some places as well, specifically I'm noticing some of the `RGB` declarations in `/src/types/utils.cpp.

I totally think that we do need to run this all on the codebase in one go once it's ironed out. But it's going to be a bit of an iterative process to find the right settings. I was playing around with a format conf a while back, but I'm hardly an expert with clang-format. Here is what I had, in case it helps any:
```
AccessModifierOffset: -4
AlignAfterOpenBracket: Align
AlignConsecutiveAssignments: false
AlignConsecutiveDeclarations: false
AlignEscapedNewlines: Left
AlignOperands: true
AlignTrailingComments: false
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: false
AllowShortCaseLabelsOnASingleLine: false
AllowShortFunctionsOnASingleLine: InlineOnly
AllowShortIfStatementsOnASingleLine: false
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: false
AlwaysBreakTemplateDeclarations: true
BinPackArguments: false
BinPackParameters: false
BreakBeforeBinaryOperators: None
BreakBeforeBraces: Allman
BreakBeforeInheritanceComma: false
BreakConstructorInitializers: AfterColon
BreakStringLiterals: false
ColumnLimit: 0
CompactNamespaces: false
ConstructorInitializerAllOnOneLineOrOnePerLine: true
ConstructorInitializerIndentWidth: 4
Cpp11BracedListStyle: false
IncludeCategories:
    - Regex: '^.*precomp'
      Priority: -1
    - Regex: '^".*"'
      Priority: 1
    - Regex: '^<.*>'
      Priority: 2
    - Regex: '.*'
      Priority: 3
IndentCaseLabels: false
IndentWidth: 4
IndentWrappedFunctionNames: false
KeepEmptyLinesAtTheStartOfBlocks: false
Language: Cpp
NamespaceIndentation: All
PointerAlignment: Left
ReflowComments: true
SortIncludes: true
SortUsingDeclarations: true
SpaceAfterCStyleCast: false
SpaceAfterTemplateKeyword: false
SpaceBeforeAssignmentOperators: true
SpaceBeforeParens: ControlStatements
SpaceInEmptyParentheses: false
SpacesInAngles: false
SpacesInCStyleCastParentheses: false
SpacesInContainerLiterals: false
SpacesInParentheses: false
SpacesInSquareBrackets: false
Standard: Cpp11
UseTab: Never
```

**Comment by fcharlie** [comment]
@adiviness Look clang-format docs: [http://clang.llvm.org/docs/ClangFormatStyleOptions.html](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) Looking at the documentation at the moment there seems to be no suitable rule to solve the above problem.

And I found that only clang-format 9 supports Microsoft code style.

Master: [https://github.com/llvm-mirror/clang/blob/master/lib/Format/Format.cpp](https://github.com/llvm-mirror/clang/blob/master/lib/Format/Format.cpp) `getMicrosoftStyle`

Release_80: [https://github.com/llvm-mirror/clang/blob/release_80/lib/Format/Format.cpp](https://github.com/llvm-mirror/clang/blob/release_80/lib/Format/Format.cpp)

I estimate that the calculator team should make some trade-offs when formatting code using clang-format.

**Comment by dlong11** [comment]
@adiviness I see that ColumnLimit is set to 0.  Is this correct?  I have seen 100 and 120 mentioned in PRs as the limit.   ColumnLimit influences lots of things, one of them being the initializer list.   You may want to set it and see what the results are.

**Comment by fcharlie** [comment]
see https://github.com/microsoft/terminal/pull/1141

**Comment by adiviness** [comment]
@fcharlie thanks for the original PR, sorry I sorta stepped on your toes with mine. This was the kick in the pants we needed to actually start to codify our coding style with a tool.

@dlong11 I believe that ColumnLimit=0 is correct, if it isn't set to 0 then our constructors aren't formatted correctly. We do try to keep the lines 100-120 ish wide as a max but we can't set it here to enforce.

**Comment by fcharlie** [comment]
@adiviness It doesn't matter, your PPT is better, I don't know much about Microsoft's amount coding style, so it's more appropriate for you to write .clang-format.

**Comment by dlong11** [comment]
@adiviness What is the constructor issue?    If you don't set a ColumnLimit you might as well not have a column limit.  It is way too hard to tell if something is "too long".    Even if you set it to something larger than 120.  (which I think is a bad idea.  The code is already hard to review on a laptop.)   Maybe we can fix the ctor issue?

I am not sure you are ever going to get exactly what you want.  Which in the big picture is OK,  clang-format will save man-years of time in code reviews over the long haul.   If you go through the submitted PRs and count how many comments and fixes there are to things like - extra lines, wrong brace placement,  extra space in the function parameters, the * should be next type, wrong indentation, the list goes on and on...   

All it takes getting the format "close enough", so we can stop spending time on the nits.    Sometimes close enough requires some decisions that we may not like, but it is worth it in time savings.   I can't imagine working daily on a repo without a formatting tool.   Especially an open source project with a lot of contributors.

**Comment by adiviness** [comment]
The constructor issue is that we format our constructors like this:
```
Foo::Foo(const int a, const int b) :
    _a{ a },
    _b{ b }
{
    // some other constructor stuff here
}
```
These stay formatted like this when ColumnLimit = 0. When it's set to something like 120, they get formatted like this: 
```
Foo::Foo(const int a, const int b) : _a{ a }, _b{ b }
{
    // some other constructor stuff here
}
```
Up to the point of the column limit, then it formats additional constructor initialization on a new line, without keeping it one field per line like what we currently do. I wasn't able to find any other combination of settings to keep the intended formatting.

**Comment by miniksa** [comment]
> The constructor issue is that we format our constructors like this:
> 
> ```
> Foo::Foo(const int a, const int b) :
>     _a{ a },
>     _b{ b }
> {
>     // some other constructor stuff here
> }
> ```
> 
> These stay formatted like this when ColumnLimit = 0. When it's set to something like 120, they get formatted like this:
> 
> ```
> Foo::Foo(const int a, const int b) : _a{ a }, _b{ b }
> {
>     // some other constructor stuff here
> }
> ```
> 
> Up to the point of the column limit, then it formats additional constructor initialization on a new line, without keeping it one field per line like what we currently do. I wasn't able to find any other combination of settings to keep the intended formatting.

If we think column limit of 120 is important, I am OK compromising some of the things like the constructor initialization lists.

**Pull request closed without merging**
