### PR TITLE
Add a setting to disable automatic pattern detection

### PR DESCRIPTION
**Pull request by PankajBhojwani**
## Summary of the Pull Request
Adds a new setting, `detectPatterns`, which takes a bool value indicating whether we should automatically detect patterns

 
## References
#5001 

## PR Checklist
* [ ] Closes #xxx
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [x] I work here

## Validation Steps Performed
Manual validation

### CODE REVIEW

**Review by miniksa — APPROVED** [review]
Presuming everyone else is OK with adding this setting, it looks good to me. I'm fine with it.

**Review by carlos-zamora — CHANGES_REQUESTED** [review]
Now that #8018 merged, you'll have to add this setting to like 2 more places.

Also curious why this is a profile setting instead of a global setting? I don't feel strongly either way but meh.

@cinnamon-msft will probably want to be involved in this discussion.

And don't forget to update the docs.

**Comment by zadjii-msft** [comment]
Wait why though? Is there some request to be able to disable URL detection? And should we maybe make it a little more specific to what this is actually accomplishing, like `detectUrls`? Or `disableUrlDetection`?

**Comment by PankajBhojwani** [comment]
> And should we maybe make it a little more specific to what this is actually accomplishing, like detectUrls? Or disableUrlDetection?

I chose `detectPatterns` because at some point we'd like to allow users to provide their own regex to detect patterns with - I suppose I could change this to `detectUrls` for now and then switch it back to `detectPatterns` when that change actually goes through if people feel strongly about it?

> Also curious why this is a profile setting instead of a global setting? I don't feel strongly either way but meh.

Similar reason as above, when we allow user defined regex patterns it probably makes more sense for it to be profile-specific, so the enabling/disabling is there too just so they tie together nicely

**Comment by zadjii-msft** [comment]
>  at some point we'd like to allow users to provide their own regex to detect patterns with

Presumably then, if they wanted a particular pattern to _not_ be detected, they would just, not provide that pattern, right? The URL pattern is only special because it's one we're defining for them, right?

Though how cool would it be

```json
"patterns": [
    {
        "name": "hyperlinks",
        "regex": "(\b(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|$!:,.;]*[A-Za-z0-9+&@#/%=~_|$])",
        "appearance": ["foreground_blue", "underlined"],
        "hoverAppearance": ["foreground_blue", "underlined", "bold"]
    },
    {
        "name": "guid",
        "regex": "(?:[{\"]|UniqueIdentifier>)[0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}(?:[}\"]|</UniqueIdentifier)",
        "appearance": ["background_#ff0088", "foreground_white"]
    },
]
```

Okay that's a shower thought, and I don't want to distract too much from the main point of the thread

**Comment by cinnamon-msft** [comment]
Has anyone asked for this? Considering the UI doesn't look any different unless you hover over the link with your mouse, I'd be surprised if this is a heavily requested feature.

I'd rather wait to see if people complain that they don't want hyperlinks rather than adding yet another setting.

**Comment by PankajBhojwani** [comment]
From @DHowett:

> we've added a potentially performance impacting feature that adds an unexpected interactive element to the terminal surface, it's only kind of us to add a suppression option

**Comment by zadjii-msft** [comment]
I can dig that line of reasoning.

**Comment by carlos-zamora** [comment]
I'm ok with the concept of disabling hyperlinks.

> at some point we'd like to allow users to provide their own regex to detect patterns with

Is the use case for this to allow different representations for different regex patterns? If so, how about we combine all of these features into one setting:

```json
"hyperlinks": true|false|object

// object format is interpreted as "true" with additional customizations (structure TBD)
```

If we want multiple regex patterns, I feel that this makes more sense as a global setting then. This would operate more similarly to how word delimiters was designed and is more cohesive.

Overall, my concern isn't that we're adding too many settings, rather that we're not consolidating them to make a more cohesive/clean story 😊

**Comment by carlos-zamora** [comment]
Had an offline conversation. This needs to be a profile setting because we plan on allowing visual customization of hyperlinks later. That visual customization _needs_ to be per-profile because we want it to stand out with the used color scheme (i.e.: avoid a black underline for hyperlinks on black background scenario).

Alternatively, if we made this a global setting now and the visual customization per-profile, you now have per-profile settings that may not be used (specifically, if `"detectHyperlinks"` is globally false). So just making it all per-profile seems to be the best approach here.

**Comment by PankajBhojwani** [comment]
Renamed to `detectHyperlinks`! We can switch it back to `detectPatterns` once we actually get the customizing elements in

**Comment by cinnamon-msft** [comment]
A few things:
- Do we have evidence that this is performance impacting? I checked out some other terminals and they don't have the option to disable hyperlinking. My only concern would be for accessibility, but if that isn't impacted I'm not convinced this is something we need.
- I would heavily suggest against planning to rename a setting, because then we'd have to support the deprecated name for backward compatibility until we get a settings migration infrastructure.
- For styling links, we could just put a new field for `hyperlinkColor` inside color schemes. Then we could have a global setting for displaying the underline.

**Comment by cinnamon-msft** [comment]
After some offline discussion, I think this setting makes sense as just an `enableHyperlinks` boolean. Then we add a future setting for the patterns we'd want to detect.

This way we can avoid setting renaming while also providing a simple setting for now and giving power users/extensions specific pattern detection in the future.

**Comment by PankajBhojwani** [comment]
> I think this setting makes sense as just an enableHyperlinks boolean. Then we add a future setting for the patterns we'd want to detect.

This setting does not disable application generated links through OSC8 though, so would `enableHyperlinks` be confusing? For example if someone sets `enableHyperlinks` to false and then runs an application that generates OSC8 links, they may not expect those links to be clickable but they will be.

**Comment by cinnamon-msft** [comment]
Should we disable OSC8 then with this setting? I know that won't improve performance, but I'm not sure users will know the difference between "auto detect hyperlinks" and "enable hyperlinks". I would assume they're treated as all or nothing?

**Comment by zadjii-msft** [comment]
In the past, we've had discussions about both:
* making the default value for a setting `false`, and 
* having settings be "positive" in nature, "enable" not "disable"

So I'm not sure which of `enableUrlDetection` or `disableUrlDetection` is better here 🙃 

In my opinion, if you're the kind of person who's passionate enough to turn this off, then you'll be competent enough to be able to understand that this setting is only disabling the ones we auto-detect, not the ones that are explicitly enabled by the app.

**Comment by DHowett** [comment]
I'm not sure how to feel about that one actually, yeah.

I think it's nice for us to offer toggles for "value add" features, but something in my gut tells me that we shouldn't let people turn off _VT features_. I dunno...

**Comment by PankajBhojwani** [comment]
From Team Sync discussion: we're not going to have this setting for now (once this becomes an extension it will solve itself)

**Comment by 89z** [comment]
https://github.com/microsoft/terminal/issues/5001
https://github.com/microsoft/terminal/issues/9981
https://github.com/microsoft/terminal/pull/7420

https://github.com/microsoft/terminal/pull/8293

**Comment by 89z** [comment]
To anyone wanting to disable, you can do it like this:

~~~
"experimental.detectURLs": false
~~~

https://github.com/microsoft/terminal/releases/tag/v1.10.2383.0

**Pull request closed without merging**
