### PR TITLE
Change the Feedback link to take you to github

### LINKED ISSUE #787: Move Feedback link to go to GitHub
Feedback hub isn't providing us much value right now. It's collecting a bunch of diagnostic logs we don't need, it's not connecting up with stuff properly, and it's dropping issues into ADO which we then have to triage there and migrate to here.

Let's just make the Feedback link go directly to GitHub for now.

### PR DESCRIPTION
**Pull request by zadjii-msft**
Fixes #787.

  Considering we're just duping all feedback hub issues to github, lets cut out
  the middleman and take them straight here.

### CODE REVIEW

**Comment by carlos-zamora** [comment]
Maybe a little nitpicky but thoughts on cutting out an extra step and going to "[https://github.com/microsoft/Terminal/issues/new](https://github.com/microsoft/Terminal/issues/new)"?

**Comment by adiviness** [comment]
> Maybe a little nitpicky but thoughts on cutting out an extra step and going to "https://github.com/microsoft/Terminal/issues/new"?

I have no strong feelings one way or the other.

**Comment by miniksa** [comment]
> Maybe a little nitpicky but thoughts on cutting out an extra step and going to "https://github.com/microsoft/Terminal/issues/new"?

I have two feelings about it:
1. Dropping people onto the main page might offer them the opportunity to read the issues before writing a new one.
2. I think the new issue form will offer them our templates and automatically try to find duplicates these days, so it might be a good call to go there.

I want @DHowett-MSFT to weigh in on this before merge though.

**Comment by DHowett-MSFT** [comment]
So the way it is today most closely mimics what we had before: dropping people onto the "feedback portal" where they can find everything. It's probably better for discovery than using the New Issues page.

If they can't find what they're about to report, "new issue" is just one click away. If they submit new feedback and github suggests the dupe they couldn't find, that's another chance to get them to +1 an existing report.

**Comment by miniksa** [comment]
OK let's roll with this then.

**Pull request merged**
