### PR TITLE
Move to 1ES engineering pools

### LINKED ISSUE #10734: Move to OneEngineering pools - WinDevPoolOSS-L
We are unifying machine pools for build/test engineering from open source and other "undocked" projects to centralize maintenance, updates, and reporting.

This task represents moving our Terminal workloads off of their existing pools and onto the ones that @kmahone has created for our part of the organization.

The appropriate pool for us as a fully open source project is `WinDevPoolOSS-L`.

The deadline for this task is September 30th.

### PR DESCRIPTION
**Pull request by miniksa**
Move to 1ES engineering pools

## PR Checklist
* [x] Closes #10734
* [x] I work here
* [x] If the builds still work, the tests pass. (release and PR builds...)

## Validation Steps Performed
- [x] Run the builds associated with this PR
- [x] Force run a release build off this branch
- [x] Force run a PGO training build off this branch

### CODE REVIEW

**Comment by miniksa** [comment]
I might have to make changes to some of the pipelines/steps for these pools. Don't sign off prematurely if you can help it. I just need to put this up here so I can run it.

**Comment by kmahone** [comment]
I suggest switching the order of the conditional and check for dev.azure.com/ms instead.
See https://github.com/microsoft/microsoft-ui-xaml/pull/5609

**Comment by zadjii-msft** [comment]
Is it a terrible bother if I request @kmahone as a reviewer for this one? He probably knows more than we do 😝

**Review by kmahone — APPROVED** [review]
It looks good to me. Just requires the switched order of the conditionals based on my above comment.

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
FYI the build you want to do a test run with is actually [OpenConsole YAML Release Build](https://microsoft.visualstudio.com/Dart/_build?definitionId=70913&_a=summary)

**Review by zadjii-msft — APPROVED** [review]
I guess ship it (once it passes)

**Pull request merged**
