### PR TITLE
Always prompt when exiting

### LINKED ISSUE #2976: Feature Request: Confirmation prompt before exit.
Feature request: A confirmation prompt before terminal app exit.
For example, if there are multiple tabs open, upon initiation of exit a prompt to confirm or cancel exit.

Particularly with the case when multiple tabs open, prompting the user to think before closing multiple tabs may prevent a accidental loss of work/processing in tabs that are not in the foreground.

Perhaps make the prompt configurable in settings with the options:

- disabled (no prompt before exit)
- multiple (prompt if multiple tabs open)
- always (prompt always before exit - for a check before closing even a single open tab)

### PR DESCRIPTION
**Pull request by Chips1234**
## Summary of the Pull Request
Add a setting with default as false. If it is true, then there will be a warning when exiting
New warning alwayswarn

## References
Closes #2976 and addresses https://github.com/microsoft/terminal/issues/6549#issuecomment-646113805.

## PR Checklist
* [X] Closes #2976 
* [X] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [X] Schema updated.

## Detailed Description of the Pull Request / Additional comments
Change the name of `CloseWarningDialog` to `CloseAllWarningDialog` to avoid confusion and the new dialog (always warn) will be referred to as `CloseWarningDialog`.

## Validation Steps Performed
Manual tests

### CODE REVIEW

**Comment by Chips1234** [comment]
If this merges, I will add a commit to #7077 for always warn on tab close

**Comment by AnuthaDev** [comment]
I think "exit" should be used instead of "quit"

**Comment by Chips1234** [comment]
> I think "exit" should be used instead of "quit"

@AnuthaDev or even "Close"? Since the multiple tab warning uses close

**Comment by AnuthaDev** [comment]
> > I think "exit" should be used instead of "quit"
> 
> @AnuthaDev or even "Close"? Since the multiple tab warning uses close

Sure :)

**Comment by swinder0161** [comment]
Please merge this asap, it is very annoying when clicking close accidentally on a running program or session

**Comment by Cuberick-Orion** [comment]
This can be of great help. Looking forward to its being released.

**Comment by htcfreek** [comment]
Will this be ready in the next release?

**Comment by zadjii-msft** [comment]
Nope. We'll make sure to update this thread when there is. 

The real issue here is that we need to figure this setting out. There's a long thread over in #6549 with a breakdown of how the options should work. It needs to be socialized with the rest of the team, preferably in a formal spec, to make sure we've got the options covered. I'd recommend subscribing to _that_ thread.

**Comment by DHowett** [comment]
Thank you so much for working on this draft work! We've chosen to take the project in a slightly different direction, and make sure that this feature is fully specified before we commit to it since it's deeply related to the other pane/tab/window closing work in your other PR.

**Pull request closed without merging**
