### PR TITLE
Defer cursor winrt event triggering

### PR DESCRIPTION
**Pull request by skyline75489**
## PR Checklist
* [X] Supports #10563
* [ ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

### CODE REVIEW

**Comment by skyline75489** [comment]
The winrt event is shockingly expensive...

Before:

image

After:

image

**Comment by lhecker** [comment]
Love it! Just a quick question: Is this thread safe? (I'm unfamiliar with the Cursor class.)

Also I believe it's kind of backwards that we use a `ThrottledFunc` for this. In my opinion we should add a "BeginDraw" and "EndDraw" event to our renderers, which could be used to do changes like this (updating TSFInputControl) in V-Sync without lagging behind.

**Comment by miniksa** [comment]
I find it weird that we have to avoid sending this on the sender side and aren't appropriately coalescing or discarding the additional notifications on the receiving side. But I'm willing to take whatever works.

>  In my opinion we should add a "BeginDraw" and "EndDraw" event to our renderers, 

@lhecker, last I checked... the renderers DO have a Begin and End draw sort of thing... can you clarify further what you mean?

**Comment by lhecker** [comment]
@miniksa An eventing system based on when the renderer draws, allows us to keep any other UI modifications in sync. For instance instead of using a throttled func, we could hook into the render loop using events and update the scrollbar in sync with when the renderer pushes pixels on the screen, without having to use any additional timers for that.

**Comment by skyline75489** [comment]
I don’t actually know if there’s a way to disable the event completely on the receiver side. We already have throttle_func as sort of “disabling” it, but that’s not good enough. The WinRt event is just so expensive that we can’t afford. 

I think @lhecker’s idea is actually how UI framework usually works, for example that’s basically how “Runloop” in iOS works. The problem here is that we have two independent “framework” here, one being the DxRenderer and related, the other being XAML. And the main way for them to communicate was through WinRT events. I see this as another consequence of tight-coupling of renderer.cpp (where the render thread lives) and DxEngine. After #10615 (seriously guys, take a look and you can see how effective that PR is) and future PR lands, we should be able to use the “hooking into the render thread” way to do something interesting. Of course the UI thread limitation in XAML still need to be taken into consideration.

**Comment by miniksa** [comment]
>  After #10615 (seriously guys, take a look and you can see how effective that PR is) and future PR lands

Dude its in my queue, it's just a big deal so I've been procrastinating. I feel seen. (I plan to look Monday... you're just catching me feeling too sleepy to ponder long term consequences...)

**Comment by miniksa** [comment]
> I don’t actually know if there’s a way to disable the event completely on the receiver side. We already have throttle_func as sort of “disabling” it, but that’s not good enough. The WinRt event is just so expensive that we can’t afford.

OK well I'm willing to take this until we get further along if it helps this much. Just leave commentary.

**Review by miniksa — APPROVED** [review]

**Review by zadjii-msft — APPROVED** [review]

**Pull request merged**
