### PR TITLE
Adding keymapping for access to Settings

### PR DESCRIPTION
**Pull request by timheuer**
First stab at adding a key mapping to settings so I can quickly access it instead of using a mouse :-)

### CODE REVIEW

**Comment by timheuer** [comment]
CTRL+SHIFT+S would work here as well.  I thought about how CTRL+S is often thought of as 'save' and would it interfere with something that might have focus in conhost when a specific terminal was there but couldn't think of it.  ALT+S was another option I thought of but I then was honestly just following CTRL+T pattern for tab to be consistent with the modifier key.

**Comment by factormystic** [comment]
Some thoughts

- should the keybinding come from a setting (or is loading keybinding from config a separate effort)
- personally I think that registering any type of mnemonic shortcut should be done with extreme caution because one man's **s**ettings is another mans **s**ave, as you already discovered
- is there a shortcut from any other app you could crib instead? Not sure what VS uses by default, but VS Code is `ctrl + ,`

**Comment by DHowett-MSFT** [comment]
Yeah, I think <kdb>Ctrl+,</kbd> is the industry standard for opening settings panels.

Bonus: it doesn't conflict with any VT sequences!

**Comment by mKay00** [comment]
@factormystic keybindings will be remappable in the settings, see #748

**Comment by DHowett-MSFT** [comment]
@timheuer Thanks!

**Pull request merged**
