### PR TITLE
Add .vsconfig for required components to build

### PR DESCRIPTION
**Pull request by huoyaoyuan**
I've edited it based on what I've seen:
- Blend and managed UWP are removed
- ARM32 workloads are removed, because the solution has only ARM64
- Keep the explicit vs141 and windows 18362 tools, remove implicit vs142 and windows 17763

I wish the official team to verify the config file on a clean VS installation with core editor only.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
.vsconfig is a thing? That’s so cool!

________________________________

**Comment by huoyaoyuan** [comment]
Further more, there can be a vsconfig verification integrated with CI.
The Visual Studio instance on CI machine (or even local instance) can treat only vsconfig mentioned tools (and there dependencies) as enabled, and warn for "invoking unmentioned component".

**Comment by DHowett-MSFT** [comment]
That is very exciting. Thanks, I’m looking forward to reviewing this/learning more tomorrow!

________________________________

**Comment by huoyaoyuan** [comment]
To clarify, the integrated verification is just my proposal now.
Currently the only way should be manually make a minimal install, follow the IDE instructions and don't do anything more, then build.

**Comment by Blealtan** [comment]
Adding this might require some modification of corresponded setup guide in `README.md`?

**Pull request merged**
