### PR TITLE
Colortool: improve color table.

### PR DESCRIPTION
**Pull request by LuanVSO**
## Summary of the Pull Request
- add suport for light backgrounds
- make color tool use 90-97 and 100-107 sequences for fg/bg
- fix loops stop condition

 
## PR Checklist
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments

additional improvements that I've seen while working on #12087

### CODE REVIEW

**Comment by zadjii-msft** [comment]
Cool idea! Any chance we could hide this behavior behind a flag? I kinda like that the original table fit neatly in 80 columns, but this is definitely also useful too!

**Comment by LuanVSO** [comment]
i will give it a try

**Comment by LuanVSO** [comment]
Done.
image
image

**Comment by LuanVSO** [comment]
Is -a / --allcolors good for you?
If it is I will add it to the spell check allow list

**Comment by miniksa** [comment]
> Is -a / --allcolors good for you @zadjii-msft ? If it is I will add it to the spell check allow list

I know I'm the "other" Mike, but I'm fine with this.

**Review by miniksa — APPROVED** [review]
Looks good to me. Thank you! (And we should file a follow-on issue to get the publishing/signing pipeline running again for ColorTool as I think it has decayed in the last year...)

**Review by zadjii-msft — APPROVED** [review]

**Pull request merged**
