### PR TITLE
Fix tab selection to bring the tab into view

### PR DESCRIPTION
**Pull request by Don-Vito**
## PR Checklist
* [x] Closes https://github.com/microsoft/terminal/issues/3638
* [x] CLA signed.
* [ ] Tests added/passed
* [ ] Documentation updated.
* [ ] Schema updated.
* [x] I've discussed this with core contributors already.

##Detailed Description of the Pull Request / Additional comments
A workaround for https://github.com/microsoft/microsoft-ui-xaml/issues/3945.
Thanks to @michael-hawker and @chingucoding for the suggested solution.

### CODE REVIEW

**Comment by Don-Vito** [comment]
BringIntoView

**Review by michael-hawker — APPROVED** [review]

**Comment by Don-Vito** [comment]
> 
> 
> It might be worth adding a tracking issue to remove this workaround as the PR on the WinUI side is already open and with a later version, this workaround wouldn't be necessary anymore.

Make sense! The issue is here: https://github.com/microsoft/terminal/issues/8833. Thanks again!

**Review by zadjii-msft — APPROVED** [review]
God it's so simple I love it.

**Comment by chingucoding** [comment]
> Makes sense! The issue is here: #8833. Thanks again!

Awesome, thanks!

**Review by carlos-zamora — APPROVED** [review]

**Pull request merged**
