### PR TITLE
Remove trailing commas that break the json schema

### LINKED ISSUE #12639: Trailing commas in profiles schema
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.1526]

### Other Software

VIsual Studio Code 1.64.2

### Steps to reproduce

- Open the Windows Terminal Setting
- Click on `Open JSON File`
- Opens in VS Code with an error on the schema:

`Unable to parse content from 'https://aka.ms/terminal-profiles-schema': Parse error at offset 14830`

The problem is 
https://github.com/microsoft/terminal/blob/main/doc%2Fcascadia%2Fprofiles.schema.json#L488
See the trailing comma.

Schema file are JSON and trailing commas are a syntax error.

### Expected Behavior

No error when opening in VS Code

### Actual Behavior

The error comes from trailing commas in the schema file: https://github.com/microsoft/terminal/blob/f217f6dc331559f57301dfb84ce3898d20c944d6/doc/cascadia/profiles.schema.json#L488

Also:
- https://github.com/microsoft/terminal/blob/f217f6dc331559f57301dfb84ce3898d20c944d6/doc/cascadia/profiles.schema.json#L864
- https://github.com/microsoft/terminal/blob/f217f6dc331559f57301dfb84ce3898d20c944d6/doc/cascadia/profiles.schema.json#L884
- https://github.com/microsoft/terminal/blob/f217f6dc331559f57301dfb84ce3898d20c944d6/doc/cascadia/profiles.schema.json#L904

### PR DESCRIPTION
**Pull request by sowmya-hub**
## Summary of the Pull Request
Fixed #12639

## PR Checklist
* [ ] Closes #xxx
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [x] Schema updated.
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #12639

## Validation Steps Performed
Ran the file through a linter to check validity.

### CODE REVIEW

**Review by DHowett — CHANGES_REQUESTED** [review]
Thanks for doing this!

It looks like this change reformats the entire file, which makes it rather difficult to review and breaks the JSON style we've been using across the repository. Would you mind scoping this change down to only the appropriate lines?

There's also a new file added to the root of the repo that we haven't figured out the purpose of.

**Comment by sowmya-hub** [comment]
> Thanks for doing this!
> 
> It looks like this change reformats the entire file, which makes it rather difficult to review and breaks the JSON style we've been using across the repository. Would you mind scoping this change down to only the appropriate lines?
> 
> There's also a new file added to the root of the repo that we haven't figured out the purpose of.

Thank you for pointing it out, I wasn't aware!

I'll go over the file and try to match the style according to styling used in the repository, then. Yes, I'll try to narrow the change down to those lines.

I'm also not sure where the new file came from, I'll do some more research on that and get back to you.

**Comment by sowmya-hub** [comment]
@lhecker thanks so much for the heads-up!  🙌 

It's helpful to know the built-in formatted is to be used!

I realise that the styling change came from the third-party linter I used. Since I copied the contents into the file, it got changed.

I've changed it and committed to my branch. Hopefully, it works now!

**Comment by lhecker** [comment]
@sowmya-hub If you check the top line of this PR, you'll see it still says `+2,382 −2,381` unfortunately. 😕
You can restore the original contents of your file by running
```sh
git restore -s origin/main doc/cascadia/profiles.schema.json
```

If you're using Visual Studio Code as well, I can only suggest to open the command palette with Ctrl+Shift+P and search for an entry called "File: Save without Formatting", which will save the file without running your linters. If you use a different editor it will probably have a similar option somewhere.

**Review by lhecker — APPROVED** [review]

**Comment by sowmya-hub** [comment]
Oh, just saw. There was an extra line at the bottom that had surfaced thanks to the lint checks, must've been the cause. 

I've run this command, neat since I didn't have to copy-paste from the original json file again! 

Oh no, hadn't realised that it had shown up there(my bad, DHowett did mention it was the root of repo.) as I was searching folder-wise.

Yes, I've saved the file without formatting this time. I'm using Visual Studio Code, via Gitpod.

**Review by DHowett — APPROVED** [review]
Thanks so much for fixing this! I appreciate you responding to our review feedback as well :smile:

**Comment by sowmya-hub** [comment]
Thank you both so much for reviewing the changes and giving me pointers as well! 😊

**Comment by DHowett** [comment]
My bad! I didn't mark this for servicing into the current active branch for the schema.

That is now done. If you can get VSCode to refresh the schema, the copy linked from `$schema` has been updated. :smile:

**Comment by claudio-salvio** [comment]
@DHowett 

Thanks for taking care of it.

The previous error message disappeared.
However now it shows a warning that says: 
`Draft 2020-12 schemas are not yet fully supported.`
It seems to generate no problems but I mention it because I don't remember this warning appearing before.

For editing I am using **VSCode Version: 1.63.2**

Greetings,
Claudio Salvio

**Pull request merged**
