### PR TITLE
build: roll back to a build container with the 14.38 compiler

### PR DESCRIPTION
**Pull request by DHowett**
The 14.39 compiler seems pretty busted.

Refs #16794

### CODE REVIEW

**Review by lhecker — APPROVED** [review]

**Review by zadjii-msft — APPROVED** [review]
everything is awful

**Comment by DHowett** [comment]
i'll hold this until the canary build completes and I can share a binary with the folks in that thread.

**Comment by Karl-WE** [comment]
"We've rolled back to an older compiler to get Terminal working on Intel Core 2 Duo machines again (!) "
That's a noble gesture.

 Would not consider these CPUs and platforms being secure and running supported OS anymore (soon).

**Comment by DHowett** [comment]
> soon

Soon, but not yet. Windows 10 still supports them, and given that we must run on Windows 10... 🙂 

This also fixed a bunch of other more insidious compiler issues around shifts and masks that have been just causing havoc.

**Pull request merged**
