### PR TITLE
Double middle click on taskbar preview closes application

### LINKED ISSUE #7451: Double middle click on taskbar preview to close despite confirmation modal
# Description of the new feature/enhancement

If I want to close a program/window, I'll often hover it in the taskbar, then middle-click the preview that appears. If there are multiple tabs open, though, a modal shows up asking me if I'm sure. That's fine. I like those kinds of warnings. But it completely blocks me from closing the window from the taskbar.

What several (sadly not all) programs do in those cases is interpret the second middle click as a confirmation and close right away. I wish Windows Terminal did this as well.

# Proposed technical implementation details (optional)

When there's currently a confirmation modal and I send another "close" command through a taskbar middle click, I wish Windows Terminal would interpret this as "Yes, I'm sure" and close.

### PR DESCRIPTION
**Pull request by rhorber**
## Summary of the Pull Request
A second close command (middle click on taskbar preview) overrides the warning dialog and closes the application.

 
## PR Checklist
* [x] Closes #7451 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
When a close command is invoked (middle click on taskbar preview or 'X' button), a new flag is set. When the user wants to close again (this time only via the taskbar preview, as the 'X' button is disabled), the application is closed. If the user cancels the dialog, the flag is reset to prevent accidental closing on a subsequent close command.

## Validation Steps Performed
I am developing with a [Windows 10 virtual machine](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) provided by Microsoft. I tested manually. I considered the 'X' button, middle click on taskbar preview, and Alt+F4. Only a middle click on the taskbar preview does override the dialog.

### CODE REVIEW

**Comment by rhorber** [comment]
Let me know if my approach isn't state of the art.
Also, I don't know if and how my change led to the failing unit test.

**Comment by DHowett** [comment]
This is clever, and I like the feature. Nothing bothers me more than when Vim doesn't exit because it wanted to ask if I was sure :smile:. Thanks! You didn't cause the UT failure -- they can just be a bit flaky. We'll get on reviewing this tomorrow/tuesday :smile:

**Comment by DHowett** [comment]
If this is ready for the team to look at, make sure you unmark it as Draft! We usually don't look at drafts too quickly. :smile:

**Comment by rhorber** [comment]
Failure: I'm glad.
Review: Yes, it's ready. I wasn't sure, when I should remove the mark 😀 (and thus rather leave it).

**Review by DHowett — APPROVED** [review]
This is great. Couple thoughts:

1. I think we should flip the sense of the boolean (`_displayingCloseDialog` instead of `_isFirstClose`)
2. We need to eventually refactor (you definitely don't need to do it for this PR!) dialog display to be "awaitable", so we don't need to add an event handler to the close button.

That would make dialog display more like this:

```
_displayingCloseDialog = true;
co_await _ShowCloseDialog();
_displayingCloseDialog = false;
```

**Comment by rhorber** [comment]
I had a shot at refactoring the dialog 😄. See [commit](https://github.com/rhorber/terminal/commit/75462a86429275d05cec8f2b8cdcb87364224968).
As I branched from my feature branch, I did not create a PR because I'm not sure, which base I should choose (master branch as base would also include this PR).

**Review by zadjii-msft — APPROVED** [review]
Sorry for the delay - just checked this out locally, and I really like the way it feels. Thanks for doing this!

**Comment by rhorber** [comment]
I'm happy I could help.

About refactoring the dialog: Is it okay that I create a PR directly (and mention this PR) or do you prefer that I first create an issue for it?

**Comment by zadjii-msft** [comment]
Meh, if the code's already done, then just make the second PR and reference this one in it. No need to make an issue to say "Do the thing I've done in {PR}" 😆

**Pull request merged**
