### PR TITLE
Don't use memcmp() to compare TextAttributes, instead just reorder the data member comparisons

### PR DESCRIPTION
**Pull request by EmJayGee**
This PR is a very small non-semantic change to change the code for comparing TextAttribute instances so that the members are compared in their "physical" order rather than in whatever order the original author chose.

The effect of this is to generate significantly better code for the comparisons. The out-of-order comparisons forced the compiler to load the first cache line, cherry pick the first word of it, then load the second cache line, cherry pick a part of it, and then proceed further along.

This led to another contributor being led to want to write code that used memcmp() to perform the comparison which is usually a sign that things have gone very very wrong. Fortunately this appears to be a simpler solution which gets the vc++ compiler at least to generate the right code.

I have not tried other compilers, only the 14.31.31103 toolkit.

 

There are other issues in PR #10566 that I'll stay away from but this is simple and straightforward. I also added a compile-time assertion in the header and some comments. I assume the comments are goodness; the static assertion may be a problem on other platforms, I cannot verify.

## PR Checklist
* [ ] Closes #xxx
* [ ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

Sorry I don't have anything more detailed than the above plus the code.

I looked at the generated code under cdb before making the fix and then after.

### CODE REVIEW

**Comment by EmJayGee** [comment]
OK I have no idea how to fix this. I have made the spelling error fixes in my branch in my fork, but I don't know where to go from here. I will see if I can keep moving ahead.

**Comment by EmJayGee** [comment]
aha all I had to do is check in to the branch and push to the fork. I guess that's part of why I couldn't delete the branch in the last issue.

**Comment by EmJayGee** [comment]
I looked at the generated code again and it's not as good as I thought. I will take another crack at it. I'm surprised at how poor it is. I'd ask the compiler team if it were prohibited from writing the optimizations I would expect here if I was still there but I'm not so. instead I'm led to try writing something that violates the "const refs can actually be passed by value" detente but if a 14 byte struct is ever actually passed by value, I'll find a hat and eat it. I guess when we have 128 bit processors.

**Comment by DHowett** [comment]
> I guess when we have 128 bit processors.

Amen.

Thanks for looking into this as much as you have been! :smile:

**Comment by EmJayGee** [comment]
OK so this code generates pretty much what is desirable. If this is a really hot path, it's possible that a branchless solution would be faster if this is as hot as the other PR author suggested but I think we might be hitting diminishing returns for esoterica. (I do love esoterica but it should generally be in strange little places, not randomly strewn across the code base.)

I will put together an issue and a PR for this new update for people to ruminate upon. It's not as elegant as the original "just swap the order" solution.

I can't figure out where the compiler optimization settings are set for the project. Is it in visual studio or do I need to find some XML file or something?

```
inline bool operator==(const TextAttribute& a, const TextAttribute& b) noexcept
{
    const char* const left = reinterpret_cast<const char*>(&a);
    const char* const right = reinterpret_cast<const char*>(&b);

    const uint64_t left1 = *reinterpret_cast<const uint64_t*>(left);
    const uint64_t right1 = *reinterpret_cast<const uint64_t*>(right);
    if (left1 != right1)
    {
        return false;
    }

    const uint32_t left2 = *reinterpret_cast<const uint32_t*>(left + sizeof(uint64_t));
    const uint32_t right2 = *reinterpret_cast<const uint32_t*>(right + sizeof(uint64_t));
    if (left2 != right2)
    {
        return false;
    }

    const uint8_t left3 = *reinterpret_cast<const uint8_t*>(left + sizeof(uint64_t) + sizeof(uint32_t));
    const uint8_t right3 = *reinterpret_cast<const uint8_t*>(right + sizeof(uint64_t) + sizeof(uint32_t));
    return left3 == right3;

static_assert((offsetof(TextAttribute, _extendedAttrs) + sizeof(TextAttribute::_extendedAttrs)) == (sizeof(uint64_t) + sizeof(uint32_t) + sizeof(uint8_t)));
}


```

**Comment by EmJayGee** [comment]
Notably, the above code is actually inlined which might have broader positive impact.

**Comment by DHowett** [comment]
Funny enough, if you do write the `memcmp` version of the comparison operator it compiles down to code that looks nearly identical (admittedly, in assembly) to what you ended up writing.

At the end of the day, that code doesn't seem too different from calling `memcmp` ourselves -- down to the risks posed by both padding and alignment -- but seemingly at greater risk, right?

**Pull request closed without merging**
