### PR TITLE
Move to Microsoft.UI.Xaml 2.4.0

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
This brings support for "Compact" tab sizing, which compresses all inactive tabs to just the size of their icons plus the close button. Neat!

It also just keeps us generally up-to-date and good citizens.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
I am so dismayed.

**Comment by WSLUser** [comment]
This is one of those things that held me off (at least Azure can build with it) from doing this PR myself.

**Comment by zadjii-msft** [comment]
Okay this happens even in (app=light, system=dark), (app=light, system=light), and (app=dark, system=light).

I'm trying to look through MUX changes to see if there's something that stands out. [microsoft-ui-xaml#2377](https://github.com/microsoft/microsoft-ui-xaml/pull/2377) looks related, but I can't easily bisect on our side to see if that's it...

**Comment by zadjii-msft** [comment]
It absolutely was [microsoft-ui-xaml#2377](https://github.com/microsoft/microsoft-ui-xaml/pull/2377).

If you insert 
```xaml
<StaticResource x:Key="AccentButtonForeground" ResourceKey="SystemControlBackgroundChromeWhiteBrush" />
```

into our `App.xaml`, that effectively reverts the part of https://github.com/microsoft/microsoft-ui-xaml/commit/1785888fe6408a9c57d7a44a9ed40b5e5b82cc17 that broke this. I'm not sure what the side effects of that are, but those are my findings so far.

**Comment by carlos-zamora** [comment]
Looking through our 1.1/1.x/backlog milestones. I'm guessing this would close:
- #5360

I'll edit this comment if/as I find more.

**Comment by zadjii-msft** [comment]
So, in the ongoing saga of the Accent Button color, this was reverted upstream in https://github.com/microsoft/microsoft-ui-xaml/pull/2420. I'm not sure what their release cadence is like - we could probably ship this PR with the workaround above for now, and revert the change when we pull the next MUX. @DHowett-MSFT I'll leave that up to you.

**Comment by DHowett-MSFT** [comment]
We can probably safely wait a bit for this one to land. It's not pressing that we hit MUX 2.4 :)

**Comment by WSLUser** [comment]
Updating will probably solve more bugs than just the one mentioned above. Nobody has just reported yet. I think the workaround should be added and merge the PR. There's a higher chance of dropping bugs than gaining new ones for Terminal.

**Comment by DHowett-MSFT** [comment]
We are very early in the next release cycle, and we can afford to wait up to 7 days to make sure we're doing the right thing. There's no urgency here :smile: because it's not landing in time for v1.0.

**Comment by zadjii-msft** [comment]
We might want to wait _one_ more MUX release, so we can get https://github.com/microsoft/microsoft-ui-xaml/pull/2201 too 😉

**Comment by WSLUser** [comment]
Ha, should be in the next preview I'd guess. Fix bugs and gain new features is always a win/win.

**Comment by WSLUser** [comment]
2.4.2 was released and contained a bug fix. We could move to that for now and update again when .3 is available for the Edge look.

**Comment by zadjii-msft** [comment]
IIRC we explicitly need the `-prerelease` versions of the MUX package to get the symbols hooked up right? I might be wrong on that, but I think there was a reason.

**Comment by DHowett** [comment]
We need the prerelease versions because we need the DLL to get into our package instead of being inside a framework package dependency.

**Comment by WSLUser** [comment]
Stable ones don't provide a dll? Also, I've been experimenting with dependabot. If we did get inside a framework package dependency, it would automatically create a pull request to bump the version. We already have other nuget packages that require updates that are being read in by dependabot. Adding MUX to the list would make more sense to me. https://app.dependabot.com/ You should enable this repo for it and see what I mean.

**Comment by DHowett** [comment]
Unfortunately, they don’t! They inject a `PackageDependency` into the application manifest, whereas prereleases include the DLL, assets and localization content directly in your package.

**Comment by WSLUser** [comment]
Strange they don't provide it as an option. Wonder if they have an issue/feature request for it already.

**Comment by DHowett** [comment]
I’ve got a good email thread with the project lead over there about this :smile:

**Comment by WSLUser** [comment]
Seems counterproductive to force apps to rely on pre-release versions that are by their very nature, unstable and subject to change but if that's what that team wants to force you to do, ¯\_(ツ)_/¯

**Comment by DHowett** [comment]
We are in a unique position. The framework is _intended_ to be consumed through a dependency package, which will be automatically managed by the store. 

The reason we can’t use that is a long-standing bug (since Windows 8!) in elevation. It turns out that _Terminal is the only package that both runs as admin and uses WinRT class activation!_ Those things together make our lives rather difficult. 


I don’t blame the Xaml team for not catering to a use case 0.5% of applications will ever hit right now with their initial efforts to take the “UWP” ui toolkit out of the platform. Like, it was never designed for this, it’s no wonder it doesn’t work 100% right. 

WinUI3, on the horizon, offers a better solution to so many of these issues.

**Comment by WSLUser** [comment]
Yes, I'm hoping we can drop the UWP bits all together and just throw all the XAML into WPF utilizing the UWP APIs being ported such as https://github.com/microsoft/microsoft-ui-xaml/issues/2005

**Comment by DHowett** [comment]
Very extremely unlikely to use WPF. We are entirely native code :p

**Comment by WSLUser** [comment]
Entirely? 🧐

**Comment by zadjii-msft** [comment]
The Windows Terminal\* is entirely native code. The WpfControl is obviously C#, and so is ColorTool, and maybe some random tests and utils, but the _Terminal_ is native, and `conhost` is native.

**Comment by WSLUser** [comment]
Well you need the XAML to go somewhere and it seems to me that WPF will be more helpful than trying to go full UWP and should alleviate the elevation issue.

**Comment by DHowett** [comment]
Switching from one framework to another while remaining in a Win32 application model application (make no mistake; WPF is Win32) will do absolutely nothing to change our station in regards to package activation, elevation or dependencies. WinUI3 is still going to be made up of WinRT classes that need to be instantiated one way or another!

**Comment by DHowett** [comment]
@carlos-zamora @zadjii-msft this is ready to review.

**Pull request merged**
