### PR TITLE
README: move build badges to shine-oss, remove colortool, move to top

### PR DESCRIPTION
**Pull request by DHowett**

### CODE REVIEW

**Comment by DHowett** [comment]
OK i think I get it now.

**Comment by DHowett** [comment]
narrator: he did not

**Comment by DHowett** [comment]
i bet i have to completely delete this build pipeline and make a new one, because that's roughly how it's been going lately.

**Review by lhecker — APPROVED** [review]

**Comment by DHowett** [comment]
bla bla bla bla bla comment indicating approval of PR

**Comment by DHowett** [comment]
K, I officially need an adult :)

**Review by zadjii-msft — APPROVED** [review]

**Pull request merged**
