### PR TITLE
Change solarized to be more usable

### PR DESCRIPTION
**Pull request by kojoru**
## Summary of the Pull Request

Based on the discussion in #2638 until the Delta E 2000 contrast algo is
implemented in Terminal, it would be great to have a Solarized Dark
color scheme that does actually have enough contrast to be realistically
used for powershell.

This color scheme is based on "Solarized (John Doe)" from ConEmu and
modified to have a more visible `DarkBlue` as also discussed in #2638

Note I didn't test if it runs after the change as I don't have enough tooling
installed anymore.

Also I didn't discuss it with the core members, it's just a starting point for 
the discussion around suboptimal experience with Solarized Dark.

 
## References

* #2638

## PR Checklist
* [ ] Doesn't close a specific issue.
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
For reference here's how it looks with the default Solarized:
image
Here's how it looks with the proposed change:
image

### CODE REVIEW

**Comment by j4james** [comment]
The dark blue in your PR doesn't seem to match your screenshot - I think it still has the original conemu value which is almost invisible on a default/black background.

Also, while I agree that this is a bit better than the standard Solarized scheme, I don't think it's appropriate to simply replace it. As strange as it may seem, there are people that actually like the standard Solarized scheme, and may have spent a good deal of time customizing their apps to work with those specific shades. They will not be happy to find their colors suddenly updated to something completely different (and this scheme _is_ completely different).

Which leaves us with the option of adding this as a separate Solarized variant, which I'm not personally in favor of either. Frankly I'd rather we just got rid of all of them, maybe with some form of backwards compatibility for people that are already using them.

**Comment by kojoru** [comment]
I'll double check the colors and see why they don't match the screenshot, thanks.

I guess adding it as a different variant might be a better option than just changing it outright. While the color scheme is completely unusable in powershell, it might work for some setups of linux or cmd, and I can theoretically imagine people who are setting up the environments against the default color scheme as opposed to the other way round.

I guess I disagree about not including it at all. Solarized Dark _is_ an extremely popular color scheme. I'd say including it in a way that's usable for powershell (the default shell in terminal and probably majority of its usage) would be a net "batteries included" win for the users.

**Comment by kojoru** [comment]
Indeed, I copied the wrong blue. That's fixed now.

**Comment by WSLUser** [comment]
I think some color schemes should be included by default. I also think increasing color perception for this theme that is arguably popular is worth changing the original default. Once Delta E 2000 is implemented, these colors will get adjusted anyways (most likely with a enabled/disabled setting like ConEmu does it). I think it's better to make Terminal more accessible for visually impaired developers/sysadmins. Since this will be included in Preview, there'll be plenty of time to revert it if there's alot of feedback requesting it to be changed back.

**Comment by j4james** [comment]
> Solarized Dark is an extremely popular color scheme.

I've seen this claim made a lot - twice now just in this thread. So I've got to ask, where do you guys get that information from? Is there a color scheme leaderboard somewhere, or has one of the big terminals published telemetry tracking those details? I'm genuinely interested to know.

> I also think increasing color perception for this theme... is worth changing the original default.

But that's not what this PR is doing. It's a completely different theme. Look at the screenshots of midnight commander below (Solarized on the left, this new scheme on the right). If we could ship this PR without any Solarized fans complaining, then it's probably safe to assume they don't exist. Because whatever merits it might have, the scheme on the right is most definitely not Solarized.

image

**Comment by WSLUser** [comment]
So this can be closed as it's getting removed from the default. At least it's posted in the issue if others want it.

**Comment by skyline75489** [comment]
@j4james Perhaps “Solarized Dark being extremely popular” is somewhat related to the fact that it's included in many terminal simulators, such as iTerm2, ConEmu and many others. Honestly those claimed to be "Solarized Dark" themes are all kinda different. I mean I've seen the left kind, and also the right kind. I don't even know which one is the so-called original one. Maybe it's because people just so often just change the theme to be more usable because the "original" one is not that good. So it's 
somehow justified to bring this kind of change in the PR? I don't really use Solarized Dark any more. Just my two cents.

**Comment by j4james** [comment]
@skyline75489 As was mentioned above, the plan is to remove it from future builds, so we won't have to deal with these issues anymore. Anyone that wants to create their own color scheme and call it Solarized will then be free to do so.

**Comment by DHowett** [comment]
I'd like to concentrate all discussion about making Solarized palatable over in #6618. Thanks, everyone, for voicing your needs here. :smile:

**Pull request closed without merging**
