### PR TITLE
Trying to figure out x64 test failures, don't review

### PR DESCRIPTION
**Pull request by miniksa**
Go away. You heard me.

### CODE REVIEW

**Comment by miniksa** [comment]
OK it passes with the 7 unit tests not including terminal core unit tests.

It hangs with terminal core unit tests added back to the set. Nnnn. Gotta dig in.

**Comment by miniksa** [comment]
2001.2914 passed right after I merged master in: https://dev.azure.com/ms/Terminal/_build/results?buildId=60613&view=results 

Running again from this branch this time, not the merge branch
2001.2916: https://dev.azure.com/ms/Terminal/_build/results?buildId=60618&view=results

**Comment by miniksa** [comment]
2916 passed... Let's try one more with azp.

**Comment by zadjii-msft** [comment]
[Here's another 86 failure](https://dev.azure.com/ms/Terminal/_build/results?buildId=60713&view=logs&j=e7365288-57d7-5349-8dfa-9c195127bd77&t=6086d516-7543-504d-074c-7d25bb0cffee) from #4403

**Comment by miniksa** [comment]
idk man

**Comment by miniksa** [comment]
ok they're still failing. we need to figure out what or turn off the flaky tests as they're just getting in the way.

**Comment by zadjii-msft** [comment]
My theory is that it has to do with something that the `ConptyRountripTests` is instantiating that none of the tests before it was instantiating. Probably a `Renderer`, though it could be something else. I'd probably just make a test that does the `METHOD_SETUP` and `METHOD_CLEANUP` for those tests a bunch in a loop, and see if that will hang the tests.

**Comment by miniksa** [comment]
Closing this in favor of #4490 for now.

**Pull request closed without merging**
