### PR TITLE
Account for WHEEL_DELTA when dispatching VT mouse wheel events

### LINKED ISSUE #6184: Vim/Neovim/tmux scroll way too fast with trackpads
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
```

Windows Terminal version `1.0.1401.0`.

I'm curious whether or not this is trackpad-related, so FWIW I'm using a Surface Book and scrolling with the trackpad.

EDIT: I tried with a normal mouse plugged into the USB port instead of the trackpad, and it's definitely trackpad-related: regular mouse wheels work just fine.

# Steps to reproduce

`tmux` set up with:

```tmux
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"	
bind -n WheelDownPane select-pane -t= \; send-keys -M
```

And/or Neovim (or just plain old Vim) with:

```vim
set mouse=a
```

# Expected behavior

The above snippets make `vim`, `nvim`, and `tmux` able to be scrolled with the mouse/trackpad on macOS and Linux. They also work in WSL... If I use Xming to run an X server, and use urxvt as my terminal emulator. So, I'd expect that they'd also work for Windows Terminal.

They work in all of the above either alone (e.g. Vim/Neovim not nested inside `tmux`), or nested (e.g. running Neovim inside `tmux`).

# Actual behavior

For some reason with the Windows Terminal, when I scroll in vim/nvim/tmux (with the editors either nested in `tmux` or un-nested) they all go absolutely nuts and scroll at like 10x speed, which is kind of unusable. FWIW I'm using a Surface Book and scrolling with my trackpad, if that makes a difference? It looks like it's just sending way more scroll events to the terminal than it should be.

Windows Terminal is otherwise dope and I'd love to be able to replace my janky Xming + urxvt setup for coding on Windows.

Here's a video I captured of the behavior in `tmux` — I tried to scroll a very small amount, and instead it scrolled 78 rows:

ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by DHowett**
By storing up the accumulated delta in the mouse input handler, we can
enlighten both conhost and terminal about wheel events that are less
than one line in size. Previously, we had a workaround in conhost that
clamped small scroll deltas to a whole line, which made trackpad
scrolling unimaginably fast. Terminal didn't make this mistake, but it
also didn't handle delta accumulation . . . which resulted in the same
behavior.

MouseInput will now wait until it's received WHEEL_DELTA (well-known
constant, value 120) worth of scrolling delta before it dispatches a
single scroll event.

Future considerations may include sending multiple wheel button events
for every *multiple* of WHEEL_DELTA, but that would be a slightly larger
refactoring that I'm not yet ready to undertake.

There's a chance that we should be dividing WHEEL_DELTA by the system's
"number of lines to scroll at once" setting, because on trackpads
conhost now scrolls a little _slow_. I think the only way to determine
whether this is palatable is to just ship it.

Fixes #6184.

### CODE REVIEW

**Comment by DHowett** [comment]
Pull request !175984 to OpenConsole states:

> Trackpad events scroll properly now
> `WM_MOUSEWHEEL` events use a wheel delta to tell an app how much they scrolled, with `WHEEL_DELTA` representing "one" scroll event. Trackpads however, frequently scroll in increments less than that. So now each scroll event gets a VT mode scroll event. Windows apps won't see a change, but VT mousemode apps will get many more scroll events on trackpads than a usual app, but it works now.

> VT mousemode apps will get many more scroll events ... than a usual app

@zadjii-msft since you originally wrote the +1/-1 wheel delta workaround in windowio.cpp (input.cpp), do you additionally sign off on this being the right solution to that problem from 2016? 😉

**Comment by zadjii-msft** [comment]
Lol yea, this is way better. Thanks for finally getting around to it 😄

**Comment by miniksa** [comment]
> Pull request !175984 to OpenConsole states:
> 
> > Trackpad events scroll properly now
> > `WM_MOUSEWHEEL` events use a wheel delta to tell an app how much they scrolled, with `WHEEL_DELTA` representing "one" scroll event. Trackpads however, frequently scroll in increments less than that. So now each scroll event gets a VT mode scroll event. Windows apps won't see a change, but VT mousemode apps will get many more scroll events on trackpads than a usual app, but it works now.
> 
> > VT mousemode apps will get many more scroll events ... than a usual app
> 
> @zadjii-msft since you originally wrote the +1/-1 wheel delta workaround in windowio.cpp (input.cpp), do you additionally sign off on this being the right solution to that problem from 2016? 😉

@DHowett, thanks for checking that.

**Comment by miniksa** [comment]
@DHowett where's the test for your new Utility function? :P

**Pull request merged**
