### PR TITLE
Fix cursor restore to happen on the tab row

### LINKED ISSUE #8918: A hidden mouse cursor won't reappear when moved if over a tab
# Environment

Windows build number: Version 10.0.18363.1256
Windows Terminal version (if applicable): commit d29d72e1e023491800b6a03bc226c35e5f9ec240

# Steps to reproduce

1. You'll need to be running a build of WT that includes the mouse hiding feature introduced in PR #8629.
2. Move the mouse so it's positioned over one of the tab labels.
3. Start typing something so the mouse cursor disappears.
4. Try and move the mouse, but without moving off the label.

# Expected behavior

The mouse cursor should reappear.

# Actual behavior

The mouse cursor remains invisible until you move it onto the main output area of the window. But you can still see focus interactions, and tooltips changing, as you move over the tab controls.

Interestingly, if you move the mouse right off the WT window, it will become visible, but then moving back onto a tab will make it disappear again.

### PR DESCRIPTION
**Pull request by Don-Vito**
Closes #8918

### CODE REVIEW

**Comment by Don-Vito** [comment]
@zadjii-msft - created this PR for the case there is a service release. This solves the issue for tabview but doesn't solve for MinMaxCloseControl.

**Comment by Don-Vito** [comment]
@zadjii-msft  - bump.

**Review by rheh — APPROVED** [review]

**Review by zadjii-msft — APPROVED** [review]

**Comment by zadjii-msft** [comment]
Sorry for the delays. Dustin's busy all week so it might not be till next Monday till this gets merged for servicing, heads up.

**Comment by Don-Vito** [comment]
@DHowett - if you are here, please take a look (this is a one-liner).

**Review by DHowett — COMMENTED** [review]
Ah, if only it was less fiddly. Thank you for doing this.

**Review by DHowett — APPROVED** [review]

**Pull request merged**
