### PR TITLE
Add High Contrast image assets

### LINKED ISSUE #6822: High contrast version of app icon - discussion
How does the Terminal team feel about high contrast icons?  If someone were to contribute a set of assets, would you accept them?  Are there any constraints or considerations for artwork that a contributor should be aware of?  Is there some graphics pipeline, not visible in source control here, that needs to be updated instead of providing finished PNG files?

To demo the possibilities, I tried hacking up a high contrast version of one of the icons.  I've presented the prototype here, in both black and white HC themes.  For context, I've also included Calculator's HC icon.

demoblack

demowhite

By way of comparison, here's the status quo:

currentblack

currentwhite

In some places (eg taskbar), the shell plates the icon, since there's not a dedicated HC icon, so the shell isn't sure whether the icon would have enough contrast with a black or white background:

currentplatedblack

This comment is forked from a discussion on #5360

### PR DESCRIPTION
**Pull request by jtippet**
## Summary of the Pull Request
Add image assets for High Contrast mode

## References
Tagging this issue so it contains a nice list of all the recent HC fixes: #5360

## PR Checklist
* [ ] Closes #6822 
* [X] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [X] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #6822

## Detailed Description of the Pull Request / Additional comments
I made several changes to DHowett's script and added it to the repo:
* Add support for generating high contrast icons
* Add the ability to easily edit the "intermediate" (previously "zbase") files for manual hinting
* Appease the spellcheck police

I created new SVGs for HC mode.  There's one SVG for both Black and White modes -- I just invert the colors.  Then I manually hinted the generated bitmaps for the production icons.  I didn't bother hinting the Dev/Pre ones, so the text does get unreadable at small sizes.

## Validation Steps Performed
Your web browser is probably making all these images blurry.  To see how the icon really looks, save the images locally and open in mspaint.

This is the full ramp of icons:
image

Here's the terminal hanging out among a carefully-chosen taskbar full of well-behaved built-in icons:
image

Same, but at 96dpi:
image

A more typical cohort:
image

Pinned to the Start Menu:
image

### CODE REVIEW

**Comment by zadjii-msft** [comment]
@msftbot make sure @DHowett and @cinnamon-msft sign off on this.

**Comment by DHowett** [comment]
This is so, so good. Thank you.

**Comment by DHowett** [comment]
I'll handle the merge on this one myself, so I cleared `AutoMerge`

**Comment by DHowett** [comment]
@jtippet Is this ready to go? I noticed you didn't mark it as closing #6822 or give it a title. I'm happy to do both, I just want to make sure

**Comment by jtippet** [comment]
> @jtippet Is this ready to go? I noticed you didn't mark it as closing #6822 or give it a title. I'm happy to do both, I just want to make sure

Yeah it's ready to go... those are oversights.

**Comment by DHowett** [comment]
Thanks so much for being our HC champion

**Pull request merged**
