### PR TITLE
Copy CWD action

### LINKED ISSUE #12860: Add an action to copy CWD path to clipboard
I think this is pretty self explanatory.
Similar concerns as the "Open in File Explorer" action, #12859.
Maybe there's a way to make the action do nothing if the active Terminal hasn't set one?

Also relevant: #3337, #5916

### PR DESCRIPTION
**Pull request by davidegiacometti**
## Summary of the Pull Request
Added action for copy CWD

 
## References
Require configuration: https://docs.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory

## PR Checklist
* [x] Closes #12860
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #12860

## Validation Steps Performed
- Ensure to have shell configured to update CWD: https://docs.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory
- Terminal > Settings > Actions: assign a shortcut to "Copy CWD" action
- Navigate directories and copy the CWD with the configured action

### CODE REVIEW

**Review by zadjii-msft — COMMENTED** [review]
I don't know if I love the action being `copyCWD`, but honestly it's short sweet and to the point. Not like I have a better suggestion 😅  It seems good to me!

(just update that one string 😄)

**Review by zadjii-msft — CHANGES_REQUESTED** [review]
I'm blocking this for more discussion based on some Teams chatter. Thanks for the patience!

**Comment by davidegiacometti** [comment]
No problem! Will update this PR and also create a PR for the documentation based on feedback.

@zadjii-msft I have also tested this on WSL and the returned CWD is `\\wsl$\Ubuntu\home\davide\.ssh`.
This is perfect for #12859, but a bit for this. What do you think?

**Comment by davidegiacometti** [comment]
Hi @zadjii-msft 
Any news on this? Feel free to close the PR if this isn't the wanted solution.

**Comment by zadjii-msft** [comment]
Alas, yea, I do have news. This is definitely on me for putting off the bad news here. 

We talked about this a little while back. The team consensus was that this is a perfectly good and sensible PR. The implementation is totally as we'd expect. However, it's probably not time for this feature quite yet. It's kinda... awkward. 
* The action doesn't overall provide that much value at the moment? Originally, I really expected this to be used with the context menu from #3337. I just don't think I really expected anyone to do it before we got around to that one
  * for the record, I've been putting off writing this response for a while, cause I thought I could sneak implement #3337 in my free time, and then we could accept this too. I got close!
  image
  But given I'm about to go on paternity before the end of the month, I highly doubt this side-hack will land soon. 
* Most people definitely don't have the path integration set up, so for most people, this action ends up just copying the `startingDirectory`.
* We probably didn't give the original idea the right amount of triage diligence to parent it to the context menu task, or at least really think it through. It was more of a showerthought.


So right now the team consensus was to 
* close this out
* take off "easy starter"
* eventually (in the fullness of time), recreate this exact PR to bring the action in (and give you a `co-authored by:` credit in the commit). 


Does that all sound reasonable? Sorry for putting this off for so long. I thought I'd be better at being the bearer of bad news, but just ended up dragging my feet. That's on me 😓

**Comment by davidegiacometti** [comment]
Don't worry @zadjii-msft, I totally understand.
Thank you

**Pull request closed without merging**
