### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by wrt54g**
## PR Checklist
* [ ] Closes #xxx
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
I added dependabot for Actions.

### CODE REVIEW

**Comment by zadjii-msft** [comment]
See also: 
* #4165
* #13363

It kinda looks like dependabot was enabled automatically for us - what would this PR change?

**Comment by wrt54g** [comment]
@zadjii-msft That's for other packages. This is for GitHub actions.

**Comment by DHowett** [comment]
I'd love to have this if it's going to provide us even better insights! Sorry for the delay.

We currently use Microsoft's "Component Governance" portal, which warns us about unsafe packages detected after a build completes, plus catalogues our entire set of packages for legal purposes. I wonder if there's a solution to this that will both (1) get us Dependabot integration and (2) continue providing security notifications through the MS CG channels...

**Comment by jsoref** [comment]
Fwiw, in theory this will get a pull request suggesting updating check-spelling, it would look something like this:
https://github.com/check-spelling/PowerToys/pull/13

I obviously don't know anything about MS CG.

**Pull request closed without merging**
