### PR TITLE
rle: fix build with clang by adding a deduction guide

### PR DESCRIPTION
**Pull request by DHowett**

### CODE REVIEW

**Comment by lhecker** [comment]
Wait why doesn't this work for you? This compiles just fine for me on clang 12 with `-std=c++17`.

**Comment by DHowett** [comment]
Ah, I was building with Clang 10. Interesting...

**Comment by lhecker** [comment]
It should even work in clang 9! https://godbolt.org/z/Esa7fv7MP

**Comment by DHowett** [comment]
```
In file included from buffer.cpp:13: ././src/inc/til/rle.h:855:25: error: no viable constructor or deduction guide for deduction of template arguments of 'rle_scanner'             rle_scanner scanner{ _runs.begin(), _runs.end() };                         ^ ././src/inc/til/rle.h:477:13: note: in instantiation of member function 'til::basic_rle<unsigned char, unsigned short, boost::container::small_vector<til::rle_pair<unsigned       char, unsigned short>, 3, void, void> >::_replace_unchecked' requested here             _replace_unchecked(start_index, end_index, replacements);             ^ buffer.cpp:200:19: note: in instantiation of member function 'til::basic_rle<unsigned char, unsigned short, boost::container::small_vector<til::rle_pair<unsigned char, unsigned       short>, 3, void, void> >::replace' requested here             _cwid.replace(gsl::narrow_cast<uint16_t>(begin), gsl::narrow_cast<uint16_t>(begin + len), gsl::make_span(&newRuns[0], glyph.size() == 1 ? 1 : 2));                   ^ ././src/inc/til/rle.h:607:16: note: candidate function template not viable: requires 1 argument, but 2 were provided         struct rle_scanner                ^ ././src/inc/til/rle.h:607:16: note: candidate function template not viable: requires 0 arguments, but 2 were provided ././src/inc/til/rle.h:505:29: error: no viable constructor or deduction guide for deduction of template arguments of 'rle_scanner'                 rle_scanner scanner(_runs.begin(), _runs.end());                             ^ buffer.cpp:243:19: note: in instantiation of member function 'til::basic_rle<unsigned char, unsigned short, boost::container::small_vector<til::rle_pair<unsigned char, unsigned       short>, 3, void, void> >::resize_trailing_extent' requested here             _cwid.resize_trailing_extent(gsl::narrow_cast<uint16_t>(_data.size()));                   ^ ././src/inc/til/rle.h:607:16: note: candidate function template not viable: requires 1 argument, but 2 were provided         struct rle_scanner                ^ ././src/inc/til/rle.h:607:16: note: candidate function template not viable: requires 0 arguments, but 2 were provided 2 errors generated.
```

**Comment by DHowett** [comment]
Sorry for the missing newlines. I have to post comments through the GitHub API. Let me try to edit that one ...

**Comment by DHowett** [comment]
https://godbolt.org/z/P3xGe1xWd
there you go :smile:

**Comment by lhecker** [comment]
This is some weird stuff. It works in gcc as well...
Can you move the deduction guide up to the struct definition? Or was there a specific reason to have it at the end of the class scope?

**Review by lhecker — APPROVED** [review]
I'm approving this to unblock you (and of course since your change is entirely correct).
It'd be nice to see it closer to the struct itself, but it _honestly_ really doesn't matter if you don't.

**Comment by DHowett** [comment]
No reason to have it so low. I initially wrote it outside the class body completely, and when that didn't work I moved it up inside quickly to test it. :)

**Review by zadjii-msft — APPROVED** [review]

**Pull request merged**
