### PR TITLE
Pass through line rendition attributes over conpty

### LINKED ISSUE #11595: Add support for Double-Height and Double-Width text to Windows Terminal
# Description of the new feature/enhancement

At least Windows 11 ships with a conhost version which supports `DECDHL` and `DECDWL`. I'm used to telling people who are asking for a better VT support something like "Hey, check out the shiny Windows Terminal. It supports quite some escape sequences that the console host does not, and you can even set it as default terminal app." Now I have to add "... unless you're looking for double height/width text where you explicitly have to use the good ol' console." This feels rather odd 😄

# Proposed technical implementation details (optional)

Consider adding this feature to Windows Terminal. 
However, from what I've read, the current architecture of conpty doesn't seem to be ready yet. So, I suppose a lot of refactoring would be necessary to get to the preconditions 😧

Related: #7865, #8664
cc @j4james

### PR DESCRIPTION
**Pull request by j4james**
This PR introduces a mechanism for passing through line rendition
attributes to the conpty client, so we can support double-width and
double-height text in Windows Terminal.

Line renditions were first implemented in conhost (with the GDI
renderer) in PR #8664, and were implemented in the DX renderer in PR
#13102.

By default this won't add any additional overhead to the conpty output,
but as soon as there is any usage of double-size text, we switch to a
mode in which every line output will be prefixed with a line rendition
sequence. This is to ensure that the line attributes in the client
terminal are always in sync with the host.

Since this does add some overhead to the conpty output, we'd prefer not
to remain in this mode longer than necessary. So whenever there is a
full repaint of the entire viewport, we check to see if all of the lines
are single-width. If that is the case, we can then safely skip the line
rendition sequences in future updates.

One other small optimization is when the conpty update is only writing
out a single character (this is something we already check for). When
that is the case, we can safely skip the line rendition prefix, because
a single character update should never include a change of the line
rendition.

## Validation Steps Performed

I've manually tested that Windows Terminal now passes the double-size
tests in _Vttest_, and also confirmed various edge cases are working
correctly in my own double-size tests.

Closes #11595

### CODE REVIEW

**Comment by DHowett** [comment]
It's unfortunate that we're keen on replacing the DX engine here! Thanks for doing all of this. @lhecker we should consider how we'll represent glyphs in the atlas that take up more _vertical_ space than one row (!)

**Comment by j4james** [comment]
> It's unfortunate that we're keen on replacing the DX engine here! Thanks for doing all of this. @lhecker we should consider how we'll represent glyphs in the atlas that take up more _vertical_ space than one row (!)

I haven't really looked at the Atlas renderer, because I assumed I would be a bit out of my depth there, but I had hoped that the line-rendition support I added to the DX renderer could be ported fairly easily by someone that knew what they were doing.

And I wouldn't think you'd need to do anything special in the atlas if you're taking the same approach - it's just a transform that's applied when each line is rendered.

**Comment by DHowett** [comment]
> And I wouldn't think you'd need to do anything special in the atlas if you're taking the same approach - it's just a transform that's applied when each line is rendered.

Possibly. The core conceit of atlas is that we rasterize each `[glyph * font]` combo one time into a GPU texture and then use a pixel shader to copy and color the glyph mask directly to the render target. I think if we approach it the same way, we may end up with scaling artifacts.

My gut tells me that we'll want to do the transform in the early phase when we're producing the glyph texture, and somehow mark that glyph as requiring multiple cells much like we would if it were multi-width. Hmm...

**Comment by j4james** [comment]
> I think if we approach line renditions the same way as we do in DX, we may end up with scaling artifacts.

Yeah, I just realised that after I posted my reply. But I'd personally be perfectly happy with that as a solution. It's certainly better than nothing. Obviously this is just me, but right now most of my use cases for double-size text involve soft fonts, which have a fixed resolution anyway, so they're always going to be scaled.

On that note, I should mention that I have a plan for soft font support over conpty which I'd like to create a PR for at some point. And again I'm hoping someone smarter than me will be able to port the DX implementation to Atlas so we can have soft fonts working there too.

**Comment by j4james** [comment]
> My gut tells me that we'll want to do the transform in the early phase when we're producing the glyph texture, and somehow mark that glyph as requiring multiple cells much like we would if it were multi-width.

Thinking about this some more, double-height glyphs may not actually be a problem, because you only ever render one half of the glyph at a time (i.e. the top is rendered independently of the bottom). So the only additional functionality I think you might need would be some extension to the ID to distinguish between variants of a particular character (single width, double-width, double-height top, double-height bottom).

And this is assuming the atlas can already handle glyphs that are multiple cell widths, and not just double width, because any existing double width character, would now potentially be quadruple width.

**Comment by DHowett** [comment]
Ah, right! It's actually just the tops and bottoms of the glyphs cleverly rendered next to eachother.

We do have support for glyphs that are >2 cells in width today; that's how we ended up implementing ligatures! That does mean that Cascadia's "infinite arrow" ligatures are, ah, expensive in terms of glyph space... but what can you do?

<details>
<summary>Glyph atlas with an infinite arrow</summary>

Each version of the ligature is rendered in full into the texture.

### screen

screen


### atlas
 
image

</details>

**Comment by lhecker** [comment]
Yep I'll gladly port everything over to AtlasEngine if you don't feel comfortable with it. Now that the new engine is sorta useable, I'm currently in the process of cleaning up that project to be better structured and easier to deal with.

For context:
* `cells`: A 3 cell wide glyph reserves 3 equally large cells in the texture atlas. The `cells` array stores those texture coordinates. The cells in the texture atlas aren't necessary next to each other, but the pixel shader will bit-blit them to appear next to each other on the screen.
* `cellCount`: The number of cells a glyph owns (in this example it's 3).
* `CellFlags`: Stores glyph and cell-specific attributes, like is-italic/intense/underlined/overlined/etc.

I'm planning to add double-height glyphs as a flag to `CellFlags`. If that flag is set, then the `cells` array stores twice as many entries as the `cellCount` indicates. All the existing code that assumes that the `cellCount` equals the width of the glyph in cells will continue to work. But if we encounter a double-height-line-rendition row then we will use the second half of the `cells` array to copy over another `cellCount`-many cells over into the lower half of the double-height row.

**Comment by j4james** [comment]
> But if we encounter a double-height-line-rendition row then we will use the second half of the `cells` array to copy over another `cellCount`-many cells over into the lower half of the double-height row.

Just FYI, that's not how double-height rendition works. The top and bottom are completely independent and don't necessarily match. So you can have the top half of the letters `ABC` over the bottom half of `XYZ`. Or say one line being just the bottom half of the characters with single height lines above and below. You can mix and match line attributes however you want.

So in the same way that you have variants of each character for italic and bold, etc. I'd assume you'd also have double-width, double-height top, and double-height bottom variants. Then when rendering a line with the `DoubleHeightTop` attribute, you'd use the corresponding top variant for all the characters in that line. What appears on the following line is irrelevant.

**Review by lhecker — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
Thanks! Now that 1.16 has branched, we're clear to land new fun stuff.

**Pull request merged**
