### PR TITLE
Make about dialog content copyable

### LINKED ISSUE #1335: About dialog should have a copy button
Or just straight up be copyable. There's gotta be a way to do that with UWP.

### PR DESCRIPTION
**Pull request by Summon528**
## Summary of the Pull Request
Make about dialog content copyable

 
## PR Checklist
* [x] Closes #1335
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
Wrap aboutText with a selectable text block.

### CODE REVIEW

**Comment by mdtauk** [comment]
Is that a ContentDialog?  Couldn't you just use the `IsTextSelectionEnabled="True"` property on the TextBlock?

**Comment by DHowett-MSFT** [comment]
It's a ContentDialog whose `Content` is a boxed `HSTRING`. This _makes_ it the `TextBlock` you're suggesting we set `IsTextSelectionEnabled` on.

**Comment by DHowett-MSFT** [comment]
(Terminal doesn't use `.xaml` files, which is something we know we need to fix, etc.)

**Comment by mdtauk** [comment]
> It's a ContentDialog whose `Content` is a boxed `HSTRING`. This _makes_ it the `TextBlock` you're suggesting we set `IsTextSelectionEnabled` on.

I asked the question, checked the code change, and saw the property being used.  Can't normally understand C++ code, so I spoke before checking lol

**Pull request merged**
