### PR TITLE
Fix signatures of some callback functions

### PR DESCRIPTION
**Pull request by beevvy**
## Summary of the Pull Request
This PR fixes a bunch of callback function signatures so that they align with the signatures expected by Windows API. Most changes are from `__cdecl` to `__stdcall`, which matters on x86, but not on x64 or ARM64.

## PR Checklist
* [ ] Closes #xxx
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
I find it hard to believe that conhost.exe as shipped in Windows would use callback functions with incorrect calling convention. Perhaps the version that ships with Windows is compiled with `/Gz` (`__stdcall`-by-default)? But OpenConsole.sln isn't.

All of these functions were found manually, so it's likely that there are more issues like this that I didn't find. It would be great if MSVC had a warning similar to GCC's `-Wcast-function-type`.

The only one signature incompatibility I found that wasn't eliminated was with `FONTENUMPROC` (I only fixed the calling convention, which is most important anyway), since a slightly different signature is being used that is similar to [`EnumFontFamProc`](https://docs.microsoft.com/en-us/previous-versions/dd162621(v%3Dvs.85)) rather than [`EnumFontFamExProc`/`FONTENUMPROC`](https://docs.microsoft.com/en-us/previous-versions//dd162618(v=vs.85)), and a slightly more invasive change would be needed.

### CODE REVIEW

**Comment by HBelusca** [comment]
Example: it is known that by default when you compile stuff using the WDK + its makefiles, that the default compiler switches will make your functions automatically stdcall. If you try to compile same code elsewhere, **if** the functions have not been marked stdcall explicitly, they will possibly be compiled with a different convention (e.g. cdecl). I suppose, by looking at this, that the Windows codebase is compiled with default function call convention stdcall, and this would explain why the same openconsole --> conhost code when being compiled as part of the Windows codebase, has its functions stdcall, but here, since openconsole is compiled separately and since it appears it doesn't use explicitly stdcall, you would end up with cdecl functions (for example). And since it doesn't matter on x64, possibly the problem has been unnoticed.

**Comment by zadjii-msft** [comment]
@msft-github-bot make sure @DHowett-MSFT and @miniksa review this

**Comment by DHowett-MSFT** [comment]
This _sounds_ correct to me, but I'll have to dig in and this is almost certainly in @miniksa's wheelhouse.

**Comment by miniksa** [comment]
I'm trying to confirm the assertion that the Windows build system automatically resolved this and that's why we didn't notice. Please hold.

**Comment by miniksa** [comment]
I checked AMD64 and x86 Windows build environments for these files and /Gz is getting applied without our own conscious effort.

**Comment by miniksa** [comment]
> The only one signature incompatibility I found that wasn't eliminated was with `FONTENUMPROC` (I only fixed the calling convention, which is most important anyway), since a slightly different signature is being used that is similar to [`EnumFontFamProc`](https://docs.microsoft.com/en-us/previous-versions/dd162621(v%3Dvs.85)) rather than [`EnumFontFamExProc`/`FONTENUMPROC`](https://docs.microsoft.com/en-us/previous-versions//dd162618(v=vs.85)), and a slightly more invasive change would be needed.

I agree that you got the important bit, but we could file that issue and take it separately. I wouldn't mind the more invasive change to get that sorted out. Let's just not let it get caught up in this one.

**Comment by miniksa** [comment]
> I'm starting to get the idea that _every time we see a cast for a function pointer we have done something terribly wrong_.

Is this something CppCoreChecks could find if we could get them up and running?

**Comment by DHowett-MSFT** [comment]
@msftbot please wait 2 more hours before merging this

**Comment by DHowett-MSFT** [comment]
@msftbot hold this pr for the next 2 hours

**Comment by HBelusca** [comment]
> I'm starting to get the idea that _every time we see a cast for a function pointer we have done something terribly wrong_.

Definitively it should ring a bell.

**Comment by beevvy** [comment]
> > The only one signature incompatibility I found that wasn't eliminated was with `FONTENUMPROC` (I only fixed the calling convention, which is most important anyway), since a slightly different signature is being used that is similar to [`EnumFontFamProc`](https://docs.microsoft.com/en-us/previous-versions/dd162621(v%3Dvs.85)) rather than [`EnumFontFamExProc`/`FONTENUMPROC`](https://docs.microsoft.com/en-us/previous-versions//dd162618(v=vs.85)), and a slightly more invasive change would be needed.
> 
> I agree that you got the important bit, but we could file that issue and take it separately. I wouldn't mind the more invasive change to get that sorted out. Let's just not let it get caught up in this one.

Filed at #889.

**Comment by beevvy** [comment]
> > I'm starting to get the idea that _every time we see a cast for a function pointer we have done something terribly wrong_.
> 
> Is this something CppCoreChecks could find if we could get them up and running?

As of VS 2019 16.0, there's nothing in CppCoreChecks that would catch this particular type of issue.

However, clang's `-Wcast-calling-convention` covers exactly this case. I ran clang-tidy on the solution and it didn't find anything I may have missed.

I don't know of any existing tool that would warn on _any_ cast of function pointer.

**Comment by miniksa** [comment]
Good call emailing the suggestion. If we could somehow use clang-tidy without having to pull in all of clang, I'd be happy to. But I think @adiviness looked at that once and it was untenable.

**Comment by adiviness** [comment]
We'd just need to extract the executables I think. I know that works fine for clang-format, I'm not sure about clang-tidy.

**Comment by beevvy** [comment]
Yeah, clang-tidy.exe is all you need.

**Comment by ChrisGuzak** [comment]
FYI, there is also a VS plug in to enable using this from within the IDE

https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools

**Comment by beevvy** [comment]
FWIW, my suggestion about implementing a check in MSVC is being tracked on the Developer Community at https://developercommunity.visualstudio.com/idea/588338/implement-a-diagnostic-for-casts-between-incompati.html

**Pull request merged**
