### PR TITLE
Don't comment on commits, cause no one's using that

### PR DESCRIPTION
**Pull request by zadjii-msft**
As discussed on teams. 

Refer to https://github.com/check-spelling/check-spelling/issues/23#issuecomment-1195826414

### CODE REVIEW

**Review by carlos-zamora — APPROVED** [review]

**Review by DHowett — CHANGES_REQUESTED** [review]
HA! I actually do use this... rarely. I push a branch containing the inbox merge to spellbot it before pushing it to main.

**Comment by zadjii-msft** [comment]
> HA! I actually do use this... rarely. I push a branch containing the inbox merge to spellbot it before pushing it to main.

I believe it will still run on pushed commits, it just won't comment. I don't know how we could look at those results though

**Comment by zadjii-msft** [comment]
image


https://github.com/microsoft/terminal/runs/7525087094?check_suite_focus=true

**Review by lhecker — APPROVED** [review]

**Comment by lhecker** [comment]
> HA! I actually do use this... rarely. I push a branch containing the inbox merge to spellbot it before pushing it to main.

I'm in favor of this PR. The commits I push aren't ready to be merged yet more often than not, and if they get spellbot comments I consider them distracting if anything (I get 2 mails every time I push my larger branches). This is different to PRs or proper merges where I do want to be careful.

**Comment by DHowett** [comment]
Makes sense to me, let's do it!

**Pull request merged**
