### PR TITLE
Add copyFormatting setting to all settings json files

### LINKED ISSUE #5403: `copyFormatting` doesn't have the agreed-upon default in the settings template
The spec for #5299 specified how we should handle the default for this setting.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
Added `copyFormatting` to defaults json files and userDefaults.

## PR Checklist
* [X] Closes #5403

### CODE REVIEW

**Comment by carlos-zamora** [comment]
I couldn't find anything in the spec about it. Makes sense to include it as false in the defaults.json and settings.json right? That way they agree with each other, and settings.json provides visibility.

**Comment by DHowett-MSFT** [comment]
image

I don't believe that's the decision we came to, because it's really shitty for our existing users

**Comment by cinnamon-msft** [comment]
I thought we agreed on `false` by default in both defaults.json and settings.json. The default experience should be plain text, and setting it to `true` in the settings.json means it's not plain text by default. Adding it into the settings.json provides visibility for existing users, in my opinion.

**Comment by carlos-zamora** [comment]
> ✔️	❌	new users have to turn HTML copy on

I think the alternative you're looking for is this then. This would be the first time we have defaults and settings completely disagree. So, that's my main issue with it.

**Comment by DHowett-MSFT** [comment]
It’s absolutely not the first time the defaults and settings template will disagree. Consider all the key bindings we just added

**Comment by zadjii-msft** [comment]
> defaults | template | result
> -- | -- | --
> ✔️ | ❌ | new users have to turn HTML copy on



I thought we decided on this, because it meant:
* new users have plain-text copy by default
* old users still have html enabled
* new users can easily discover that this is a setting and enable it

**Comment by carlos-zamora** [comment]
Ok. So I updated it on defaults.json to match what you said. I updated the default in the schema too because that needs to align as well.

I specifically kept universal-defaults the same, because there's no settings.json on that version right?

Also, @msftbot make sure @cinnamon-msft signs off on this.

**Comment by carlos-zamora** [comment]
@msftbot make sure @cinnamon-msft signs off on this

**Pull request merged**
