### PR TITLE
Make sure caption controls "dim out" when window loses NC focus

### PR DESCRIPTION
**Pull request by AnuthaDev**
Hello frands, I gib smol code

## Summary
Make the caption controls "dim out" when window loses focus
 
## References
https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-ncactivate
https://github.com/microsoft/terminal/pull/5881
https://github.com/microsoft/terminal/pull/3025

## PR Checklist
* [x] Applies to #1625
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
Added a handler for WM_NCACTIVATE to propagate the focus change to the Titlebar Control.

The unfocused color is set to ForegroundBaseLow

## Validation Steps Performed
None
Typed code on phone, PC is too weak to compile the whole project.

Also, My combined knowledge of c++ and xaml is still miniscule, so please have mercy😅😅

### CODE REVIEW

**Comment by DHowett** [comment]
😢 you could have just updated the existing pull request/asked for it to be reopened lol

**Comment by DHowett** [comment]
You haven't resolved the issues brought up in #6577. When you do, we'll reopen that one. It's not worthwhile to submit the same change without updates when the bot closes it because you haven't updated it :P

**Comment by AnuthaDev** [comment]
> You haven't resolved the issues brought up in #6577. When you do, we'll reopen that one. It's not worthwhile to submit the same change without updates when the bot closes it because you haven't updated it :P

Uhmm, please check again

**Comment by AnuthaDev** [comment]
@DHowett I copied the description from that PR and edited it afterwards...

**Comment by AnuthaDev** [comment]
> 😢 you could have just updated the existing pull request/asked for it to be reopened lol

Oh well, that didnt cross my mind lol...

**Comment by DHowett** [comment]
Oh, I see. Okay. We'll review this. Thanks/sorry!

**Comment by AnuthaDev** [comment]
> bot closes it because you haven't updated it :P

Sorry, I was busy studying for exams.😞😞

**Comment by AnuthaDev** [comment]
Hmm, how do I implement ```bool Focused()``` in the .cpp file?(using another private variable?), I dont know c++, lol.

**Comment by zadjii-msft** [comment]
Hey so I finally had a chance to loop back on this PR. Turns out, you're super close to getting this working right. I threw together the remaining bits in 9a776208 if you want to take a look - you should be able to merge them into your PR without much hassle. 

Thanks for the patience!

**Comment by AnuthaDev** [comment]
@zadjii-msft Thanks a lot!😄

> I threw together the remaining bits in 9a77620 if you want to take a look

Thanks, but as I mentioned in the description, I can't compile the code to test. Code looks good😊.

> you should be able to merge them into your PR without much hassle.

Ohhh, I am not too sure about that😅. I only know the most [trivial](https://xkcd.com/1597/) git commands and especially after the change of base branch, I am afraid I would mess up.

So, if you could tell me *exactly* what commands I need to use, I would be extremely grateful 🙏🙏.

**Comment by AnuthaDev** [comment]
Tried rebasing, failed miserably

**Pull request closed without merging**
