### PR TITLE
Convert Pasted Line Endings and then send to compty

### LINKED ISSUE #1091: Pasted text includes CRLF pairs where unneeded
Multiline text pasted from the clipboard includes CRLF pairs in all cases; this is inappropriate for "Unix-space" sessions, such as WSL.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.145]
Windows Terminal version (if applicable): 71e19cd82528d66a0a7867cbed85990cfc1685f1
```

# Steps to reproduce

Select multiline text in Terminal.
Copy it (via right-click, ostensibly)
Paste it (again via right-click)

# Expected behavior

When pasting into a Unix-space session -- such as WSL -- pasted text should have a reasonable set of line-ending characters.

# Actual behavior

Line endings are "doubled" on text paste to Unix-space sessions.

### PR DESCRIPTION
**Pull request by pi1024e**
## Summary of the Pull Request
This is from a PR request by @d-bingham. However, there have been 89 commits since then, and there are merge conflicts that have not been attended to in a month, and I think converting pasted line endings is a neat idea, so this PR has the changes in PR#1094, but rebased to be current.

 
## References
PR#1094

## PR Checklist
* [x] Closes #1091
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed
* [x] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan.

## Detailed Description of the Pull Request / Additional comments
@d-bingham said 

> The new option, convertPasteLineEndings does what it says -- replacing Windows-space CRLF pairs with Unix-space LFs in text pasted to the console. This option applies to both the keyboard-shortcut paste and the right-click paste. Without this most multiline text pasted into Terminal will be "double-spaced" due to the Windows-style CRLF pairs. Furthermore, any multiline text copied from Terminal (in trim whitespace mode) generates CRLF pairs, which guarantees double-spacing when copying from a WSL Terminal session.
Changes:

> - Added TermControl::_SendPastedTextToConnection which adds a pre-processing layer on top of _SendInputToConnection to allow line-ending conversion

> - Various code in Profile/TerminalSettings to support the new option "convertPasteLineEndings" (optional, defaults to false)

## Validation Steps Performed
I performed manual and automated testing to ensure this would not break any current code.

### CODE REVIEW

**Comment by pi1024e** [comment]
cc: @zadjii-msft, I would like to get your input, as conpty does no such thing.

**Comment by pi1024e** [comment]
@DHowett May I please get your opinion on this too?

**Comment by DHowett-MSFT** [comment]
Hey, so, I just had a look at a bunch of other terminal emulators. It looks like they all (unconfigurably!) transform `\n` to `\r` (on Linux) and `\r\n` to just `\r` (on Windows). I think we can safely do that and not need to introduce a new setting.

Here's why I think that: Windows Terminal wants to be a standards-compliant--or, as compliant as it can be--terminal emulator. It should act in every way like every other terminal emulator. If that means that it only ever sends an _enter_ keypress as `CR` (`\r`), so be it.

By making Windows Terminal compliant with [specified standard](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html) (search for `| CR` to get to the keyboard section), we can leave the compatibility work of translating CR back into CRLF for Windows applications in ConPTY.

Also, unrelatedly, it is very hard for us to accept pull requests that also make unrelated code style and formatting changes. Please try to refrain from doing that!
Thanks.

**Comment by pi1024e** [comment]
So we should put this functionality in Conpty? got it.

**Comment by DHowett-MSFT** [comment]
Wait no! Conpty handles this correctly (translating \r to Enter), so Terminal should _always_ translate \r\n to \r. We don’t need a configuration option for it :)

**Comment by pi1024e** [comment]
Ok, got it. so no need to do this here, right?

**Comment by DHowett-MSFT** [comment]
Right, we just need to make `convertPasteLineRndibgs` the default and remove the option to disable it.

**Comment by DHowett-MSFT** [comment]
I did mean “endings” 😄

**Comment by thisguychris** [comment]
oh wow, we need this! 😱

**Comment by pi1024e** [comment]
So should I go and do those changes? Or is there work being done already

**Comment by DHowett-MSFT** [comment]
@pi1024e we’d love that! No work is ongoing here.

**Comment by DHowett-MSFT** [comment]
I'm going to close this one out -- please let me know if you still want to work on the final iteration! If not, I might make an attempt at it myself. :smile:

**Comment by pi1024e** [comment]
I am going to open a new PR following your advice. Thank you!

**Pull request closed without merging**
