### PR TITLE
Added Escape Key to CharacterHandler so it can be handled instead of returned.

### PR DESCRIPTION
**Pull request by pi1024e**
## PR Checklist
* [x ] Closes ##1295
* [ x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
Simply, the escape key is not handled, and it should be, as well as adjustments for more clear and maintainable code.

## Validation Steps Performed
-Manual testing to ensure no test errors.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Hey @pi1024e, thanks for the contribution. It's generally not great to introduce a bunch of unrelated changes in a single pull request. :smile: We should make sure we comport this with #1974.

**Comment by zadjii-msft** [comment]
This looks strictly like a superset of the changes in #1974. I'd rather we take that PR first, then have a discussion if we want to take any of the rest of these changes.

**Comment by miniksa** [comment]
Agreed with the above. I don't want to take this on account of the fact that it's a grab bag of undiscussed things.

If it's updated/submitted with just the one concern at hand, I'm happy to review.

**Comment by pi1024e** [comment]
I agree with this! Let us merge #1974 first!

**Comment by zadjii-msft** [comment]
Can we get a better title and description of what this PR is supposed to do? It looks like there's a bunch of unrelated changes in a bunch of files, but I have no idea _why_.

**Comment by pi1024e** [comment]
You are right. In

**Comment by pi1024e** [comment]
Issue has been resolved already in another PR, so I am going to close this

**Pull request closed without merging**
