### PR TITLE
Prevent deadlock in UIA Move API

### PR DESCRIPTION
**Pull request by carlos-zamora**
Fixes a bug where interacting with Windows Terminal when using Narrator causes Windows Terminal to hang.

`UiaTextRangeBase::Move()` locks, but later calls `UiaTextRangeBase::ExpandToEnclosingUnit()` which attempts to lock again. The workaround for this is to introduce a `_expandToEnclosingUnit()` that _does not_ lock the console. Then, `Move()` calls this new method, thus only allowing one lock to be established at a time.

This bug is observed to be in v1.11.2221.0 and _not_ in v1.9.1942.0.

### CODE REVIEW

**Comment by DHowett** [comment]
> ide-effect of #10653, which prevents re-entry (the ability to lock multiple times on the same thread).

nit: the lock we were using BEFORE 10653 was ALSO not re-entrant. Don't blame it if it didn't cause it! :smile:

**Comment by carlos-zamora** [comment]
> > ide-effect of #10653, which prevents re-entry (the ability to lock multiple times on the same thread).
> 
> nit: the lock we were using BEFORE 10653 was ALSO not re-entrant. Don't blame it if it didn't cause it! 😄

🤷 my bad. Updating the comment.

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in 1

**Comment by DHowett** [comment]
@msftbot merge this in 1 year

**Comment by DHowett** [comment]
@msftbot merge this in 1 minute

**Review by miniksa — APPROVED** [review]

**Pull request merged**
