### PR TITLE
doc: Add logos to README

### PR DESCRIPTION
**Pull request by cinnamon-msft**
## Summary of the Pull Request
Let's add our logos to our README to spice it up.

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]

**Review by miniksa — COMMENTED** [review]
I had personally thought this was going to be more like 

LOGO "Windows Terminal"

(with Cascadia as the font of course) like some of the examples...

Not just all 3 logos.

**Comment by DHowett** [comment]
I rather agree! I'd love to have a Windows Terminal banner :smile:

**Comment by lhecker** [comment]
I honestly like this version already and we can always improve on it later on.
But I'm also quite intrigued now in how a `LOGO "Windows Terminal"` version would look like as a comparison.
Either way: Nice!

**Review by UnrealApex — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
It's good enough for now.

**Pull request merged**
