### PR TITLE
Show color slider in Tab color picker

### LINKED ISSUE #7948: Impossible to set custom tab color after setting it to black
# Environment

```none
Windows build number: Win32NT, 10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 1.3.2651.0
```

# Steps to reproduce

1. Right click on tab and select _Color..._
1. Click _Custom_
1. Click _More_
1. Remove value from hex code field, tab background is set to black
1. Try to pick any color from color picker

# Expected behavior

User should be able to pick new color from color picker.

# Actual behavior

Tab color is black and can't be change by picking color from color picker, it can be only change by selecting one from predefined list or by setting any other color hex code other than black
image

### PR DESCRIPTION
**Pull request by alannt777**
Adds the color slider to the tab color picker

## PR Checklist
* [x] Closes #7948 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] ~Tests added/passed~
* [ ] ~Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx~
* [ ] ~Schema updated.~
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #7948 

## Validation Steps Performed

*Not required*

### CODE REVIEW

**Comment by alannt777** [comment]
@zadjii-msft All checks have passed. Waiting for a review

**Comment by WSLUser** [comment]
Please change OP to say "works-around" instead of closes the issue. Also, this might require a doc update in https://docs.microsoft.com/en-us/windows/terminal/tips-and-tricks under `Color a tab - Tip`. The MS Terminal team can decide that. I would add `Use the hex field  or color slider` and also add a warning about setting the hex field to black #00000.

**Comment by alannt777** [comment]
Ok @WSLUser

**Comment by DHowett** [comment]
@alannt777 Speaking as a maintainer of this project: you were correct to say that it closes #7948, because the user-visible behavior _as seen from terminal_ will be addressed. :smile:

@WSLUser's discussion points are likely more applicable to the upstream bug on microsoft-ui-xaml, which will need documentation in their doc group.

**Comment by DHowett** [comment]
As an aside: it's not generally helpful to ping individual team members for _new_ reviews or issues. Every one of us gets every action taken on this repo as an e-mail. If the review's been around for a while (more than 4 hours is a good start) and you've got specific reviewer comments and you'd like to "bring somebody back", it is then appropriate to tag them. 😁

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
Thanks for the contribution, and for catching the misconfiguration to begin with!

**Comment by alannt777** [comment]
> As an aside: it's not generally helpful to ping individual team members for _new_ reviews or issues. Every one of us gets every action taken on this repo as an e-mail. If the review's been around for a while (more than 4 hours is a good start) and you've got specific reviewer comments and you'd like to "bring somebody back", it is then appropriate to tag them. 😁

That makes sense. Because now I can choose the how light and how dark a color is without a hex or an RGB value!

**Comment by alannt777** [comment]
@DHowett Please send a screenshot of the color picker when you build it. I can't build it because I don't have the C++ build tools (I don't know C++)

**Review by zadjii-msft — APPROVED** [review]
Yea this is way better, thanks!

**Pull request merged**
