### PR TITLE
Make top titlebar padding consistent with WinUI and other apps

### PR DESCRIPTION
**Pull request by gabrielconl**
The current titlebar padding of 4px on the top was decided in #3513, and it was chosen because it persisted even in maximized mode. That was over a year and a half ago, and in the meantime with #5881 the issue was fixed.

WinUI and other tabbed apps like Chrome and Edge have the left padding equal to the one on top, because it looks more balanced.

This fix increases the height of the caption buttons in windowed mode by 4px, which in turn makes the effective top padding be 8px. (that's how it worked before as well)

top-padding

### CODE REVIEW

**Comment by lhecker** [comment]
The effective padding on the left in your screenshot is 7px and not 8px.
Personally I love this change, but before merging it I'd want the left padding to be increased by 1px in order for it to be truly symmetric. Maybe @cinnamon-msft has any other opinions about this?

**Comment by gabrielconl** [comment]
This happens because tabs are moved 1px to the left to cover the separators, but the new styles in WinUI 2.6 fix this.

**Comment by lhecker** [comment]
@gabrielconl Are you sure this is fixed? Do you happen to know the issue that fixed this supposedly?
As I was intrigued by this I've upgraded `Microsoft.UI.Xaml` to `2.6.0-prerelease.210430001` and tried both with `ControlsResourcesVersion="Version2"` and without and in neither case the padding was anything but 7px.

**Comment by gabrielconl** [comment]
It seems they added back the -1px margin. It should be compensated by increasing left padding in `TabViewHeaderPadding`. I'll create an issue for that, but I could also update it here before 2.6.

**Comment by gabrielconl** [comment]
I updated the padding because Terminal already has a custom one, and it should be equal now. I created an issue in microsoft/microsoft-ui-xaml/issues/5105, but Terminal won't get it until maximizing is done in a different way.

**Comment by gabrielconl** [comment]
We should wait until microsoft/microsoft-ui-xaml#5114 gets a decision, because this PR wouldn't be needed anymore.

**Pull request closed without merging**
