### PR TITLE
Fix build issue : TerminalApp.h missing

### PR DESCRIPTION
**Pull request by iwhp**
## Summary of the Pull Request

Compile/Build issue:
[Build Error] Cannot open include file: 'winrt/TerminalApp.h': No such file or directory

 
## References

Related to #659 and #489, #565

## PR Checklist
* [ ] Closes #xxx
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

### CODE REVIEW

**Comment by xa0082249956** [comment]
After adding the reference - 
**Yes!** VS2019 can build it successfully.
 **Not so great,** building process in VS2017  will fail, with the errors like
> Duplicate type Microsoft.Terminal.Settings.**********.

**Comment by DHowett-MSFT** [comment]
So that's the problem with this fix. The bug exists for 50% of people, and the build fix works for them... but for the _other 50%_, the build fix actually breaks them. It's completely incomprehensible.

**Comment by zadjii-msft** [comment]
You know, this might be something to summon @kennykerr and @Scottj1s for.

For whatever reason, some people have a problem if the `TerminalApp` project (many dependencies) doesn't directly reference the `TerminalSettings` project (no dependencies). However, if we were to change this, then the people who didn't originally have the build error will now have a new error, concerning having duplicate types from `TerminalSettings`.

Any ideas what we might be doing wrong here?

The linked threads have a lot more info.

**Comment by DHowett-MSFT** [comment]
It seems like Visual Studio 2019 helps this out a bit, so we might just want to wait until the toolset change lands. I'm going to close this in the meantime.
Thanks for contributing!

**Comment by iwhp** [comment]
I am using Visual Studio 2019 Preview 16.2.0 Preview 2 and it compiles without issues.

**Pull request closed without merging**
