### PR TITLE
Split rolling and PR builds. Drop ARM64, X86 from PR.

### PR DESCRIPTION
**Pull request by miniksa**
## Summary of the Pull Request
Edits the definition file to distinguish further between the rolling build (the one that happens in master as it's updated) and the PR builds (that happen on every push to a pull request to master.) We will build less in PR since it rolls so often by removing the lines that reveal very few to no bugs at PR time. We'll leave them on in rolling so stuff can still be caught.

## PR Checklist
* [x] Closes a desire to not waste builds.
* [x] I work here.
* [ ] We'll see if the build still works.
* [x] No specific docs.
* [x] I talked about this with @DHowett-MSFT already.

## Validation Steps Performed
* [x] This PR itself should validate that the definition still works in PRs. I think we have to wait for it to go to master to see if the trigger still works there.

### CODE REVIEW

**Comment by miniksa** [comment]
I still might need to follow up on the naming/placement/registration of the YML files.

**Comment by DHowett-MSFT** [comment]
Reckon we can drop x86 from PR for now? You will also need to change the build definition to refer to the new name.

**Comment by miniksa** [comment]
> 
> 
> Reckon we can drop x86 from PR for now? You will also need to change the build definition to refer to the new name.

I am searching and searching and searching around for where the heck the build definitions are.

**Comment by DHowett-MSFT** [comment]
We may need two definitions, or it might be better to use the same definition but put `condition` on the ones we don’t want ... they’re at dev.azure.com/ms/Terminal

**Comment by miniksa** [comment]
> Reckon we can drop x86 from PR for now? You will also need to change the build definition to refer to the new name.

I think we probably can. We'll have to be on the lookout for "signed/unsigned mismatch" in master. That's the only thing I've ever seen be caught by x86 build.

**Comment by miniksa** [comment]
> 
> 
> We may need two definitions, or it might be better to use the same definition but put `condition` on the ones we don’t want ... they’re at dev.azure.com/ms/Terminal

Ugh conditions is way better. I just didn't manage to read that page at https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml before you said so.

**Comment by miniksa** [comment]
> 
> 
> > We may need two definitions, or it might be better to use the same definition but put `condition` on the ones we don’t want ... they’re at dev.azure.com/ms/Terminal
> 
> Ugh conditions is way better. I just didn't manage to read that page at [docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml) before you said so.

Actually, that doesn't look right. The problem is I can't seem to figure out what the valid syntax is to specify a condition in the template job reference...

**Comment by DHowett-MSFT** [comment]
Is condition really not allowed on a job template? That seems like madness...

**Comment by miniksa** [comment]
> 
> 
> Is condition really not allowed on a job template? That seems like madness...

Nope, but you can make pass-through parallel stages. So I did that. Should offer us more flexibility going forward anyway.

**Comment by DHowett-MSFT** [comment]
@msftbot merge this in 1 minutes

**Pull request merged**
