### PR TITLE
Match the RequestedTheme of our TeachingTips to the set `theme`

### LINKED ISSUE #9717: [BASH] Window Rename TeachingTip does not handle mixed system + terminal theme
It's another problem with the app theme being a sack of lies.

_originated in 4/2 bug bash_

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

Make sure that the window renamer and other toasts follow the requested app theme. We accomplish this by doing something similar to what we do with ContentDialogs. Since TeachingTips aren't in the same XAML root, we have to traverse the entire tree upwards setting RequestedTheme. If we don't, then we'll update the background color of the TeachingTip, but not the text inside it. 

## References
* Added in #9662 and #9523 

## PR Checklist
* [x] Closes #9717
* [x] I work here
* [n/a] Tests added/passed
* [n/a] Requires documentation to be updated

## Validation Steps Performed
Tested with system theme light & dark, and `theme` set to `light, dark, and unset, and verified that they worked as expected.

### CODE REVIEW

**Review by DHowett — COMMENTED** [review]
I hate that this is necessary, but I appreciate you figuringit out

**Review by DHowett — APPROVED** [review]
I hate that this is necessary, but I appreciate you figuringit out

**Comment by DHowett** [comment]
@msftbot merge this in 7 minutes

**Comment by DHowett** [comment]
Oh, it was this one with the conflict

**Review by carlos-zamora — APPROVED** [review]

**Pull request merged**
