### PR TITLE
doc: remove unimplemented `-t` arg from `split-pane`

### LINKED ISSUE #4878: The split-pane subcommand has a --target\-t parameter
The [split-pane](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md#split-pane) section in the [UsingCommandlineArguments](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md) document says that there is a `[--target,-t target-pane]` parameter.  However if you try to use it you get a windows error box stating "The following argument was not expected: -t".

I've not looked into the code base in great detail, but from looking at [this](https://github.com/microsoft/terminal/blob/b6ec670bd8cf8ac7f6f7e67ac28a0210ba56b2c8/src/cascadia/TerminalApp/AppCommandlineArgs.cpp#L193) section I'm assuming that this parameter hasn't been implemented yet.

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request
Fixes #4878

## PR Checklist
* [x] Fixes #4878
* [x] I work here
* [x] Requires documentation to be updated

### CODE REVIEW

**Comment by HSVAdam** [comment]
Has this issue been merged with master.  I just reimaged this machine and have the no keyboard input right away.

**Comment by DHowett** [comment]
You mean, has this documentation change been merged to fix your keyboard input? It’s just a documentation change ...

**Comment by zadjii-msft** [comment]
@HSVAdam I think you're looking for #4448, I typo'd when I accidentally duped #7288 to this one.

**Comment by HSVAdam** [comment]
@zadjii-msft Yes that is it thank you.  I will comment on there.

**Comment by DHowett** [comment]
Whoops, sorry for the snark ;)

**Pull request merged**
