### PR TITLE
Update actions/add-to-project to version 0.5.0

### PR DESCRIPTION
**Pull request by Jvr2022**
Update ctions/add-to-project to version 4.0.1

### CODE REVIEW

**Comment by zadjii-msft** [comment]
Any particular reason why? Also, why 0.4.1 and not 0.5.0?

**Comment by Jvr2022** [comment]
I do always not the newest version because most of the times there are bugs in newest versions. Do u want more info about all changes?

**Comment by zadjii-msft** [comment]
I mean, I looked through the changelog and it seemed like overall, it was 99% just bumps to dependencies, a fix for a future deprecation warning (which I'm not sure we've ever actually been exposed to), and support for GHES. We may as well go all the way to 0.5 while we're here.

**Comment by Jvr2022** [comment]
So u dont want merge this?

**Comment by Jvr2022** [comment]
Need i close it?

**Comment by Jvr2022** [comment]
Should i update the code to 0.5.0? @zadjii-msft

**Comment by zadjii-msft** [comment]
I'd say either bump it all the way up, or just leave it 🤷

**Review by zadjii-msft — APPROVED** [review]

**Review by lhecker — APPROVED** [review]

**Pull request merged**
