### PR TITLE
Add a sample outline shader

### LINKED ISSUE #9010: Create an outline shader for increased legibility against background images
# Description of the new feature/enhancement

> Note: This was originally suggested in #7809 but the discussion instead turned into how to change the color of the **_font itself_** before it was closed, so I'll try to be more specific right from the start and also provide some images.

I like using images as backgrounds for Command Prompt and Git Bash, but the text tends to blend into the image in some places and create a bad contrast (as seen below).

![][terminal text bg off]

_Background image source: https://unsplash.com/photos/MPqbZXcvAvU_

# Proposed technical implementation details (optional)

I want to be able to set a text background with something like a `fontBackground` property in the settings, complete with a `#rrggbbaa` format so it's possible to have it semi-transparent.

| What we have now                | What I want (mockup)           |
| ------------------------------- | ------------------------------ |
| ![][terminal text bg off small] | ![][terminal text bg on small] |

[terminal text bg off]: https://user-images.githubusercontent.com/17113053/106393309-a36f0a00-63f6-11eb-8bf7-93e5694a114b.png
[terminal text bg off small]: https://user-images.githubusercontent.com/17113053/106519213-439e5f00-64db-11eb-9d2a-c5677571ed3f.png
[terminal text bg on small]: https://user-images.githubusercontent.com/17113053/106519216-4436f580-64db-11eb-9e9f-74e0b2255083.png

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

I accidentally the whole thing

image
image

## References
* Heavily inspired by the original rasterbars shader.

## PR Checklist
* [x] Closes #9010
* [x] I work here
* [n/a] Tests added/passed
* [n/a] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments
I know it's not FHL anymore, but I couldn't help myself.

## Validation Steps Performed
looked at it

### CODE REVIEW

**Comment by miniksa** [comment]
> image

Dude. You made MEME GENERATOR mode.

**Review by miniksa — APPROVED** [review]

**Comment by DHowett** [comment]
oh my god, it IS meme mode.

**Review by DHowett — APPROVED** [review]

**Comment by tobiaskarnat-remondis** [comment]
Can the outline colour please be made equal to the defined background colour?

**Comment by zadjii-msft** [comment]
I mean, you can modify the shader however you want. I'm no expert in hlsl, I'm sure there's some way to do that. We'll probably just leave this sample as-is, because it's supposed to just be a minimal sample for people to build on.

**Comment by tobiaskarnat-remondis** [comment]
I already tried to modify the shader, but I don't know any hlsl. Maybe someone else knows how to do this?
Would be nice if this was a built-in function, but does looks not so nice currently with three colours (front, outline, background) mixed.
grafik

**Pull request merged**
