### PR TITLE
Revert "Add magic incantation to tell Store we support Server"

### PR DESCRIPTION
**Pull request by DHowett**
This reverts commit abab8705fea32854a6b55153b5736f9fd9dacb66.

It went badly, as you might imagine.

### CODE REVIEW

**Comment by DHowett** [comment]
image


if we have this in our manifest, we can never publish another update.

Well done.

**Review by zadjii-msft — APPROVED** [review]

**Review by zadjii-msft — CHANGES_REQUESTED** [review]
`Package-Can`?

**Comment by DHowett** [comment]
> `Package-Can`? 

Oh right, we probably copied Can after this change went in. 

Even so, Can doesn't go to the store... hm.

**Comment by DHowett** [comment]
I might actually like to leave it present in Can, so that AppInstaller users can use it on Server!

**Review by lhecker — APPROVED** [review]

**Review by zadjii-msft — APPROVED** [review]

**Pull request merged**
