### PR TITLE
Add Alt+Shift+Q key binding for closing pane

### PR DESCRIPTION
**Pull request by rosti-il**
Just add the `Alt+Shift+Q` key binding to the default `settings.json` for closing the current pane.
I think it's useful for default configuration.

### CODE REVIEW

**Comment by zadjii-msft** [comment]
But why? `ctrl+shift+w` is already bound to close pane...

**Comment by rosti-il** [comment]
> But why? `ctrl+shift+w` is already bound to close pane...

I didn't know that. I just found in `settings.json` the `alt+shift+d` binding to split pane and thought there is no binding to close it because the `ctrl+shift+w` is a default and isn't defined there.

Is there some way to see all my current key bindings?

**Comment by DHowett** [comment]
@rosti-il Sure!

You can see the "default" bindings by opening the settings defaults that ship with terminal.
Hold down <kbd>Alt</kbd> and click on `Settings` in the menu. :smile:

This is not documented well, but it _is_ documented in your settings file.

image

**Comment by rosti-il** [comment]
@DHowett Thanks, that's also good to know, but I've asked about a different thing. How to see all current bindings altogether? Some of the default bindings may also be overridden in the `settings.json`.

**Comment by DHowett** [comment]
There is no way to see the resultant set of bindings.

You may be interested in the arc of #1564 :)

**Pull request closed without merging**
