### PR TITLE
Duplicated tabs open next to the current tab

### LINKED ISSUE #14313: Duplicated tab should be next to original tab
Currently the duplicated tab is added on the far right, IMO it should be next to the original tab.

### PR DESCRIPTION
**Pull request by vamsiikrishnaak**
## Summary of the Pull Request
Added an additional optional parameter that indicates the position of the new tab being created.

https://user-images.githubusercontent.com/17508246/206831900-d8349fb6-4241-4c37-8dd8-e1645ba94c90.mp4

https://user-images.githubusercontent.com/17508246/206831949-02e4156e-f471-4d2f-b54b-3b0d294c62fe.mp4

## PR Checklist
* [x] Closes #14313 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed

## Detailed Description of the Pull Request / Additional comments
An optional parameter is added to TerminalPage::_CreateNewTabPane() and TerminalPage::_InitializeTab() which indicates the insert position of the duplicated tab.
During a new tab creation (not duplicate), this optional parameter has a default value(-1) and the new tab is inserted at the end.
The duplicated tab is inserted next to the original one even if it is not focused.

## Validation Steps Performed
Created different tabs and duplicated them.
Duplicated tabs that are focused and not focused.

### CODE REVIEW

**Comment by vamsiikrishnaak** [comment]
@microsoft-github-policy-service agree

**Comment by DHowett** [comment]
Thanks for the contribution! Sorry for the delay in reviewing it. As we enter the holidays, we're going to be running a bit short-staffed. :smile:

**Review by lhecker — APPROVED** [review]

**Comment by DHowett** [comment]
@zadjii-msft I am 100% okay saying "duplicated tabs open next to the current tab" actually...

**Review by zadjii-msft — APPROVED** [review]

**Comment by noheromen** [comment]
Hi, I know this issue is closed, but I actually find it annoying. I liked that duplicate tabs would open at the end... not next to the one that is duplicated. Can you please provide setting, where this can be changed between two options?

**Pull request merged**
