### PR TITLE
fix: dep/nuget/packages.config to reduce vulnerabilities

### LINKED ISSUE #17048: Upgrade Selenium version
Upgrade version of Selenium.

### PR DESCRIPTION
**Pull request by skanda890**
## Summary of the Pull Request
This reduces vulnerabilities.
## References and Relevant Issues
This closes #17048
## PR Checklist
- [X] Closes #17048
- [ ] Tests added/passed
- [ ] Documentation updated
   - If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
- [ ] Schema updated (if necessary)

### CODE REVIEW

**Comment by skanda890** [comment]
I think this PR was created by accident.

**Review by DHowett — CHANGES_REQUESTED** [review]
Hey there! Selenium 4 is incompatible with WinAppDriver (the testing solution we use) and it will therefore not work with our project. If you're going to upgrade dependencies--especially between major versions--please make sure that you've completed a local build and test cycle!

**Comment by skanda890** [comment]
> Hey there! Selenium 4 is incompatible with WinAppDriver (the testing solution we use) and it will therefore not work with our project. If you're going to upgrade dependencies--especially between major versions--please make sure that you've completed a local build and test cycle!

Then which version does it support?

**Comment by skanda890** [comment]
This must be fine right.

**Review by skanda890 — COMMENTED** [review]
I think now Win supports Selenium.

**Comment by DHowett** [comment]
Thanks for this! We're moving nuget feeds, so we will re-evaluate our dependencies at that time.

**Comment by skanda890** [comment]
@DHowett, I wonder if Selenium 3.142.7 works with WinAppDriver.

**Comment by skanda890** [comment]
WinAppDriver#1839.

**Comment by skanda890** [comment]
microsoft/WinAppDriver#1839

**Comment by DHowett** [comment]
I'm not involved with WinAppDriver any longer, and I cannot vouch for the veracity of any information generated by that... thing.

**Comment by skanda890** [comment]
> I'm not involved with WinAppDriver any longer, and I cannot vouch for the veracity of any information generated by that... thing.

Do you know anyone who is involved with WinAppDriver.

**Comment by DHowett** [comment]
I do not, I am sorry.

**Pull request closed without merging**
