### PR TITLE
Set the default startup project

### PR DESCRIPTION
**Pull request by davkean**
## Summary of the Pull Request

Visual Studio defaults the startup project to the first project listed in the solution. Set the default to CascadiaPackage, which launches the packaged terminal. This required moving both its solution folder and the project itself to the top of the solution.

The other moves in the file is VS "fixing" the ordering based on the move. This prevents the solution from being automatically changed by VS when other folks open it.

## Validation Steps Performed
- Opened solution with Visual Studio 2017 and Visual Studio 2019 on a clean enlistment (.vs deleted) and verified that CascadiaPackage project was the default.

### CODE REVIEW

**Comment by zadjii-msft** [comment]
The code change itself I'm fine with, but the real question I have for the rest of the team is _is this something we want_?

**Comment by DHowett-MSFT** [comment]
I don’t like that it’s magic. Perhaps we should bug the VS folks about why it is magic?

**Comment by davkean** [comment]
I'm one of the "VS" folks, and it's just picking the first debuggable project in the solution.

Today without this change, a new contributor opens the solution, presses F5 and the debugger complains the project is not debuggable.
After this change, a new contributor opens the solution, presses F5 and the debugger deploys and launches Terminal.

**Comment by davkean** [comment]
It's current configurable, but it's a per user setting (stored in the not committed .vs folder). It's definitely a reasonable suggestion to have it configured and stored in the solution itself.

**Comment by davkean** [comment]
@miniksa @adiviness can you merge this in? I don't have rights to.

**Pull request merged**
