### PR TITLE
Misc pane refactoring

### PR DESCRIPTION
**Pull request by Rosefield**
Some changes I had sitting around after working on #11153 that weren't
appropriate to put in that pr. Each commit should be  independent if
particular ones are unwanted.

Slight overlap with #11305. There is some more code removal that can be
done after that is merged, specifically `AttachPane` can be deleted once
`SplitPane` handles adding multiple panes at once correctly.

## Details
- Makes `WalkTree` more useful, and closer to a real iterator. Add a
  convenient `_FindPane` built on top of that.
- Coalesces `PrecalculateAutoSplit` and `PreCalculateCanSplit` since
  they are basically identical logic. 
- `Pane::Relayout` functionally did nothing because sizing was switched
  to `star` sizing at some point in the past, so it was just deleted.

## Validation 
Quick smoke test to make sure automatic splitting works, focus movement
still works correctly.

### CODE REVIEW

**Comment by zadjii-msft** [comment]
(heads-up: may let this sit for a bit to put the wraps on 1.12, fyi)

**Comment by Rosefield** [comment]
I didn't expect this to get merged for 1.12 :)

**Review by lhecker — DISMISSED** [review]

**Review by zadjii-msft — DISMISSED** [review]
Little worried about us not needing the `ResizeContent` stuff anymore, but I'm not totally sure why we needed it in the first place. Maybe for when we initally open the Terminal with `snapToGridOnResize`? idk.

Sorry we've been so slow on PRs these last couple weeks, it was a little busy behind the scenes.

**Comment by Rosefield** [comment]
Just trying to go through my old PRs. I don't particularly care if they are merged or not, just want to stop worrying about them existing.

**Comment by zadjii-msft** [comment]
Sorry about that, we got all messed up in the run up to 1.12, and now it's the holidays so it's especially hard to find the right people. I'll bump this myself in the morning

**Review by zadjii-msft — APPROVED** [review]

**Review by lhecker — APPROVED** [review]

**Comment by zadjii-msft** [comment]
@DHowett is sick currently but I'm putting this into his inbox for when he gets back

**Comment by Rosefield** [comment]
No worries, thanks for following up on it.

**Review by DHowett — APPROVED** [review]
I am totes cool with this. Thanks for waiting, @Rosefield, and thanks doubly for working on it.

**Pull request merged**
