### PR TITLE
Batch RTL runs to ensure proper draw order

### PR DESCRIPTION
**Pull request by schorrm**
Consecutive RTL GlyphRuns are drawn from the last to the first.

## References
#538, #7149 , all those issues asking for RTL closed as dupes.

## PR Checklist
* [ ] Closes #xxx
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [X] Manual test.
* [X] I've discussed this with core contributors already. See description below.

## Detailed Description of the Pull Request / Additional comments
As @miniksa suggested in a comment on #7149 -- handle the thingy on the render side.
If we have GlyphRuns abcdEFGh, where EFG are RTL, we draw them now in order abcdGFEh.
This has ransom-noting, because I didn't touch the font scaling at all. This should fix the majority of RTL issues, except it *doesn't* fix issues with colors, because those get split in the TextBuffer phase in the renderer I think, so they show up separately by the GlyphRun phase.

## Validation Steps Performed
image

### CODE REVIEW

**Comment by miniksa** [comment]
> except it _doesn't_ fix issues with colors, because those get split in the TextBuffer phase in the renderer I think, so they show up separately by the GlyphRun phase.

That's completely true. And I've got a mental backlog item to make it so every line in the DxRenderer is collected up completely (including all the colors) into a single CustomTextLayout prior to drawing the whole line at once. If I prioritized that, it would fix it, I believe, in combination with this PR.

**Comment by miniksa** [comment]
Updated title and reduced description body to read more easily in `git log`.

**Comment by schorrm** [comment]
The prior behavior is just capricious. Adding would be a new flag (I think in effect, split every Hebrew char into its own GlyphRun). But this isn't breaking any sort of prior behavior that worked.

**Comment by schorrm** [comment]
Or that flag could just zero out bidiLevel

**Comment by schorrm** [comment]
@miniksa I made a small change to the commit message (from last to first) since I realized that my earlier one was too confusing.

**Comment by miniksa** [comment]
@DHowett for this one specifically, batching the RTL runs together is behavior that the default `IDWriteTextLayout` would have been doing for us if I didn't roll the `CustomTextLayout`. Having them be drawn as a unit so the origins are offset is correct. We wouldn't flag this specific PR on and off.

We would do, as @schorrm says, something like zeroing/ignoring all bidiLevel flags for a guest-controlled RTL scenario.

**Comment by DHowett** [comment]
Okay. I don't want to ship 1.3 without a flag that gives the users an escape hatch (config flag) to force LTR when they're using a guest application that tries to handle RTL on its own (by assuming LTR.) It doesn't have to be in this PR, but if it regresses `vim -H` without the ability to opt into a behavior that works with `vim -H` by the time we ship, we'll revert it and put it back on the table for 1.4. :smile:

**Comment by DHowett** [comment]
Does this _replace_ #7149, require it or aurmgne tit?

**Comment by schorrm** [comment]
So I would say it actually doesn't regress vim -H, barring an incredibly bizarre font fallback accident to make it work.
Re #7149: in terms of fixing RTL this replaces it. However, 7149 may be worthwhile to adapt into a random note fix on its own.

**Comment by schorrm** [comment]
We didn't **support** ConHost behavior. If you had a janky enough font setup it might split enough GlyphRuns to make it kind of look like that sometimes. Sometimes.

**Comment by schorrm** [comment]
If you can tell me how I can get a flag from the JSON, I'm happy to add this behavior, but I think it makes sense to treat this separately.

**Comment by schorrm** [comment]
Okay, take a look at the last. That's not on me, that's a runtime error in the CI I think.

**Comment by schorrm** [comment]
You can see it passed x86 which was the one it was failing, and then it failed x64 because of memory starvation while compiling something unrelated.

**Comment by schorrm** [comment]
That's nice. It recovered the memory issues. Do I have to do the spellcheck thingy?

**Comment by DHowett** [comment]
I’d like that :)

**Comment by schorrm** [comment]
I did the spelling thingy.

**Comment by zadjii-msft** [comment]
(I'm consciously leaving this for @DHowett to hit the merge button, since he was the last one with concerns about it)

**Comment by DHowett** [comment]
Thanks @schorrm!

**Pull request merged**
