### PR TITLE
.gitattributes: removed php display in the project

### PR DESCRIPTION
**Pull request by snxx-lppxx**
Since `*.inc` uses `cpp`, I changed the display via `.gitattributes`.

### CODE REVIEW

**Comment by miniksa** [comment]
Sorry, you mean `sources.inc`? I dunno if that's strictly cpp as much as it's "weird make file stuff". Does it look better like this? Screenshot?

**Comment by snxx-lppxx** [comment]
Hi @miniksa!
> *.inc - can be used in C/C ++, Pascal, Java, PHP (web pages) and other languages.
---
image

GitHub Linguist did not correctly identify this file, which is why 0.2% php appears in the project.

**Review by carlos-zamora — APPROVED** [review]

**Comment by miniksa** [comment]
> Hi @miniksa!
> > *.inc - can be used in C/C ++, Pascal, Java, PHP (web pages) and other languages.
> ---
> image
> 
> GitHub Linguist did not correctly identify this file, which is why 0.2% php appears in the project.
> 
> #### After:
> 
> image
> 

Ohhhhhh. OK. If this fixes that, I'm fine with it.

**Review by miniksa — APPROVED** [review]

**Review by zadjii-msft — APPROVED** [review]
sure okay

**Pull request merged**
