### PR TITLE
Disambiguate the shell extension CLSIDs to allow usage SXS

### LINKED ISSUE #6416: "Open Terminal Here" can't be used with both the dev build and preview at the same time
The Dev build one seems to always stomp the preview one.

* Is this because they share the same `Verb` string? _This is easy to fix_
* Or maybe is this because they share the same ClsId? _This would be annoying to fix_.

### PR DESCRIPTION
**Pull request by DHowett**
Fixes #6416

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]
update the pr body?

**Comment by DHowett** [comment]
Is there something that belongs in the PR body? I've signed the CLA, this fixes an issue, there are no more details, there's no docs. :smile:

**Comment by zadjii-msft** [comment]
yea okay, this is a good case where there's nothing else needed. Just feels weird 😝

**Comment by DHowett** [comment]
Well hey, I should not be above the rules. I'm adding some info about validation.

**Comment by DHowett** [comment]
@zadjii-msft it's only a 3-line diff to add it to drive roots and fix #6654 at the same time. :smile: 

I may rollup.

**Comment by DHowett** [comment]
Nevermind, they're assholes.

**Review by zadjii-msft — CHANGES_REQUESTED** [review]
image

**Review by zadjii-msft — APPROVED** [review]

**Review by carlos-zamora — APPROVED** [review]

**Pull request merged**
