### PR TITLE
Improve Word Navigation/Selection Performance

### LINKED ISSUE #4703: Conhost: UIA word navigation is slow
# Environment

Windows build number: 1909 (18363.657).

Windows Terminal version (if applicable): Open Console (commit b8e33560f90ff7c4b3294f83bbeabb1b6a74d3e1).

Any other software? Yes, test build of NVDA and Open Console build used [available here](https://codeofdusk.com/UIASlowWordNavTest.zip).

# Steps to reproduce

1. Run the included NVDA build (a patched version of nvaccess/nvda#10784 that uses native UIA word navigation and disables our workarounds in Windows Console).
2. From advanced preferences (press insert+n/right-click tray icon -> preferences -> settings -> advanced), enable UI automation in Windows Console.
3. Run the latest conhost from this repository (a build of commit b8e33560f90ff7c4b3294f83bbeabb1b6a74d3e1 is included in the zip).
4. Attempt to navigate by word (numpad 4/6 with numlock disabled).

# Expected behavior

NVDA quickly reads the previous or next word, similar to Windows Terminal.

# Actual behavior

An approximately one second lag is observed for each word movement.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
1) Improves the performance of word-recognition operations such as word
   navigation in UIA and selection.

2) Fixes a bug where attempting to find the next word in UIA, when none
   exists, would hang

3) TraceLogging code only runs when somebody is listening

## Detailed Description of the Pull Request / Additional comments
- The concept of a delimiter class got moved to the CharRow.
- The buffer iterator used to save a lot more information than we needed
- I missed updating a tracing function after making GetSelection return
  one text range. That is fixed now.

## Validation Steps Performed
Performed Word Navigation under Narrator and NVDA.
NOTE: The release build should be used when testing to optimize
performance

Closes #4703

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Kicking the x86 to run that leg again

**Comment by codeofdusk** [comment]
While the performance of debug builds (i.e. just running `bcz` with no arguments) is still slow, generating a release build with `bcz release` (as suggested in the PR description) dramatically improves UIA word navigation for both patched NVDA and Narrator. Thanks @carlos-zamora!

**Comment by DHowett-MSFT** [comment]
@codeofdusk thank you for testing this out!

**Comment by codeofdusk** [comment]
@DHowett-MSFT @carlos-zamora As an aside, do you have an idea of when work on new text events for terminal (#2447) will start? Once implemented we can add support for Windows Terminal to NVDA.

**Comment by carlos-zamora** [comment]
> @DHowett-MSFT @carlos-zamora As an aside, do you have an idea of when work on new text events for terminal (#2447) will start? Once implemented we can add support for Windows Terminal to NVDA.

@codeofdusk I've been working on that now but I've been having trouble getting them to work (specifically for output). I'm able to fire a TextChanged event when new output appears, but I can't seem to understand how my UIA Providers are able to respond. Is it dependent on a setting on the XAML control?

**Comment by codeofdusk** [comment]
> > @DHowett-MSFT @carlos-zamora As an aside, do you have an idea of when work on new text events for terminal (#2447) will start? Once implemented we can add support for Windows Terminal to NVDA.
> 
> @codeofdusk I've been working on that now but I've been having trouble getting them to work (specifically for output). I'm able to fire a TextChanged event when new output appears, but I can't seem to understand how my UIA Providers are able to respond. Is it dependent on a setting on the XAML control?

I'd think firing a text changed event would suffice, but I'm not quite sure. Could you send a test build/point me at a branch and I can explore with NVDA? Cc @MichaelDCurran and @leonardder for more detailed implementation suggestions.

**Comment by carlos-zamora** [comment]
> > > @DHowett-MSFT @carlos-zamora As an aside, do you have an idea of when work on new text events for terminal (#2447) will start? Once implemented we can add support for Windows Terminal to NVDA.
> > 
> > 
> > @codeofdusk I've been working on that now but I've been having trouble getting them to work (specifically for output). I'm able to fire a TextChanged event when new output appears, but I can't seem to understand how my UIA Providers are able to respond. Is it dependent on a setting on the XAML control?
> 
> I'd think firing a text changed event would suffice, but I'm not quite sure. Could you send a test build/point me at a branch and I can explore with NVDA? Cc @michaelDCurran and @leonardder for more detailed implementation suggestions.

Sure! I'll send it in the morning and @ you three in #2447. Thank you so much!

**Pull request merged**
