### PR TITLE
Feature: mjpeg streaming for terminal control background

### PR DESCRIPTION
**Pull request by sipsorcery**
This PR adds a rudimentary mjpeg receiver to allow the terminal control background to display a stream. 

**Update:** 

Motivation for this feature

The example screenshots and video are a little bit gimmicky but there could be some very useful scenarios for the ability to employ an information rich terminal background:

 - Network monitoring tools could cause the background to display results, e.g. a ping could cause a host in a network map to change colour,

 - Quick video calls (my own goal). For developers who spend a lot of time in a console it's advantageous to avoid context switches to other applications for minor tasks. If a quick video call could be done "in-terminal" that could be a small efficiency gain,

 - Infrequent graphical notifications. A video stream of 1 frame/second or less could be used to show notifications for configurable events. Again this could be a context switch saving for people that permanently have a terminal open. GitHub notifications would be a good use case. I do 90% of my git interactions from the command line. If the results of commit CI jobs were automatically displayed in the terminal background (that I keep open solely for git interactions) it could save me reading an email and visiting a web page.

It's perhaps easier to illustrate than to explain. The two screenshots below show stills of two different streams. Small mp4 captures are [here](https://github.com/sipsorcery/sipsorcery-mediafiles/raw/master/terminal/terminal_mjpeg1.mp4) and [here](https://github.com/sipsorcery/sipsorcery-mediafiles/raw/master/terminal/terminal_mjpeg2.mp4) (the second one's a bit spooky).

terminal_mjpeg_test_pattern

terminal_mjpeg_max

To test out the feature the steps are:

 - Set the `backgroundImage` to a file path with `;mjpeg:1234` appended. The `1234` represents a loopback port that the mjpeg receiving socket will listen on. For example:

`"backgroundImage": "C:/Users/aaron/Pictures/gravatar_400x400.png;mjpeg:10010"`

 - Start a source stream to the listening port. For example:

`ffmpeg -re -f lavfi -i testsrc=size=1280x720:rate=10 -vf "drawtext=fontfile=/Windows/Fonts/arial.ttf: expansion=normal: text='%{localtime}': r=25: x=1100: y=50: fontcolor=black" -vcodec mjpeg -pix_fmt yuvj420p -huffman 0 -f rtp rtp://127.0.0.1:10010`

Known Issues:
 - Only one terminal control can listen on a port at a time so starting a second terminal with the same `backgroundImage` setting will not be able to create a listening socket.

### CODE REVIEW

**Comment by jsoref** [comment]
You're going to want to rebase and push before you take advice from the bot, otherwise you're going to hit a conflict.

The conflicts shouldn't be hard to resolve `whitelist` was renamed to `expect` -- If you need help, I can help on Sunday.

**Comment by miniksa** [comment]
This is quite interesting. A few quick reads on it:

1. I don't really like that the port thing can conflict. But I can't really think of another transport for this to use that wouldn't conflict. I guess technically the receiver could operate at a higher level above multiple tabs and shunt out the jpegs to any tab subscribed so you can have the same content on multiple.
2. I would really hope that there would be some lower-level registration inside the XAML/MUX platform that could pick up the streams and update the jpegs instead of pushing them into the property from the top on a loop. But maybe that sort of extensibility doesn't exist?
3. I generally like the idea. I was wondering at some point if we couldn't just have a full blown mp4 stream running as the background to feed in whatever live content you want. This is definitely in that vein.
4. I'm concerned about the licensing/derivation on `mjpeg.h`. We would have to have that reviewed.

I want to discuss this with @zadjii-msft and @DHowett before going much further forward on this.

**Comment by sipsorcery** [comment]
Thanks for taking a look.

> 1. I don't really like that the port thing can conflict. But I can't really think of another transport for this to use that wouldn't conflict. I guess technically the receiver could operate at a higher level above multiple tabs and shunt out the jpegs to any tab subscribed so you can have the same content on multiple.

I can think of a few ways to deal with it but they increase the scope of the PR and the original intent was to see if this feature was likely to be accepted before adding extras. If it was a blocker I could fix it.

Solutions off the top of my head (in increasing order of scope creep):
 - Use an OS ephemeral port for each pane by binding against port 0. Once the socket has bound  print it out above the terminal pane's initial prompt,
 - Same as above but rather than printing to the terminal pane add a key binding command that can print out the listening socket for the current pane,
 - Integrate a lightweight ASP.Net Web API that can be queried to list the available terminal panes and their listening sockets.

I don't think the shunting idea would be ideal. Displaying the same mjpeg feed in multiple panes doesn't seem that useful and could get annoying depending on the feed.

> 2. I would really hope that there would be some lower-level registration inside the XAML/MUX platform that could pick up the streams and update the jpegs instead of pushing them into the property from the top on a loop. But maybe that sort of extensibility doesn't exist?

If there is such a property I've never found it and if it does exist I'd love to hear about it. I have a demo VoIP softphone application that's been floating around for years and I've always [updated the video stream](https://github.com/sipsorcery/sipsorcery/blob/cab1e7dac6651c7c78ca46d3f30941b682a6b6c5/examples/Softphone/Softphone.xaml.cs#L607) using the exact same approach of setting a bitmap image source.
 
> 3. I generally like the idea. I was wondering at some point if we couldn't just have a full blown mp4 stream running as the background to feed in whatever live content you want. This is definitely in that vein.

This PR goes further than streaming an mp4 or other static content (which can already be achieved with the existing [MediaPlayElement](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.mediaplayerelement?view=winrt-19041)) and allows the streaming of live content. The simplest live content is mjpeg but if that was incorporated and useful then it could be the initial step in VoIP, WebRTC and other live streaming sources.

> 4. I'm concerned about the licensing/derivation on mjpeg.h. We would have to have that reviewed.

Yes same, hence the header comments. It's always a quandary when "leveraging" existing source code. I do think in this case the scope of the changes I've made to the various ffmpeg source blocks  make the `mjpeg.h` a new work. Plus the ffmpeg sources are C and I've employed C++ idioms. The Huffman tables are part of the JPEG spec so they wouldn't count as GPL licensed. If any other large blocks were of concern I could most likely re-write them.

**Comment by WSLUser** [comment]
@DHowett Has there been any progress for the legal aspects of this PR? I'd love to start using this.

**Comment by zadjii-msft** [comment]
Hey, sorry it's been like half a year since we took a look at this. We discussed this a bit as a team recently. The consensus was that as _neat_ as this feature is, we're not really comfortable shipping it directly in the Terminal. It probably makes the most sense as an extension (#4000), but we're not confident that we could support this adequately in the Terminal itself. 

I've added this to the mega list of extension ideas in #4000. We'll make sure to keep this PR in mind when we do get to extensions, because it's a GREAT example of something that developers should be able to do.

Sorry again for leaving you on _Read_ for so long!

**Pull request closed without merging**
