### PR TITLE
rename profiles.json to settings.json, clean up the defaults

### LINKED ISSUE #3291: Roaming profile still lives; isn't deleted by the sync service
When WT deletes the profile from the roaming directory, that deletion never gets pushed up to the settings sync host. That's probably by design. Unfortunately, it means that on new installations, releases-old profiles can be magically resurrected from the ether.

We could (perhaps should) write a tombstone file to the roaming settings folder indicating that we've moved the settings out of it and not to try again.

### LINKED ISSUE #5186: Rename profiles.json to settings.json
# Description of the new feature/enhancement
The settings file should be named to settings.json instead of profiles.json. It just makes sense. :)

# Proposed technical implementation details (optional)

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
This pull request migrates `profiles.json` to `settings.json` and removes the legacy roaming AppData settings migrator.

It also:

* separates the key bindings in defaults.json into logical groups
* syncs the universal terminal defaults with the primary defaults
* removes some stray newlines that ended up at the beginning of settings.json and defaults.json

Fixes #5186.
Fixes #3291.

### move profiles.json to settings.json

This commit also changes Get*Settings from returning a string to
returning a std::filesystem::path. We gain in expressiveness without a
loss in clarity (since path still supports .c_str()).

NOTE: I tried to do an atomic rename with the handle open, but it didn't
work for reparse points (it moves the destination of a symbolic link
out into the settings folder directly.)

(snip for atomic rename code)

```c++
auto path{ pathToSettingsFile.wstring() };
auto renameBufferSize{ sizeof(FILE_RENAME_INFO) + (path.size() * sizeof(wchar_t)) };
auto renameBuffer{ std::make_unique<std::byte[]>(renameBufferSize) };
auto renameInfo{ reinterpret_cast<FILE_RENAME_INFO*>(renameBuffer.get()) };
renameInfo->Flags = FILE_RENAME_FLAG_REPLACE_IF_EXISTS | FILE_RENAME_FLAG_POSIX_SEMANTICS;
renameInfo->RootDirectory = nullptr;
renameInfo->FileNameLength = gsl::narrow_cast<DWORD>(path.size());
std::copy(path.cbegin(), path.cend(), std::begin(renameInfo->FileName));

THROW_IF_WIN32_BOOL_FALSE(SetFileInformationByHandle(hLegacyFile.get(),
                          FileRenameInfo,
                          renameBuffer.get(),
                          gsl::narrow_cast<DWORD>(renameBufferSize)));
```

(end snip)

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
I have yet to update all the docs references to profiles.

**Comment by carlos-zamora** [comment]
@leonMSFT should approve this so that we get the whole team to approve it haha

**Comment by DHowett-MSFT** [comment]
lol y’all

**Comment by oising** [comment]
I guess I should update my PR for WT env vars?

**Comment by DHowett-MSFT** [comment]
Yeah! That'd be excellent.

**Comment by oising** [comment]
@DHowett-MSFT Done.

**Pull request merged**
