### PR TITLE
Add an accelerator key for the shell extension

### LINKED ISSUE #13061: "Open In Terminal" doesn't have a letter selector or hot key
### Windows Terminal version

_No response_

### Windows build number

_No response_

### Other Software

_No response_

### Steps to reproduce

Open in Terminal when in Explorer is handicapped for keyboard users as there is no direct way to trigger opening a terminal with the keyboard,  and if you use your "menu" key on the keyboard, it opens the right click menu, but "Open in Terminal" has no hotkey associated with it, so the only way to select it is to arrow down, which is too fiddly.

image

### Expected Behavior

Hotkey and Letter select should be enabled

### Actual Behavior

I cried.

### PR DESCRIPTION
**Pull request by ianjoneill**
Adds an accelerator key for the shell extension: `T` for stable, `P` for preview and `D` for dev.

# Validation
Ran a dev build and saw the keyboard accelerator assigned.

Closes #13061

### CODE REVIEW

**Comment by ianjoneill** [comment]
How do I appease the spelling bot? I don't think adding `iew` as an allowed word is the right approach. Ideally there would be some way of stating this is OK for this one file, but I don't see how you do that.

**Comment by zadjii-msft** [comment]
Hokay so some notes from discussion:
* We like the idea
* I think we liked (W, P, and D) as characters anyways - there's always gonna be conflicts with these letters, so might as well go with sensible options. 
* Localization for this might be **H**ard. We're gonna look into it on our end and see what the right way to markup these strings is. We need to make sure the translators know that the `&amp;` identifies the leading character as an accelerator, and for non-latin-character-based languages, the localizations have a trailing latin character for loc purposes. 

So we're gonna hold this for 1.15, while we sort out that loc issue. Thanks for your patience!

**Comment by ianjoneill** [comment]
So to confirm, you'd like `D` for dev, `P` for preview and `W` for stable? i.e. for English:

```
Open in Terminal (&Dev)
Open in Terminal &Preview
Open in Terminal (&w)
```

**Comment by zadjii-msft** [comment]
Oh my god I'm so sorry, I clearly didn't even read that comment before I posted it. I meant **T**, not _W_. 🤦 

```
Open in Terminal (&Dev)
Open in Terminal &Preview
Open in &Terminal
```

The action item is still on me to follow up with the File Explorer team (or someone...?) to figure out the right way to express these for future localization. Sorry for the delays, releasing 1.14 has been a persistent fire drill

**Comment by ianjoneill** [comment]
Yeah I figured it was probably a typo - hence why I questioned it rather than blindly applying it 😛

**Review by DHowett — APPROVED** [review]
I'm cool with this -- we can "progressively render" the cross-language accelerator story. What do you think, @zadjii-msft?

**Comment by DHowett** [comment]
Thanks @ianjoneill  :)

**Comment by ianjoneill** [comment]
The CI officially hates me - if I merge main into this branch will it still auto-merge, or is it better for you to re-trigger the build yourself?

**Comment by zadjii-msft** [comment]
Just triggered a rerun of the feature tests, they've been flaky all day, sorry 😕

**Comment by ianjoneill** [comment]
Thanks! I don't know why, but I seem to be particularly unlucky with build flakes.

**Pull request merged**
