### PR TITLE
ci: try out the new Cache build step

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
It's dependent on all of our packages.config files.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Admittedly, if this works, it will save us a grand total of ... 36 seconds.

**Comment by oising** [comment]
Ok, so you're keying against all projects' packages -- so if one package.config changes, the whole cache is blown. I guess it's better than nothing! What about the C++ portion? Apparently this Cache thing uses [CCache](https://ccache.dev/) under the covers for C/C++.

**Comment by miniksa** [comment]
My thought was to add the pch object files, the pch header files, and the vcxproj files that go with them as a cache as well. That would probably save a big bunch... @DHowett-MSFT, should I try pushing an update to this branch with some of that or should I make another one and another draft PR?

**Comment by miniksa** [comment]
> My thought was to add the pch object files, the pch header files, and the vcxproj files that go with them as a cache as well. That would probably save a big bunch... @DHowett-MSFT Dustin Howett FTE, should I try pushing an update to this branch with some of that or should I make another one and another draft PR?

Ugh, I didn't realize that `path:` caches that entire directory and not like... individual files. Maybe nevermind then. Perhaps we look at clcache.

**Comment by miniksa** [comment]
> Ok, so you're keying against all projects' packages -- so if one package.config changes, the whole package cache is blown. I guess it's better than nothing! What about the C++ portion? Apparently this Cache thing can use [CCache](https://ccache.dev/) under the covers for C/C++.
> 
> ( https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#ccache-cc )
> 
> UPDATE: never mind, it seems only for gnu c/c++, not MSVC -- but then I found https://github.com/frerich/clcache :P

I tried clcache.

It doesn't work because it will refuse to cache when you need symbols in their own file (the /Zi switch):
https://github.com/frerich/clcache/blob/master/README.asciidoc

I can't see a way around /Zi because we have to have our binaries be debuggable and there is NO WAY we are pushing all the debugging data into the binary itself.

**Comment by miniksa** [comment]
> > Ok, so you're keying against all projects' packages -- so if one package.config changes, the whole package cache is blown. I guess it's better than nothing! What about the C++ portion? Apparently this Cache thing can use [CCache](https://ccache.dev/) under the covers for C/C++.
> > ( https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#ccache-cc )
> > UPDATE: never mind, it seems only for gnu c/c++, not MSVC -- but then I found https://github.com/frerich/clcache :P
> 
> I tried clcache.
> 
> It doesn't work because it will refuse to cache when you need symbols in their own file (the /Zi switch):
> https://github.com/frerich/clcache/blob/master/README.asciidoc
> 
> I can't see a way around /Zi because we have to have our binaries be debuggable and there is NO WAY we are pushing all the debugging data into the binary itself.

Further... it can't cache with PCHs. This doesn't look great...

**Pull request closed without merging**
