### PR TITLE
Fix fullscreen after maximize

### LINKED ISSUE #3709: Entering Fullscreen from Maximized doesn't work right
###### Moved from  #3707

# Environment

**Windows build number**: 10.0.18363.0 Microsoft Windows NT 10.0.18363.0

**Windows Terminal version (if applicable)**: 0.7.3291.0

*Another behavior* is that when going into Full-Screen mode from a maximized window, you still see the taskbar and the padding around the shell looks all messed up:

image

fullscreens to:

image

### PR DESCRIPTION
**Pull request by greg904**
## Summary of the Pull Request

Fixes the sides disappearing when entering full screen mode when the window is maximized.
However, now, a Vista-style frame briefly appears when entering/exiting full screen.

 
## PR Checklist
* [x] Closes #3709
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [x] Requires documentation to be updated (no)
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments

When the non-client island window is maximized and has the WS_OVERLAPPEDWINDOW style, SetWindowPos is "lying": the position ends up being offset compared to the one we gave it (found by debugging). So I changed it to use WS_POPUP like the client island window was already doing. But now it has the Vista frame that appears briefly when entering/exiting full screen like the client island window.

## Validation Steps Performed

### CODE REVIEW

**Comment by zadjii-msft** [comment]
@greg904 Is there any way to _not_ get that vista-style window frame to appear for a brief second, _and_ fix this bug?

Overall, I'm happy that this works better, but that frame felt really jarring in my own testing :/

**Comment by greg904** [comment]
I don't know how to do it. Chromium's code https://github.com/chromium/chromium/blob/master/ui/views/win/fullscreen_handler.cc is pretty much the same as here and yet Chromium doesn't have the issue. I'm missing something somewhere.

**Comment by greg904** [comment]
I don't really have time now unfortunately so I would prefer that you submit your own PR.

**Comment by zadjii-msft** [comment]
@greg904 No problem. Thanks for the initial fix 😄

**Pull request merged**
