### PR TITLE
Allow IME Text Wrapping

### LINKED ISSUE #3657: Improve wrap around/edge behavior when inputing text in IME
When the cursor is near the right side or bottom of the window, does the canvas appear hanging off the side of the window, or is it clipped by the bounds of the window?

If it's clipped, should we file a follow up to try and position the canvas heuristically based on the cursor position relative to the bounds of the window, to keep it in bounds?

_Originally posted by @zadjii-msft in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0Mjk2Mzk0Mjcw/pull_requests/unread_timeline_

Terminal should do better than the original and wrap around and edge behavior when inputting text in the IME.  Current behavior isn't any better than the original command-line (inputted text is off screen).  But input should wrap around like in Notepad.

### PR DESCRIPTION
**Pull request by leonMSFT**
## Summary of the Pull Request
This PR turns on TextWrapping on `TSFInputControl::TextBlock`. Once the TextBlock hits the end of the Terminal window, it will wrap downwards, but the TextBlock will have as much width as it had when composition started. Unfortunately, this means if composition starts right at the end of the Terminal with enough width for just one character, there will be a vertical line of characters down the right side of the Terminal 😅. It's definitely not ideal, and I imagine this won't be the last time we visit this issue, but for now users can see what they're typing.

## PR Checklist
* [x] Closes #3657
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed

## Validation Steps Performed
Played around with IME towards the edge of the Terminal window.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
(Do we need to use `ClampedAdd` when we're _also_ using `ClampedNumeric<T>`? @miniksa?)

**Comment by miniksa** [comment]
>  (Do we need to use `ClampedAdd` when we're _also_ using `ClampedNumeric<T>`? @miniksa?)

No, all operators off of Clamped Numeric are clamped. As long as the left hand side is already one, you are good as far as I'm aware.

**Comment by miniksa** [comment]
Also, @dhowett-msft, the GitHub mobile app quote reply function edits your post with my admin rights instead of, you know, quote replying.

**Comment by DHowett-MSFT** [comment]
well _that_ is a weird bug :)

**Comment by carlos-zamora** [comment]
Should we create a follow up task/issue to clean this up?

**Pull request merged**
