### PR TITLE
Add the Tango color schemes for Terminal and ColorTool

### LINKED ISSUE #5281: Please Support the Tango Color Theme
# Description of the new feature/enhancement

Include the Tango color scheme in the list of predefined color schemes.

Ideally both Tango Light and Tango Dark, but including just Tango Dark, which is often called simply Tango would be fine as well, since that is what most people would want.

Both of these are included in iterm2 and various other places.

This is the default terminal color scheme on Ubuntu and various other linux distributions.

It is, in my opinion, the nicest set of terminal colors, and many linux and mac users agree.

I am using it in my `settings.json` as:

```json
    {
      "background": "#000000",
      "black": "#000000",
      "blue": "#3465a4",
      "brightBlack": "#555753",
      "brightBlue": "#729fcf",
      "brightCyan": "#34e2e2",
      "brightGreen": "#8ae234",
      "brightPurple": "#ad7fa8",
      "brightRed": "#ef2929",
      "brightWhite": "#eeeeec",
      "brightYellow": "#fce94f",
      "cyan": "#06989a",
      "foreground": "#d3d7cf",
      "green": "#4e9a06",
      "name": "Tango Dark",
      "purple": "#75507b",
      "red": "#cc0000",
      "white": "#d3d7cf",
      "yellow": "#c4a000"
    }
```

# Proposed technical implementation details (optional)

I am happy to do all the necessary work on a proper PR for this, I just need a bit of guidance.

I found `cascadia/TerminalApp/defaults.json` but the comment at the top says it's a generated file.

Please tell me what generates it, and I will add all the necessary source material, attributions, copyrights and theme sources as necessary.

### PR DESCRIPTION
**Pull request by rkitover**
The Tango color scheme is part of the Tango Desktop Project, which was
released to the public domain in 2009.

More information:

http://tango-project.org/

Add the "Tango Dark" and "Tango Light" color scheme presets.

- Fix #5281.

Signed-off-by: Rafael Kitover <rkitover@gmail.com>

## PR Checklist
* [x] Closes #5281
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #5281

### CODE REVIEW

**Comment by zadjii-msft** [comment]
@msftbot make sure both @cinnamon-msft and @DHowett-MSFT sign off on this

**Comment by skyline75489** [comment]
I didn't even realize we got so many color schemes now. Perhaps cuz I'm using a very old profile from version 0.6 or something. If this is possible, I'm gonna add [Dracula](https://github.com/dracula/windows-terminal) (which is MIT licensed) as soon as I can.

**Comment by cinnamon-msft** [comment]
I think defaults-universal.json also needs to be updated?

**Comment by rkitover** [comment]
@cinnamon-msft I only saw any color schemes defined in `defaults.json`.

**Comment by zadjii-msft** [comment]
@cinnamon-msft They might be off the hook on that - `defaults-universal` only has "Vintage" as a scheme, and it's not like users can edit the settings on that version anyways 😄

**Comment by rkitover** [comment]
Sorry, the "Vintage" theme is indeed in `defaults-universal.json`, I missed that.

I can copy all the themes to `defaults-universal.json`, but this breaks DRY.

Why don't we make a `color-schemes.json` or some such?

**Comment by zadjii-msft** [comment]
@rkitover Don't worry about it, `defaults-universal.json` is really only used internally as a testing tool. 

There's #2933, which I'm roughly using as "be able to import settings from other files as well as `profiles.json`" that would enable having additional files for settings (like a `color-schemes.json`), but that's _way_ out of scope for 1.0 at this point 😄

**Pull request merged**
