### PR TITLE
[Settings UI] Clamp vintage cursor height and history size

### LINKED ISSUE #9175: Allow "vintage" cursor to have values lower than 25
# Description of the new feature/enhancement

Allow "vintage" cursor to have values lower than 25, it is presently capped between 25 to 100.  I just want to have the capability of setting it to a smaller value that is larger than `underline`

# Proposed technical implementation details (optional)

Remove the bottom limit and allow floating point values.

### LINKED ISSUE #9357: Vintage cursor height in SUI does not clamp values to 1-100
vintage

Windows Terminal Preview v1.7.572.0

allowed input range may be too large

_Originally posted by @maggch97 in https://github.com/microsoft/terminal/issues/9175#issuecomment-789489274_

### PR DESCRIPTION
**Pull request by eugenesmlv**
## Summary of the Pull Request
Add `Minimum` and `Maximum` for the cursor height numberbox in the SUI.
Add `Minimum` for the history size numberbox in the SUI.

## PR Checklist
* [x] Closes #9357, Closes #9175
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA

## Validation Steps Performed
Manual validation

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]
@ the rest of the team - I think we should stick with 1-100 here, despite 25-100 being the valid values currently, because we _should_ accept 1-100 as reasonable values. See #9175

**Comment by eugenesmlv** [comment]
@zadjii-msft I found out that the history size number box also has no bottom limit and allows the user to set negative values. Should we fix that? I could do it in this PR or file an issue.

HistorySizeNumbox

**Comment by zadjii-msft** [comment]
> Should we fix that?

Yep we definitely should! I wouldn't mind if you included that in this PR. If this merges before you add that though, I'll make sure to file a follow up. Good catch!

The min for that one should just be 0.

**Review by carlos-zamora — APPROVED** [review]
We should consider representing "Cursor Size" a slider if we're introducing a minimum/maximum. I'll file a follow-up task.

Thanks for doing this!

**Pull request merged**
