### PR TITLE
Remove `constexpr` from `_altBufferMarks`

### PR DESCRIPTION
**Pull request by PankajBhojwani**
## Summary of the Pull Request
Compiler was raising the error: `expression did not evaluate to a constant.`, causing the solution to fail when building. Removing this `constexpr` fixes it.

## PR Checklist
* [ ] Closes #xxx
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Validation Steps Performed
Solution builds now

### CODE REVIEW

**Comment by DHowett** [comment]
Huh. This was added for the audit mode build. Isn't that gonna make it fail?

**Comment by lhecker** [comment]
The default constructor for `std::vector` is `constexpr` since C++20. This should work on any conforming C++20 compiler and unless I did something wrong, it did work in VS 17.3.6.

**Comment by lhecker** [comment]
For reference: <https://godbolt.org/z/5qq667fq1>

**Comment by PankajBhojwani** [comment]
Got on a call with @lhecker and turns out this repros on his machine as well (with VS 17.3.6)

**Review by lhecker — APPROVED** [review]

**Comment by DHowett** [comment]
Is it worth doing this?

```cpp
static
#ifndef NDEBUG
constexpr
#else
const
#endif
std::vector foobarbaz{};
```

? 

That way we keep the optimization on release without introducing a TLS storage check to make sure no two threads enter at the same time?

Or... is that moot because we're returning a const ref anyway?

**Review by zadjii-msft — APPROVED** [review]

**Comment by lhecker** [comment]
> Or... is that moot because we're returning a const ref anyway?

I think it's moot because `constexpr` doesn't mean it's constexpr anyways. That's what `consteval` is for. 🥴 So I'm fairly confident that no matter whether we write `constexpr` or not, most of the time it should compile to the exact same thing.

**Review by carlos-zamora — APPROVED** [review]

**Comment by carlos-zamora** [comment]
@msftbot merge this in 10 minutes

**Pull request merged**
