### PR TITLE
github: migrate our bug report template to an issue form

### PR DESCRIPTION
**Pull request by DHowett**
This is a feature that we are alpha-testing with GitHub.

[<kbd>Preview</kbd>](https://github.com/microsoft/terminal/blob/dev/duhowett/issueform1/.github/ISSUE_TEMPLATE/Bug_Report.yml)

### CODE REVIEW

**Comment by j4james** [comment]
> the only way to validate it is by having it in the main branch.

Can you not create a private repo and test it there?

**Comment by DHowett** [comment]
> > the only way to validate it is by having it in the main branch.
> 
> Can you not create a private repo and test it there?

alas, during the issue forms beta it's enabled by request per repository. I'm attempting to figure out if we can just _preview_ changes without merging them :)

**Comment by KalleOlaviNiemitalo** [comment]
Can you test it by temporarily selecting a different branch as the default branch?

**Comment by DHowett** [comment]
@KalleOlaviNiemitalo terribly clever. I love it! Thanks!

The github folks let me know that this is supposed to be possible through the file preview! That's [here](https://github.com/microsoft/terminal/blob/dev/duhowett/issueform1/.github/ISSUE_TEMPLATE/Bug_Report.yml). Check it out :smile:

**Review by zadjii-msft — APPROVED** [review]

**Comment by KalleOlaviNiemitalo** [comment]
Is there a sample issue that has been filed with the issue forms beta (in any public repository)?

**Comment by zadjii-msft** [comment]
@KalleOlaviNiemitalo I believe this is an example: https://github.com/ansible/ansible/issues/73959

**Comment by DHowett** [comment]
Yep, I was about to link https://github.com/ansible/ansible/issues/73875

**Comment by KalleOlaviNiemitalo** [comment]
The GitHub mobile app on iOS doesn't seem to support issue forms yet. image

**Comment by DHowett** [comment]
_argh_

**Comment by DHowett** [comment]
It looks like they're working on a fix for this (though the last update on that thread was 23 days ago.)

**Comment by lukehefson** [comment]
@DHowett I just noticed that y'all have been bitten by this recent change to issue forms: https://github.com/gh-community/issue-forms-feedback/issues/91#issuecomment-823356578

So you'll need to remove the following from https://github.com/microsoft/terminal/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.yml

```
title: ''
labels: ''
assignees: ''
```

In order to make the form work again!

Also note that later today we'll be deprecating `about: ` in favour of `description: ` as well as `issue_body`. For more information see: https://github.com/gh-community/issue-forms-feedback/discussions/75#discussioncomment-576035

**Comment by zadjii-msft** [comment]
@lukehefson Thanks for the heads up! As an FYI, I don't think the repo you linked to is public - mind sharing a copy of the linked comment(s) here?

**Comment by lukehefson** [comment]
> We deprecate both `issue_body` in favour of WYSIWYG on-click textareas and deprecate `about: ` as a top-level configuration in favour of `description: ` both on Tuesday the 20th of April.

@zadjii-msft It's not public– it's our private feedback repo. But let me know if you, or any other Maintainers want an invite!

**Pull request merged**
