### PR TITLE
Fix TermControl initialization to pre-seed working dir

### PR DESCRIPTION
**Pull request by Don-Vito**
## PR Checklist
* [x] Closes https://github.com/microsoft/terminal/issues/8969
* [x] CLA signed. 
* [ ] Tests added/passed
* [ ] Documentation updated. 
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already.

### CODE REVIEW

**Comment by Don-Vito** [comment]
@skyline75489 - can you please take a look that I am not ruining stuff? :blush:

**Comment by skyline75489** [comment]
That's a good one-liner fix. I'm OK. Just want to make sure if this is @DHowett wants.

**Comment by DHowett** [comment]
I think this is the wrong way around— we’re telling TermControl that an OSC 9;9 occurred using its internal API so that it calls TermControl’s working directory handler to trigger the working directory event. Can TerminalApp just handle this at the top layer? :)

**Review by DHowett — CHANGES_REQUESTED** [review]
Discussion

**Comment by Don-Vito** [comment]
> 
> 
> Discussion

@DHowett - I am afraid I failed to follow the part with directory handler. My understanding wast that `_workingDirectory` in `TerminalApi` is just a container for the source of truth.

**Comment by skyline75489** [comment]
I think what Dustin says is to add new event for "working directory change" and a callback for that event, like we did for title change ("pfnTitleChanged") and the other things.

**Comment by skyline75489** [comment]
Well, due to my laziness, there's no such event at the moment. Or I'm misunderstanding Dustin. I'm still in the bed probably not really thing straight 😅

**Comment by Don-Vito** [comment]
> 
> 
> Well, due to my laziness, there's no such event at the moment. Or I'm misunderstanding Dustin. I'm still in the bed probably not really thinking straight 😅

There is no such event, and actually I am also confused. 

We could probably manage _workingDirectory on a higher level than in Terminal, in the first place, i.e., to introduce some event in Terminal and forward it to the TerminalApp. In this case the source of truth would reside in the app. However currently it is in Terminal.

**Comment by Don-Vito** [comment]
> 
> 
> Yea I'm confused too. This is exactly how I would've done it... But Dustin is out for the next couple days, so we'll see what he has to say

Let's leverage Dustin's absence to push some shitty code! 💃

**Review by DHowett — APPROVED** [review]
Thanks for the explanation! Chester is right- I thought that we had an event that fired out of the control to alert the application.

In general, I find myself unhappy with the number of places we use TerminalSettings/CoreSettings/ControlSettings to communicate state from TerminalApp _back_ to TerminalApp. Know what I mean?

Is the StartingDirectory a Core setting, or is it a control setting? If it’s a core setting, there is probably a different place we should be propagating it in. Using a Control setting to have Control tell Core something seems like it’s also the wrong speed. 

None of these are complaints or concerns about the work you’ve done here, @Don-Vito! Just musing :smile:

**Review by zadjii-msft — APPROVED** [review]
Oh okay that makes sense then

**Pull request merged**
