### PR TITLE
Merge the DotNet_###Test "platforms" back into the right place

### PR DESCRIPTION
**Pull request by DHowett**
I originally added these platforms to prevent the .NET components from
building when you built the entire solution, and to prevent them from
building in CI.

It turns out that managing an extra thousand project-platform-config
triples is an absolute pain, **and** that we should have been building
these things in CI the entire time. So.

This should make life _a lot_ easier.

As a bonus, this PR enables the WPF test harness to build for ARM64.

### CODE REVIEW

**Comment by DHowett** [comment]
image

**Review by zadjii-msft — APPROVED** [review]
halle-friggin-lujiah

**Comment by zadjii-msft** [comment]
@msftbot merge this in .01 days

**Comment by zadjii-msft** [comment]
@msftbot merge this in .01 minutes

**Comment by DHowett** [comment]
Interesting, that x86 failure. I'll dig.

**Pull request merged**
