### PR TITLE
Update gsl from 3.1.0 to 4.0.0

### PR DESCRIPTION
**Pull request by AtariDreams**
This is the latest stable version of GSL

### CODE REVIEW

**Review by lhecker — APPROVED** [review]

**Review by DHowett — CHANGES_REQUESTED** [review]
I am worried about this change. Are these changes -- to remove `GSL_MULTI_SPAN_H` and include `<gsl/util>` and `<gsl/narrow>` backwards compatible with 3.1.0?

The code in this repository is compiled inside Windows as well, and the Windows build system is stuck on GSL 3.1.0 at this moment.

If the changes in `LibraryIncludes` and `atlas/pch` are incompatible with GSL 3.1.0, we may not be able to bring code back into Windows until we fix those incompatibilities.

**Comment by AtariDreams** [comment]
Sadly no. I did not consider this...

Perhaps I could workaround this by using an ifdef macro that defines something that wouldn't be defined on the Windows build, but I don't know if this is a bandaid that could cause problems down the line when this code is maintained in the future.

**Comment by AtariDreams** [comment]
#define GSL_MULTI_SPAN_H doesn't matter. We can keep that in. It won't make a difference. The headers though...

**Comment by lhecker** [comment]
I think we should close this PR for now. While your work on upgrading our dependencies is absolutely fantastic, in this case we should just live with 3.1.0 for now IMO. It doesn't have any known bugs and works fine. We're also on C++20 now which features all of the classes we need GSL for. So _technically_ we could actually just drop GSL as a dependency entirely now.

**Comment by carlos-zamora** [comment]
Yeah, I agree with @lhecker here. I think the concerns with compiling in Windows and possibly dropping GSL entirely make updating to 4.0.0 something we don't want to pursue (at least, not yet). Thanks for all the work @AtariDreams, though. We really appreciate it 😊

**Pull request closed without merging**
