### PR TITLE
Add cursorColor to color scheme

### PR DESCRIPTION
**Pull request by yitzhaks**
Add the option to set the cursor color as part of the color scheme.

This is very useful for light themes, where the cursor disappears unless its color
is set in the profile.

Related to issue #764, but doesn't fully resolve it.

## Validation
I tested this manually by creating a light color scheme, setting the cursor color
to black and setting the profile color scheme to the newly created color scheme.
I validated the cursor is black, then set the cursor color in the profile (to red)
and saw it trumps the cursor color from the color scheme.

### CODE REVIEW

**Comment by yitzhaks** [comment]
While locally validating, I didn't see my changes to the built-in color schemes reflected. Is this expected?

**Comment by carlos-zamora** [comment]
@DHowett-MSFT Also, the discussion on #764 sounds like `cursorColor` could/should be added to color schemes, but the others (i.e.: `cursorShape`, `fontFace`, and `fontSize`) should not. I agree with that reasoning. Should we just close that issue once this PR goes in?

**Comment by yitzhaks** [comment]
I added the tests @zadjii-msft suggested (and a tiny bit more).
@carlos-zamora, regarding existing users, they shouldn't be negatively impacted by this change.
If they didn't set a `cursorColor` in their profile they'll:

1. If they didn't set a `colorScheme`, they'll get `#FFFFFF` (from the default built-in color scheme).
2. If they set a built-in `colorScheme`, they'll get the cursor color from that color scheme. This is the only case users should see any changes, and only for the good (in the case of light color schemes where the cursor was invisible they'll now see their cursor, which is what spurred the discussion in the first place).
3. If they set a custom `colorScheme`, they'll get `DEFAULT_CURSOR_COLOR` == `#FFFFFF` (as the default for `cursorColor` when it's not set in their color scheme).

If they set a `cursorColor` in their profile, it will trump any `cursorColor` in the color scheme.
All these cases are covered by the tests I added, so I think we're good here.

**Comment by DHowett-MSFT** [comment]
And yes, this should just close the referenced issue. Cursor shape shouldn’t be part of a color palette. :)

**Comment by zadjii-msft** [comment]
@carlos-zamora You should make another pass on this one, so we can get it merged

**Comment by yitzhaks** [comment]
@DHowett-MSFT, whenever you're ready :)

**Comment by DHowett-MSFT** [comment]
Thanks for the contribution!

**Pull request merged**
