### PR TITLE
Remove a 1px gap under the tabs only visible at >150%

### PR DESCRIPTION
**Pull request by zadjii-msft**
Set the padding to the default TabViewHeaderPadding (8,0,0,0), but with
-1 on the bottom. This prevents a small 1px gap that can appear on 150%
scale displays between the tab item and the content. The 1 on top helps keep
the tab the correct relative height within the tab row.

Regressed in #15078 

See also MSFT:40692364

### CODE REVIEW

**Comment by DHowett** [comment]
Does this regress 100% scale displays?

**Review by lhecker — APPROVED** [review]
Checking the date at which the bug fix got committed is most impressive. Should we have a follow-up issue to remind us about removing this hack?

**Comment by zadjii-msft** [comment]
> Does this regress 100% scale displays?

nope. The only "regression" is we get 1px less of the curve at the bottom, but like, 'K' if you ask me.

**Comment by zadjii-msft** [comment]
From bug bash:

image

This is fixed in 4d47892db
image

**Comment by DHowett** [comment]
OK plz no hate me, but

...

does this make "I can't click the tabs in the top pixel when the window is maximized" _worse_?

**Comment by zadjii-msft** [comment]
@DHowett I've made this _no worse than before_. I feel like we should do the #11309 fix separately

**Review by DHowett — APPROVED** [review]
I hate it so much. BODGY comment?

**Pull request merged**
