### PR TITLE
Enable Control Flow Guard in the common build props

### LINKED ISSUE #5452: Could CFG be added to the main processes?
Hi Team,

I realize that this is preview version of Windows Terminal but would you consider adding Control Flow Guard (CFG) to the following processes, please?

WindowsTerminal.exe
OpenConsole.exe

[https://docs.microsoft.com/en-us/windows/win32/secbp/control-flow-guard](https://docs.microsoft.com/en-us/windows/win32/secbp/control-flow-guard)

I realize this only gives a moderate increase in security but it would be consistent with many other of the running Windows processes. If these were running within AppContainers it would be forgivable, but they are running with Medium level integrity. I have attached a screenshot from Process Explorer (process integrity is shown in the center of the image

Windows_Terminal_Preview
).

Thanks for your time and for creating this app. I’m really looking forward to the final version.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
Fixes #5452.

This will make security go brrrrrrr

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
(I'm verifying right now)

**Comment by zadjii-msft** [comment]
Yea what kind of negative side effects are there for this? If there's only a _minor_ perf impact, then why the heck isn't this enabled by default in new VS projects?

**Comment by DHowett-MSFT** [comment]
That's a great question!

Well, it failing right out the gate is a great indicator.

**Comment by DHowett-MSFT** [comment]
Who would have thought a boolean value's supported contents were Guard and .. i don't know what the other option is. Guard and NULL i guess.

**Comment by DHowett-MSFT** [comment]
This will also help us pass BinSkim :smile:

**Comment by DHowett-MSFT** [comment]
@zadjii-msft not sure about side effects, but a bunch of other tools have it enabled. vs code, edge, svchost, runtimebroker, wsl.exe itself (though it's just a wrapper).. so I'm inclined to say we should just do it and deal with what may come of it

**Pull request merged**
