### PR TITLE
Modify solarized themes for windows terminal to make all text visible

### PR DESCRIPTION
**Pull request by soul4soul**
## Summary of the Pull Request

I have been wanting to use the solarized theme provided in windows terminal since release. I have been unable to use it since the terminal becomes unreadable with the solarized themes supplied. The Solarized theme doesn't specify colors in a manner which complies with the options required by windows terminal. For example there is no concept of "bright" colors in the Solarized spec. This change treats the normal colors the same as the bright colors.

All of the text is at least visible now. The the colors (white/black/green/blue/etc..) no longer match the backgrounds. Black is still hard to read on the dark theme. White is still hard to read on the light theme.

## PR Checklist
* [ ] Closes #xxx
* [X ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
Dark Theme

| Old | New |
| --- | --- |
| dark_old | dark_new |

Light Theme

|Old|New|
| --- | --- |
|light_old|light_new|

Palette

|Old|New|
| --- | --- |
|old_palette|new_palette|

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
So, regarding there being no "bright" colors in the solarized spec: I don't believe we _are_ using them as bright colors. Just like Solarized, we use them to gain an additional 9 color palette slots. These themes are specialized for things that know about Solarized, and perhaps they were not appropriate to ship for general purpose use as Terminal themes.

/cc @zadjii-msft thoughts?

**Comment by j4james** [comment]
I'm not going to try and defend the Solarized color schemes, because I think they're awful. But if you don't like those colors, then you really ought to come up with your own name for whatever alternatives you're proposing, and not just replace the official Solarized values. People that actually like the Solarized schemes assumedly expect the colors exactly the way they are.

And if it comes to proposing new schemes to be included in the app by default, I'd like to think we could do better than a scheme that can't distinguish bright from dark. At the very least open an issue first and give people a chance to vote on it.

Just my 2c.

**Comment by soul4soul** [comment]
Can you point me to the official Solarized documentation for its use with conhost/windows terminal? I don't see it listed on the [website](https://ethanschoonover.com/solarized/) or [repo](https://github.com/altercation/solarized). I see official use of the color palettes for other terminals but not conhost/wt.

To try and get a point of reference I remembered VS Code has a Solarized theme and a built in terminal. Below is a comparison of the wt theme and VS code terminal both using Solarized dark. One of several differences is that all text in VS Code is visible which is critically important.

| wt | VS Code |
| --- | --- |
| wt | image |

If there is no room to change the the Solarized themes I agree with @DHowett-MSFT sentiment about removing them.

**Comment by zadjii-msft** [comment]
I'm mostly looking at the following table, which is taken from [here](https://ethanschoonover.com/solarized/#the-values) on the solarized site. Clipped to only the relevant columns:

       
SOLARIZED | HEX     | 16/8 | TERMCOL   | M/HEX   | RGB         
--------- | ------- | ---- | -------   | ------- | ----------- 
base03    | `#002b36` |  8/4 | brblack   | `#1c1c1c` |   0  43  54 
base02    | `#073642` |  0/4 | black     | `#262626` |   7  54  66 
base01    | `#586e75` | 10/7 | brgreen   | `#585858` |  88 110 117 
base00    | `#657b83` | 11/7 | bryellow  | `#626262` | 101 123 131 
base0     | `#839496` | 12/6 | brblue    | `#808080` | 131 148 150 
base1     | `#93a1a1` | 14/4 | brcyan    | `#8a8a8a` | 147 161 161 
base2     | `#eee8d5` |  7/7 | white     | `#e4e4e4` | 238 232 213 
base3     | `#fdf6e3` | 15/7 | brwhite   | `#ffffd7` | 253 246 227 
yellow    | `#b58900` |  3/3 | yellow    | `#af8700` | 181 137   0 
orange    | `#cb4b16` |  9/3 | brred     | `#d75f00` | 203  75  22 
red       | `#dc322f` |  1/1 | red       | `#d70000` | 220  50  47 
magenta   | `#d33682` |  5/5 | magenta   | `#af005f` | 211  54 130 
violet    | `#6c71c4` | 13/5 | brmagenta | `#5f5faf` | 108 113 196 
blue      | `#268bd2` |  4/4 | blue      | `#0087ff` |  38 139 210 
cyan      | `#2aa198` |  6/6 | cyan      | `#00afaf` |  42 161 152 
green     | `#859900` |  2/2 | green     | `#5f8700` | 133 153   0 

Which, if you re-order the rows to be in terminal color order, looks like the following:

SOLARIZED | HEX     | 16/8 | TERMCOL   | M/HEX   | RGB         
--------- | ------- | ---- | -------   | ------- | ----------- 
base02    | `#073642` |  0/4 | black     | `#262626` |   7  54  66 
red       | `#dc322f` |  1/1 | red       | `#d70000` | 220  50  47 
green     | `#859900` |  2/2 | green     | `#5f8700` | 133 153   0 
yellow    | `#b58900` |  3/3 | yellow    | `#af8700` | 181 137   0 
blue      | `#268bd2` |  4/4 | blue      | `#0087ff` |  38 139 210 
magenta   | `#d33682` |  5/5 | magenta   | `#af005f` | 211  54 130 
cyan      | `#2aa198` |  6/6 | cyan      | `#00afaf` |  42 161 152 
base2     | `#eee8d5` |  7/7 | white     | `#e4e4e4` | 238 232 213 
base03    | `#002b36` |  8/4 | brblack   | `#1c1c1c` |   0  43  54 
orange    | `#cb4b16` |  9/3 | brred     | `#d75f00` | 203  75  22 
base01    | `#586e75` | 10/7 | brgreen   | `#585858` |  88 110 117 
base00    | `#657b83` | 11/7 | bryellow  | `#626262` | 101 123 131 
base0     | `#839496` | 12/6 | brblue    | `#808080` | 131 148 150 
violet    | `#6c71c4` | 13/5 | brmagenta | `#5f5faf` | 108 113 196 
base1     | `#93a1a1` | 14/4 | brcyan    | `#8a8a8a` | 147 161 161 
base3     | `#fdf6e3` | 15/7 | brwhite   | `#ffffd7` | 253 246 227 


This is also the order that the very excellent [iTerm2-Color-Schemes](https://github.com/mbadolato/iTerm2-Color-Schemes#builtin-solarized-dark) repo uses

**Comment by DHowett-MSFT** [comment]
Until we can get to discussion consensus, I'm gonna close this one. Feel free to continue the chat - this just isn't actionable right now!

**Comment by soul4soul** [comment]
> 
> 
> I'm mostly looking at the following table, which is taken from [here](https://ethanschoonover.com/solarized/#the-values) on the solarized site. Clipped to only the relevant columns:

Ah I see! I wasn't interrupting that table correctly. Now I understand the comments about not following the Solarized scheme.

**Comment by zadjii-msft** [comment]
@DHowett-MSFT I know we don't love the default Solarized themes, and it's too late to remove them, but what are your thoughts on shipping these proposed changes as "Solarized [Light|Dark] (Patched)"? 

Actually lets get some more peeps in this discussion: @carlos-zamora @leonMSFT @miniksa @cinnamon-msft @craigloewen-msft @the-entire-console-team-and-everyone-we-know-why-not

**Comment by cinnamon-msft** [comment]
I'm okay with shipping these modified schemes. Also, if we're going to ship these, I feel like we could add more in? Not sure how everyone feels about shipping a ton of themes in-box.

**Comment by j4james** [comment]
In case anyone has missed this point, let me reiterate that these patched Solarized schemes are still very much broken. By making the light and dark colors the same, they are guaranteed to produce invisible text in some applications.

If we are going to include these, I'd urge you to try and find a bunch of good color schemes to include as well. Otherwise we're going to be left with 4 of the 9 bundled schemes being some variant of Solarized, all of which have problems of some sort. That's not a great user experience.

**Pull request closed without merging**
