### PR TITLE
Move the VT parser's parse state into instanced storage

### LINKED ISSUE #3108: VT parser's "should process character by character" flag is a singleton
https://github.com/microsoft/terminal/blob/0691c21876229dc573a18473ca04bfc78c0d6803/src/terminal/parser/stateMachine.cpp#L1351-L1355

Because of this, in...

* conhost: VT input and VT output can cause eachother to switch into and out of stateful processing
* Windows Terminal: Two tabs emitting VT at the same time can cause VT tearing, where the parser gives up partway through one tab's sequence _because another tab completed parsing one._

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
## Summary of the Pull Request
It was bad before, but now it is not.

## PR Checklist
* [x] Closes #3108
* [x] CLA cla cla
* [x] Tests added/**passed**
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already, and I wear the guise of the people of the core.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
This is, in theory, a testable bug.

**Comment by DHowett-MSFT** [comment]
This is, in practice, a testable bug.

**Comment by DHowett** [comment]
followup: tried 4640, doesn't trigger. Seems to be related to static lifetime things in functions with non-trivial constructors.

**Comment by DHowett-MSFT** [comment]
The VT parser used to be keeping a boolean used to determine whether it
was in bulk or single-character parse mode in a function-level static.
That turned out to not be great.

Fixes #3108; fixes #3073.

**Comment by DHowett-MSFT** [comment]
_WHAT._ I typed that into the squash/merge box ...

**Pull request merged**
