### PR TITLE
doc: Remove unnecessary link to VC redist, update md lint rules

### LINKED ISSUE #7889: README.md link broken
The link to "Desktop Bridge VC++ v14 Redistributable Package" in README.md is unavailable.

### PR DESCRIPTION
**Pull request by zadjii-msft**
Terminal ships with this dependency embedded, and it is not required that you install it separately. Since the link is broken, let's just remove it entirely.

* [x] fixes #7889 
* [x] related to https://github.com/microsoft/terminal/issues/7917#issuecomment-707955335
* [x] I work here
* [x] is a docs update

<hr>

Additionally, update the markdown linter rules in the wake of #7637, because apparently that was never actually applied to any files, so now the onus is on the first person to touch any of our markdown files.

### CODE REVIEW

**Comment by skyline75489** [comment]
I wonder if there's anything else in the README that has decayed.

For example, suggested change:

```diff
-Kayla Cinnamon, Program Manager: @cinnamon_msft 
+Kayla Cinnamon, Program Manager: @cinnamon_msft (**Make sure you follow her ❤️** )
-Dustin Howett, Engineering Lead: @dhowett 
+Dustin Howett, Engineering Lead: @dhowett (**This guy tweets a lot**)
-Michael Niksa, Senior Developer: @michaelniksa
+Michael Niksa, Senior Developer: @michaelniksa(**He doesn't really tweet**)
-Mike Griese, Developer: @zadjii
+-Mike Griese, Developer: @zadjii (**nah, no tweet. But he just became a father! 🎉 **)
-Carlos Zamora, Developer: @cazamor_msft
+Carlos Zamora, Developer: @cazamor_msft(**Our a11y hero**)
-Leon Liang, Developer: @leonmsft
+Leon Liang, Developer: @leonmsft(**hey there, how you doing**)
-Pankaj Bhojwani, Developer
+Pankaj Bhojwani, Developer(**so...you're still using facebook?**)
```

**Comment by zadjii-msft** [comment]
Ah. We didn't actually update any files for the linter, we just _added it_. Well that's a hassle.

**Review by DHowett — COMMENTED** [review]
Were most of these changes made before the line length was set to 400? It looks like they all got super short.

**Comment by zadjii-msft** [comment]
> 
> 
> Were most of these changes made before the line length was set to 400? It looks like they all got super short.

Yea, they were. I can revert those if you want.

**Review by DHowett — APPROVED** [review]

**Pull request merged**
