### PR TITLE
ci: run the tests as a separate build stage

### LINKED ISSUE #11858: Put the x64 feature tests in a separate build phase that downloads the x64 build artifacts
It's driving me nuts that the machine sometimes goes LOL no and goes away on a rerun. Let's not waste time with all the other compile phases and such.

### PR DESCRIPTION
**Pull request by DHowett**
This commit moves the unit and feature tests to a separate stage, which can be retried more easily.

Closes #11858

### CODE REVIEW

**Comment by zadjii-msft** [comment]
woah, that looks like it works. Thats so cool

**Review by miniksa — APPROVED** [review]
Oh thank goodness. This is exactly what I wanted.

**Comment by DHowett** [comment]
The way we're shuttling all exe/dll/etc artifacts from build to build scares me a little and we might want to use pipeline artifacts instead (docs say they're faster!), but... if you guys are cool with it I can be cool with it too

**Review by zadjii-msft — APPROVED** [review]

**Comment by zadjii-msft** [comment]
If it works, I'm cool with it 

> implying I really understand our ci config

**Comment by miniksa** [comment]
> The way we're shuttling all exe/dll/etc artifacts from build to build scares me a little and we might want to use pipeline artifacts instead (docs say they're faster!), but... if you guys are cool with it I can be cool with it too

I honestly had no idea there were two different types of artifacts. So that should be a follow on investigation, IMO.

**Comment by DHowett** [comment]
I'm going to run the non-CI version against this to make sure Helix can still submit/report.

**Comment by DHowett** [comment]
yes, this works in helix. the tests fail, but submission works.

I should move helix submission to *another* sub-job

**Pull request merged**
