### PR TITLE
Minor grammar fixes for the vintage AddASetting.md doc

### PR DESCRIPTION
**Pull request by debghs**
## Summary of the Pull Request
Added some Punctuation Marks as Required.
## References and Relevant Issues
None.
## Detailed Description of the Pull Request / Additional comments
There were some missing Punctuation Marks(Ex: Colon(:) and Full Stop(.)), so I have added them.
## PR Checklist
- [ ] Closes #xxx
- [ ] Tests added/passed
- [ ] Documentation updated
   - If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
- [ ] Schema updated (if necessary)

### CODE REVIEW

**Comment by debghs** [comment]
@microsoft-github-policy-service agree

**Review by lhecker — APPROVED** [review]

**Review by DHowett — CHANGES_REQUESTED** [review]
Thanks for the contribution! I appreciate it.

I have a couple questions. It looks like the new rule is applied inconsistently. There are still some bullet points that don't end with a `.` or a `:`.

Did you have a guiding principle about where you added them?

Some of the things in the bulleted lists aren't sentences (like `NT_CONSOLE_PROPS`, for example) and shouldn't necessarily end in a full stop.

**Comment by debghs** [comment]
@DHowett, the thought process behind adding these punctuation marks has been:
1. Ending a sentence with a Full-Stop(.) .
2. While listing one or more subpoints, using a Colon(:).

However, as you have pointed it out, the implementation of the above is indeed, inconsistent.

So, I propose these further changes:
- Adding Full-Stops at the end of the subpoints of point number 5.
- As you stated rightly, the bulleted lists under point number 7 are not sentences and thus need not contain  Full-Stops. Omission of those.
- Additionally, in regard to the idea behind using a Colon(:), I would propose that there should be a Colon added after the second subpoint of point number 3, as it describes more subpoints under itself (as is done in the subpoint of point number 7).
 
I hope this explains my thought process and answers your questions.
I would like to commit these changes along with any further suggestions that you may have.

**Comment by zadjii-msft** [comment]
(overrode on the basis that _this doc isn't really used anymore_, so it's not really worth nitpicking over. Any improvements are welcome 😝 )

**Pull request merged**
