### PR TITLE
Add ServicingPipeline.ps1, a script I use to service Terminal

### PR DESCRIPTION
**Pull request by DHowett**
This script takes pull requests from a project board, cherry-picks them,
and updates the project board. It also yells at you if there are
conflicts to resolve, and generally tries to keep track of everything.
It is quite cool.

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]
It is quite cool.

**Comment by zadjii-msft** [comment]
I'm assuming this depends on you already importing some github module? that should probably be mentioned...

**Comment by DHowett** [comment]
> I'm assuming this depends on you already importing some github module? that should probably be mentioned...

Oh dang you're right. Yea.

**Review by miniksa — APPROVED** [review]

**Comment by tahaluindo** [comment]
Yeah

**Comment by DHowett** [comment]
I've chosen to use `Requires -Module PSGitHub` so that the powershell engine itself will import or complain :)

**Pull request merged**
