### PR TITLE
Remove the WinTelnetEngine

### PR DESCRIPTION
**Pull request by DHowett**
Nobody was using it.

Discussed in #2661.

### CODE REVIEW

**Comment by DHowett** [comment]
This will conflict @j4james in #6506

**Comment by j4james** [comment]
I don't think it matters much, but I just wanted to point out that the xterm engine currently sends underline sequences (i.e. `\e[4m` and `\e[24m`) that the Windows telnet client doesn't support. It's just going to ignore them, so it's probably not a big deal, but it is a little extra overhead.

And technically xterm (as defined by terminfo) supports a bunch more attributes that we could be sending, and which the Windows telnet wouldn't support. But if telnet is the only thing using this engine then that doesn't matter either. And I guess that would also mean we could drop the underline sequence too.

**Comment by DHowett** [comment]
Yeah.. right now, Telnet's the only thing I know of using this engine. I'm not too worried about giving it new and fun features/making it match `xterm`-without-`256color` compatibility given that the server's only used for internal diagnostic scenarios and it is absolutely on the way out.

**Comment by DHowett** [comment]
Er, using that* engine.

**Comment by miniksa** [comment]
@DHowett, I thought there was still a server recovery scenario that used telnetd for emergency recovery on a datacenter rack via serial port. We would have a protocol obligation to maintain that one without sending additional sequences.

**Comment by miniksa** [comment]
> @DHowett, I thought there was still a server recovery scenario that used telnetd for emergency recovery on a datacenter rack via serial port. We would have a protocol obligation to maintain that one without sending additional sequences.

Hm, my brain might be slow this morning. This is SAC/EMS that I'm referring to, not telnetd.exe. Let me make sure that it's not trying to use the wintelnet-level of PTY output.

**Comment by miniksa** [comment]
> > @DHowett, I thought there was still a server recovery scenario that used telnetd for emergency recovery on a datacenter rack via serial port. We would have a protocol obligation to maintain that one without sending additional sequences.
> 
> Hm, my brain might be slow this morning. This is SAC/EMS that I'm referring to, not telnetd.exe. Let me make sure that it's not trying to use the wintelnet-level of PTY output.

False alarm. It just uses a standard ConPTY start through `CreatePsuedoConsole`. OK, I'm good with this.

**Comment by DHowett** [comment]
That was a rollercoaster

**Pull request merged**
