### PR TITLE
Update caption buttons to use glyphs

### PR DESCRIPTION
**Pull request by dansmor7**
The min/max/close buttons now use the same font glyphs used in Windows instead of paths.
They will also look different depending on whether you use Windows 10 or 11.

### CODE REVIEW

**Comment by DHowett** [comment]
WOW! Can you share some screenshots? I didn't realize these glyphs existed!

**Comment by dansmor7** [comment]
Old / new / settings app:
windowed
maximized

**Comment by zadjii-msft** [comment]
Does this happen to fix either of:

* #7751
* #7577

by any chance? I'm guessing they might!?

**Comment by dansmor7** [comment]
With certain scaling levels, the new fluent icons are always blurry on titlebars (win32, UWP, terminal).
I didn't check, but I assume that the glyphs will not be blurry on Windows 10 because they use the old font.
However, the glyps seem to have some alignment issues, making them even more blurry, and I'm not sure if I can fix that.

I looked into the minimize button problem:
* The UWP titlebar has 4px/5px, just like Terminal, but win32 titlebars have 5px/4px
* The new fluent icons have rounded caps, but the win32 minimize one doesn't (it's very subtle)
* The win32 minimize button is not blurry when the other buttons are

From this I presume that the minimize button is still using the old icon. So perhaps the Terminal/UWP vertical alignment is correct.

UWP/win32/Terminal current/Terminal new:
125%
scaling125

300%
scaling300

**Comment by dansmor7** [comment]
I was able to improve the rendering by wrapping the icon inside a Viewbox.

However, it won't perfectly match UWP, because scaling is calculated differently.
The icon width is 10px, which on 1.25x scaling would become 12.5px.
UWP titlebars truncate that to 12px, while Xaml renders that as 13px.

This is probably the best that can be done for now.

125x scaling:
image

**Comment by dansmor7** [comment]
I found these icons [here](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font).

**Comment by DHowett** [comment]
> I found these icons [here](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font).

OH DANG! I was convinced they were a private API. Naw, we gotta do this. I love it.

**Comment by zadjii-msft** [comment]
You know what, I'll just fix it in post

**Comment by DHowett** [comment]
This has been going very well in 1.16; I marked it up for 1.15 but then thought twice. @zadjii-msft can you gut-check me? It's worked beautifully on everything we've thrown at it.

**Comment by zadjii-msft** [comment]
@DHowett No one on the team (read: on 1.16) uses Windows 10. That would be my reluctance. But it's a pretty easy revert if something does ~explode~ look slightly bad, so #shipit?

**Comment by DHowett** [comment]
> uses Windows 10

I do! I'm also a crazy person. :)

**Pull request merged**
