### PR TITLE
Make sure we fully clean up state when closing a peasant

### LINKED ISSUE #11215: Mysterious hang in Monarch::_getMostRecentPeasantID
version **1.12.2521.0**. 
Unsure how I got into this state. Probably 
* open windows 1, 2, 3. 1 is not the MRU window.
* Close 2 and 3. 
* Try `globalSummon` the window. Terminal is in an infinite loop now inside `Monarch::_getMostRecentPeasantID`

but my repo's in the middle of a weird merge ATM so I can't verify on `main`

The symbols for this build don't include accurate source info, or at least my windbg is fucky. But what seems to be happening is `_getMostRecentPeasantID` is in the `while (_mruPeasants.cbegin() + positionInList < _mruPeasants.cend())` loop. We're looking for ID=3, which we don't find in the list of peasants, so `_getPeasant` ends up returning null. We determine that we _should_ have cleaned out that peasant ID from the MRU entries at that point, so we try again. However, we didn't. The MRU list still contains 3 at index 0, so we go looking for it again.

`auto maybeThePeasant = peasantSearch == _peasants.end() ? nullptr : peasantSearch->second;` in `Monarch::_getPeasant` ends up setting `maybeThePeasant` to `null`, which we then happily return (without cleaning up any MRU entries for it).

absolutely baseless list of possible commits to investigate:
* #11143
* #11043
* #10972

I did not have the tray icon enabled.

Filing on myself so I don't lose this, but I don't think I'm getting anything more out of this debugger

There's no valuable logs other than a million `Monarch_Collect_WasDead(Id=3, Desktop={guid})`

### PR DESCRIPTION
**Pull request by Rosefield**
Fix infinite loop when trying to summon a window after close.

In #10972 code was added to try to clean up state manually when a window
was closed instead of waiting for it to be detected as a dead peasant.
Unfortunately I didn't know any better and missed cleaning up
`_mruPeasants` as well. The result is there  would be an infinite loop
in `_getMostRecentPeasant` since `_getPeasant` will only clean up ids if
it finds a peasant, not if it doesn't find anything. This is the minimal
change to get this working, but it might be a good idea to make
`_getPeasant` be more thorough about cleanup.

## Validation Steps Performed
Tested that before the change we infinitely loop, and after the change
we summon correctly.

Closes #11215

### CODE REVIEW

**Comment by Rosefield** [comment]
@zadjii-msft I added a test for this particular case. In the future it might be worth evaluating in the tests if they should use `_closePeasant` instead of `_killPeasant` but that seems out of scope for this bug fix. I confirmed that the test runs forever (or at least until I killed it) without the code change, and with the change it passes.

**Comment by Rosefield** [comment]
Being top  contributor to this project is so easy
1. Make large sweeping changes
2. Find a bunch of bugs that are a result of (1.)
3. Fix them in individual PRs
4. ???
5. Profit.

**Comment by zadjii-msft** [comment]
> * Make large sweeping changes
> * Find a bunch of bugs that are a result of (1.)

you've basically described my entire time on the Console team

**Review by DHowett — APPROVED** [review]
Thanks!

**Comment by DHowett** [comment]
@msftbot merge this in 4 minutezs

**Comment by DHowett** [comment]
@msftbot merge this in 1 minute

**Review by zadjii-msft — APPROVED** [review]
Thanks for adding tests here. We may (in general) just need more tests now that a peasant can close gracefully rather than just "no longer exist", but this will probably cover the biggest case. Thanks!

**Pull request merged**
