### PR TITLE
[DRAFT] Data Oriented Design Rewrite of OutputCellIterator

### PR DESCRIPTION
**Pull request by skyline75489**
## PR Checklist
* [ ] Closes #xxx
* [ ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

### CODE REVIEW

**Comment by skyline75489** [comment]
Just to give you guys some example how impactful this method is

Before:

image

After:

image


Despite the huge saving in CPUs, the time consumed for catting a large file isn't shortened. I suspect this is because the VtIO is now the bottleneck?

**Comment by DHowett** [comment]
> how impactful

image


😉

**Comment by skyline75489** [comment]
No, you didn’t see that😅

think of this as a pioneer PR for the future TextBuffer rewrite. The performance gain will be *huge*.

**Comment by skyline75489** [comment]
> Despite the huge saving in CPUs, the time consumed for catting a large file isn't shortened.

Nope. I can't figure it out why this happens. Closing this because I don't see real meaning in it if it only leads to great number in profiler.

**Pull request closed without merging**
