### PR TITLE
Deps: Bump Newtonsoft.Json from 10.0.3 to 12.0.3

### PR DESCRIPTION
**Pull request by WSLUser**
Bump Newtonsoft.Json from 10.0.3 to 12.0.3

## References
Part of #5297

## PR Checklist
* [ ] Closes (none)
* [x] CLA signed
* [ ] Tests added/passed N/A
* [ ] Requires documentation to be updated N/A
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Validation Steps Performed
CI builds successfully

### CODE REVIEW

**Comment by WSLUser** [comment]
Sorry for the extra commits. I was doing an experiment that needed reversion for now.

**Comment by WSLUser** [comment]
> The UIA tests don't run in CI

Will this still be relevant after https://github.com/microsoft/terminal/pull/6417 is merged? This dep only affects Windows Terminal, not conhost or conpty.

**Comment by zadjii-msft** [comment]
> Will this still be relevant after #6417 is merged? This dep only affects Windows Terminal, not conhost or conpty.

I'm actually pretty sure the UIA tests _only_ apply to conhost. We don't really have any UI tests for the Terminal yet (😭)

#6417 is just removing a bunch of unused code from the WindowsTerminal project that was fortunately not needed.

**Comment by WSLUser** [comment]
> We don't really have any UI tests for the Terminal yet (😭)

I wonder if you can steal some from the WinUI team. 

Since the UIA tests are only run for conhost, can we merge this in?

**Comment by DHowett** [comment]
Not without validation. Something being “just for conhost” gets MORE scrutiny, not LESS.

**Comment by WSLUser** [comment]
I think you misunderstood me. Conhost is out of the picture completely. Not related at all to this change.

**Comment by DHowett** [comment]
_these are the UIA tests for conhost and conhost alone_, it’s not just in the picture—it is the _entire_ picture!

**Comment by WSLUser** [comment]
Maybe I'm misunderstanding. Is this particular dep being used by conhost? I thought it was not. I will run the UIA tests on VS locally and see if anything is flagged as an error.

**Comment by DHowett** [comment]
Meh. I just ran the tests locally, and I'm not worried about this dependency any more. I mean, it's fine that it's outdated, but sure, let's update it.

**Pull request merged**
