### PR TITLE
Change settings content frame transition to drill in

### LINKED ISSUE #10632: Settings Page Animation Restarts When Switching To Settings Tab
When you have a setting tab already open and switch back and forth between the Settings tab and any other tab, the animation of the page (where the page content appears vertically centered and moves upward - which is a bit of an odd animation itself) will restart again, even though this isn't the first time opening the page.

It might have been intended, but I find it a little.... odd.

# Proposed technical implementation details (optional)

A different animation might make this appear less odd. Like fade, or any number of animations.

https://user-images.githubusercontent.com/4098042/125307353-9a635c80-e2f5-11eb-896f-d39a75b7345c.mp4

### PR DESCRIPTION
**Pull request by Don-Vito**
## PR Checklist
* [x] Closes #10632
* [x] CLA signed. 
* [ ] Tests added/passed
* [ ] Documentation updated.
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already.

### CODE REVIEW

**Comment by Don-Vito** [comment]
@carlos-zamora - this changes the default transition for all scenarios (both for internal navigation and when switching tabs). Hope it makes sense. At least for me it feels better :blush:

**Comment by carlos-zamora** [comment]
From #10632:
DrillIn

**Review by carlos-zamora — APPROVED** [review]
Love it! Thanks!

**Review by zadjii-msft — APPROVED** [review]

**Comment by DHowett** [comment]
So, it doesn't _fix the issue_ but it sure does make it less jarring. Let's see how it does!

**Comment by Don-Vito** [comment]
DrillIn2

**Comment by Don-Vito** [comment]
> 
> 
> So, it doesn't _fix the issue_ but it sure does make it less jarring. Let's see how it does!

Theoretically, we can override the transition (e.g., by suppression) after the settings tab is open the first time. However, I actually quite love this experience.

**Review by miniksa — APPROVED** [review]
I love it

**Comment by DHowett** [comment]
> I love it

ME TOO

**Comment by DHowett** [comment]
@msftbot merge this in 1 minutes

**Pull request merged**
