### PR TITLE
Make the window border actually follow the user's theme

### LINKED ISSUE #4980: White border when Terminal is dark while Windows is in Light theme
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19582.1001]
Windows Terminal version (if applicable): 0.10.761.0
```

# Steps to reproduce

1. Set Windows theme to Light. 
1. In `profiles.json`, set `"requestedTheme": "dark"` and `"showTabsInTitlebar": true`
1. Focus on the window.

# Expected behavior

No white borders, regardless of Windows theme color. (Like as VSCode)

# Actual behavior

image

Though https://github.com/microsoft/terminal/pull/4817 fixes the white border issue for Dark mode in Windows, the border still presents with the combination of dark theme for Terminal settings and light theme for Windows.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
## Summary of the Pull Request

One of our great contributors already hooked up all the logic for this,
we just needed a theme library that could handle the request.

## PR Checklist
* [x] Fixes #4980
* [x] CLA signed
* [x] Tests added/passed
* [ ] Requires documentation to be updated

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Most of the diffs here are updating the nuget package :smile:

**Comment by DHowett-MSFT** [comment]
@msftbot merge this in 5 minutes

**Comment by mdtauk** [comment]
Does this make the border follow the System theme, or the app settings JSON "RequestedTheme"

**Comment by DHowett-MSFT** [comment]
The application's currently-active theme.

**Comment by DHowett-MSFT** [comment]
The border currently follows the _system_ theme.

**Comment by mdtauk** [comment]
Thank you @DHowett-MSFT

**Pull request merged**
