### PR TITLE
Search box visual tweaks

### PR DESCRIPTION
**Pull request by gabrielconl**
Made some changes to the search box:
* Adjusted spacing inside the box
* Detached the search box from the titlebar (as explained [here](https://github.com/microsoft/terminal/issues/1375#issuecomment-856667292))
* The search box is now 8px further to the left, in case the scrollbar is always enabled
* Made some controls use default properties, so that they'll adjust nicely to the 2.6 styles

Other: the search box and command palette now use OverlayCornerRadius

Before/After:
image

### CODE REVIEW

**Comment by zadjii-msft** [comment]
@cinnamon-msft for the design sign off, but _I_ sure think it looks cool. 

\<showerthought\> Plus, if it's detached, then we could add a little handle somewhere and allow the user to just like, drag it wherever they want in the Terminal. That would solve the whole "dock to top" vs "dock to bottom" debate! I'm absolutely not saying you should do this now though. That's just a crazy idea.\</showerthought\>

**Comment by cinnamon-msft** [comment]
I dig it. :) The only thing I'm not too keen on is that the close button is larger than the rest of the buttons. Is that just the default properties being applied?

**Comment by DHowett** [comment]
I suspect that that is "correct" -- the close button is not a search option!

**Comment by cinnamon-msft** [comment]
Right.. but I haven't found other search dialogs that have a larger close button compared to the other options :/

**Comment by gabrielconl** [comment]
It was inspired by the InfoBar, which has a larger button that has the same space on top, right and bottom.
image

Would either of these look better?
A) consistent 8px menu padding
image

B) equal spacing around the close button
image

**Comment by cinnamon-msft** [comment]
I think I like option A better. 😄

**Comment by gabrielconl** [comment]
I looked into getting some more default properties for the menu. Would that be ok for this PR?
image

**Comment by gabrielconl** [comment]
The brushes can be done in a different PR, because it will take a bit longer. I wanted to use the default ones from menus, but in light mode it's hard to see which button is selected.

Is the design ok as it is now?

**Review by zadjii-msft — APPROVED** [review]
Checked this out locally - looks good to me, thanks!

**Comment by zadjii-msft** [comment]
\<aside> It'd be cool if there was a shadow underneath the search dialog, like there is for the command palette. Almost certain there's an existing issue for this...

**Comment by zadjii-msft** [comment]
@msftbot make sure @cinnamon-msft signs off on this one

**Review by cinnamon-msft — APPROVED** [review]

**Comment by DHowett** [comment]
I wonder how we got a merge conflict o_O

**Comment by zadjii-msft** [comment]
> I wonder how we got a merge conflict o_O

It was the spellcheck PR 🤷 I think I merged it but I'm afraid that the GH conflict resolve tool secretly botched the xaml formatting. Guess we'll see...

**Pull request merged**
