### PR TITLE
Only focus the active pane once initialization is complete

### LINKED ISSUE #6586: wt split-pane (multiple copies) seems to have occasional focus issues
# Environment

```none
Windows build number:  10.0.18363.0
Windows Terminal version (if applicable): 1.1.1671.0

Any other software? No
```

# Steps to reproduce

Run a command line which opens multiple tabs, and some split panes. Supply a name for each tab using `--title`.

Example command line:

`wt.exe -p "Command Prompt" -d . --title Cmd1 ; split-pane -H -p Cmd -d . ; new-tab -p "Windows PowerShell" -d . --title Posh1 ; new-tab -p "Windows PowerShell" -d . --title Posh2 ; split-pane -H -p "Windows PowerShell" -d . ; split-pane -H -p "Windows PowerShell" -d . ; new-tab -p "Windows PowerShell" -d . --title Posh3 ; split-pane -V -p "Windows PowerShell" -d .`

# Expected behavior

Each tab gets the name you assigned it.

# Actual behavior

Tabs sometimes get the names you supplied, and sometimes not. Since this problem is intermittent, I suspect it's a threading bug. I would guess you are using the same string variable to parse parts of the command line successively and passing each to a thread. The variable is getting clobbered.

Also of note, this is likely the same problem that is causing #6340, because they also describe it happening intermittently.

Thanks.

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

Since the days immemorial of the Terminal, the TermControl has auto-focused itself when it finalizes its layout. This has led to the problem that `wt ; sp ; sp ; sp...` ends up focusing one of these panes at random.

This PR fixes this issue by getting rid of the auto-focusing. Panes now manually get focused when created. We manually focus the active pane when a commandline is dispatched. since we're internally tracking "active" separate from "focused", this ends up working as you'd hope.

## PR Checklist
* [x] Closes #6586
* [x] I work here
* [ ] Tests added/passed
* [n/a] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments

I also had to turn the cursor off by default. Most `TermControl`s would never get the `LostFocus` event, so their cursors would get left `On`, and that's not right.

## Validation Steps Performed

I've run the following things a bunch of times to make sure they work: 
* `wtd sp ; sp ; sp`
* `wtd sp ; sp ; sp ; fp -t 0`
* `newTab`
* `splitPane`
* use the command palette to do the above as well

Where the result used to be random (cases 1 & 2), the result is exactly what you'd expect now. 

It doesn't work at all for

```
wtd sp ; sp ; sp ; mf left
```

Presumably because we can't `move-focus` directionally during startup. However, that doesn't work _today_ either, so it's not making it worse. Just highlights that single scenario doesn't work right.

### CODE REVIEW

**Comment by Rosefield** [comment]
I'm curious, why doesn't the directional movement work in startup? Is it because the actual controls don't have a size yet? I will happily report that mf {next,previous}InOrder does work during startup should you need the functionality.

**Comment by zadjii-msft** [comment]
>  Is it because the actual controls don't have a size yet? 

Exactly that. See for example, `Pane::PreCalculateAutoSplit`. During startup, none of the panes have actually been added to the UI tree yet, so they don't have `ActualHeight`/`ActualWidth`s yet. There's some work that we do to try and figure out where the actual positions of panes _will_ be, based off of how big the window is, and roughly how much the pane will take of that window. The math sucks there though, and I was too lazy to try and figure that our for `moveFocus` at this time 😋

**Comment by Rosefield** [comment]
Would you try this commit and see if directional movement works during startup with it? https://github.com/Rosefield/terminal/commit/003125e595c75cec077a7a5c71c8d55abdca673f

**Review by DHowett — APPROVED** [review]
I can't immediately see any issues here, so LGTM! Interested to see you try @Rosefield's suggestion!

**Comment by zadjii-msft** [comment]
@Rosefield 

> Would you try adding this commit and see if directional movement works during startup with it? [Rosefield@003125e](https://github.com/Rosefield/terminal/commit/003125e595c75cec077a7a5c71c8d55abdca673f) If so I can clean it up and make a separate PR with it.

Oh my god it works _fantastically_. :shipit: Thanks!

**Review by PankajBhojwani — APPROVED** [review]

**Pull request merged**
