### PR TITLE
doc: add useAcrylic unfocused limitation to docs

### PR DESCRIPTION
**Pull request by ackvf**
## PR Checklist
* [ ] Closes #xxx
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
I have updated the documentation so that people are not confused about acrylic transparency any more.

## Validation Steps Performed
does not apply

### CODE REVIEW

**Comment by cinnamon-msft** [comment]
Should the JSON schema description also be updated?

**Comment by ackvf** [comment]
@cinnamon-msft Sure, why not. Can you point me to the file?

**Comment by cinnamon-msft** [comment]
Here you go! https://github.com/microsoft/terminal/blob/master/doc/cascadia/profiles.schema.json

**Comment by DHowett-MSFT** [comment]
Thanks!

**Pull request merged**
