### PR TITLE
Open the system menu when user right clicks the drag bar

### PR DESCRIPTION
**Pull request by greg904**
Related to #1375 ("Click/Right click icon should display
Minimize/Maximize/Close menu")

### CODE REVIEW

**Comment by AnuthaDev** [comment]
This menu should also open when the user presses alt+space

**Comment by DHowett** [comment]
@anuthadev it, uh, does? At least on all of my machines..?

**Comment by greg904** [comment]
Without the code to manually set the buttons state, there was a bug where when you maximized the window and right clicked on the drag bar, it would show "maximize" normal and "restore" grayed out which is the opposite of what we want.
Note that the menu correctly updated if you left clicked the drag bar before right clicking after the maximize.

I don't really know why it happens or how to properly fix it.
I tried some things like:
- set the second parameter (bRevert) of GetSystemMenu to TRUE but the menu would no longer appear
- send a WM_INITMENU message before calling TrackPopupMenu but it didn't update the menu
None of these things worked so I ended up setting the buttons' state manually before the menu opens.
I found this solution from stackoverflow and it's the only one that I found unfortunately. It doesn't mean that it is the only one that exists of course. Maybe you can look at how ApplicationFrameHost does it.

**Comment by AnuthaDev** [comment]
> @anuthadev it, uh, does? At least on all of my machines..?

Oh, Okay, I thought it didn't and suggested to add the funtionality. Sorry😅😅

**Comment by skyline75489** [comment]
I should probably mention that, for some reason the system menu added in the PR is not localized.

image

I don't know if it's just me and I'm too lazy to file a issue. So let's put it here.

**Comment by DHowett** [comment]
@skyline75489 _wow_. Okay, if you press <kbd>alt+space</kbd> do you get a localized menu? That one is 100% provided by the system :smile:

**Comment by skyline75489** [comment]
No, I still get a non-localized menu. It also happens on the store version WT. I'm beginning to doubt that maybe it's because somehow my locale is incorrect? But that can't really explain why explorer.exe is just fine.

**Comment by skyline75489** [comment]
Oh I forgot to mention. I was originally using English version of Windows. Then I added the Simplified-Chinese language pack. So maybe this is messing up my locale setting? I'll check what it behaves on my home PC when I get home.

**Comment by mixmastamyk** [comment]
The menu also doesn't honor the system theme.  I'm using dark mode and it is still light.

**Comment by DHowett** [comment]
But, like, so do Task Manager and Notepad

**Comment by Lemmingh** [comment]
@skyline75489
Based on my test, the menu respects the **preferred language list**.

## Environment

* Windows Terminal: `1.0.1811.0`
* Windows: `Windows 10 Pro, Version 1909, Build 10.0.18363.900, 64-bit`
* System locale: `zh-CN` (CP936, Chinese Simplified, China), UTF-8 enabled
* Windows display language: `en-US` (English, United States)
* Language list:
  1. Japanese
  2. Chinese (Simplified, China)
  3. English (United States)

## Steps

1. Fresh start a Windows Terminal.
2. Press <kbd>Alt + Space</kbd>. The menu is in **Windows display language** (English).
3. Right click on the title bar. The menu is in **the first language in the language list** (Japanese).
4. Press <kbd>Alt + Space</kbd>. The menu is in Japanese. Besides, the characters on this menu look a bit weird now.

**Comment by sylveon** [comment]
I believe this might be some sort of system issue. I have similar code for a similar scenario, and when right-clicking the titlebar the menu has nothing disabled until I hit Alt-Space. After hitting the key combo once then the menu returned by `GetSystemMenu` worked right.

Before Alt-Space (incorrect):
image

After (correct):
image

So my wild guess is that the menu is not initialized properly until Alt-Space is hit or the *system* titlebar is right-clicked (because it's in cahoots with user32, it can perform initialization that we can't). This might also explain the localization problem.

I can workaround the no items disabled issue by doing my own code which disables items (like this PR), but localization would need to be fixed within Windows itself.

**Comment by sylveon** [comment]
Also notice how "Close" is default/boldened only after

**Pull request merged**
