### PR TITLE
closeTab warning (When more then one pane is open, moved from original)

### LINKED ISSUE #5301: closeTab should present a confirmation dialog
# Description of the new feature/enhancement
`closeTab` should present a confirmation dialog if multiple panes are open. This would prevent users from accidentally closing all panes in a tab by accident.

### PR DESCRIPTION
**Pull request by Chips1234**
Please note that this is moved from the original, #5874 since that one's commits are a mess, I'm recreating it with a new fork and branch.

## Summary of the Pull Request
Adds a dialog that warns the user when tab close is requested and more than one pane is open. **The feature can be disabled in settings.**
Close pane warning

## References
Closes #5301 

## PR Checklist
* [X] Closes #5301 
* [X] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [X] Documentation updated (for setting to disable warning).
* [X] Schema updated.

## Validation Steps Performed
Manual

### CODE REVIEW

**Comment by Chips1234** [comment]
I did implement a Globalappsetings Boolean just like the warning with close all tab dialog

**Comment by Chips1234** [comment]
However, if you _always_ want to be prompted I guess we can create a new issue for it (since the current Boolean cannot support that)

**Comment by Chips1234** [comment]
@zadjii-msft We could possibly add a second boolean setting: "alwaysWarnCloseTab"

**Comment by Chips1234** [comment]
@zadjii-msft Can you please review this?

**Comment by zadjii-msft** [comment]
As I mentioned before, I want to make sure there's a plan here for the actual settings here before signing off. The code in this PR isn't all that tricky, but I'm worried that we'll get the necessary approvals from other team members and auto-merge this without a plan. So I'm blocking on the "make a plan" element of this PR first and foremost.

**Comment by Chips1234** [comment]
But you can block this dialog from appearing in settings. Look at my commit. @zadjii-msft

**Comment by zadjii-msft** [comment]
I'm more concerned about making sure that we have a comprehensive plan for all the future variants of this scenario. I don't want to just slap another setting in there that'll make it harder for us to have a comprehensive solution to all the scenarios in #6549

**Comment by DHowett** [comment]
Thank you so much for working on this! We've chosen to take the project in a slightly different direction, and make sure that this feature is fully specified before we commit to it. We'd love to have you back, of course, in the future! :smile:

**Pull request closed without merging**
