### PR TITLE
Compensate for new warnings and STL changes in VS 16.7

### PR DESCRIPTION
**Pull request by miniksa**
New warnings were added in VS 16.7 and `std::map::erase` is now `noexcept`.
Update our code to be compatible with the new enforcement.

## PR Checklist
* [x] Closes broken audit in main after Agents updated over the weekend.
* [x] I work here.
* [x] Audit mode passes now
* [x] Am core contributor.

## Validation Steps Performed
* [x] Ran audit mode locally

### CODE REVIEW

**Comment by skyline75489** [comment]
Wait a minute they are allowed to do that? I thought noexcept was only a nightmare in users’ code. Isn’t there some kind of regulation to prevent the signatures of std functions from changing?

**Comment by DHowett** [comment]
I believe that _removing_ noexcept is considered a breaking change, but adding it may not be?

**Comment by DHowett** [comment]
@msftbot merge this in like 5 minutes

**Comment by miniksa** [comment]
I swear I'm not crazy. On my machine (with 16.7.1) it says that `erase` is `noexcept` despite the CI failing the static analysis build saying it is not:

image

**Comment by miniksa** [comment]
My machine is using this path for STL: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\include
The build machine is using this path for STL: 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801\include

Which would mean the build machine is on Visual Studio 16.6.5.

**Comment by miniksa** [comment]
I'll yank the noexcept from erase until the build machines rev to 16.7. But I have no idea why them going to (apparently) 16.6.5 this weekend broke all the other stuff.

Basically what I'm saying is... GUH.

**Pull request merged**
