### PR TITLE
Fix #7064: Ignore key events without scan code

### LINKED ISSUE #7064: Autohotkey AltGr+7, AltGr+8, AltGr+9, and AltGr+0 reassignments lost in Windows Terminal Preview and Windows Terminal
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```
Microsoft Windows [Version 10.0.19042.388]
# Steps to reproduce

# Expected behavior

I use the Spanish (ES) keyboard configuration and I have an autohotkey script that reassigns AltGr+, (comma), AltGr+. (period), AltGr+7, AltGr+8, AltGr+9, and AltGr+0 to <, >, «, », ‹, and ›, respectively.

I installed Windows Terminal and these keys-to-output reassignments worked great in tabs running PowerShell, cmd, Debian, and Ubuntu.
# Actual behavior

I subsequently installed Windows Terminal Preview and found that AltGr+7, AltGr+8, AltGr+9, and AltGr+0 no longer produced any output. But the reassignment of outputs of AltGr+, (comma) and AltGr+. (period) to < and >, respectively, remain functional.

Windows Terminal also began exhibiting the same behavior. 

The 6 autohotkey keys-to-output reassignments continue to work for all other applications.

### LINKED ISSUE #7120: Windows Terminal 1.1 breaks remapped CapsLock key inside WSL
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.959] (1909)
Windows Terminal version (if applicable): 1.1.2021.0

Any other software? PowerToys v0.19.2, Ubuntu 20.04 WSL fresh install from Microsoft Store with no custom config
```

# Steps to reproduce

* In Windows PowerToys, map "Caps Lock" key to "Ctrl" (left or right doesn't matter)
* Open Ubuntu WSL in Windows Terminal
* Open Vim or Neovim, go into Insert mode
* Press "Caps Lock" (which is mapped to "Ctrl")

# Expected behavior

"Caps Lock" should be treated as "Ctrl". No visible result.

# Actual behavior

"Caps Lock" is treated as "Control-Space", and tries insert any previously inserted text again.

---

## Work-Around

The issue goes away by adding this to settings.json

```json
"experimental.input.forceVT": true,
```

Therefore it is likely caused by #6309 

## More Details, Debugging info

I originally thought it was a bug in PowerToys, but since the work-around works, I figure the bug must be here.
It's a bit annoying, because I like to escape out of normal mode in vim by pressing `<CapsLock>-[` (which should be treated as `<Ctrl>-[`, which is again treated as `<esc>`). Now I instead insert the text i wrote twice.

If i input `<Ctrl-V><Caps-Lock>` in Vim insert mode, vim inserts `<C-Space>`. This is how I determined the remapped key is interpreted as `<C-Space>`.

* This happens only inside Windows-Subsystem for Linux (WSL1) inside windows terminal
* I tested with a new installation of Ubuntu from the Microsoft Store, with no customizations to Ubuntu, Vim or wslconf
* I tested inside and outside of tmux, which did not make any difference
* The issue is _not present_ running WSL from CMD or Powershell, i.e. not using windows terminal.
* The issue is _not present_ running Neovim directly from Powershell Core inside windows terminal
* The issue is _not present_ running vim in Linux (tested Alpine) inside windows terminal as a Docker container

### PR DESCRIPTION
**Pull request by lhecker**
Up until #4999 we deferred all key events to the character event handler
for which `ToUnicodeEx` returned a valid character and alternatively
those who aren't a special key combination as listed in
`TerminalInput`'s implementation.

Since #4999 we started acknowledging/handling all key events no matter
whether they're actually a known key combination. Given non-ASCII inputs
the Win32 `SendInput()` method generates certain sequences that aren't
recognizable combinations though and if they're handled by the key event
handler no follow up character event is sent containing the unicode
character.

This PR adds another condition and defers all key events without scan
code (i.e. those not representable by the current keyboard layout) to
the character event handler.

I'm absolutely not certain that this PR doesn't have a negative effect
on other kinds of inputs.

Is it common for key events to not contain a scan code? I personally
haven't seen it happen before AutoHotKey/SendInput.

Before this PR is merged it'd be nice to have a good testing plan in
place in order to ensure nothing breaks.

## Validation Steps Performed

Remapped `AltGr+8` to `»` using AutoHotKey using `<^>!8::SendInput {Raw}»`.
Ensured `»` is printed if `AltGr+8` is pressed.

Closes #7064
Closes #7120

### CODE REVIEW

**Comment by zadjii-msft** [comment]
This _seems_ reasonable to me, but I also don't really know if there are other kinds of inputs without scan codes. I guess I haven't seen it, but I'm also not usually looking for that. 


I'm not sure how we could be more pre-emptive about other input methods that we don't know, but we could make sure to add tests to cover _this_ case, so that we don't regress it again in the future. Maybe something like just testing that `HandleKey` with a 0 scancode returns false? I know that doesn't check that we still get a character event afterwards, but it's something...

**Comment by lhecker** [comment]
I‘ll add a unit test as soon as I can. 🙂

**Comment by miniksa** [comment]
I don't really see a usage of 0 scan code that would turn into something we could know how to handle without further user32 intervention. 

So I'm okay with this being "it's better than it was and if something proves us wrong, we'll refine further then."

**Comment by lhecker** [comment]
PR fixed. 👍

**Comment by DHowett** [comment]
Okay, let's scream test this!

**Comment by DHowett** [comment]
As always, thank you @lhecker!

**Pull request merged**
