### PR TITLE
Fix setting launch position in the Settings UI not working

### LINKED ISSUE #14469: 1.17 still displays launch params (Default,Default) despite values being set
image

### PR DESCRIPTION
**Pull request by PankajBhojwani**
## Summary of the Pull Request
This change should have been a part of #14190 but was missed. 

## PR Checklist
* [x] Closes #14469 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Validation Steps Performed
Setting launch position in the settings UI works now

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]
WAIT REALLY? THATS IT‽

**Review by carlos-zamora — APPROVED** [review]

**Comment by DHowett** [comment]
@PankajBhojwani was launch position UI part of 1.16?

**Comment by ianjoneill** [comment]
There's still something a bit funky with this:


https://user-images.githubusercontent.com/5821575/206863885-efbda70c-3f7c-4bec-8864-7d10a41ebed1.mp4

**Comment by ianjoneill** [comment]
^ This is fixed in #14522

**Pull request merged**
