### PR TITLE
DEPS: Update CLI11 to 1.9

### PR DESCRIPTION
**Pull request by zadjii-msft**
Updates CLI11 to 1.9. Doesn't look like any of the tests broke.

* [x] I work here
* [x] Ran existing tests

### CODE REVIEW

**Comment by DHowett** [comment]
Do we need to update a cgmanifest JSON?
What changed upstream from 1.8 to 1.9?

**Comment by WSLUser** [comment]
> > Config file handling was revamped to fix common issues, and now supports reading TOML.
> 
> Adding options is significantly more powerful with support for things like
> std::tuple and std::array, including with transforms. Several new
> configuration options were added to facilitate a wider variety of apps. GCC
> 4.7 is no longer supported.
> 
> Config files refactored, supports TOML (may become default output in 2.0) #362
> Added two template parameter form of add_option, allowing std::optional to be supported without a special import #285
> string_view now supported in reasonable places #300, #285
> immediate_callback, final_callback, and parse_complete_callback added to support controlling the App callback order #292, #313
> Multiple positional arguments maintain order if positionals_at_end is set. #306
> Pair/tuple/array now supported, and validators indexed to specific components in the objects #307, #310
> Footer callbacks supported #309
> Subcommands now support needs (including nameless subcommands) #317
> More flexible type size, more useful add_complex #325, [#370][]
> Added new validators CLI::NonNegativeNumber and CLI::PositiveNumber #342
> Transform now supports arrays #349
> Option groups can be hidden #356
> Add CLI::deprecate_option and CLI::retire_option functions #358
> More flexible and safer Option default_val [#387][]
> Backend: Cleaner type traits #286
> Backend: File checking updates [#341][]
> Backend: Using pre-commit to format, checked in GitHub Actions #336
> Backend: Clang-tidy checked again, CMake option now CL11_CLANG_TIDY #390
> Backend: Warning cleanup, more checks from klocwork #350, Effective C++ #354, clang-tidy #360, CUDA NVCC #365, cross compile #373, sign conversion #382, and cpplint #400
> Docs: CLI11 Tutorial now hosted in the same repository #304, #318, #374
> Bugfix: Fixed undefined behavior in checked_multiply #290
> Bugfix: ->check() was adding the name to the wrong validator #320
> Bugfix: Resetting config option works properly #301
> Bugfix: Hidden flags were showing up in error printout #333
> Bugfix: Enum conversion no longer broken if stream operator added #348
> Build: The meson build system supported #299
> Build: GCC 4.7 is no longer supported, due mostly to GoogleTest. GCC 4.8+ is now required. #160
> Build: Restructured significant portions of CMake build system #394
> Converting from CLI11 1.8:
> Some deprecated methods dropped
> add_set* should be replaced with ->check/->transform and CLI::IsMember since 1.8
> get_defaultval was replaced by get_default_str in 1.8
> The true/false 4th argument to add_option is expected to be removed in 2.0, use -capture_default_str() since 1.8

I was trying to update several deps at once or I would of already done this one. I also verified this change did not cause any issues. But it brings more features and bug fixes that may make our current parser a bit better. I do seriously recommend allowing ingestion of TOML at some point, not just json as it could prove useful in extensions or settings in general.

**Comment by zadjii-msft** [comment]
@DHowett None of the `dep/` folder dependencies have a cgmanifest, presumably because those aren't actually ingested into the OS.

I'm not sure that we need any of the new features or if any of the bug fixes apply to us. I was mostly just doing a mechanical update this morning as I had my coffee.

**Comment by DHowett** [comment]
> no cgmanifest

That one we should fix :) it’s not just for OS ingestion, but general project health.

**Comment by zadjii-msft** [comment]
OKeydokey, that's easy enough

**Comment by DHowett** [comment]
@msftbot merge this in 1 minute

**Pull request merged**
