### PR TITLE
Move the context menu strings to a separate resw compartment

### PR DESCRIPTION
**Pull request by DHowett**
This is so that they can be localized separately, and into more
languages.

### CODE REVIEW

**Comment by DHowett** [comment]
Tested!

We're also shortening them.

**Review by cinnamon-msft — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in 24 hours

**Comment by fxzxmic** [comment]
image
Is this a bug?

**Comment by zadjii-msft** [comment]
@fxzxmic that's https://github.com/microsoft/terminal/issues/12351

**Comment by fxzxmic** [comment]
@zadjii-msft Oh, thank you. I'm just not sure if it was intentional or if it was a bug.

**Pull request merged**
