### PR TITLE
Fix marking of new selection start

### PR DESCRIPTION
**Pull request by Don-Vito**
## PR Checklist
* [x] Closes https://github.com/microsoft/terminal/issues/9725
* [x] CLA signed. 
* [ ] Tests added/passed
* [ ] Documentation updated. 
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. 

## Validation Steps Performed
* [x] single click = no selection
* [x] single click and drag = selection starting from first point
* [x] single click in unfocused pane and drag = focus pane, selection starting from first point
* [x] double-click = selects a whole word
* [x] triple-click = selects a whole line
* [x] double-click and drag = selects a whole word, drag selects whole words
* [x] triple-click and drag = selects a whole line, drag selects whole lines
* [x] Shift single-click = defines start point
* [x] second Shift single-click = defines end point
* [x] Shift double-click = selects entire word
* [x] Shift triple-click = selects entire line
* [x] Shift double-click and drag = selects entire word, drag selects whole words
* [x] Mouse mode: Shift single-click = defines start point
* [x] Mouse mode: second Shift single-click = defines end point
* [x] Mouse mode: Shift double-click = selects entire word
* [x] Mouse mode: Shift triple-click = selects entire line
* [x] Mouse mode: Shift double-click and drag = selects entire word, drag selects whole words
* [x] With existing selection: single-click outside the selection and drag = establishes a new selection starting from the click point

### CODE REVIEW

**Comment by Don-Vito** [comment]
@zadjii-msft - sorry 🤦Do we have a task for UT coverage? I volunteer to do it (the moment I get a week with more than 5 minutes to write code).

**Comment by zadjii-msft** [comment]
> sorry 🤦

Haha, don't worry about it. This is just one of the absolute worst bits of spaghetti code in the entire Terminal.

> Do we have a task for UT coverage? I volunteer to do it (the moment I get a week with more than 5 minutes to write code).

I actually caught this because I'm currently working on unittests over in #6842. The whole `TermControl` is getting split into 3 pieces, with the bottom two being fully unit testable. An unfortunate side effect is that I'll absolutely be blowing up any in-flight PRs that touch that area of the code, so maybe it's best to hold off for a bit. 

Hopefully, I haven't regressed things too bad. I'll definitely be adding the list here to my "to check" list, but my initial PR will probably have tests for only a few of them. I'll add the rest to #7001  I'm hoping to get that submitted for review at the start of 1.9 and spend the entire cycle reviewing and iterating on anything that might have regressed.

**Review by carlos-zamora — APPROVED** [review]

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
Thanks :smile:

**Comment by DHowett** [comment]
@msftbot merge this in 2 minutes

**Comment by DHowett** [comment]
You're probably going to hate me, but... this use case fails:

* [ ] click-drag (set selection), shift-click-drag (extend selection while dragging)

Right now, shift-click-drag resets the start point when the drag happens (but successfully extends when the click happens!)

**Pull request merged**
