### PR TITLE
Hook up the keybindings to the SUI

### LINKED ISSUE #8767: Make SettingsTab respect keybindings
# Description of the new feature/enhancement

Some keybindings should be respected when in the settings tab. At the very least, we should respect "closeTab".

Ideally, we'd respect all app-level keybindings. This includes tab management, mode switching (i.e always on top, focus mode, fullscreen, etc...), and command palette. In the end, we'll really have "support" for "all" keybindings because the architecture checks if there's a terminal that can actually handle the action.

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

This is really similar to what we're doing with the CommandPalette. We're adding a `PreviewKeyDown` handler to the SUI `MainPage`, that connects to `TerminalPage::_HandleKey`. That allows the SUI a chance to search the keymap to dispatch actions for keybindings, similar to how the command palette does it. 

This also means it's now possible for the SUI to invoke _all_ the actions available to the Terminal. This includes the ones like `IncreaseFontSize`, which require a _Terminal_ to actually do something. So we have to make sure all the calls to `_GetActiveControl` actually check that the result is non-null before using it. 

A bunch of the actions do nothing now from a SUI tab, others behave _weird_. Like "Rename tab" / "Open Tab Renamer" do nothing. "Duplicate Tab" again does nothing - we try making a new settings tab, which just focuses the settings tab again. "Copy text" definitely does nothing, same with paste.

## PR Checklist
* [x] Closes #8767
* [x] I work here
* [ ] Tests not added 
* [n/a] Requires documentation to be updated

## Validation Steps Performed
I performed all the actions that I changed. I did not test all actions exhaustively, because I felt that searching for callers of `GetActiveTerminalControl()` was exhaustive enough.

### CODE REVIEW

**Review by Don-Vito — APPROVED** [review]

**Comment by DHowett** [comment]
> "Copy text" definitely does nothing, same with paste.

Can people copy/paste in the text fields inside the SUI still?

**Comment by DHowett** [comment]
I wonder why we didn't put key binding handling in a Preview handler for Page

**Comment by Don-Vito** [comment]
> 
> 
> I wonder why we didn't put key binding handling in a Preview handler for Page

Same here :smile:

**Comment by Don-Vito** [comment]
Guys do you have any idea, why KeyDown doesn't get propagated to the TerminalPage? This could be much safer.

**Comment by DHowett** [comment]
KeyDown should almost never get to the TerminalPage; it is "bubbled" up from the deepest layer to the outermost, so once TermControl marks the key event as handled (which it should do, because it sends every non-bound key to the connected process) it's _done_.

**Comment by Don-Vito** [comment]
> 
> 
> KeyDown should almost never get to the TerminalPage; it is "bubbled" up from the deepest layer to the outermost, so once TermControl marks the key event as handled (which it should do, because it sends every non-bound key to the connected process) it's _done_.

This one I understand :smile:
I am asking about the SUI.

**Comment by DHowett** [comment]
Oh. Hm. Great question :smile:

**Review by carlos-zamora — COMMENTED** [review]
This is remarkably straightforward. There's a ~few cases~ case I'm curious about though before signing off:
- does "ctrl+c/v/a" still go through to the textbox when it's bound?
- ~do "tab", "ctrl+tab", and "arrow keys" still go through through when bound?~ "play stupid games, win stupid prizes" case

Can we also get a gif of you opening/interacting with the Command Palette in SUI? Aside from it being cool, just want to double check that CmdPlt eats key strokes like tab, text input, etc. properly.

**Comment by zadjii-msft** [comment]
> does "ctrl+c/v" still go through to the textbox when it's bound?

Ah butts. It does not. The `TerminalPage` eats it before the text box has a chance at it. 

We could manually exempt <kbd>Ctrl+C</kbd>, <kbd>Ctrl+V</kbd>, <kbd>Tab</kbd>, <kbd>Backspace</kbd>, but that's starting to feel like the wrong solution.

**Comment by DHowett** [comment]
I thought that it returned false in non-terminal cases, indicating that the event should continue propagating. Hmm.

**Comment by zadjii-msft** [comment]
Hmm. Binding `MainPage`'s `KeyDown` as opposed to `PreviewKeyDown` seems to work the way we'd expect. Perhaps that lets the TextBox do it's own thing in PKD, and when nothing else has claimed the event, it gets another chance in `KeyDown`?

**Comment by zadjii-msft** [comment]
Guh ignore me. That does not always work as expected, especially with <kbd>Tab</kbd>. More often than not, the focus will move within the page, rather than bubble up to the `_KeyDownHandler` to give us a chance at the action. So that's not what we want 😕

**Comment by Don-Vito** [comment]
> 
> 
> Guh ignore me. That does not always work as expected, especially with Tab. More often than not, the focus will move within the page, rather than bubble up to the `_KeyDownHandler` to give us a chance at the action. So that's not what we want 😕

I've written this 5 days ago in the ticket 😛 
What about handling switch tab and close tab by now (via PreviewKeyHandler) until we understand what swallows the events?

**Comment by zadjii-msft** [comment]
> I've written this 5 days ago in the ticket 😛

Yea you're not wrong. I thought I could solve it quick without reading 🤦‍♂️ 

As a team, we thought maybe the best way to go about this would be to do just the tab switching solution for the timeframe of 1.6, and come back to this discussion for 1.7. @Don-Vito You still cool spinning up that fix?

**Comment by Don-Vito** [comment]
> 
> 
> > I've written this 5 days ago in the ticket 😛
> 
> Yea you're not wrong. I thought I could solve it quick without reading 🤦‍♂️
> 
> As a team, we thought maybe the best way to go about this would be to do just the tab switching solution for the timeframe of 1.6, and come back to this discussion for 1.7. @Don-Vito You still cool spinning up that fix?

@zadjii-msft - waited to make sure you are not working on this. Can try to do it now. I hope it won't take too long.

**Comment by zadjii-msft** [comment]
@Don-Vito You're the best, thanks 😄

**Comment by Don-Vito** [comment]
@zadjii-msft, @carlos-zamora - please see https://github.com/microsoft/terminal/pull/8885

**Comment by zadjii-msft** [comment]
Frankly, I don't think this is needed with #8885, even in 1.7. I bet what we have will be good enough, now that I've seen it.

**Pull request closed without merging**
