### PR TITLE
Add action to run multiple actions.

### LINKED ISSUE #3992: Add a `ShortcutAction` for running multiple `ShortcutAction`s
Perhaps people want to run a whole bunch of commands in a row with a single keybinding? We should let them to that.

### PR DESCRIPTION
**Pull request by Rosefield**
## Summary of the Pull Request
Add a new action that can contain multiple other actions.

 
## PR Checklist
* [x] Closes #3992
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [x] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
Creates a shortcut action that allows a list of actions to be specified as arguments. Steals a bunch of the serialization code from my other pr. Overall, because I had the serialization code written already, this was remarkably easy.

I can't think of any combined action to be added to the defaults, so I think this is just a thing for the documentation unless someone else has a good example. I know there are lot of times when the recommended workaround is "make an action with commandline wt.exe ..." and this could be a good replacement for that, but that is all personalized.

I didn't add this to the command line parsing, since the command line is already a way to run multiple actions.

## Validation Steps Performed
Created a new command, confirmed that "Move right->down" showed up in the command palette, and that running it did the correct behavior (moving right one pane, then down one pane).
```
      {
        "command": {
          "action": "multipleActions",
          "name": "Move right->down",
          "actions": [
            {"action":  "moveFocus", "direction": "right" },
            {"action":  "moveFocus", "direction": "down" },
          ]
        }
      }
```

### CODE REVIEW

**Comment by Rosefield** [comment]
Note that despite this saying there are no merge conflicts, the build will break on merge because of multiple definitions of the IVector converter. If this is approved before https://github.com/microsoft/terminal/pull/10972 I'll make that fix here.

**Review by carlos-zamora — APPROVED** [review]
Looks good to me! Thanks :)

As always, super excited for this one to land hahaha. I've wanted this for a while now.

**Comment by carlos-zamora** [comment]
Oh, don't forget to update the docs please!
> Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx

**Comment by Rosefield** [comment]
For future me problems, is there a way to mute msftbot?

image

**Comment by carlos-zamora** [comment]
> For future me problems, is there a way to mute msftbot?

omg, yeah, your best bet would be to create an outlook rule to automatically delete them. I keep meaning to do that for myself haha

**Review by zadjii-msft — APPROVED** [review]
STOKED to land this.

**Pull request merged**
