### PR TITLE
Exclude more rarely-used stuff from Windows headers

### PR DESCRIPTION
**Pull request by skyline75489**
This PR defines a series of `NOSOMETHING` macros in PCHs, in order to
prevent `windows.h` from bringing a lot of rarely used things into the
project. 

Theoretically this should make PCH generation and overall complication
faster, but I didn't really benchmark the speed. 

Another benefit would be reducing the symbol noises caused by
`windows.h`.

### CODE REVIEW

**Comment by miniksa** [comment]
Oh goodness. Let's list out what these actually do.

* NOCLIPBOARD
  * Blocks `CF_*` clipboard formats
  * Blocks Open/Close/Empty clipboard
* NOCOMM
  * Modem stuff
* NOHELP
  * WinHelp and friends (I think this is deprecated)
* NOKERNEL
  * `GetProcAddress` and a bunch of process/thread management stuff
* NOMB
  * `MessageBox` and friends
* NOMCX
  * Modem extensions
* NOMSG
  * Message queuing (Wndproc and such)
* NOSERVICE
  * Service Controller
* NOSOUND
  * Open/Close/Start/Stop sound
  * Notably not `PlaySound`
* NOUSER
  * Icon, Cursor... System Metrics, System Parameters Info...

Now let's list out if any Terminal/Console project has used them.
* NOCLIPBOARD
  * Console and Terminal use clipboard routines to access the clipboard.
* NOCOMM
  * Nothing touches the modem
* NOHELP
  * WinHelp is dead, nothing should touch it.
* NOKERNEL
  * Console and I believe Terminal need process/thread management and debug stuff from this.
* NOMB
  * Nothing should use MessageBox in production except maybe a last chance error, but sometimes people use this for debugging.
* NOMCX
  * Nothing touches the modem
* NOMSG
  * We use message queuing all the time.
* NOSERVICE
  * Console doesn't touch the service controller, but I believe Terminal does now to check about the input service.
* NOSOUND
  * Only `PlaySound` is used for a system beep. I don't believe we have any other sounds.
* NOUSER
  * System metrics and parameters are used all over the place.

Then my feeling on this:
1. I'd rather we remain relatively consistent with what's in all the namespaces in our projects unless there's a measurable and appreciable improvement in compilation time or debugging ease.
2. I'd rather not block out anything that we used or have the potential to use even on a semi-regular or debugging basis so there's not another roadblock to debugging a problem that is a bit more obtuse/obscure to understand.
3. I'm fine with blocking things that we really shouldn't have any reason to do.

So overall... I think I'd be fine with blocking out:
* NOCOMM
* NOMCX
* NOHELP
and probably
* NOSOUND

But I think all the rest are going to get us into a future difficult-to-debug pitfall that's not worth it unless you can justify it with some sort of improvement metrics.

**Comment by skyline75489** [comment]
I actually have the same concern that it will “get us into a future difficult-to-debug pitfall ”. I’ll try to make this PR less aggressive.

**Comment by zadjii-msft** [comment]
Hey so I don't think I'm qualified to review this one. It looks fine to me, but I don't really have an opinion or enough background to know what the side effects would be. I'm gonna leave it to @miniksa and @DHowett, they're probably the best suited to reviewing this.

**Review by miniksa — APPROVED** [review]
I'm okay with this limited subset since it's stuff we shouldn't be using anyway really, but defer veto rights to @DHowett if he doesn't want to take this at all.

**Review by DHowett — APPROVED** [review]
Sure! Thanks.

**Pull request merged**
