### PR TITLE
chore: Update to TAEF 10.93.240607003

### PR DESCRIPTION
**Pull request by DHowett**

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]

**Review by lhecker — APPROVED** [review]

**Comment by DHowett** [comment]
This test failure on ARM64 is _durable_ (it keeps failing) and _nonsensical._

https://github.com/microsoft/terminal/blob/d3a18b904123b95a7b5a1ea2307f064cf3e28c94/src/buffer/out/ut_textbuffer/TextAttributeTests.cpp#L116-L127

Line 127 is failing, because `GetColor` is returning `#0C0C0C` instead of `#00FF00`. We just constructed the attribute with green as the background index above.

I need to look at this on an actual ARM64 device...

**Comment by DHowett** [comment]
_Also it only fails in release._

Figures.

**Comment by DHowett** [comment]
I am starting to suspect an ARM64 code generation issue.

image

javaw_2xkLxkOjd0

`attr.GetBackground().GetColor(...)` optimizes down into a direct load of index 0 from the color table.

This is after the entire attribute is const-initialized to _for sure_ be `IsRGB`.

**Comment by DHowett** [comment]
Here's a less red-yarn-and-thumbtacks image of the comparison and data flow

devenv_5CdphvOEYk

**Comment by zadjii-msft** [comment]
Did we ever file an internal issue on the ARM codegen thing here?

**Comment by lhecker** [comment]
I believe it's this one: https://developercommunity.visualstudio.com/t/Bad-ARM64-codegen--maybe-during-constant/10583372

**Comment by zadjii-msft** [comment]
got it, so that's https://task.ms/dd/1969044 internally. For the sake of triaging the PR backlog, I'm gonna move this to a draft (since we can't merge till the compiler bug is fixed)

**Comment by DHowett** [comment]
> we can't merge till the compiler bug is fixed

The compiler bug reproduces in complete isolation, without TAEF. I don't think this PR caused it, it only found it.

**Comment by DHowett** [comment]
If this arm64 build passes, I will reupdate and ingest taef 10.92

**Comment by DHowett** [comment]
The compiler bug _may_ only be fixed by VS 17.11 (!)

**Comment by DHowett** [comment]
Banished back to draft status

**Comment by DHowett** [comment]
It's still broken! AHHAHAHA

**Review by lhecker — APPROVED** [review]

**Pull request merged**
