### PR TITLE
Update to the latest vswhere version

### PR DESCRIPTION
**Pull request by Jvr2022**
Updated from 2.6.7 to 3.1.7

### CODE REVIEW

**Comment by Jvr2022** [comment]
Hi @DHowett,

there is now specific issue it’s for staying up-to-date

**Comment by Jvr2022** [comment]
I change the version to 3.1.4

**Comment by Jvr2022** [comment]
Its now downgraded

**Comment by zadjii-msft** [comment]
... could you maybe link the specific issue? I don't think we've been noticing any issues. I'm all for staying up to date, but something like this is usually predicated on _some_ specific reason...

**Comment by DHowett** [comment]
We will not be able to validate this change until we copy vswhere into our package feed. Sorry for the delay!

**Comment by Jvr2022** [comment]
Can we add support

**Pull request closed without merging**
