### PR TITLE
Update C++/WinRT to 2.0.201017.1

### PR DESCRIPTION
**Pull request by DHowett**
We cannot use the most recent version of C++/WinRT due to
microsoft/cppwinrt#780 (or similar).

### CODE REVIEW

**Review by miniksa — APPROVED** [review]

**Review by zadjii-msft — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in 2 minutes

**Comment by Don-Vito** [comment]
Most probably unrelated, but after pulling the upstream/main I am getting errors like this:

TerminalCore.lib(Terminal.obj) : error LNK2038: mismatch detected for 'C++/WinRT WINRT_NO_MAKE_DETECTION': value 'make detection enabled (DEBUG and !WINRT_NO_MAKE_DETECTION)' doesn't match value 'make detection disabled (!DEBUG or WINRT_NO_MAKE_DETECTION)' in pch.obj

I guess it is something local for me... but not sure what :smile:

**Comment by DHowett** [comment]
So! This version of C++/WinRT introduces "version mismatch detection". Unfortunately, that means you'll need to Clean Solution instead of doing an incremental build :smile:

**Comment by Don-Vito** [comment]
Actually I am already post cleaning and building the solution. I even wiped my local git :smile:

**Comment by DHowett** [comment]
https://github.com/microsoft/terminal/pull/8067 oop

**Pull request merged**
