### PR TITLE
Remove "Window Persistence" feature flag

### LINKED ISSUE #12422: Move the window persistence velocity flag to enabled always
as in title, and https://github.com/microsoft/terminal/issues/9800#issuecomment-1032017078

### PR DESCRIPTION
**Pull request by carlos-zamora**
Removes the `Feature_PersistedWindowLayout` feature flag so that it's always enabled.

Closes #12422

### CODE REVIEW

**Comment by carlos-zamora** [comment]
(if we want to keep the feature flag still, I can just revert that last commit. But I don't really understand a reason to do that, so figured I'd just remove it haha)

**Comment by DHowett** [comment]
I closed and reopened it to trigger the CLA bot, but it did not work...

**Comment by zadjii-msft** [comment]
does CLA bot know something we don't 😅

**Review by zadjii-msft — APPROVED** [review]
IMO alwaysEnabled==="we can just delete this now"

**Comment by DHowett** [comment]
@zadjii-msft, did we agree that 1.13 or 1.14 would be the first public version with session save/restore? I forget.

**Comment by DHowett** [comment]
AKA: do i backport this

**Review by DHowett — COMMENTED** [review]
OOSP I APPROVE

**Comment by zadjii-msft** [comment]
@DHowett IIRC you mentioned enabling this for 1.14 Stable (i.e. no backport). I didn't argue, but if it were up to me I'd turn it on in 1.13 Stable (backport). There's not really any bugfixes for this feature going in to 1.14, so keeping it in 1.14+ seems arbitrary. That's my 2c.

**Pull request merged**
