### PR TITLE
Simplify nested condition and make progress > 0 condition explicit

### PR DESCRIPTION
**Pull request by karurung**
I simplified the `if`, `else` logic to improve the code's clarity and maintainability.
I reduced nested conditions, so it will be more efficient.

### CODE REVIEW

**Review by DHowett — COMMENTED** [review]
Thanks! May I ask what compelled this change? We use this pattern (nested conditions) fairly often and usually for a reason... are you planning to address those as well?

**Comment by DHowett** [comment]
In addition, you will need to run the code formatter and change the title of this pull request to explain succinctly what you are doing...

**Comment by karurung** [comment]
Hi, I didn't make a big change.
I simplified the nested conditional to improve code readability. I think this change makes it easier to read.
I also made the condition for `progress > 0` explicit, which makes more clear.

**Comment by lhecker** [comment]
You need to fix the indentation of the code in order for this to be merged.
But even if you fixed it, I'd be personally against merging this, because this is mostly a small, subjective change. It can be argued that the previous code is more readable, because it clearly distinguishes between valid values of the parameter `progress` and the member `_taskbarProgress`.

**Comment by karurung** [comment]
Thank you for give me a feedback!

**Pull request closed without merging**
