### PR TITLE
Fix some additional typos

### LINKED ISSUE #14670: typos
**code comments**

Coincidentally
hasn't
marshaller
marshal
preceding
process

```
$ grep -nr Coincidentially terminal
terminal/src/renderer/atlas/AtlasEngine.h:819:            // Coincidentially that's exactly what we want as the cursor texture lives at {0, 0}.
$ grep -nr hasnt terminal
terminal/src/cascadia/Remoting/WindowManager.cpp:313:            // future. The AppHost hasnt yet set up the callbacks, and the rest
$ grep -nr marshaler terminal
terminal/src/host/ft_uia/Common/ShortcutHelper.cs:91:                // The marshaler doesn't like using the existing instance that we made above because it's a value type and
$ grep -nr "marshall the" terminal
terminal/scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj:93:    marshall the Core types across the boundary.
$ grep -nr preceeding terminal
terminal/src/host/ft_host/CJK_DbcsTests.cpp:2049:// In other words, writing a trailing CHAR_INFO will also automatically write a leading CHAR_INFO in the preceeding cell.
$ grep -nr precess terminal
terminal/src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp:195:    //     to precess the rest of the arguments in the json object.
$ 
```

**markdown**

every time
foresee

```
$ grep -n everytime terminal/doc/Niksa.md
148:So from our little team working hard to make developers happy, we virtually never make the cut for servicing. We're sorry, but we hope you can understand. It's just the reality of the situation to say "nope" when people ask for a backport. In our team's ideal world, you would all be running the latest console bits everywhere everytime we make a change. But that's just not how it is today.
$ grep -n forsee "terminal/doc/specs/drafts/#997 Non-Terminal-Panes.md"
63:I don't forsee this implementation by itself raising security concerns. This
$
```
.github/actions/spelling/expect/expect.txt

As pointed out in a previous PR 'everytime' doesn't belong in expect.txt.

### PR DESCRIPTION
**Pull request by musvaage**
Fix spelling errors in code comments and markdown
Closes #14670

### CODE REVIEW

**Comment by musvaage** [comment]
@microsoft-github-policy-service agree

**Review by DHowett — CHANGES_REQUESTED** [review]
Thanks! Unfortunately, we need to keep the typos in the `oss` directory; the files that we pull in from other open-source projects are intended to match that upstream project in content exactly. Sorry :/

**Comment by musvaage** [comment]
noticed this looking at the patch

the fix would be

find a deserializer

```
$ ed -s terminal/src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp <<<'193,194p'
    //   * If json is an object, we'll attempt to retrieve the action name from
    //     its "action" property, and we'll use that name to fine a deserializer
$ 
```

**Comment by musvaage** [comment]
presuming the second commit is correct this would be ready to merge

**Review by DHowett — APPROVED** [review]
Thanks so much for doing this! I wonder if some of these words have been left over in the spell checking `expect` list. Perhaps it will yell at us later and tell us what we can remove :)

**Comment by musvaage** [comment]
> spell checking expect list

solely everytime

but thereon see comment in linked to ticket

**Review by zadjii-msft — APPROVED** [review]

**Pull request merged**
