### PR TITLE
template: Add Chocolatey template

### LINKED ISSUE #2573: Chocolatey issue template
# Description of the new feature/enhancement

Adding a template for Chocolatey to the issue template list where a warning is that they should not create an issue here, will (hopefully) prevent additional issues.

# Proposed technical implementation details (optional)

When someone creates an issue and clicks on the Chocolatey question option, a text will be displayed to stop creating this issue and go to another repo.

### PR DESCRIPTION
**Pull request by mkevenaar**
This will add an issue template to hold of people with issues regarding the Chocolatey package.

## PR Checklist
* [X] Closes #2573
* [X] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [X] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #2573

## Detailed Description of the Pull Request / Additional comments
This adds an extra template to the issues list with a text to stop creating this issue and go to another repo.

## Validation Steps Performed
N/A

### CODE REVIEW

**Comment by zadjii-msft** [comment]
IMO I like this. My reluctance to endorsing a 3rd party provided Chocolatey package in the first place was people coming to us for chocolatey-specific bugs. We're not the maintainers of the chocolatey package, so I don't really want to have to remember where to point people for those kinds of bugs.

I don't believe we'll need templates for each and every distribution method. All the other methods we own, so I'm fine with all the other bugs coming in the same way. 

I'm a little worried that it does create precedent on us to make a template for each external distribution we endorse. That might not scale super well, but maybe we can just lump all of them together in the "chocolatey / \<your distribution here>" template

That being said, no one reads the templates anyways, so _does it matter?_ 😜

**Comment by gep13** [comment]
>@zadjii-msft said...
That being said, no one reads the templates anyways, so does it matter? 😜

There is some truth to that, but for those of us who do read the templates, I thinking guiding people into the "pit of success" is a good thing.

**Comment by miniksa** [comment]
Putting Kayla and Rich on this to decide since it's a community management concern.

**Comment by DHowett-MSFT** [comment]
We haven't gotten many chocolatey bugs, honestly, and I'm fine with redirecting them as appropriate. Sorry we never merged this one in!

**Pull request closed without merging**
