### PR TITLE
Update Bug_Report.yml

### PR DESCRIPTION
**Pull request by snxx-lppxx**
Added label for "Bug Report".

### CODE REVIEW

**Review by carlos-zamora — APPROVED** [review]
Thank you!

**Review by lhecker — APPROVED** [review]

**Review by DHowett — COMMENTED** [review]
Thanks! I was going to say, "No -- it is the team's job to add this tag when they believe it is a bug", but now i am not sure. @zadjii-msft thoughts?

**Review by DHowett — CHANGES_REQUESTED** [review]
discussion

**Comment by zadjii-msft** [comment]
I agree with Dustin on this one. I'd reckon that most [questions](https://github.com/microsoft/terminal/issues?q=is%3Aissue+label%3AIssue-Question) actually start out as "bug report"s that stem from a misunderstanding or generally not reading the docs. 

It's not a terrible lot of work to swap out the tags. I know that I personally reserve the Bug tag for when I'm fairly confident something actually is a bug and either needs more investigation or is generally on the backlog somewhere. I suppose that's really `Needs-Triage`'s job.

**Comment by zadjii-msft** [comment]
Let's go for it.

**Pull request merged**
