### PR TITLE
Ensure reading the buffer content actually returns the content

### LINKED ISSUE #14378: Buffer exports only contain spaces
### Windows Terminal version

main - a01500f

### Windows build number

10.0.22621.819

### Other Software

_No response_

### Steps to reproduce

Open a PowerShell tab, right click on the tab and select Export Text.

### Expected Behavior

The tab content to be exported to a file.

### Actual Behavior

Lots of spaces are exported instead.

### PR DESCRIPTION
**Pull request by ianjoneill**
## Summary of the Pull Request
Ensures that reading the buffer content actually returns the content.

## References
Regressed in #13626.

## PR Checklist
* [x] Closes #14378
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed

## Validation Steps Performed
Added a test.

### CODE REVIEW

**Comment by ianjoneill** [comment]
The CI hates me.

```
Error: Verify: IsLessThan(tries, 5): Make sure we set up the new console in time - Values (5, 5) [File: C:\a\_work\1\s\src\host\ft_host\InitTests.cpp, Function: ModuleSetup, Line: 280]
Error: TAEF: Setup fixture 'ModuleSetup' for the scope 'C:\a\_work\1\a\drop\Release\x64\test\ConHost.Feature.Tests.dll' failed.
```

**Review by zadjii-msft — APPROVED** [review]
❤️

**Review by DHowett — APPROVED** [review]
Sheesh good catch!

**Review by lhecker — APPROVED** [review]
oof... Thanks for catching this!

`GetText()` is now returning a `wstring_view` which doesn't have the previous `replace()` member function. So I checked all other callers of `GetText()` in #13626 and fortunately this was the only code that had any meaningful changes.

**Pull request merged**
