### PR TITLE
Add functionality to resize any given icon

### PR DESCRIPTION
**Pull request by StEvUgnIn**
## PR Checklist
* [X] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [X] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [X] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

### CODE REVIEW

**Comment by zadjii-msft** [comment]
... What now? I'm very confident that adding these properties to the _json schema_ won't actually add any functionality to the terminal. If you could elaborate more, we'd be happy to revisit this PR.

**Comment by StEvUgnIn** [comment]
@zadjii-msft But this was a draft PR, why did you close it?

**Comment by zadjii-msft** [comment]
@StEvUgnIn Well, there wasn't a description of what this PR was trying to do, there wasn't any _real_ code, there wasn't a linked issue... The change to the schema wouldn't have actually even done anything. If you could describe better what you're trying to do, and provide some actual code, then we can always reopen this. But otherwise this is just creating unnecessary clutter in our (already overloaded) PR backlog.

**Comment by DHowett** [comment]
(Just to confirm: changing the JSON schema to say "the json file supports width and height" unfortunately will not make the _terminal code_ support width and height :smile:)

**Comment by DHowett** [comment]
I understand. This was a PR to begin work, where the schema was a proposal for the implementation :smile: Sorry

**Pull request closed without merging**
