### PR TITLE
Replace some of our macros to reduce confusion, increase success

### PR DESCRIPTION
**Pull request by zadjii-msft**
As mentioned in https://github.com/microsoft/terminal/issues/9354#issuecomment-790034728

`GETSET_SETTING` is too visually similar to `GETSET_PROPERTY`, but with a _VERY_ different meaning. I think that merely changing the name of the macro would make it harder for us to make this mistake again. 

* [x] will inevitably conflict with #9371
* [x] scratches an itch
* [x] I work here

### CODE REVIEW

**Review by carlos-zamora — APPROVED** [review]

**Comment by DHowett** [comment]
I'd rather we keep our macros namespaced to the area they're associated with. SETTING is a touch too generic for me... perhaps `INHERITABLE_SETTING` which really does explain what it is (rather than GETSET :P)

**Review by DHowett — CHANGES_REQUESTED** [review]
discussion

**Comment by DHowett** [comment]
In fact, I'd also eventually like to rename `GETSET_PROPERTY` to something like `WINRT_MUTABLE_PROPERTY` or the like -- not because i don't like getset, but because it is a macro from our winrt helpers.

**Comment by zadjii-msft** [comment]
Meh sure. Get ready for this PR to touch _every single header_

**Review by DHowett — APPROVED** [review]
nit: update PR title!

**Comment by DHowett** [comment]
btw: if you're doing actual `s//` you can use `\b` as part of the regex to match "word boundary". "`\bSETTING`" means "SETTING but only if it didn't have letters before it" :smile:

**Review by carlos-zamora — APPROVED** [review]

**Pull request merged**
