### PR TITLE
Enable holding ctrl to open the Terminal elevated from File Explorer

### LINKED ISSUE #14810: The Explorer context menu should be run as admin when holding `ctrl`
# Description of the new feature/enhancement

When Windows Terminal (WT) is pinned to the taskbar or the start menu, and I need to run it quickly as administrator, I just have to press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>left click</kbd> over its icon, this way is faster than going to the WT icon in the taskbar (or the start menu icon), then right click, hover over "Terminal", then another right click and finally select "Run as administrator".

But this keyboard shortcut doesn't work for the WT item in the context menu of Windows Explorer. When I try the combination <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>left click</kbd>, it only opens a normal (not elevated) WT session.

Sometimes I need to run some script as admin contained in some folder, and for that I have to open WT as admin. As Ctrl+Shift+Left click doesn't work with "Open in Terminal" from the context menu of Windows Explorer, I have to use the longer path:
-Win+X (or the long path example I mentioned when WT is pinned to the taskbar)
-Click on Terminal (Admin)
-And when WT is open as admin I have to type `cd Folder_path_to_work_with `

# Proposed technical implementation details (optional)

I would like that WT, in the context menu of Windows Explorer, can be executed as administrator just by using the shortcut <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>left click</kbd>, this way there would be no need to add another entry in the context menu such as `Open in Terminal as admin` to run WT as administrator.

This way, it would be faster to open WT as admin. When a user needs to open a folder with WT as admin, he just has to right click on the folder (or on an empty field inside the folder), then use the shortcut <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>left click</kbd> in "Open in Terminal" from the context menu to make WT open as admin, and when WT is open it is ready with the path of the folder to work with. 

But if it is not possible that Ctrl+Shift+left click to work for WT to open as admin, then it is necessary for WT to add another entry in the context menu so that it can be run as admin.

What do you think about it?

### PR DESCRIPTION
**Pull request by jamespack**
## Summary of the Pull Request
This pull request adds support for holding the control key and clicking the Open Terminal Here context menu item to elevate the request.
## References and Relevant Issues
14810

## PR Checklist
- [ x] Closes #14810
- [ ] Tests added/passed
- [ ] Documentation updated
   - If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
- [ ] Schema updated (if necessary)

### CODE REVIEW

**Comment by jamespack** [comment]
@microsoft-github-policy-service agree

**Comment by jamespack** [comment]
There is more than one way to attack this. I took the cheap route however, according to [Raymond Chen](https://devblogs.microsoft.com/oldnewthing/20041130-00/?p=37173)

> Note that if you are implementing a context menu handler, then you shouldn’t be using either GetKeyState or GetAsyncKeyState, because the context menu can be invoked programmatically without any user action. 

I suppose its possible on a system that is starved for resources or incredibly busy to miss the control key state. However, in my testing that never happened (I know, works on my machine 😂).

I believe implementing IContextMenu pushes the shortcut to the extended menu in Windows 11 (which may be ok with you).

An alternative would be to implement an additional verb that is dedicated to elevating. The drawback here is that the flag to show the LUA shield is ignored for commands that are not on the non-extended menu. So, you would need a new Icon to that includes the shield to communicate to the user that it would be elevated. I implemented that locally. Photos attached.

Ultimately, I'm good with whatever your team thinks is best. Even if that is something else entirely :)

elevatedicon
SecondVerbWithLua

**Comment by DHowett** [comment]
(Sorry for the delay here! We've been treading water with the big stuff we've got in store for v1.18, but I assure you we'll get this reviewed :smile:)

**Comment by jamespack** [comment]
No worries

**Review by DHowett — APPROVED** [review]
Okay, personally, I think this is a really clever way to handle it even if it's not the _most correct_ way. Let's do it.

Though, isn't admin launch typically both control and shift? Is there something that prevents us from using shift?

**Comment by DHowett** [comment]
Note to merger: please make sure you update the title to be in imperative form, and clean up the body. :)

**Review by zadjii-msft — APPROVED** [review]

**Comment by Dhyfer1** [comment]
> Okay, personally, I think this is a really clever way to handle it even if it's not the _most correct_ way. Let's do it.
> 
> Though, isn't admin launch typically both control and shift? Is there something that prevents us from using shift?

So my [issue](https://github.com/microsoft/terminal/issues/14810) was closed and @zadjii-msft added a commit that referenced my issue in this thread. In my issue I was saying that Windows Terminal when it is pinned to the taskbar or the start menu can be easily opened as admin if you use the key combination <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Left Click</kbd>, but this key combination does not work for the Windows Terminal entry in the context menu of the file explorer, because it opens a normal (not elevated) Windows Terminal session. So it would be a good idea to be able to run Windows Terminal (in the context menu) as admin using also that same key combination.

**Comment by DHowett** [comment]
_Yeah, I was wondering about that too..!_ Shouldn't we have changed it to Ctrl+Shift before merging?

**Comment by Dhyfer1** [comment]
@DHowett Are you asking me? I don't know. I'm just a normal user who wants to be able to run Windows Terminal as admin from the context menu.

Are you asking me? I don't know. I'm just a normal user who wants to be able to run Windows Terminal as admin from the context menu.

Also, if it is possible that Windows Terminal can be run as admin from the context menu, I can save myself from having to type the `cd Folder_path_to_work_with` command when I want to open a folder in Windows Terminal. I think I explained it better in my issue, just check it out.

**Comment by DHowett** [comment]
Oh, I'm sorry. I was putting the question out for the team/community at large to answer :smile:

As implemented in this pull request, the shell extension will launch terminal as admin if you <kbd>Ctrl</kbd>-click "Open in Terminal." That, or a version where we change it so it also requires <kbd>Shift</kbd>, will be released with Preview v1.18 soon. :)

**Comment by jamespack** [comment]
I could open another pull request with shift required as well. If there is appetite for that. Not sure if there is some period where internal only is a thing. But happy to do it 😁

**Comment by DHowett** [comment]
@jamespack I would love that! Nothing internal-only here, Terminal's all about doing it with the community :smile:

**Comment by jamespack** [comment]
Right on. I will do that then.

**Comment by Dhyfer1** [comment]
> As implemented in this pull request, the shell extension will launch terminal as admin if you Ctrl-click "Open in Terminal." That, or a version where we change it so it also requires Shift, will be released with Preview v1.18 soon. :)

Wow. That sounds great. Thanks! I hope that version arrives soon, I already want to try it. By the way, where can I download Windows Terminal Dev?

**Pull request merged**
