### PR TITLE
Allow single cell selection with Shift+Click

### PR DESCRIPTION
**Pull request by Don-Vito**
Closes https://github.com/microsoft/terminal/issues/5766

### CODE REVIEW

**Comment by DHowett** [comment]
holy s*** you're on a roll

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot make sure @carlos-zamora signs off

**Review by miniksa — APPROVED** [review]

**Comment by DHowett** [comment]
We won't be seeing Carlos until next year, so...

**Comment by DHowett** [comment]
@msftbot forget everything I told you

**Pull request merged**
