### PR TITLE
Add Close... option to Tab context menu

### LINKED ISSUE #5524: Feature request: close tabs to the right
# Description of the new feature/enhancement

Hey, I was hoping for a feature in Windows Terminal that I've seen in many browsers and text editors: being able to close all tabs to the right of the current one. Here are some examples:

Sublime:
image

Firefox:
image

Chrome:
image

ConEmu:
image

The scenario I have is that I keep long-lived tabs like build processes, servers, etc. in the leftmost positions in my terminal, then I have "temporary" tabs on the right. Every once in a while, I end up with 20+ tabs open, so I want to activate the 6th or 7th one and close all tabs to the right to get rid of all of the clutter.

Even just having a customizable keyboard shortcut would be great, but this is the kind of thing that could live in a context menu eventually (#1912).

P.S. much of this text was copy/pasted from [here](https://github.com/Maximus5/ConEmu/issues/1321).

### PR DESCRIPTION
**Pull request by mpela81**
## Summary of the Pull Request
Add a "Close..." option to the tab context menu, with nested entries to close tabs to the right and close other tabs (actions already available)
immagine

 
## References
#1912 

## PR Checklist
* [x] Closes #5524
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
First contribution :slightly_smiling_face:
Tried to follow some suggestions from https://github.com/microsoft/terminal/issues/1912#issuecomment-667079311

### CODE REVIEW

**Comment by skyline75489** [comment]
Hi! Thanks for your contribution! The engineer who knows the most about this (@zadjii-msft ) is currently on paternity leave. And with the ongoing pandemic and everybody working from home, the team is just even more short-handed. Just want to let you know the feedback from the team may be slow. But I'm sure they will be more than willing to review your PR when they are available.

Why do I use `they`, you ask? Well I'm not part of the internal engineering team. I'm just a MS employee who wrote some code for this project. Feel free to contact me. Thanks again 😃

**Comment by mpela81** [comment]
@skyline75489, thanks for your comment, needless to say the team can review this at their convenience.

Well, by the way, I may need some expert hand as I'm getting random crashes 😞 
I don't have exact repro steps (play with tabs and their menus for a while). The call stack is all about external code, no clue at the moment on how to debug it 🤔 

```
Windows.UI.Xaml.dll!GetProgrammaticHitTestingParams(CCoreServices * coreServices, CUIElement * uiElement, ITransformer * * transformer, CUIElement * * ppThisNoRef, CPopupRoot * * popupRootNoRef, CUIElement * * popupHitTestSubtreeRootNoRef, bool * isRootNull) Line 5395    C++
    Windows.UI.Xaml.dll!UIElement_HitTestPoint(CUIElement * uiElement, CCoreServices * coreServices, XPOINTF ptHit, bool canHitDisabledElements, bool canHitInvisibleElements, int * pnCount, CUIElement * * * ppElements) Line 5513    C++
    Windows.UI.Xaml.dll!DirectUI::VisualTreeHelper::FindElementsInHostCoordinatesPointStatic(Windows::Foundation::Point intersectingPoint, Windows::UI::Xaml::IUIElement * pSubTree, unsigned char ppElements, unsigned char) Line 250  C++
    Windows.UI.Xaml.dll!DirectUI::VisualTreeHelper::FindAllElementsInHostCoordinatesPointStatic(Windows::Foundation::Point intersectingPoint, Windows::UI::Xaml::IUIElement * pSubTree, unsigned char includeAllElements, Windows::Foundation::Collections::IIterable<Windows::UI::Xaml::UIElement *> * * ppElements) Line 329  C++
    Windows.UI.Xaml.dll!DirectUI::CascadingMenuHelper::OnPointerExited(Windows::UI::Xaml::Input::IPointerRoutedEventArgs * args, bool parentIsSubMenu) Line 284 C++
    Windows.UI.Xaml.dll!DirectUI::MenuFlyoutSubItem::OnPointerExited(Windows::UI::Xaml::Input::IPointerRoutedEventArgs * args) Line 140 C++
    Windows.UI.Xaml.dll!DirectUI::ControlGenerated::OnPointerExitedProtected(Windows::UI::Xaml::Input::IPointerRoutedEventArgs * pE) Line 1404  C++
    Windows.UI.Xaml.dll!DirectUI::Control::FireEvent(KnownEventIndex nDelegate, DirectUI::DependencyObject * pSender, IInspectable * pArgs) Line 267    C++
...
```

Thanks again!

**Review by zadjii-msft — APPROVED** [review]
This is awesome, thanks for doing this!

**Comment by zadjii-msft** [comment]
As far as the crash is concerned - I'm not seeing that locally when playing around with this. I vaguely recall seeing a similar crash when debugging a MenuFlyout like, maybe 14 months ago, but the crash ended up being a transient thing, or was related to XAML debugging or something. I think this is probably safe to go in now, and we can keep an eye on it

**Comment by mpela81** [comment]
Noticed that master branch has progressed in the meantime, I guess PR will require some change because of the new TerminalSettingsModel #7667

**Review by leonMSFT — APPROVED** [review]
This is great, I love the detail of disabling the menu items if it doesn't apply to that tab! 😄

**Comment by mpela81** [comment]
Ah thanks for your reviews so far 🤞

**Comment by zadjii-msft** [comment]
This is bizarre, Github can't seem to forget about this one failed CI build from a week ago, despite re-running the CI successfully since then. I think we're going to have to merge this one manually with an override - the CI failure was definitely unrelated to this PR, and the CI has subsequently passed...

**Pull request merged**
