### PR TITLE
Added shift+ins to defaults.json

### LINKED ISSUE #3162: somebody needs to add ctrl&shift+ins to the default settings
# Description of the new feature/enhancement

when typing "shift + insert",wsl should insert the content in clipboard into command line

# Proposed technical implementation details (optional)

### PR DESCRIPTION
**Pull request by cinnamon-msft**
## Summary of the Pull Request
Added `shift+insert` as a keybinding for `paste` in defaults.json

 
## PR Checklist
* [x] Closes #3162 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Validation Steps Performed
I tried it in Ubuntu and it works.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Should we also add ctrl+in for copy? Should we also put this in defaults-universal.json?

**Comment by DHowett-MSFT** [comment]
re-running just x86.

**Comment by jelez** [comment]
what is the default for Microsoft Surface Laptop users (there is no Ins key there)

**Comment by zadjii-msft** [comment]
@jelez the you can also use <kbd>ctrl+shift+c</kbd> for copy:

https://github.com/microsoft/terminal/blob/4608fd0b94af2f4cf6ceec7b324ba36462e9c06b/src/cascadia/TerminalApp/defaults.json#L210-L211

**Pull request merged**
