### PR TITLE
Changed default padding to 8,8,8,8 and default font size to 11

### LINKED ISSUE #1371: Feature Request: improve default profile padding
The default profiles have a 0,0,0,0 padding and it doesn't look good pinned against so tight against the window frame.

Recommend changing the default to indent to 4,2,0,0.  Curious what others use for their preferred padding.

I'll submit the PR (along with potentially other default profile changes that seem like forward progress)

### PR DESCRIPTION
**Pull request by cinnamon-msft**
## Summary of the Pull Request
Changed default padding to 5,5,5,5 and default font size to 11

 
## PR Checklist
* [x] Closes #1371
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Why 11?
Also, our data shows that 5,5,5,5 is only the _second most popular_ padding. 10,10,10,10 is almost neck-and-neck but edges 5 out by ~10 hits.

**Comment by cinnamon-msft** [comment]
Oh my apologies, I must have been looking at old data for the padding. I can change it to all 10s instead?

I chose 11 because it's mentioned in the issue and I also find it's more readable.

**Comment by miniksa** [comment]
> Why 11?

> I chose 11 because it's mentioned in the issue and I also find it's more readable.

**Comment by zadjii-msft** [comment]
So I know @yodurr mentioned 11 in the issue, but again, _why 11_? Do we have any data that suggests that 11 is the most common setting? Like I'm fine with 8,8,8,8 if that's the most common value, but I don't think we know anything about the font size preferences

**Comment by T3RY4** [comment]
Hmm, in my mind maybe better whould give this value to the user. I think about something like start options (font size, font color, background settings, etc). Like default I prefer font size 14 with 8,8,8,8.

**Comment by Luuk34** [comment]
> Hmm, in my mind maybe better whould give this value to the user.
+1

**Comment by DHowett-MSFT** [comment]
You mean something like _the Terminal has a big configuration file you can use to tweak literally any of these options_?

**Comment by T3RY4** [comment]
Something like style.cfg that on first startup will request user to write some design preferences or use created style.cfg.

**Comment by DHowett-MSFT** [comment]
Oh you’re asking for something like a giant settings file where the user can be in control of all these things

**Comment by yodurr** [comment]
My reasoning for 11 instead of 10 is, similar to the padding changes, size 11 seemed like an improvement to the defaults.  It's not based on customer research (which I would love to see happen to drive these changes going forward)

**Comment by DHowett-MSFT** [comment]
If we're going for "seemed like an improvement", we should consider 12, which is the common default font size pretty much everywhere.

**Pull request merged**
