### PR TITLE
Correct paths in the the runut and runft test scripts

### LINKED ISSUE #8485: Some test scripts don't work correctly
# Environment

Windows build number: Version 10.0.18363.1198
Windows Terminal version (if applicable): Commit 62131720aa7a95df7ed397801c373d4eab0fd3d6

# Steps to reproduce

1. In a cmd shell, change to the tools directory. 
2. Setup the build environment by running `razzle.cmd`
3. Produce a release build by running `bz.cmd rel`
4. Attempt to run the feature tests: `runft.cmd`
5. Attempt to run the Terminal Core unit tests: `runut /name:TerminalCore*`

# Expected behavior

The tests should run.

# Actual behavior

The feature tests fail with the following errors:
```
Warning: TAEF: The test file "C:\terminal\bin\x64\Debug\ConHost.Feature.Tests.dll" does not exist.
Error: TAEF: None of the specified test files were found.
```

The unit tests fail with the following errors:
```
Warning: TAEF: The test file "C:\terminal\bin\x64\Release\Terminal.Core.Unit.Tests.dll" does not exist.
Error: TAEF: The selection criteria did not match any tests.
Error: TAEF: No test cases were executed.
```

The `runft` error is simply a result of the script being hardcoded to test a `Debug` build.
https://github.com/microsoft/terminal/blob/ae550e0969595f062b15c2ff5cc33d4afe8ebc3f/tools/runft.cmd#L7

We just need to change that `Debug` to `%_LAST_BUILD_CONF%` to make it work with both debug and release builds.

The `runut` error is the result of the path of `Terminal.Core.Unit.Tests.dll` being incorrect.
https://github.com/microsoft/terminal/blob/ae550e0969595f062b15c2ff5cc33d4afe8ebc3f/tools/runut.cmd#L19

That can be fixed by changing that line to:
```
%OPENCON%\bin\%PLATFORM%\%_LAST_BUILD_CONF%\UnitTests_TerminalCore\Terminal.Core.Unit.Tests.dll ^
```

That said, I'm note positive that's the right solution, because it used to work with the current path. I can't remember when exactly it first broke, but I'm assuming it was the result of a change in the project structure. If that change wasn't intentional then maybe it's the project that needs correcting instead of updating the test script.

### PR DESCRIPTION
**Pull request by j4james**
This corrects the path to `Terminal.Core.Unit.Tests.dll` in the `runut`
unit test script and makes the `runft` feature test script capable of
working with _Release_ builds as well as _Debug_ builds.

The path to `Terminal.Core.Unit.Tests.dll` changed when the project was
restructured, and the `runut` script was never updated to reflect that
change. That has now been corrected.

And the `runft` script used to be hard coded to look for tests in the
_Debug_ directory, but it has now been updated to use the
`%_LAST_BUILD_CONF%` environment variable, so it should work for both
_Debug_ and _Release_ builds.

## Validation Steps Performed
I've manually confirmed that the `runut` and `runft` scripts now work as
expected.

Closes #8485

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]
_thank you_

**Review by carlos-zamora — APPROVED** [review]

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in 2 minutes

**Comment by Jspooner09** [comment]
No longer have a computer virus. I am returning message with a small Apple Iphone


Jimmy R. Spooner


CONFIDENTIALITY: The information contained in this transmission may contain privileged and confidential information. It is intended only for the use of the person(s) named above. If you are not the intended recipient, you are hereby notified that any review, dissemination, distribution or duplication of this communication, and the information contained in it, is strictly prohibited. If you are not the intended recipient, please contact the sender and immediately destroy all copies of the original message.



On Thursday, December 3, 2020, 1:29 PM, Carlos Zamora <notifications@github.com> wrote:




@carlos-zamora approved this pull request.

**Comment by Jspooner09** [comment]
I have a computer virus caling on small Apple iPhone


Jimmy R. Spooner4590 Cazes AvenueNorth Port, Fl. 34287Cell 941-894-4722jimmyspooner@yahoo.comjspooner1914@gmail.com

CONFIDENTIALITY: The information contained in this transmission may contain privileged and confidential information. It is intended only for the use of the person(s) named above. If you are not the intended recipient, you are hereby notified that any review, dissemination, distribution or duplication of this communication, and the information contained in it, is strictly prohibited. If you are not the intended recipient, please contact the sender and immediately destroy all copies of the original message.



On Thursday, December 3, 2020, 1:38 PM, msftbot[bot] <notifications@github.com> wrote:




Hello @DHowett!

Because you've given me some instructions on how to help merge this pull request, I'll be modifying my merge approach. Here's how I understand your requirements for merging this pull request:
   
   - I won't merge this pull request until after the UTC date Thu, 03 Dec 2020 18:39:48 GMT, which is in 2 minutes

If this doesn't seem right to you, you can tell me to cancel these instructions and use the auto-merge policy that has been configured for this repository. Try telling me "forget everything I just told you".

**Comment by DHowett** [comment]
@Jspooner09 please leave our repository alone.

**Pull request merged**
