### PR TITLE
Show the context menu verb only when shift key is down

### LINKED ISSUE #6113: The explorer context menu should only appear on shift+click
Follow-up from #6100. 

The Explorer context menu is notoriously cluttered. We shouldn't add to that clutter if we can avoid it. This issue represents me taking the time to investigate how exactly to make the menu only appear on shift+right click, not _just_ right click.

### PR DESCRIPTION
**Pull request by mooons**
## Summary of the Pull Request

- Show the context menu verb only when shift key is down. Not configurable right now. Add a config in the future, maybe?
- Change the verb name a bit to keep it consistent with the existing "Open PowerShell window here". Anyway this should be overridden by #6112 at some point.

 
## References

Related: #8105

## PR Checklist
* [x] Closes #6113
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests ~~added/~~ passed (`Invoke-OpenConsoleTests` Total=329, Passed=329)
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Validation Steps Performed

Haven't found a proper way to test ShellExtension so I went creative: (much appreciated if anybody can point me to the proper way to test this :p)

- Installed Windows Terminal (stable) from Microsoft Store
- Built x64 Release WindowsTerminalShellExt.dll
- Copied built WindowsTerminalShellExt.dll under `C:\Program Files\WindowsApps\`
- (Optional) Copied WindowsTerminal.exe under `C:\Program Files\WindowsApps\` for verb icon
- Under `HKCR\PackagedCom\Package\Microsoft.WindowsTerminal_1.6.10571.0_x64__8wekyb3d8bbwe\Class\{9F156763-7844-4DC4-B2B1-901F640F5155}\`, changed `DllPath` to `..\WindowsTerminalShellExt.dll`
- Manually verified the change in explorer -- works as expected.

In a folder, shift up;
1 in dir shift up

In a folder, shift down:
2 in dir shift down

On a folder, shift up:
3 on dir shift up

On a folder, shift down:
4 on dir shift down

### CODE REVIEW

**Review by zadjii-msft — CHANGES_REQUESTED** [review]
Yea, this is exactly how I'd imagine this would be implemented. I'm gonna block this PR for a bit to give the team a chance to discuss in our next team sync - probably next Monday.

IMO, I definitely want there to be a setting to configure this, since people are totally split on whether they want this to appear on <kbd>Click</kbd> or <kbd>Shift+Click</kbd>. However, we don't have a really good way of configuring settings for the context menu quite yet. Setting up the context menu to be able to read the settings isn't something I'd ask of a community member, but we haven't really committed writing that code to a particular milestone quite yet. So I'm afraid that this PR might sit open for a while while we figure that out. 

The code's totally fine, I just wanted to give you a heads up. Thanks!

**Comment by mooons** [comment]
Thanks @zadjii-msft .

I agree the configurable context menu part can be a bit tricky. From my limited understanding of the code base atm, ShellExtension doesn't seem to like the headers in TerminalSettingsModel right now otherwise it should be possible to allow ShellExtension to read global settings? On DLL load (`WindowsTerminalShellExt.dll`), read config once. Whenever context menu related config changes, save json then reload the DLL.

Or, a `IPropertySetStorage` or something similar could act as a bridge in-between?

Just some random thoughts. :D

**Comment by zadjii-msft** [comment]
Hey so sorry to leave this one on read for so long. Apparently, I never came back and replied to this thread last year when we had this discussion 😕 

IIRC, we were cool with the idea, but concurred that it needed to be something that needed a setting to toggle this behavior. As it stands, there's probably no line-of-sight on actually providing settings for the context menu entry at this time 😢 We've got a lot of cool ideas, just not any time to implement them. At this time last year, I think we were still hoping to get to doing the settings for the context menu a little faster, but alas, changing resourcing and priorities has tossed those plans to the wind.

I also don't want to ask you to try and hook these things up, either. Theoretically, you could just add a project reference to `Terminal.Settings.Model`, and include the settings model header in `pch.h`. That wouldn't be too hard, I don't think, since I _think_ the `WindowsShellExt` project is already using cppwinrt.

My only big worry here is what the perf impact of loading the settings when the context menu is invoked. We'd have to also make sure to obey `fOkToBeSlow`.... It's a lot to ask of an external contributor. I'm certainly willing to help if you'd like to take a crack at it again.

Again, apologies for leaving this on read so long. That's on me.

**Comment by Phroneris** [comment]
So, until this feature is approved, are there any workarounds for users?
How can I edit Registry to do the same?

The known method https://github.com/microsoft/terminal/issues/7008#issuecomment-662621638 removes the menu completely, not just when Shift isn't pressed.

**Pull request closed without merging**
