### PR TITLE
wpf: Make the terminal border fill more visible when the terminal renderer is smaller than the WPF window

### PR DESCRIPTION
**Pull request by javierdlg**
## Summary of the Pull Request
Changed the terminal background to a more visible graphic that uses the terminal foreground/background as the color scheme when the terminal theme is set. 
This is only shown when the terminal renderer is smaller than the WPF view.
image

 
## PR Checklist
* [ ] Closes #xxx
* [ ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Validation Steps Performed
Manual validation.

### CODE REVIEW

**Comment by DHowett** [comment]
nit: please make sure you set a title for your pull request that is short and understandable like an e-mail subject. Pretend that it completes the sentence "This commit will ..."

**Comment by javierdlg** [comment]
Please don't automerge this PR, we're waiting on a final approval by UX.

We are also open to suggestions for the background style

**Comment by DHowett** [comment]
I'm converting this one to a draft until you've got UX approval. Just so nobody can merge it :smile:

**Comment by javierdlg** [comment]
Thanks! I didn't know GitHub had draft PRs

**Comment by zadjii-msft** [comment]
@javierdlg Was this PR superseded by #10026?

**Comment by javierdlg** [comment]
@zadjii-msft indeed! Closing this PR...

**Pull request closed without merging**
