### PR TITLE
Make sure to account for the size the padding _will be_ scaled to

### LINKED ISSUE #2061: Terminal is starting up at a size that's different from initialRows/initialCols
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.264]
Windows Terminal version (if applicable): 8ffff8ea 0.2.1991.0
Any other software? WSL
```

# Steps to reproduce

The relevant-looking parts of profiles.json are:

```
{
    "globals" : 
    {
        "defaultProfile" : "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
        "initialCols" : 80,
        "initialRows" : 40,
    },
    "profiles" : 
    [
        {
            "commandline" : "wsl.exe -d Ubuntu-18.04",
            "fontFace" : "DejaVu Sans Mono for Powerline",
            "fontSize" : 9,
            "guid" : "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
            "padding" : "0, 0, 0, 0"
        }
    ]
```

# Expected behavior

I should see an 80x40 terminal.

# Actual behavior

I get an 80x37 terminal, with extra blank horizontal space after the last usable column:

image

### PR DESCRIPTION
**Pull request by zadjii-msft**
* [x] Fixes #2061 for good this time

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
@msftbot merge this in 2 minutes

**Comment by RaviiKmr** [comment]
Is the fix only available in the preview build? If yes then when will this be updated to the non preview build?

**Comment by DHowett** [comment]
@RaviiKmr This was fixed and released before 1.0 came out, so it should be in 1.0. What makes you think you're seeing the issue fixed by this PR?

**Comment by RaviiKmr** [comment]
@DHowett Sorry, I didn't see that.

**Pull request merged**
