### PR TITLE
Add an updated roadmap

### LINKED ISSUE #12082: Updates to Terminal repo milestones, 2022 edition
The Terminal repo right now consists of a collection of various different "milestones" that have evolved organically over the years. We've got Console milestones, we've got Terminal milestones, we have milestones that vaguely align with OS releases, and then we've got like, four different milestones that are all the "backlog" in one way or another ("Console Backlog", "Terminal Backlog", "Windows vNext", and "Icebox"). All together, they don't create a very clear picture of what's going on in the Terminal land. To try and clear this up, we're going to de-duplicate some of these, and try something new for 2022. 

* The "Console Backlog" and the "Terminal Backlog" are both getting deprecated. They'll be collectively replaced with just a unified **"Backlog"** milestone, which will track things we'd like to get to, but we don't have any time planned for. 
* "Windows vNext" is also being deprecated. Originally, it was a rolling milestone to track things that should be in "the next version of Windows". Unfortunately, it wasn't tracked super well, so it's effectively become a second Console Backlog.
* We're going to use four milestones for tracking bits of the next _year_ of planning. These are separated into two "release" milestones, and two "semester" milestones.
  - **"Terminal v1.{n}"** (as of when this was written, this is v1.13): Shots we're calling for the upcoming release. Features & tasks we expect to land, blocking bugfixes, or other high-pri fixes
  - **"Terminal v1.{n+1}"** (currently, v1.14): Same as above, for the following release. With two 6-week release milestones, this is about 3 months of planning. This is a useful buffer for "we really should do this SOON, but not ASAP. 
  - **"22H1"** will represent the first 6 months of 2022. This will help align internally with the OS release cadence. 
    - If there are `conhost` bugs that need to get fixed in the upcoming release of Windows, then they go here. 
    - Accessibility bugs will also go here, or into the current semester. 
  - **"22H2"** is the same idea. A planning buffer for the second half of 2022. This includes Terminal features we expect to land in the second half. 
    - Terminal P2+ bugs will go here. 
* Terminal v2, Console Backlog, Terminal Backlog, Windows vNext are all going to be emptied into "22H1", "22H2", and the "Backlog", based on current priority labels. 
* We're also going to rename "Terminal v3" to **Up Next"**. This is for features, we think are highest on the backlog. The next big set of features we want to work on. Things that should be at the top of our list to fill up the upcoming semester.
* We're leaving the **""Icebox"** as-is right now, albeit, possibly workshopping the name in the near future. This will remain for features that we think are cool, valid feature requests for the Console&Terminal. However, we'll admit we're never going get to these features.   We'd likely accept PRs from the community for things in here. 
* We had a really successful **"Engineering Improvements"** milestone over the last few weeks, so we'll probably try that again next year. At the end of each year, I'll just move the closed issues in the EIM milestone to a specific "Engineering Improvements {current_year}" milestone. 

We're intentionally not planning out more specifically that 1.n and 1.n+1 - we're generally a fairly responsive team, where priorities can shift quickly during the course of the year. Trying to lick cookies for specific milestones more than 3 months out has generally been an exercise in futility. 

As always, as priorities shift, and resourcing changes, issues can move between these milestones fluidly. 

Hopefully, by grouping bugs into semester-sized milestones, we can address some of them in a timelier fashion. Currently, they just get stuck into "Terminal v2", which we've been pulling features and tasks into as well, which has only created a longer bug backlog 😄.

I'll be going through and moving our issues into this new structure likely sometime early in 2022. 

If this doesn't end up working, we'll take our learnings and try something else for 2023 😄

### PR DESCRIPTION
**Pull request by zadjii-msft**
To reflect changes to the repo for the new year. 

* [x] Closes #12082, since I'm done re-organizing those now.

### CODE REVIEW

**Review by miniksa — APPROVED** [review]
I agree with this roadmap for the most part so I'm signing off. 

I wonder if some clarity is due on why we need to align with semesters (that is, because our paychecks come out of the Windows organization and this Terminal product is consumed as a preinstall app in the Windows product... therefore we have to occasionally align to meet those large-product tolerances and schedules). Do we think that would help folks understand the rationale for our decisions and priorities? Or add unnecessary complexity that is really an Us Problem and not a Community Problem?

**Comment by zadjii-msft** [comment]
> clarity is due on why we need to align with semesters

That's a fair concern. I suppose in the past, the Console repo was always aligned with Windows releases, then when we became the Terminal repo we kinda threw that to the wind. Since probably 99% of folks following the repo aren't familiar with that history, there's probably no harm in calling it out. I'll add an update with the spellcheck.

**Review by carlos-zamora — APPROVED** [review]
Looks good to me!

FYI @cinnamon-msft since this is a good resource to be aware of

**Comment by DHowett** [comment]
It looks like there's a lot of 2021 dates in here still -- on purpose?

**Comment by zadjii-msft** [comment]
> It looks like there's a lot of 2021 dates in here still -- on purpose?

I just left the previous releases in the table. Seemed like it wasn't a bad idea. We don't have any 2022 releases yet, so we can just remove them whenever we have a 2022 release (and update this doc 😛 )

**Pull request merged**
