### PR TITLE
Update the Theme schema for 1.17

### LINKED ISSUE #14560: [1.17] `theme` schema needs updating
GetImage (4)

### PR DESCRIPTION
**Pull request by zadjii-msft**
What it says on the tin. 

I finally figured out the right way to validate schema updates in VsCode, which made this a lot faster. Tossed notes in the wiki for next time I do this. 

Closes #14560

### CODE REVIEW

**Review by DHowett — APPROVED** [review]
Thanks! Can I bother you for a version of this that is true to 1.16's theme code as well? :D

**Comment by zadjii-msft** [comment]
whoops never hit send

image

**Comment by zadjii-msft** [comment]
> Thanks! Can I bother you for a version of this that is true to 1.16's theme code as well? :D

I think the only new thing is `useMica` so that should be easy

**Review by carlos-zamora — APPROVED** [review]
_Now_ I feel comfortable using themes haha. Thanks!

**Pull request merged**
