### PR TITLE
Add an enum-compatible bitset class.

### LINKED ISSUE #10432: Consider introducing an enum-compatible bitset class
# Description of the new feature/enhancement

I'm working on something at the moment where I need to manipulate various flag values. Typically we do this with an enum and a bunch of macro helper functions like `WI_SetFlag`, and `WI_IsFlagSet`. However, I found some scenarios that didn't work very well with this approach, and I was wondering if it might be better achieved with a `std::bitset`. Unfortunately a `std::bitset` isn't that great when working with enum values either, but I figured we could perhaps create a lightweight `til` template class that extends `std::bitset` with better enum support.

# Proposed technical implementation details (optional)

The main things I want to achieve with this class are:
1. Being able to use `enum class` values as parameters without having to cast them to a `size_t` first. This would require extended versions of `set`, `reset`, `flip`, and `test` which accept the enum type for the _pos_ parameter.
2. Being able to initialize the bitset with one or more enum values instead of an integer with the appropriate bits set. This can be achieved with a variadic template constructor.
3. Being able to set or reset multiple values at the same time. This would require additional methods named something like `set_all` and `reset_all`, again using a variadic template to support multiple parameters.
4. Being able to easily test multiple values at the same time. Something like `test_any` or just `any` to test if any of the given values are set, and `test_all` or `all` to test if all values are set.

I've got a WIP implementation which I've been using in my own code and also tested as a replacement for the current `GridLines` implementation in the renderer, and I think it does make the code slightly more readable. Would you be interested in a PR for this?

### PR DESCRIPTION
**Pull request by j4james**
## Summary of the Pull Request

This introduces a new TIL class that is equivalent in functionality to a `std::bitset`, but where the positions in the bitset are enum values. It also has a few additional methods allowing for setting and testing multiple positions at the same time. The idea is that this class could be used in place of the `WI_SetFlag` and `WI_IsFlagSet` macros when working with sets of flags.

## PR Checklist
* [x] Closes #10432
* [x] CLA signed.
* [x] Tests added/passed
* [ ] Documentation updated.
* [ ] Schema updated.
* [x] I've discussed this with core contributors already. Issue number where discussion took place: #10432

## Validation Steps Performed

I've added a few unit tests that verify the behaviour of all the new methods that aren't part of `std::bitset`. I've also tried it out as a replacement for the `GridLines` enum used in the renderer, and confirmed that it has all the functionality needed to replace that cleanly.

### CODE REVIEW

**Comment by lhecker** [comment]
What's the reason this class extends `std::bitset` instead of just having a single `Type _data;` field? Because of conveniency (...which would be quite understandable)?

While `std::bitset` _usually_ compiles the parameters given to it into constants during compilation, this isn't always the case. Not relying on `std::bitset` would allow us to compile the class to efficient assembly in all cases.

Here's a comparison of the assembly with and without `std::bitset` for a "dynamic" positional parameter: https://godbolt.org/z/cv6c8z31v
You'll have to ignore the first definition for `custom<custom_enum>::set(custom_enum,bool)`, as that one isn't used by either of the 2 functions that follow. `custom_dynamic` compiles to just 6 basic instructions and to 0 stack allocations. Please don't ask me why `bitset_dynamic` allocates 40 bytes on the stack. MSVC is just confusing. 😐

**Comment by j4james** [comment]
> What's the reason this class extends `std::bitset` instead of having a single `Type _data;` field? Because of conveniency (...which would be quite understandable)?

Yeah. I didn't really want to reinvent the wheel. I just wanted a light-weight wrapper of `std::bitset` which let me use enums for the position parameters. And while I know the assembly produced can be awful at times, it was OK for most of the common cases. It also has the advantage that it can handle larger sizes if needed later, although that's admittedly not that likely.

That said, if you're volunteering to put together a better solution than this, I'd be happy to let you take over. I just needed a quick replacement for the macros (which simply don't work in certain situations), so I could move on with the work I was originally trying to do.

**Comment by j4james** [comment]
I should also mention that the reason I've left this as a draft is so I could spend more time using it and see if it actually does meet my needs. And if the stuff I'm working on turns out to be a complete disaster, I might just give up on everything anyway, in which case there's no real need for this (although I do still think it would be nice to cut down on our macro usage regardless).

**Comment by lhecker** [comment]
I've hacked this together today: https://gist.github.com/lhecker/95a9c54c6d51a30c68099a4b37511b40
Thanks to the lack of a boolean parameter for `set()` it now compiles directly down to the `bts` (bit test and set) instruction. Neat! But we'll have to see if it'll be useful as well. 😄

**Comment by j4james** [comment]
> Thanks to the lack of a boolean parameter for `set()` it now compiles directly down to the `bts` (bit test and set) instruction.

That is very cool, but we definitely also need a version of set that takes a bool, even if it has to be handled as a special case.

Also note that the data type is not necessarily the underlying type of the enum. You can easily fit 64 values in a byte enum, but that's going to require a 64-bit data type for the bitset.

**Review by zadjii-msft — APPROVED** [review]
This seems cool to me. If this ends up working for you, then let's ship it.

**Review by carlos-zamora — APPROVED** [review]
This is awesome!

**Review by MrGolden1 — APPROVED** [review]

**Comment by miniksa** [comment]
Two approvals but it's still draft. @j4james... do you want to bring this in?

**Comment by j4james** [comment]
@miniksa I'm happy to have it merged as it is (well once I've rebased to fix the conflicts), but the code I was planning to use it with hasn't really got anywhere and I kind of put it on hold to play with Sixel for a while. I'm hoping to get back to it eventually, but in the meantime I thought you probably wouldn't want this in the code base when it wasn't actually being used anywhere.

**Comment by miniksa** [comment]
Eh, since it's tested and _you_ plan to use it, @j4james, I trust you'll get back to it. We can bring it in. I'm just trying to trim the PR queue down so it's maybe not so intimidating when we go look at it. :)

**Comment by j4james** [comment]
I've rebased and marked it ready for review now. Feel free to merge whenever you want. Worst case, if it doesn't get used, someone in the future will have the joy of deleting two files. 😉

**Pull request merged**
