### PR TITLE
Update tab hover colors

### PR DESCRIPTION
**Pull request by dansmor7**
The hover tab color used to be generated from the selected tab color, which would end up lighter or darker, and white-gray colors would end up pink.
It is now simply the selected tab color with 60% opacity. This is also how brushes are created for accent buttons and color buttons (although with different opacity levels).

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]
:chef_kiss:

**Review by DHowett — APPROVED** [review]
I love it. Thanks!

**Comment by DHowett** [comment]
@zadjii-msft /propose 1.15

**Comment by zadjii-msft** [comment]
meh, I haven't checked this out locally, just the code eyeball test. Lemme give it a once over before I give it the 1.15 👍

**Comment by zadjii-msft** [comment]
# :shipit:

**Comment by DHowett** [comment]
Ah, very cool. How does it look now with the slightly modified opacity values, as well?

**Comment by DHowett** [comment]
Images removed from body of PR


Normal/hover/selected, before/after:
image
image

**Comment by dansmor7** [comment]
image

I'm not sure if it's better. I thought it wasn't colorful enough, but now it's too similar to the selected tab.
And the unselected tab is also a bit too colorful.

**Comment by DHowett** [comment]
I'm actually okay with these options. Custom tab colors are already pretty niche, and folks probably won't be keeping a bunch of tabs _of the same color_ next to each other long enough to be annoyed by the similarity.

@zadjii-msft, what do you think about the new ramp?

**Comment by zadjii-msft** [comment]
I only tested the new ramp, and it seemed good to me TBH.

**Comment by DHowett** [comment]
I'll merge this now for 1.15's cut. @dansmor7, if you want to play with it some more I'm happy to bring that into 1.16 or a later servicing release of 1.15. Thanks for the really quick feedback loop! :)

**Pull request merged**
