### PR TITLE
Add Dark+, CGA and IBM color schemes

### LINKED ISSUE #6176: Add Dark+
# Description of the new feature/enhancement

VSCode's theme, **Dark+**, is absolutely gorgeous.

VSCode Neofetch

I think it would be totally appropriate to add it to the default schemes.

image

# Proposed technical implementation details (optional)

```jsonc
{
    "name": "Dark+",
    "foreground": "#cccccc",
    "background": "#1e1e1e",
    "cursorColor": "#cccccc",
    "black": "#000000",
    "red": "#c62f37",
    "green": "#37be78",
    "yellow": "#e2e822",
    "blue": "#396ec7",
    "purple": "#b835bc",
    "cyan": "#3ba7cc",
    "white": "#e5e5e5",
    "brightBlack": "#666666",
    "brightRed": "#e94a51",
    "brightGreen": "#45d38a",
    "brightYellow": "#f2f84a",
    "brightBlue": "#4e8ae9",
    "brightPurple": "#d26ad6",
    "brightCyan": "#49b7da",
    "brightWhite": "#e5e5e5"
}
```

### LINKED ISSUE #16754: Add color scheme for EGA (the "16 color ANSI" palette)
# Description of the new feature/enhancement
The 16 color standard EGA palette used on PCs back in the day was a very defining look (and still in use today for the correct look of DOS CLI/TUI programs and ANSI art etc), and I think it should definitely be a default colorscheme that comes with Windows Terminal.

# Proposed technical implementation details (optional)

Add a default color scheme (call it "EGA" or "ANSI" or "MS-DOS" or whatever):

```json
{
    "background": "#000000",
    "black": "#000000",
    "blue": "#0000AA",
    "brightBlack": "#555555",
    "brightBlue": "#5555FF",
    "brightCyan": "#55FFFF",
    "brightGreen": "#55FF55",
    "brightPurple": "#FF55FF",
    "brightRed": "#FF5555",
    "brightWhite": "#FFFFFF",
    "brightYellow": "#FFFF55",
    "cursorColor": "#00AA00",
    "cyan": "#00AAAA",
    "foreground": "#AAAAAA",
    "green": "#00AA00",
    "name": "16 Color ANSI",
    "purple": "#AA00AA",
    "red": "#AA0000",
    "selectionBackground": "#FFFFFF",
    "white": "#AAAAAA",
    "yellow": "#AA5500"
}
```

### PR DESCRIPTION
**Pull request by zadjii-msft**
As discussed in #6176 and #16754. 

The "CGA" and "IBM 5153" names I'm told are the right ones to use: https://github.com/microsoft/terminal/issues/16754#issuecomment-2024066880

Closes #6176 
Closes #16754

### CODE REVIEW

**Comment by zadjii-msft** [comment]
new-color-schemes

**Review by lhecker — APPROVED** [review]

**Comment by DHowett** [comment]
Qs:

## Dark+

Does Dark+ not differentiate bright colors from dark colors? How should this work with bold=intense?

## CGA, EGA, IBM, VBA, SiS S3

I know I am a heathen, but... I can't tell the difference between all these new schemes and, like, Vintange. _And I am saying this as someone who has his own nearly identical scheme, URXVT:_ image

**Comment by zadjii-msft** [comment]
> Does Dark+ not differentiate bright colors from dark colors? How should this work with bold=intense?


color  | normal       | bright
------ | ------------ | ------------
black  | `#000000`    | `#666666`
red    | `#cd3131`    | `#f14c4c`
green  | `#0dbc79`    | `#23d18b`
yellow | `#e5e510`    | `#f5f543`
blue   | `#2472c8`    | `#3b8eea`
purple | `#bc3fbc`    | `#d670d6`
cyan   | `#11a8cd`    | `#29b8db`
white  | `#e5e5e5`    | `#e5e5e5`

those are literally different colors

**Comment by zadjii-msft** [comment]
> . I can't tell the difference between all these new schemes and, like, Vintange


From the thread: 

image

CGA left, vintage right. 

I'm a man of the people, but I also don't _super_ care. Dark+ I think we definitely should add inbox (because it's the vscode scheme), but I'm also thinking that maybe we should just have a "schemes" extension we publish with _everything_ lmao

**Comment by DHowett** [comment]
> those are literally different colors

Man, that is SUBTLE.

**Review by DHowett — APPROVED** [review]

**Pull request merged**
