### PR TITLE
Switch all DSR responses to appending instead of prepending

### LINKED ISSUE #1637: Automatically triggered Replace mode using vim in OpenSSH on cmd / powershell though Windows Terminal
Replace input mode will triggered automatically when using vim though OpenSSH Client in cmd.

# Environment

```none
Windows build number: [Version 10.0.18362.175]
Windows Terminal version (if applicable): 0.2.1715.0

Remote Linux PC: Ubuntu LTS 1604

OpenSSH Client: Stock version in Windows 10 1903 Build 18362.175
```

# Steps to reproduce

1. Open Windows Terminal
2. Open new tab running cmd / powershell / powershell 6
3. ssh to a Ubuntu 1604 LTS PC
4. Open any document using vim

# Expected behavior

Not trigger any input mode, the status bar at the bottom displays the path of the file that vim opened.

# Actual behavior

Triggered Replace input mode.

### PR DESCRIPTION
**Pull request by DHowett**
This fixes an issue where two CPRs could end up corrupted in the input
buffer. An application that sent two CPRs back-to-back could
end up reading the first few characters of the first prepended CPR
before handing us another CPR. We would dutifully prepend it to the
buffer, causing them to overlap.

```
^[^[2;2R[1;1R
^^      ^^^^^ First CPR
  ^^^^^^ Second CPR
```

The end result of this corruption is that a requesting application
would receive an unbidden `R` on stdin; for vim, this would trigger
replace mode immediately on startup.

Response prepending was implemented in !997738 without much comment.
There's very little in the way of audit trail as to why we switched.
Michael believes that we wanted to make sure that applications got DSR
responses immediately. It had the unfortunate side effect of causing
subsequence CPRs across cursor moves to come out in the wrong order.

I discussed our options with him, and he suggested that we could
implement a priority queue in InputBuffer and make sure that "response"
input was dispatched to a client application before any application- or
user-generated input. This was deemed to be too much work.

We decided that DSR responses getting top billing was likely to be a
stronger guarantee than most terminals are capable of giving, and that
we should be fine if we just switch it back to append.

Thanks to @k-takata, @tekki and @brammool for the investigation on the
vim side.

Fixes #1637.

### CODE REVIEW

**Comment by DHowett** [comment]
I know @zadjii-msft is on leave, but he's been floating around and may be peripherally interested in this. :smile:

**Review by miniksa — APPROVED** [review]
Yep, just as we discussed.

**Comment by DHowett** [comment]
@msftbot merge this in 1 hour

**Review by carlos-zamora — APPROVED** [review]

**Comment by FremdSprach** [comment]
Great work!

BTW, how soon will there be a fixed release? The milestone page says there would be a bug-fixed release "Push to Microsoft Store at end of week 3". 3rd week monthly? so I guess it's around Sep 19?

**Comment by bendem** [comment]
Thank you so much for this, you guys are the best ! ❤️

**Comment by DHowett** [comment]
For those of you who are still following along at home, this fix was too late for Windows 10. Windows Server 2022 and Windows 11 both have the fix and the SSH server will operate properly.

We're looking at our options for making these kinds of fixes available to all versions of Windows in the future. 🙂

**Pull request merged**
