### PR TITLE
Update to the latest MUX prerelease (2.3.191217003)

### LINKED ISSUE #3300: Tab bar doesn't grow when you resize the window, it only shrinks
Open a number of tabs. Make the window narrower. Make it wider again.

It looks like this:

image

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

This latest MUX prerelease fixes the issue where the tab row wouldn't expand to fill the width of the window after shrinking the window size.

## PR Checklist
* [x] Closes #3300
* [x] I work here
* [n/a] Tests added/passed
* [n/a] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments

Thanks again @teaP for help fixing this

## Validation Steps Performed

Launched the terminal, played with it a bit

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Wow, and there's no other issues switching to 2.3?

**Comment by zadjii-msft** [comment]
@DHowett-MSFT Sure didn't seem like there was...

**Comment by DHowett-MSFT** [comment]
FWIW: this isn't actually a prerelease in anything but name. It's a full normal build from their release branch, but in the mode that makes it put the DLLs into our package :smile:

**Comment by miniksa** [comment]
@msftbot wait 3 seconds before merging

**Comment by miniksa** [comment]
@msftbot don't wait to merge

**Comment by miniksa** [comment]
@msftbot go jump in a lake

**Comment by miniksa** [comment]
@msftbot delay merging this pull request for 1 min

**Pull request merged**
