### PR TITLE
Make panes use XAML star sizing

### LINKED ISSUE #3744: Sometimes panes won't expand and take up blanks
# Environment

```none
Windows build number: 18363.476
Windows Terminal version (if applicable): 0.7.3291.0
```

# Steps to reproduce
1. create lots of split panes and resize some panes.
2. run `exit` on some of panes to close some panes.
3. sometimes other panes won't take up the spaces of closed panes.

# Expected behavior
Other panes should take up the blank space of the window after I close some panes.

# Actual behavior
The blank spaces still leave blank.
image
image

However, if you resize the window, the panes will return to normal.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
Dustin and Mike had a discussion on star sizing. Mcpiroman connected the dots. I just swooped in and implemented it.

## References
https://github.com/microsoft/terminal/issues/3996#issuecomment-566676111
https://github.com/microsoft/terminal/issues/3744#issuecomment-568926636

## PR Checklist
* [X] Closes #3744

## Detailed Description of the Pull Request / Additional comments
Star sizing allows us to keep things proportional. Since a 1::1 proportion is the same as a 100::100 proportion, I just went in and added star sizing. In the words of a some dude with a big metal fist, everything is perfectly balanced now.

image

## Validation Steps Performed
Verified for vertical, horizontal, and uneven splits.

### CODE REVIEW

**Comment by carlos-zamora** [comment]
After looking at it for a while, I think it's not worth it. We calculate the minimum size of each pane (and snap it to the text buffer grid) using pixels. We could probably rewrite all of that to just create a ratio. But that's risky and not really worth it.

Also, I could be wrong about this, but I'd imagine it's not a huge perf impact anyways.

**Comment by DHowett-MSFT** [comment]
I was less worried about perf and more worried about how when we start up the terminal our size is 0x0 and when we try to do math on that we hyperexplode :smile:

**Comment by DHowett-MSFT** [comment]
(This is why new-tab and split-pane "defer" their execution, in part)

**Comment by carlos-zamora** [comment]
Ewwww. So you're worried about `0*` being passed over to xaml?

**Comment by DHowett-MSFT** [comment]
I'm not worried about 0 being passed to xaml, I'm more worried about us saying "our size was 0, and we have a 4-pixel pane separator, so your size is -4 and YOUR size is -4, good luck"

then xaml explodes us
for good reason

**Comment by mcpiroman** [comment]
Oh, well I only wrote that this *seems* like a perfect solution. But then I realized that it is not and I was about to comment it, and then I ended up seeing that this got merged and I that I apparently forgot about it ;). So because of the snapping and 0-size issues it may actually be easier to adjust the size manually. Especially with #4068, there will be an event in a parent pane that one of the children got closed, so we could just set it the size of ourself here and be done.

**Pull request merged**
