### PR TITLE
Teach the command palette to clamp its indices on page up/down

### LINKED ISSUE #8189: Command Palette: page up/down "wrap" backwards when you're too close to the bottom of the list
We may need to clamp the index when moving down/up.

A video of me reproducing the issue.

/cc @Hegunumo

### PR DESCRIPTION
**Pull request by Don-Vito**
This commit will teach CommandPalette to clamp the scroll page up and
scroll page down navigation so as to not wrap.

Closes #8189

### CODE REVIEW

**Comment by Hegunumo** [comment]
It looks good to me!

**Comment by Don-Vito** [comment]
> 
> 
> It looks good to me!

@Hegunumo - thanks a lot!

**Review by zadjii-msft — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
Love this approach. Thanks!

**Comment by DHowett** [comment]
Oi, there's a conflict now!

**Comment by Don-Vito** [comment]
> 
> 
> Oi, there's a conflict now!

Solving it at this moment 😊

**Review by DHowett — APPROVED** [review]

**Pull request merged**
