### PR TITLE
Remove deprecated Windows Terminal Universal project

### LINKED ISSUE #12118: Pull Terminal Universal
We no longer have images that consume this package. As such, pull it from the build process.

### PR DESCRIPTION
**Pull request by miniksa**
Remove deprecated Windows Terminal Universal project

## PR Checklist
* [x] Closes #12118 
* [x] I work here

### CODE REVIEW

**Comment by DHowett** [comment]
You may want to grep the codebase for WindowsTerminalUniversal. There's a few in the pipelines!

**Comment by DHowett** [comment]
HOW DID I MISS YOU DOING THAT sorry

**Review by DHowett — APPROVED** [review]

**Comment by miniksa** [comment]
> You may want to grep the codebase for WindowsTerminalUniversal. There's a few in the pipelines!

I did something significantly less slick than "grep" and did <key>Ctrl+Shift+F</key> in `vscode`... but yeah.

**Review by zadjii-msft — APPROVED** [review]
You'll be missed

OH WAIT OH WAIT no, you won't.

**Pull request merged**
