### PR TITLE
spelling: attribute

### PR DESCRIPTION
**Pull request by jsoref**
## Summary of the Pull Request

split out per @miniksa 

## References

https://github.com/microsoft/terminal/pull/4295#pullrequestreview-353162609

## PR Checklist
* [ ] Closes #xxx
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

### CODE REVIEW

**Comment by miniksa** [comment]
Attempting this right now on the Windows side in `user/miniksa/spelling`...

**Comment by miniksa** [comment]
This is now MSFT:25154975

**Comment by miniksa** [comment]
Committed today in PR:4297546 on the inside. @DHowett-MSFT will replicate it out and then this PR can probably be closed.

**Comment by DHowett-MSFT** [comment]
Ugh: I misspelled it in the commit message. This merged in with bb4cd6488. Thanks for your patience!

**Comment by jsoref** [comment]
That's ok, the commit message for the original spelling PR is also pretty embarrassing. I didn't really expect the bot to take the description as the commit message (it had a note which was no longer applicable).

**Comment by DHowett-MSFT** [comment]
Yeah, that's something we can always do with more work on. :smile:

**Pull request closed without merging**
