### PR TITLE
Add Elevate flag to the SUI

### PR DESCRIPTION
**Pull request by zadjii-msft**
Does what it says on the box

image

* [x] I work here
* [x] Discussed in OneNote

### CODE REVIEW

**Comment by zadjii-msft** [comment]
May conflict with the other SUI PRs. Go do those first you barbarians!

#11720 and #12144

**Comment by ianjoneill** [comment]
A related question now that this is included in the SUI:

Is there any reason why the `elevate` flag isn't duplicated when a profile is duplicated? (I thought maybe it wasn't included previously as it wasn't in the SUI)

If it should be, I think it's a one-line fix, adding it around here, which I can do if you like 🙂 
https://github.com/microsoft/terminal/blob/fe52368f9b76b9f29494b332f586c16504620e2a/src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp#L283-L297

**Comment by zadjii-msft** [comment]
@ianjoneill yes please submit a PR for that. That was an oversight, I believe that the original elevate PR even predates duplicating profiles by a good amount 😅

**Comment by DHowett** [comment]
> @ianjoneill yes please submit a PR for that. That was an oversight, I believe that the original elevate PR even predates duplicating profiles by a good amount 😅

How did the X macros for settings not help this?

**Comment by zadjii-msft** [comment]
> How did the X macros for settings not help this?

Apparently we didnt use the macro for that one!

`UseAtlasEngine`, `BellSound`, and `Elevate` are all missing from the duplicate. Connection type too, but that one's... tricky maybe. `Opacity` is duplicated, but it's not otherwise in the appearance macro. Uh oh.

**Review by miniksa — APPROVED** [review]

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@PankajBhojwani make sure that you get this one merged in!

**Comment by DHowett** [comment]
@msftbot merge this in 5 minutes

**Pull request merged**
