### PR TITLE
Add `openTabRenamer` action

### PR DESCRIPTION
**Pull request by Coridyn**
Adds a `ShortcutAction` to allow editing the tab title via the TextBox
(just like double-clicking the tab, but triggered from a key binding or
command palette).

* This implements "scenario 3" outlined in zadjii-msft's comment:
  https://github.com/microsoft/terminal/pull/6557#issuecomment-646153274

* The `openTabRenamer` action name is taken from the discussion in this
  PR:
  https://github.com/microsoft/terminal/pull/6567#issuecomment-646319010

Related to #6256 (but doesn't address pane renaming)

### CODE REVIEW

**Comment by Coridyn** [comment]
Sorry, there are two items that I don't know how to address:


1. Cannot trigger tab renaming from the command palette because the "enter" keyup event from the palette is also sent to the edit textbox, closing it immediately

- Steps to replicate:
  - open command palette (Ctrl+Shift+P)
  - search for "rename" and highlight the new "Rename tab title..." action
  - hit enter to activate the tab rename action
  - note that the rename textbox is shown but then immediately removed because it receives the "enter" event from the command palette


2. Focus is set to the "New Tab" button after the rename textbox is removed (either by hitting enter or escape)
  - it would be nice to have focus return back to the console
  - I've noted this same behaviour also happens when the rename was triggered by double-clicking on the tab title, so it might be out of scope of this item and should be handled in its own issue?
  

------------------------------------------------


For item 1 the only thing I can think of is to add a `KeyDown` listener and flag variable so we only process the `KeyUp` event if it was preceded by a `KeyDown`, something like this:


```
// We'll only process KeyUp event if `receivedKeyDown` is true
auto receivedKeyDown = false;
tabTextBox.KeyDown([&receivedKeyDown](const IInspectable&, Input::KeyRoutedEventArgs const&) {
    receivedKeyDown = true;
});

tabTextBox.KeyUp([weakThis, &receivedKeyDown](const IInspectable& sender, Input::KeyRoutedEventArgs const& e) {
    auto tab{ weakThis.get() };
    auto textBox{ sender.try_as<Controls::TextBox>() };
    if (tab && textBox && receivedKeyDown)
    {
        // ...
    }

    receivedKeyDown = false;
});
```

But that doesn't seem very nice.

Otherwise, is there is some way to only add the `tabTextBox` to the `tabViewItem` after the KeyUp has been processed, or to know which control raised the `KeyUp` event?

**Comment by zadjii-msft** [comment]
Hey sorry, just getting back from leave now and catching up on older PRs. As far as the focus issues are concerned, you've stumbled into one of the horrible bug factories of this project I'm afraid 😬 See #6680 for more details.

Your proposed solution to issue 1 seems sensible to me. A bit hacky, but everything we're doing with focus is a tad bit hacky, and that doesn't seem any worse. I'm a tad bit worried about `receivedKeyDown` being a stack variable - I think it'll work fine if we make that a member of `Tab` instead, and reset it when the renamer is first opened. 

As far as issue 2 goes, since that's already existing behavior, I wouldn't worry about it too much during this PR. we can always punt that to a future bugfix.

Other than that, there have been some settings changes recently, so you'll need to do a merge from master, but it _should_ just be re-namespacing things.

**Review by zadjii-msft — COMMENTED** [review]
Other than doing that keyup thing you mentioned earlier, and merging with `master`, the rest of this looks great!

**Comment by Coridyn** [comment]
Thanks for the feedback on this.

I'll make `receivedKeyDown` a member variable and see how it goes - you're right it didn't work as a stack variable 😅

**Comment by Coridyn** [comment]
This has been rebased onto main and I've been able to try it out locally.

Implementing the `_receivedKeyDown` flag has fixed the issue with the text box closing immediately from the command palette.

**Comment by zadjii-msft** [comment]
@Coridyn Thanks! I'll try and take a look at this tomorrow morning. In the meantime, don't worry about the linter error - it's being a tad aggressive and we're still trying to figure out the right balance here. We'll probably push an update to `main` that disables the json linting, so just hang tight ☺️ 
/cc @DHowett who might be able to disable the linter while I'm out today

**Review by zadjii-msft — APPROVED** [review]
This looks good to me, thanks for throwing this together!

**Comment by zadjii-msft** [comment]
Oh hey don't worry about the linter error - that's just the linter being a little over-zealous while we calibrate it the way we'd like. I'll take care of that.

**Review by DHowett — APPROVED** [review]
This is lovely. Thanks for working on it, and sorry we took forever to review it!

**Comment by yasintz** [comment]
👏 👏

**Comment by Coridyn** [comment]
Awesome, thanks for your help @zadjii-msft and @DHowett!

**Pull request merged**
