### PR TITLE
Add schema check to PR template

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
We need to do a better job of updating the schema as we go. I'm hoping this might help a bit.

### CODE REVIEW

**Comment by cinnamon-msft** [comment]
Maybe phrase it to have people confirm they updated it?

**Comment by carlos-zamora** [comment]
Umm... I literally replaced the word "documentation" with "schema"... What were you (plural) thinking?

**Comment by cinnamon-msft** [comment]
Probably lines 12 and 13

**Comment by carlos-zamora** [comment]
> Probably lines 12 and 13

I know the lines haha. I meant the wording!

**Comment by carlos-zamora** [comment]
> Whatever. I'm not gonna block this on grounds of ideology.
> 
> I don't think it's necessary to have "i updated the docs" or "i updated the schema" as a first-order bit on our pull request checklist. Most of my changes don't _need_ to do either of those things, but if I don't check them off my pull request looks like this:
> 
> ```
> 3 of 8 checked.
> ```
> 
> If I delete the ones that don't matter to me, it looks like this
> 
> ```
> 3 of 3 checked.
> ```
> 
> which, yes, measures "completeness" to some rough approximation. I also think we're not looking at those checklists at all, and they are just something for the filer to handle.
> 
> Maybe we should get rid of CLA checkbox (the bot handles this) and "I've discussed this with the team" (it looks user-hostile to say up front "we could close this for no reason, whatever" and we've _never_ availed ourselves of that option through explicit callout)

The thing is, I think at the very least we need _something_. The template works great for bugs, but I agree that it's not ideal for PRs. Does anybody know how other repos handle this issue?

**Pull request merged**
