### PR TITLE
winconpty: close the pty host handle after terminating it

### LINKED ISSUE #8706: WT doesn't close process handles to openconsole.exe
# Environment
Microsoft Windows 10 Pro for Workstations
10.0.19042.685 (2009, 20H2)
WindowsTerminalPreview_1.5.3242.0_x64

Release version does it too.
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
Monitor WT's open "Process" handles while opening/closong new tabs or panes.

# Expected behavior
WT will close its newly acquired handle to OpenConsole.exe 

# Actual behavior
WT does not close the handle

Using HANDLE64.EXE (Sysinternals, could also use their ProcessExplorer) ...

```
v:\> rem New Instance

v:\> handle64 -a -p windowsterminal.exe | findstr Process
  9DC: Process       OpenConsole.exe(10016)
  A04: Process       cmd.exe(3136)

v:\> rem Open a second tab

v:\> handle64 -a -p windowsterminal.exe | findstr Process
  9DC: Process       OpenConsole.exe(10016)
  A00: Process       OpenConsole.exe(9848)
  A04: Process       cmd.exe(3136)
  AC8: Process       cmd.exe(8480)

v:\> rem Close the newly opened tab

v:\> handle64 -a -p windowsterminal.exe | findstr Process
  9DC: Process       OpenConsole.exe(10016)
  A00: Process       <Non-existant Process>(9848)
  A04: Process       cmd.exe(3136)
```

### PR DESCRIPTION
**Pull request by DHowett**
It rather raises the question as to how we missed this.

Closes #8706

### CODE REVIEW

**Comment by DHowett** [comment]
@msftbot merge this in 5 minutes

**Review by zadjii-msft — DISMISSED** [review]

**Review by miniksa — APPROVED** [review]

**Comment by zadjii-msft** [comment]
@DHowett FYI, this broke the tests? That makes me a tad bit worried

**Comment by DHowett** [comment]
What on earth?

**Comment by DHowett** [comment]
This looks like another instance of test machine FT flakiness. It doesn't even use ConPTY in these tests!

**Comment by DHowett** [comment]
@zadjii-msft this looks like the thing your backoff/retry timer had fixed, but more aggressive:

```
Error: Verify: IsLessThan(tries, 5): Make sure we set up the new console in time - Values (5, 5) [File: C:\a\1\s\src\host\ft_host\InitTests.cpp, Function: ModuleSetup, Line: 279]
```

Unrelated to this changeset. I've re-queued the run.

**Comment by zadjii-msft** [comment]
Wait, but, I totally saw it fail the ConPtyTests earlier. W E I R D

**Comment by DHowett** [comment]
@zadjii-msft  clean bill of health after fixing handle jiggler

**Review by zadjii-msft — APPROVED** [review]
that'll do it

**Pull request merged**
