### PR TITLE
Convert WIL submodule to global NuGet. Update to latest.  Replace winrt::resume_foreground with wil::resume_foreground

### LINKED ISSUE #12776: Usage of winrt::resume_foreground should be replaced with wil::resume_foreground
# Description of the new feature/enhancement
See [https://github.com/microsoft/wil/commit/492c01bb535daadf719d4445d6107aadf1e60812](https://github.com/microsoft/wil/commit/492c01bb535daadf719d4445d6107aadf1e60812) for a detailed explanation of the problems with `winrt::resume_foreground` and how `wil::resume_foreground` addresses them.

# Proposed technical implementation details (optional)
Basically just find/replace.  This helper is relatively new to WIL so an updated WIL version is necessary.

### LINKED ISSUE #12777: It would be nice to remove the WIL submodule in favor of a single global NuGet package
# Description of the new feature/enhancement
This builds on top of #12707.  As I understand it the primary motivation for using a git submodule instead of NuGet is just that it is too annoying to have to manage dozens of packages.config files and their corresponding import statements.  Now that there is a single global nuget definition that is a nonissue and we can switch over.

It would also be nice to update to the latest version of WIL.

# Proposed technical implementation details (optional)
Delete WIL submodule
Delete usage of WIL submodule path
Add WIL to global nuget (packages.config, targets import)
Import common.nugetversions.* to the projects that didn't already have it.

### PR DESCRIPTION
**Pull request by dmachaj**
## Summary of the Pull Request
This builds on top of #12707. As I understand it the primary motivation for using a git submodule instead of NuGet is just that it is too annoying to have to manage dozens of packages.config files and their corresponding import statements. Now that there is a single global nuget definition that is a nonissue and we can switch over.

This also updates to the latest version of WIL.

Now that the latest version of WIL is available it uses it to replace `winrt::resume_foreground` with `wil::resume_foreground`.  See [https://github.com/microsoft/wil/commit/492c01bb535daadf719d4445d6107aadf1e60812](https://github.com/microsoft/wil/commit/492c01bb535daadf719d4445d6107aadf1e60812) for a detailed explanation of the problems with `winrt::resume_foreground` and how WIL addresses them.

 
## PR Checklist
* [ ] Closes #12776, Closes #12777
* [ ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Validation Steps Performed
Ran `git clean -fdx` to wipe my clone to be completely clean.  Opened the solution in Visual Studio 2022 and build it.  Used `razzle.cmd`, `b`, and `runut.cmd` to run the tests.

### CODE REVIEW

**Comment by miniksa** [comment]
Looks good... but I wonder if we should be using `WIL_DELETE_WINRT_RESUME_FOREGROUND` to prevent people from using the worse `winrt::resume_foreground` accidentally in the future.

**Comment by dmachaj** [comment]
> Looks good... but I wonder if we should be using WIL_DELETE_WINRT_RESUME_FOREGROUND to prevent people from using the worse winrt::resume_foreground accidentally in the future.

Good call.  I forgot about that one between reading the commit on Friday and sending the PR this week.

**Review by miniksa — APPROVED** [review]

**Comment by dmachaj** [comment]
> > Looks good... but I wonder if we should be using WIL_DELETE_WINRT_RESUME_FOREGROUND to prevent people from using the worse winrt::resume_foreground accidentally in the future.
> 
> Good call. I forgot about that one between reading the commit on Friday and sending the PR this week.

(sad trombone) looks like that didn't make it into the final commit.  [https://github.com/microsoft/wil/pull/199/commits/3942327a303e88ea5b0341cd5b58446d4d810042](https://github.com/microsoft/wil/pull/199/commits/3942327a303e88ea5b0341cd5b58446d4d810042)

**Review by zadjii-msft — APPROVED** [review]

**Comment by zadjii-msft** [comment]
@msftbot merge this in 1 minute

**Pull request merged**
