### PR TITLE
Updating readme for more explicit VS2019 Instructions

### PR DESCRIPTION
**Pull request by timheuer**
Added some more explicit and correct terms for the VS 2019 components that are needed.

### CODE REVIEW

**Comment by fcharlie** [comment]
In fact, you can build Windows Terminal with MSVC v142.

```bat
git clone https://github.com/microsoft/Terminal.git
cd Terminal
git submodule init
git submodule update
nuget restore OpenConsole.sln
msbuild /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142 /p:TargetPlatformVersion=10.0.18362.0 /p:PreferredToolArchitecture=x64 OpenConsole.sln
```

**Comment by jongio** [comment]
This issue claims that v141 is not required for 2019 https://github.com/microsoft/Terminal/issues/565

**Comment by timheuer** [comment]
> This issue claims that v141 is not required for 2019 #565

I saw that as well and discussed with the team at Build.  Frankly it's just a matter of confidence that the team is not building on that toolset so I was trying to match their environments.  IMO I think the project should move to VS2019 and v142 toolset, but didn't want to presume that 'it just worked' and guide others along a path that perhaps had issues.  The source as-is very much indicates the targets they have built against and while retargeting can happen (and appears to work), it just doesn't match what is in current development.  I think that issue should be renamed to be explicit about the suggestion.

**Comment by miniksa** [comment]
@timheuer is this still relevant after the other changes to help VS2019 find packages and whatnot?

If so, can you fix the conflict because when I browse the diff to try to review this, I see the entire file as a diff. 

Thanks!

**Comment by timheuer** [comment]
I think still helpful to call it out, will look at conflicts now

**Comment by timheuer** [comment]
@miniksa - conflicts resolved.

**Pull request merged**
