### PR TITLE
Replace the "user docs" with references to the real docs

### PR DESCRIPTION
**Pull request by DHowett**
I have filed https://github.com/MicrosoftDocs/terminal/issues/138 with some of the snippets removed from these docs, like the tips/tricks from settings.

## PR Checklist
* [ ] Closes a bug
* [x] CLA signed
* [ ] Tests added/passed
* [x] Documentation updated
* [ ] Schema updated
* [x] I work here

### CODE REVIEW

**Comment by WSLUser** [comment]
Don't forget about https://github.com/MicrosoftDocs/terminal/issues/98. I think the doc belongs there and should help reduce the amount of issues we get asking for setting up different custom profiles.

**Comment by DHowett** [comment]
That’s why I haven’t yet removed ThirdPartyProfiles! :)

**Review by cinnamon-msft — APPROVED** [review]

**Comment by cinnamon-msft** [comment]
Thanks for doing this!!

**Review by carlos-zamora — APPROVED** [review]
I swear you had a PR before that tried to do something similar, but I couldn't find it.

I also swear that there was an issue that that PR closed, but, again, I couldn't find it.

**Comment by DHowett** [comment]
There was a PR (keyword: “upstate”) and there was not an issue linked from it!

**Comment by mattwojo** [comment]
Added 3rd party profiles to docs.ms in case you want to remove and close this. https://github.com/MicrosoftDocs/terminal/pull/366

**Pull request merged**
