### PR TITLE
Fix UIA ScrollIntoView at EndExclusive

### LINKED ISSUE #7839: narrator scan mode [ctrl+end] crashes conhost
_ut supra_

### PR DESCRIPTION
**Pull request by carlos-zamora**
`ScrollIntoView` is responsible for scrolling the viewport to include
the UTR's start endpoint. The crash was caused by `start` being at the
exclusive end, and attempting to scroll to it. This is now fixed by
clamping the result to the bottom of the buffer.

Most of the work here is to allow a test for this. `ScrollIntoView`
relied on a virtual `ChangeViewport` function. By making that
non-virtual, the `DummyElementProvider` in the tests can now be a
`ScreenInfoUiaProviderBase`. This opens up the possibility of more
UiaTextRange tests in the future too.

Closes #7839

### CODE REVIEW

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
The change that I am going to bring to Windows:

```diff
diff --git a/src/types/UiaTextRangeBase.cpp b/src/types/UiaTextRangeBase.cpp
index e26415999..99589eeb0 100644
--- a/src/types/UiaTextRangeBase.cpp
+++ b/src/types/UiaTextRangeBase.cpp
@@ -796,9 +796,13 @@ try
         // check if we can align to the bottom
         if (static_cast<unsigned int>(endScreenInfoRow) >= viewportHeight)
         {
+            // GH#7839: endScreenInfoRow may be ExclusiveEnd
+            //          ExclusiveEnd is past the bottomRow
+            //          so we need to clamp to the bottom row to stay in bounds
+
             // we can align to bottom
-            newViewport.Bottom = endScreenInfoRow;
-            newViewport.Top = endScreenInfoRow - viewportHeight + 1;
+            newViewport.Bottom = std::min(endScreenInfoRow, bottomRow);
+            newViewport.Top = base::ClampedNumeric<short>(newViewport.Bottom) - viewportHeight + 1;
         }
         else
         {
```

**Comment by miniksa** [comment]
> `ScrollIntoView` is responsible for scrolling the viewport to include
> the UTR's start endpoint. The crash was caused by `start` being at the
> exclusive end, and attempting to scroll to it. This is now fixed by
> clamping the result to

You accidentally a word in the description.

**Review by miniksa — APPROVED** [review]

**Comment by carlos-zamora** [comment]
@msftbot merge this in 5 minutes

**Comment by codeofdusk** [comment]
@DHowett Guessing this PR is also supposed to have a merged into Windows comment?

**Comment by DHowett** [comment]
You'd be guessing wrong! :smile:

**Comment by DHowett** [comment]
I'll let folks on this PR know what build it's available in, when it's available in a public build.

**Pull request merged**
